mesosphere/dcos-commons

build.gradle, src/main/java/org/apache/mesos/scheduler/SchedulerDriverFactory.java, src/test/java/org/apache/mesos/scheduler/SchedulerDriverFactoryTest.java
Each framework should be constructing these in the same way. Can be expanded as things are normalized further.
=> Add a factory for creating MesosSchedulerDrivers.

build.gradle, src/main/java/org/apache/mesos/offer/MesosResourcePool.java, src/main/java/org/apache/mesos/offer/TaskException.java, src/main/java/org/apache/mesos/offer/TaskUtils.java, src/test/java/org/apache/mesos/offer/MesosResourcePoolTest.java, src/test/java/org/apache/mesos/offer/OfferEvaluatorTest.java, src/test/java/org/apache/mesos/offer/TaskUtilsTest.java
Resources weren't actually being consumed from the MesosResource Pool.
=> Fix resource accounting bug.

acme-scheduler-example/src/main/java/org/apache/mesos/acme/scheduler/AcmeScheduler.java, src/main/java/org/apache/mesos/reconciliation/DefaultReconciler.java, src/main/java/org/apache/mesos/reconciliation/TaskStatusProvider.java, src/main/java/org/apache/mesos/scheduler/plan/Completable.java, src/main/java/org/apache/mesos/scheduler/plan/ReconciliationPhase.java, src/main/java/org/apache/mesos/scheduler/plan/ReconciliationStrategy.java, src/main/java/org/apache/mesos/scheduler/plan/StageScheduler.java, src/main/java/org/apache/mesos/scheduler/plan/api/BlockInfo.java, src/test/java/org/apache/mesos/scheduler/plan/DefaultStageManagerTest.java
Avoids making any functional changes
=> Varous formatting nits and some additions to docs

src/main/java/org/apache/mesos/offer/CreateOfferRecommendation.java, src/main/java/org/apache/mesos/offer/DestroyOfferRecommendation.java, src/main/java/org/apache/mesos/offer/LaunchOfferRecommendation.java, src/main/java/org/apache/mesos/offer/OfferAccepter.java, src/main/java/org/apache/mesos/offer/OfferRecommendation.java, src/main/java/org/apache/mesos/offer/ReserveOfferRecommendation.java, src/main/java/org/apache/mesos/offer/UnreserveOfferRecommendation.java, src/main/java/org/apache/mesos/protobuf/ResourceBuilder.java, src/main/java/org/apache/mesos/state/StateStore.java, src/main/java/org/apache/mesos/state/StateStoreException.java
No effective changes to functionality
=> Various nitpicks to docs/formatting

build.gradle, src/main/java/org/apache/mesos/config/ConfigStore.java, src/main/java/org/apache/mesos/config/CuratorConfigStore.java, src/main/java/org/apache/mesos/state/CuratorStateStore.java, src/test/java/org/apache/mesos/config/CuratorConfigStoreTest.java, src/test/java/org/apache/mesos/state/CuratorStateStoreTest.java
Expected that most users will just want to use a reasonable default
=> Add a CuratorStateStore constructor with default retry policy

build.gradle, src/main/java/org/apache/mesos/offer/ExecutorRequirement.java, src/main/java/org/apache/mesos/offer/OfferEvaluator.java, src/main/java/org/apache/mesos/offer/OfferRequirement.java, src/main/java/org/apache/mesos/protobuf/OfferBuilder.java, src/test/java/org/apache/mesos/offer/ExecutorRequirementTest.java, src/test/java/org/apache/mesos/offer/OfferEvaluatorTest.java, src/test/java/org/apache/mesos/offer/OfferRequirementTest.java, src/test/java/org/apache/mesos/offer/ResourceTestUtils.java
Executors and using existing Executors
=> Add ExecutorRequirement creation representing creating new

src/main/java/org/apache/mesos/offer/MesosResourcePool.java, src/main/java/org/apache/mesos/offer/OfferAccepter.java, src/main/java/org/apache/mesos/offer/OfferEvaluator.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultStage.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultStageManager.java
(and other logging improvements)
=> Emit single-line logs: Use ShortDebugString

build.gradle, src/main/java/org/apache/mesos/offer/TaskUtils.java, src/main/java/org/apache/mesos/reconciliation/DefaultReconciler.java
been acked and will always result in TASK_LOST.
=> Fix reconciliation.  Don't reconcile terminal tasks, because they've

src/main/java/org/apache/mesos/dcos/Capabilities.java, src/main/java/org/apache/mesos/offer/OfferAccepter.java, src/test/java/org/apache/mesos/dcos/CapabilitiesTest.java
1. Added Null check (instead of size > 0)
2. Generalized supportNamedVips check.
=> Minor Improvements.

tools/ci-upload.sh
And avoid printing an error about custom-universes.txt being unavailable in build.sh'es
=> Add some flexibility to ci-upload defaults

tools/dcos_login.py, tools/launch_ccm_cluster.py
=> use python logging system in launch_ccm_cluster.py

tools/launch_ccm_cluster.py
cc @nickbp 
make sure the output is json formatted for `jq`
=> print json

tools/launch_ccm_cluster.py
Support messages for shutdown as well
=> Emit success status when cluster launch is successful

tools/dcos_login.py
=> fix stacktrace

tools/ci_upload.py
cc @nickbp 
to support using ci_upload.py for production upload
I'd also like it if we can start trying to maintain relatively pep8-compliant python code (line breaks at 80, etc.)
=> add S3_URL and ARTIFACT_DIR to ci_upload.py

build.gradle, src/main/java/org/apache/mesos/scheduler/DefaultScheduler.java, src/main/java/org/apache/mesos/specification/DefaultService.java
1. Start order of API server and Scheduler register call was backwards
2. Didn't have the right dependencies installed for
serialization/deserialization
=> Fix API Server

src/main/java/org/apache/mesos/testing/QueuedSchedulerDriver.java
=> add isSuppressed to QueuedSchedulerDriver

README.md
Updated README with a gradle config to be included in dependent projects. Addresses #134.
=> Added usage via Maven

build.gradle, src/main/java/org/apache/mesos/scheduler/plan/DefaultInstallStrategy.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultPlanManager.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultStageStrategy.java, src/main/java/org/apache/mesos/scheduler/plan/PhaseStrategy.java, src/main/java/org/apache/mesos/scheduler/plan/ReconciliationStrategy.java, src/test/java/org/apache/mesos/scheduler/plan/DefaultPlanStrategyTest.java
cc @nickbp 
cc @gabrielhartmann grep'ing for "return null" shows a few other locations we should probably fix as well
=> make getCurrentBlock() return Optional

src/main/java/org/apache/mesos/state/api/StateResource.java
cc @nickbp 
cc @gabrielhartmann grep'ing for "return null" shows a few other locations we should probably fix as well
=> guice injection in StateResource

build.gradle, src/main/java/org/apache/mesos/reconciliation/DefaultReconciler.java, src/test/java/org/apache/mesos/reconciliation/DefaultReconcilerTest.java
=> change isReconciled

cli/commands.go
Compare to https://github.com/mesosphere/dcos-commons/blob/6a5e665c56dcb9eb478b89619453f4f5e0fdbad2/src/main/java/org/apache/mesos/scheduler/plan/api/PlanResource.java#L45
=> Plan admin tasks are POST requests

src/main/java/org/apache/mesos/specification/DefaultService.java
See added note about 'user' field in class javadoc. Is that accurate?
=> Nits for DefaultService

src/main/java/org/apache/mesos/offer/OfferEvaluator.java, src/main/java/org/apache/mesos/offer/OfferRequirement.java, src/main/java/org/apache/mesos/state/JsonSerializer.java, src/main/java/org/apache/mesos/state/Serializer.java, src/main/java/org/apache/mesos/state/api/JsonPropertyDeserializer.java, src/test/java/org/apache/mesos/offer/OfferEvaluatorTest.java, src/test/java/org/apache/mesos/offer/OfferRequirementTest.java
Intentionally no changes to functionality.
=> Reindent Offer<Evaluator/Requirement>[Test], fix lint warnings

tools/github_update.py
cc @nickbp plz include required env vars in comments at the top of scripts so client code knows what the interface is
=> add doc for GITHUB_TOKEN

tools/ci_upload.py
=> add docs to ci_upload.py

tools/github_update.py
=> more env var docs to github_update.py

tools/release_builder.py
=> upload docker image

tools/launch_ccm_cluster.py
=> Set default region to 'eu-central-1'

src/main/java/org/apache/mesos/offer/TaskUtils.java
Reduce per-label-type logic to the bare minimum
=> Clean up label juggling code

src/main/java/org/apache/mesos/offer/MesosResourcePool.java, src/main/java/org/apache/mesos/offer/OfferEvaluator.java, src/main/java/org/apache/mesos/offer/OfferRequirement.java, src/test/java/org/apache/mesos/offer/MesosResourcePoolTest.java, src/test/java/org/apache/mesos/offer/OfferRequirementTest.java
- Adds logging of OfferEvaluator decisions
- Cleans up MesosResourcePool internals a bit, mainly the init logic, while adding Javadocs
=> Use Optionals in OfferEvaluator/MesosResourcePool

src/main/java/org/apache/mesos/scheduler/DefaultScheduler.java, src/main/java/org/apache/mesos/state/api/StateResource.java, src/test/java/org/apache/mesos/state/api/StateResourceTest.java
Creates an endpoint `/v1/state/tasks/connection/{taskName}`, which returns
```
{
"dns": "task-name.framework-name.mesos"
"ports": "2000-3000,8080"
}
```
=> ConnectionResource

src/main/java/org/apache/mesos/scheduler/DefaultScheduler.java, src/main/java/org/apache/mesos/scheduler/DefaultTaskKiller.java, src/main/java/org/apache/mesos/scheduler/TaskKiller.java, src/main/java/org/apache/mesos/scheduler/api/TaskResource.java, src/main/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryScheduler.java, src/main/java/org/apache/mesos/scheduler/recovery/constrain/TimedLaunchConstrainer.java, src/main/java/org/apache/mesos/state/api/StateResource.java, src/test/java/org/apache/mesos/scheduler/api/TaskResourceTest.java, src/test/java/org/apache/mesos/state/api/StateResourceTest.java
Moved /v1/state/tasks to /v1/tasks
Added POST /v1/tasks/restart/<task-name>?replace=<replace>
=> [INFINITY-588] Restart task endpoint

docs/tutorial.md
Still to do: change uses of "we" to "you."
=> suzanne's edits: first pass

cli/commands.go
Updates CLI to align with [PlanResource](https://github.com/mesosphere/dcos-commons/blob/master/src/main/java/org/apache/mesos/scheduler/plan/api/PlanResource.java#L60).
Reorders/groups the default Plan commands themselves while we're at it.
=> Fix restart/forceComplete: add phase/block args

docs/tutorial.md
=> Add backslash to janitor command, forward slash to plan status URL

docs/tutorial.md
=> Fix links in Integration Tests

src/main/java/org/apache/mesos/offer/DefaultOfferRequirementProvider.java, src/main/java/org/apache/mesos/specification/DefaultTaskSet.java, src/main/java/org/apache/mesos/specification/DefaultTaskSpecification.java, src/main/java/org/apache/mesos/specification/TaskSpecification.java, src/test/java/org/apache/mesos/specification/CustomTaskSetTest.java, src/test/java/org/apache/mesos/specification/TestTaskSetFactory.java, src/test/java/org/apache/mesos/specification/TestTaskSpecification.java
=> [INFINITY-594] Add health checks to TaskSpecification

src/main/java/org/apache/mesos/offer/OfferUtils.java, src/main/java/org/apache/mesos/scheduler/DefaultScheduler.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultPlanCoordinator.java, src/test/java/org/apache/mesos/offer/OfferUtilsTest.java, src/test/java/org/apache/mesos/scheduler/DefaultSchedulerTest.java, src/test/java/org/apache/mesos/scheduler/plan/DefaultPlanCoordinatorTest.java
Ensure that Resource Cleaner does not get an Offer that is already being dirtied.
=> Provide only unaccepted offers to Resource Cleaner

docs/tutorial.md
blocked on https://github.com/mesosphere/sdk-reference-framework/pull/10
=> [INFINITY-611] Add health checks to the tutorial

src/main/java/org/apache/mesos/curator/CuratorStateStore.java, src/main/java/org/apache/mesos/scheduler/DefaultScheduler.java, src/main/java/org/apache/mesos/scheduler/plan/Block.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultBlock.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultInstallStrategy.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultPhase.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultPhaseStrategy.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultPhaseStrategyFactory.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultPlan.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultPlanCoordinator.java, src/main/java/org/apache/mesos/scheduler/plan/DefaultPlanManager.java, src/main/java/org/apache/mesos/scheduler/plan/Phase.java, src/main/java/org/apache/mesos/scheduler/plan/PhaseStrategy.java, src/main/java/org/apache/mesos/scheduler/plan/PlanCoordinator.java, src/main/java/org/apache/mesos/scheduler/plan/PlanManager.java, src/main/java/org/apache/mesos/scheduler/plan/RandomRecoveryStrategy.java, src/main/java/org/apache/mesos/scheduler/plan/ReconciliationStrategy.java, src/main/java/org/apache/mesos/scheduler/plan/Status.java, src/main/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryPlanManager.java, src/main/java/org/apache/mesos/state/StateStore.java, src/main/java/org/apache/mesos/state/StateStoreCache.java, src/test/java/org/apache/mesos/scheduler/DefaultSchedulerTest.java, src/test/java/org/apache/mesos/scheduler/plan/DefaultPlanCoordinatorTest.java, src/test/java/org/apache/mesos/scheduler/plan/DefaultPlanManagerTest.java, src/test/java/org/apache/mesos/scheduler/plan/DefaultPlanStrategyTest.java, src/test/java/org/apache/mesos/scheduler/plan/RandomRecoveryStrategyTest.java, src/test/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryPlanManagerTest.java
Also makes significant changes to `DefaultRecoveryPlanManager`
=> [INFINITY-502] Add suppress/revive support to DefaultScheduler

build.gradle, src/main/java/org/apache/mesos/executor/CustomExecutor.java, src/main/java/org/apache/mesos/testing/QueuedSchedulerDriver.java, src/test/java/org/apache/mesos/scheduler/DefaultSchedulerTest.java, src/test/java/org/apache/mesos/scheduler/plan/RandomRecoveryStrategyTest.java, src/test/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryPlanManagerTest.java
... and fix the current warnings
=> Provide full lint/deprecation warnings instead of -X messages

src/main/java/org/apache/mesos/scheduler/plan/DefaultBlock.java, src/main/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryPlanManager.java, src/test/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryPlanManagerTest.java
@mohitsoni:  Tested on sdk-reference-framework with 1s sleep and plan behaves as expected, and framework continuously recovers.
=> Fix multiple Task failure bug. [INFINITY-628]

sdk/core/src/main/java/org/apache/mesos/scheduler/DefaultScheduler.java, sdk/core/src/main/java/org/apache/mesos/scheduler/plan/DefaultBlock.java
Adding new construction options such that Tardigrade can be configured in the DefaultScheduler.
=> Config tardigrade

examples/reference/build.sh, examples/reference/universe/config.json, examples/reference/universe/marathon.json.mustache
1. Fixes reference example universe build 
2. Fixes executor URI
3. Fixes health checks in reference example
=> Reference example fix

sdk/core/src/test/java/org/apache/mesos/offer/constrain/AgentRuleTest.java, sdk/core/src/test/java/org/apache/mesos/offer/constrain/AndRuleTest.java, sdk/core/src/test/java/org/apache/mesos/offer/constrain/AttributeRuleTest.java, sdk/core/src/test/java/org/apache/mesos/offer/constrain/HostnameRuleTest.java, sdk/core/src/test/java/org/apache/mesos/offer/constrain/MaxPerAttributeGeneratorTest.java, sdk/core/src/test/java/org/apache/mesos/offer/constrain/NotRuleTest.java, sdk/core/src/test/java/org/apache/mesos/offer/constrain/OrRuleTest.java, sdk/core/src/test/java/org/apache/mesos/offer/constrain/TaskTypeRuleGeneratorTest.java, sdk/core/src/test/java/org/apache/mesos/offer/constrain/TestPlacementUtils.java
Should've been included in PR #246 but forgot..
=> Add tests for PlacementRule serialization

build.gradle, sdk/scheduler/build.gradle
Moves version to root and adds instructions.
=> Release 0.8.1

build.gradle
Before:
```
Upload s3://downloads.mesosphere.io/maven/dcos-commons/dcos-commons/unspecified/dcos-commons-unspecified.jar
```
After:
```
Upload s3://downloads.mesosphere.io/maven/mesosphere/dcos-commons/0.8.1/dcos-commons-0.8.1.jar
```
=> Fix publish, revert to 0.8.1-SNAPSHOT

frameworks/hdfs/TEST_README.md, frameworks/hdfs/integration/requirements.txt, frameworks/hdfs/integration/tests/test_sanity.py, frameworks/hdfs/integration/tests/test_utils.py, frameworks/hdfs/test.sh
Copied over basic sanity test (install hdfs) from dcos_hdfs_service project. @NimaVaziri
=> Basic sanity test integration test for HDFS

frameworks/kafka/build.sh
=> Update reflects local vs S3 publishing change

new-service
=> Updated new-service script

README.md
=> Add Uber as user

frameworks/helloworld/integration/tests/test_sanity.py, frameworks/helloworld/integration/tests/test_utils.py, frameworks/helloworld/src/main/dist/svc.yml, frameworks/helloworld/src/main/dist/svc_plan.yml, frameworks/helloworld/src/main/java/com/mesosphere/sdk/helloworld/scheduler/Main.java, frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceSpecTest.java, frameworks/helloworld/universe/config.json, frameworks/helloworld/universe/marathon.json.mustache, sdk/scheduler/src/main/java/org/apache/mesos/specification/DefaultPodSpec.java, sdk/scheduler/src/main/java/org/apache/mesos/specification/DefaultResourceSet.java, sdk/scheduler/src/main/java/org/apache/mesos/specification/DefaultService.java, sdk/scheduler/src/main/java/org/apache/mesos/specification/DefaultServiceSpec.java, sdk/scheduler/src/main/java/org/apache/mesos/specification/yaml/YAMLToInternalMappers.java, sdk/scheduler/src/test/java/org/apache/mesos/specification/TestPodFactory.java
Reverts mesosphere/dcos-commons#312
JIRA tracking bug that needs fixing: https://mesosphere.atlassian.net/browse/INFINITY-724
=> Revert "Dev interface improvements"

README.md
This is based on the requirements for [dcos-vagrant](https://github.com/dcos/dcos-vagrant/blob/master/docs/deploy.md#software) which is used by dcos-docker.
=> Updated Quick Start to add versions

new-service.sh
Fixes renaming the project folder and not copying over binary data
=> Fixes misnaming main directory

sdk/executor/src/main/java/com/mesosphere/sdk/executor/CustomExecutor.java
=> Fix NullPointerException when agent is restarted and CustomExecutor

frameworks/helloworld/README.md, frameworks/helloworld/src/main/dist/svc_uri.yml, frameworks/helloworld/src/main/resources/svc_uri.yml, frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/HelloWorldServiceSpecTest.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultPodSpec.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/PodSpec.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawPod.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java
- DefaultPodSpec,
- YAMLToInternalMap,
- RawPod,
- PodSpec are updated.
While pasing to the TaskSpec, pod uris' are appended to task uris'
added  simple_uri.yml in hello-world framework
=> "uris" keyword is added in pod level for yaml file.

tools/release_builder.py
Previously would fail for a new package (e.g. hello-world)
Going to go ahead and merge this, but cc @nickbp for review (optional)
=> make release_builder.py work with a new package

sdk/common/src/main/java/com/mesosphere/sdk/offer/CommonTaskUtils.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/api/EndpointsResource.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/MesosResource.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceRequirement.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/TaskRequirement.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/TaskKiller.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanCoordinator.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultStep.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultStepFactory.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanUtils.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PodInstanceRequirement.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManager.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryStep.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultPlanGenerator.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultService.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/PodInstance.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/state/StateStoreUtils.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/api/TaskResourceTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/ResourceRequirementTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanCoordinatorTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanSchedulerTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultStepFactoryTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManagerTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultPlanGeneratorTest.java
- Add javadocs where needed
- Drop dead code/unused params
- Simplify boolean logic
- Use logging parameterization
=> Ocean of non-functional nitpicky fixes

frameworks/helloworld/integration/tests/test_sanity.py, frameworks/helloworld/universe/config.json, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultPlanGenerator.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultPodSpec.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultService.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/PlanGenerator.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawPhase.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawPlan.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawPod.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawResourceSet.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawTask.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLServiceSpecFactory.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultPlanGeneratorTest.java, sdk/scheduler/src/test/resources/invalid-pod-name.yml, sdk/scheduler/src/test/resources/invalid-replacement-failure-policy.yml, sdk/scheduler/src/test/resources/invalid-resource-set-name.yml, sdk/scheduler/src/test/resources/invalid-task-name.yml, sdk/scheduler/src/test/resources/invalid-task-resources.yml, sdk/scheduler/src/test/resources/valid-exhaustive.yml
Enables placement in hello-world along with an integration test that it's enforced.
=> Enable YAML marathon placement, remove remaining Raw*.java setters

frameworks/helloworld/src/main/dist/svc_plan.yml, frameworks/helloworld/src/main/dist/svc_uri.yml, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultHealthCheckSpec.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/HealthCheckSpec.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawTask.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultHealthCheckSpecTest.java, sdk/scheduler/src/test/resources/full-manual-plan.yml, sdk/scheduler/src/test/resources/invalid-replacement-failure-policy.yml, sdk/scheduler/src/test/resources/invalid-task-resources.yml, sdk/scheduler/src/test/resources/valid-exhaustive.yml, sdk/scheduler/src/test/resources/valid-minimal-health.yml
Mesos supports a single health-check
=> Make ServiceSpec YAML have a single health-check

frameworks/hdfs/integration/tests/test_data_integrity.py, frameworks/hdfs/integration/tests/test_recovery.py, frameworks/hdfs/integration/tests/test_utils.py, frameworks/hdfs/universe/config.json
=> Added data integrity tests to HDFS

frameworks/helloworld/integration/tests/test_sanity.py, frameworks/helloworld/integration/tests/test_utils.py, sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorConfigStore.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorStateStore.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorUtils.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerErrorCode.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerUtils.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultService.java
cc @nickbp for review
blocked on https://github.com/dcos/shakedown/pull/101
=> [WIP] [INFINITY-706] Add ZK lock to prevent multiple running schedulers

frameworks/hdfs/integration/tests/test_data_integrity.py, frameworks/hdfs/integration/tests/test_upgrade.py
Added data integrity check to upgrade test: write data, do upgrade, read data. Minor refactoring and code style changes.
=> Added data integrity check to upgrade test

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/CanaryStrategy.java
=> CanaryStrategy forgot to proceed itself

frameworks/helloworld/integration/tests/test_upgrade.py
Modified the hello-world upgrade test to upgrade from the version in Universe. Added downgrade test.
=> Modified hello-world upgrade test to upgrade from the version in Universe

tools/save_properties.py
A script to save the <version>.properties build file in S3.
=> Added a script to save build properties

frameworks/hdfs/integration/tests/test_data_integrity.py
Disabled the data integrity tests since they were failing in Jenkins.
=> Disabled hdfs data integrity tests

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawContainer.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawTask.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProviderTest.java, sdk/scheduler/src/test/resources/valid-docker.yml
=> use proper docker protobufs and fix rlimits NPE

frameworks/template/integration/tests/test_sanity.py, frameworks/template/integration/tests/test_utils.py
- Optimized imports
- Removed unused nested dict options code around service installation
- Added simple test around DCOS service health as an example
=> Replace local spin() method with shakedown version

sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorConfigStore.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorPersister.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorStateStore.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorUtils.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/curator/CuratorSchemaVersionStoreTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/CuratorTestUtils.java
Added authorization for zookeeper, where user can opt for world:anyone permission or username:password authentication. On opting username:password, it will have world readable permissions too.
=> add zookeeper authorization

build.gradle
To be immediately followed by 0.10.1-SNAPSHOT.
=> Cut release for 0.10.0

frameworks/helloworld/build.gradle
Bumped the version in preparation for a release.
=> Bumped hello-world version

frameworks/hdfs/build.sh, frameworks/helloworld/build.sh, frameworks/kafka/build.sh, frameworks/prototype/build.sh, frameworks/template/build.sh, sdk/common/build.gradle, sdk/executor/build.gradle, sdk/scheduler/build.gradle, sdk/testing/build.gradle
Tested with `./gradlew -p sdk/common/ publishToMavenLocal`.  Was able to resolve dependencies.
=> Publish all projects to maven

docs/pages/dev-guide/developer-guide.md
@sascala:  Any reason we shouldn't move to this style of code snippets.  I think the style we had up until now was an result of the conversion tool we used to move from Google docs right?
=> Standardize and provide types to code snippets

frameworks/kafka/universe/marathon.json.mustache
TASKCFG_ALL_KAFKA_OFFSET_METADATA_MAX_BYTES
=> Removed duplicate entry

frameworks/hdfs/src/main/dist/hdfs-site.xml
Make persistent voluem paths consistent
Make name-node port ordering consistent
=> [HDFS] Improve hdfs-site.xml template consistency

docs/pages/dev-guide/developer-guide.md
- Standardize on FRAMEWORK_NAME instead of SERVICE_NAME as the environment variable to use (e.g., bootstrap script expects FRAMEWORK_NAME).
- Fixed Markdown syntax for nested lists
- Fixed some typos
- Added section on how to avoid proxylite task failure
=> Tweaks to developer guide

docs/pages/dev-guide/developer-guide.md, frameworks/proxylite/src/main/dist/svc.yml, frameworks/proxylite/src/main/docker/files/configure.py
Add the ProxyPassReverse equivalent.
=> proxylite: Bump to version 1.0.1

frameworks/elastic/src/main/dist/elastic_service.yml, frameworks/elastic/tests/config.py, frameworks/elastic/tests/test_shakedown.py
- Added shakedown test around Admin Router -> proxylite -> kibana integration
=> [ELASTIC] Updated proxylite to 1.0.1

docs/pages/dev-guide/developer-guide.md, frameworks/helloworld/README.md, frameworks/prototype/universe/marathon.json.mustache, frameworks/proxylite/universe/marathon.json.mustache, frameworks/template/universe/marathon.json.mustache
Fixes some example usage in docs as well
=> Fix VIPs for successful config deployment

frameworks/elastic/src/main/dist/elastic_service.yml
Also increased grace period for kibana, since 10 minutes might not actually be enough for it.
=> Added readiness check to elasticsearch and kibana tasks

frameworks/kafka/docs/api-reference.md, frameworks/kafka/docs/configure.md, frameworks/kafka/docs/connecting-clients.md, frameworks/kafka/docs/index.md, frameworks/kafka/docs/install-and-customize.md, frameworks/kafka/docs/limitations.md, frameworks/kafka/docs/managing.md, frameworks/kafka/docs/quick-start.md, frameworks/kafka/docs/table-of-contents.md, frameworks/kafka/docs/troubleshooting.md, frameworks/kafka/docs/uninstall.md
I'm assigning this to you, @gabrielhartmann , because I believe you're on call.
=> adding kafka docs to this repo

docs/pages/dev-guide/developer-guide.md
A fallback if proxylite is not compatible with the application.
=> dev-guide: Add instructions for Repoxy

frameworks/spark/tests/test_sanity.py
Will need to ask if I can run the tests on a branch.
=> Fix absent smoke test marker; caused smoke tests to fail.

docs/pages/dev-guide/developer-guide.md, frameworks/proxylite/src/main/dist/svc.yml, frameworks/proxylite/src/main/docker/files/configure.py, frameworks/proxylite/tests/test_sanity.py
This changes the internal route syntax.
=> proxylite: Add HTTPS backend support

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultService.java
DefaultService is initialized and started by init method. Framework service classes extending DefaultService will call this init method in their constructor.
=> [SDK] Add init method in DefaultService

sdk/executor/build.gradle
Removed empty version string. Also, added distZip and distTar config.
=> Executor build.gradle changes

sdk/scheduler/src/main/java/com/mesosphere/sdk/config/DefaultConfigurationUpdater.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/config/ConfigurationUpdaterTest.java
* Additions:
- Do not give error if a task's config is not ServiceSpec
- If a config is not ServiceSpec do not delete it
* Existing:
- Delete duplicates configs
- Delete unnecessary configs
=> [SDK] Modify DefaultPlacementUpdater not fail but skip old Configuration formats

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultVolumeSpec.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/VerifyVolumePathTest.java
* Regex string to verify path is "[a-zA-Z0-9]+([a-zA-Z0-9_-]*[/\\\\]*)*"
* See examples in VerifyVolumePath.java
=> [SDK] Add VolumeSpec path validation

sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorStateStore.java
StateStore keeps TaskInfo and TaskStatus and index information based on TaskName.
```
<TaskName>/<TaskInfo>
<TaskName>/<TaskStatus>
```
Each TaskInfo has a unique TaskID. Each TaskStatus also has a unique TaskID. TaskID changes at launch. Every time you restart you get a new TaskID.
When we receive a request to update status in ```StateStore.storeStatus(TaskStatus)```,  we first find its TaskName.  You need to know which task's status to update:  see the path "TaskName/TaskStatus".
- Conventional way of finding TaskName in Status update:
Normally you look existing TaskInfos and find the task that has same TaskID (TaskIDs in TaskStatus and TaskInfo should match if they belong to same task).
- Old method of generating TaskName during Status update:
However, what we were doing was extracting …
=> [SDK] Modify storeStatus to compare TaskIDs to search/find task name and TaskInfo

frameworks/prototype/src/main/java/com/mesosphere/sdk/prototype/scheduler/Main.java, frameworks/prototype/tests/test_sanity.py
=> Reintroduce shakedown for prototype framework

frameworks/elastic/src/main/dist/svc.yml, frameworks/elastic/universe/marathon.json.mustache
=> Upgrade Elastic Stack to 5.2.2

frameworks/kafka/cli/dcos-kafka/main.go, frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/api/BrokerResource.java, frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/api/KafkaZKClient.java, frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/api/TopicResource.java, frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/scheduler/KafkaService.java
Fix problems in 
* broker get
* topic describe
* topic producer_test
* topic partitions
=> [KAFKA] Fix BrokerResource and TopicController endpoints

docs/pages/dev-guide/developer-guide.md, new-framework.sh
=> [INFINITY-944] Developer doc improvements

frameworks/elastic/cli/dcos-elastic/main.go
- Changed boilerplate text
- Removed unused example section
=> [ELASTIC-45] Fix Elastic CLI help errors

test.sh, tools/README.md, tools/setup_permissions.sh
I've also refactored `setup_permissions.sh` to be organized by permission, and I've changed the comments in that file, which were incorrect.
=> [INFINITY-1074] Authorize marathon to launch tasks as root in strict mode tests

frameworks/hdfs/docs/api-reference.md, frameworks/hdfs/docs/configure.md, frameworks/hdfs/docs/connecting-clients.md, frameworks/hdfs/docs/index.md, frameworks/hdfs/docs/install.md, frameworks/hdfs/docs/managing.md, frameworks/hdfs/docs/quick-start.md, frameworks/hdfs/docs/troubleshooting.md, frameworks/hdfs/docs/uninstall.md
=> HDFS is now in "preview"

frameworks/cassandra/universe/package.json, frameworks/elastic/universe/package.json, frameworks/hdfs/universe/package.json, frameworks/kafka/universe/package.json, frameworks/spark/universe/package.json
Really, we need a separate from DCOS versions docs for services.
=> [ELASTIC-51] Link updates

frameworks/kafka/universe/config.json, frameworks/kafka/universe/marathon.json.mustache
defaults: always enable, never cleanup
=> [KAFKA] Remove config Upgrade options to change defaults 

tools/launch_ccm_cluster.py
Old repo location has no support for strict mode.
=> [INFINITY-1130]Use templates that support permission modes.

tools/launch_ccm_cluster.py
quick fix; not sure why this shows all changes in branch instead of actually diffing against master; change is just https://github.com/mesosphere/dcos-commons/commit/aefc174664875e21102bea48befcb7725665e7b6 at this point
=> Infinity 1130 launchccm permissions templates

test.py, tools/clustinfo.py, tools/fwinfo.py, tools/launch_ccm_cluster.py
Goals:
* run tests faster in parallel
* Better logging (timestamps!)
* Render failures unambiguously via junit xml (not done yet)
* Try to reduce the number of environment variables floating around.
=> [Infinity-1012] parallelize pr tests

sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorStateStore.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/CommandUtils.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/NamedVIPEvaluationStage.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStage.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultResourceSet.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawResourceSet.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawServiceSpec.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawTask.java
Unclear why the style fixes were needed in this PR and missed in other PRs.  The functional change is related to `CommandUtils.java`.
=> [SDK][KAF-285] Fix port envvars

build.gradle
=> Back to 14.0-SNAPSHOT

test.py, test.sh, tools/clustinfo.py, tools/contrib/README, tools/contrib/junit_xml/__init__.py, tools/contrib/six.py, tools/fwinfo.py, tools/run_tests.py
Goals:
* run tests faster in parallel
* Better logging (timestamps!)
* Render failures unambiguously via junit xml (not done yet)
* Try to reduce the number of environment variables floating around.
* New test runner, parallelizes, junit for test actions, verifies requirements.
=> [INFINITY-1012] Make tests go faster ( parallelize)

tools/enable_mount_volumes.py
- Prior config: 1 12GB volume => 1 12GB mount
- New config: 1 24GB volume => 2 12GB mounts
Multiple partitions on a single volume keeps management simple, while also ensuring the script doesn't take twice as long (most time is spent waiting on the EBS volume).
=> Update test script to create two mount volumes

tools/github_update.py
Github updater was only checking for CI env when run directly as a python script.
Refactor to also apply the CI env check when using the updater as an API.
=> Fix local builds (INFINITY-1216)

frameworks/helloworld/tests/test_sanity.py, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultPodSpec.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/config/ConfigurationUpdaterTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/config/DefaultTaskConfigRouterTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProviderTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultServiceSpecTest.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/BaseServiceSpecTest.java
Begin considering the executor as a part of a pods configuration (spoiler, it already was)
=> [INFINITY-1114] Hello-world does not restart tasks when upgrading to new version

build.sh
Simple goal; test the merged state.
=> [INFINITY-1107] merge pull request for build & test

build.gradle
This release contains: 
- a fix for suppress revive (#634)
- a fix for operation recording (#785)
=> Release dcos-commons 0.13.3

tools/github_update.py
Was still an issue when the updater was being called directly from python scripts.
=> [INFINITY-1268] Be permissive of network flakes in github_updater

frameworks/elastic/docs/install.md, frameworks/elastic/docs/quick-start.md, frameworks/hdfs/docs/install.md, frameworks/kafka/docs/install-and-customize.md
I'm assigning this to you to review, @gabrielhartmann , because I believe you're on call. If I'm incorrect, please reassign.
=> CLI installation

frameworks/template/README.md, frameworks/template/src/main/dist/svc.yml, frameworks/template/src/test/java/com/mesosphere/sdk/template/scheduler/ServiceSpecTest.java, frameworks/template/universe/config.json, frameworks/template/universe/marathon.json.mustache, frameworks/template/universe/package.json
Updates packaging with generic bits to match.
=> Populate template README with starter content and identifiers stubbed out

build.gradle, frameworks/hdfs/build.gradle
Reverts mesosphere/dcos-commons#781
=> Revert "Preparing to release HDFS."

frameworks/hdfs/universe/package.json
The Universe PR validation will look for this exact sentence:
"This DC/OS Service is currently in preview."
See https://jira.mesosphere.com/browse/DCOS-14968 for details.
=> HDFS-447: HDFS preInstallNotes: use the exact "in preview" sentence

frameworks/elastic/CONTRIBUTING.md, frameworks/elastic/src/main/dist/svc.yml, frameworks/elastic/universe/marathon.json.mustache
- Added CONTRIBUTING.md to document version bump process
- Incremented support diagnostics version to 5.9 via SUPPORT_DIAGNOSTICS_VERSION env var
Completes INFINITY-1308
=> Upgrade Elastic to 5.3.0

tools/modify_master.py
Add an intelligent wait that waits for the mesos master to be back up before continuing
Set agent_removal_rate_limit and max_agent_ping_timeouts.
=> Improve the master settings modification code

frameworks/cassandra/universe/marathon.json.mustache, frameworks/elastic/universe/marathon.json.mustache, frameworks/hdfs/universe/marathon.json.mustache, frameworks/helloworld/universe/marathon.json.mustache, frameworks/kafka/universe/marathon.json.mustache, frameworks/prototype/universe/marathon.json.mustache, frameworks/proxylite/universe/marathon.json.mustache, frameworks/spark/universe/marathon.json.mustache, frameworks/template/universe/marathon.json.mustache, sdk/common/src/main/java/com/mesosphere/sdk/offer/CommonTaskUtils.java, sdk/executor/src/main/java/com/mesosphere/sdk/executor/CustomExecutor.java, sdk/executor/src/main/java/com/mesosphere/sdk/executor/HealthCheckHandler.java, sdk/executor/src/main/java/com/mesosphere/sdk/executor/ProcessTask.java, testing/sdk_install.py
Also change TASK_ERROR to TASK_FAILED
=> [INFINITY-1312] Set `isHealthy` field on TaskStatus

tools/release_builder.py
`minDcosReleaseVersion` is now set to `1.8`
=> [INFINITY-1331] Update release_builder now to set the min version to 1.8

tools/release_builder.py
Updates `release_builder.py` to now update the stub-universe (optionally) with `beta-optin` flag.
=> [INFINITY-1309] Beta Universe package and PR builder

frameworks/elastic/src/main/dist/svc.yml
=> [ELASTIC] Expose transport endpoints via VIPs

tools/universe_builder.py
@nickbp @mrbrowning Comments and/or approval please.
=> [INFINITY-1330] Only template json files; only copy in non-dotfiles.

tools/modify_master.py
I think this is causing the dcos cli fetch to fail
=> Try to make PRs reliable for now

frameworks/elastic/tests/test_shakedown.py, frameworks/elastic/universe/config.json, testing/sdk_test_upgrade.py
- Update upgrade/downgrade to accept additional options, so we can keep username consistent between upgrade/downgrade
Completes ELASTIC-67
=> Make default user `nobody`

tools/enable_mount_volumes.py
@nickbp Just notifying you of typo.
=> [INFINITY-1363]Incomplete refactor or similar while editing this in e8df7d4db88809bb43145e1a394aa1b44726873e

tools/release.sh
This is something of a priority, please give me a review within the next hour or so.
=> [INIFINITY-1349] Locate init_paths.sh based on the location of release.sh

frameworks/kafka/tests/test_shakedown_basics.py
Create topic fails sometimes, saying that "replication factor: 3 larger than available brokers: 2"
=> [KAF-327] Wait till all brokers register after replace

sdk/scheduler/src/main/java/com/mesosphere/sdk/api/PlansResource.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/api/types/PlanSummaryInfo.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/api/PlansResourceTest.java
`http://gabriel-6-elasticl-1nuxgnksmygqx-1734026918.us-west-2.elb.amazonaws.com/service/hello-world/v1/plan-summary`
```
[{
status: "COMPLETE",
message: "com.mesosphere.sdk.scheduler.plan.DefaultPlan: 'deploy [7b225031-2e09-46a0-a7e1-61fc4dbdb16b]' has status: 'COMPLETE'.",
name: "deploy"
},
{
status: "COMPLETE",
message: "com.mesosphere.sdk.scheduler.plan.DefaultPlan: 'recovery [2ddacb1a-8179-40f4-b531-923d5209f817]' has status: 'COMPLETE'.",
name: "recovery"
}
]
```
=> [INFINITY-1395] Add plan-summary endpoint

test.sh, tools/cli_install.py, tools/venvutil.py
handle args correctly in cli_install
=> [INFINITY-1410] decomposed venv construction needs setup_scripts.

tools/modify_master.py
@benclarkwood I haven't yet done the bugfixing round, but I'm showing this now so you can critique if desired.
=> [INFINITY-1406] Change modify_master to act as a context manager, to get write-on-descope

tools/run_tests.py
I haven't finished testing this locally, but i have shown pip does what I want.
=> Force v 0.4.16 for dcos python until we fix our test code & shakedown.

frameworks/cassandra/universe/marathon.json.mustache, frameworks/elastic/universe/marathon.json.mustache, frameworks/hdfs/universe/marathon.json.mustache, frameworks/helloworld/universe/marathon.json.mustache, frameworks/kafka/universe/marathon.json.mustache, frameworks/prototype/universe/marathon.json.mustache, frameworks/proxylite/universe/marathon.json.mustache, frameworks/spark/universe/marathon.json.mustache, frameworks/template/universe/marathon.json.mustache
Add -XX:-HeapDumpOnOutOfMemoryError to all scheduler marathon configs.
=> [INFINITY-1454] Elastic scheduler OOMing in soak cluster. Need to capture a heap dump.

frameworks/spark/universe/resource.json, tools/universe_builder.py
* upgraded jre dependency from 8u121 to 8u131.
* changed spark-standalone dependency to use common jre-url and libmesos-bundle-url (did not touch spark-...-hadoop dependency).
=> Upgrade JRE dependency from 8u121 to 8u131

build.gradle
org.apache.mesos:mesos:1.3.0-rc1
=> [SDK] Use Mesos library 1.3.0-rc1 for new protobuf definitions

test.py, tools/fwinfo.py, tools/run_tests.py
Some hacks to increase reliability in the face of trouble with virtualenv & jenkins, for use in the CI job running permissive & strict against dcos 1.8 and 1.9
=> [INFINITY-1484] strict 18 19

tools/configure_test_cluster.py, tools/create_service_account.sh, tools/launch_ccm_cluster.py
Download enterprise-cli that could work & make configure_test_cluster.py work standalone from launch_ccm_cluster.py
=> [INFINITY-1581] configure clusters for tests

frameworks/hdfs/universe/marathon.json.mustache
* set hdfs (duplicate specification of) JRE_VERSION and TASKCFG_ALL_JRE_VERSION to account for jre path change due to jre upgrade from 8u112 to 8u131.
=> Upgrade HDFS JRE path from 8u112 to 8u131

README.md
=> Update download links for VirtualBox and Vagrant

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultService.java
This is majorly a hack, but it's an efficient hack.
I'm not sure if this is worth integration testing or not. If ya'll think it is, I'll add one.
=> Uninstall: Check the uninstall envvar as well when determining if the Service should register against Mesos or not.

testing/sdk_install.py
On 1.10
* Don't run janitor
* wait for marathon to show completed
=> testing uninstall for 1.10.

frameworks/cassandra/universe/marathon.json.mustache, frameworks/elastic/universe/marathon.json.mustache, frameworks/hdfs/universe/marathon.json.mustache, frameworks/helloworld/universe/marathon.json.mustache, frameworks/kafka/universe/marathon.json.mustache, frameworks/template/universe/marathon.json.mustache, testing/sdk_install.py
This reverts commit 1ddbdeba39d1850b3c4e8c5222485d1186fe092a.
Additionally, it disables the new uninstall behavior.
=> Revert uninstall to unblock CI.

sdk/bootstrap/main.go, sdk/bootstrap/src/pkg/mesos/ip.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mesosphere/dcos-commons/1082)
=> Added API to retrieve IP on a CNI network.

cli/client/cosmos.go, cli/client/cosmos_test.go, cli/client/testdata/output/404.txt, cli/commands/testdata/output/no-stored-options.txt, cli/commands/update.go, cli/commands/update_test.go, cli/config/config.go
These are some improvements to CLI messaging that were suggested by @keithchambers last week.
=> Improvements to CLI messaging

frameworks/helloworld/README.md
helloworld tutorial is embedded the developer-guide
=> fix broken link

docs/pages/developer-guide.md
@ssk2 this is the same minor grammar fix as the one closed.
=> grammar fix

frameworks/cassandra/universe/package.json, frameworks/elastic/universe-kibana/package.json, frameworks/elastic/universe/package.json, frameworks/hdfs/universe/package.json, frameworks/kafka/universe/package.json
Tidied up the wording on the preInstallNotes.
=> Improve preInstallNotes wording.

sdk/scheduler/src/main/java/com/mesosphere/sdk/api/PlansResource.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/api/PlansResourceTest.java, testing/sdk_marathon.py
Previously only Plan and Step restart were allowed.  Complete restart capabilities with Phase restart capability.  Needed for EdgeLB.
/cc @nlsun
=> Allow phase restart

frameworks/elastic/tests/config.py
=> [ELASTIC-96] Fix incorrect port bug in get_elasticsearch_master

docs/pages/tutorials/kafka-tutorial.md
- Revised faulty or unclear instructions of the Kafka Tutorial
=> Changing Kafka Tutorial

testing/sdk_install.py, testing/sdk_utils.py
Retry install and uninstall 5 times, waiting 5 seconds between attempts. Insulates against Marathon flakes.
=> [INFINITY-1778] Insulate sdk_install from failures

frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/api/KafkaZKClient.java, frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/cmd/CmdExecutor.java, frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/scheduler/KafkaService.java, frameworks/kafka/tests/test_sanity.py, frameworks/kafka/universe/config.json, frameworks/kafka/universe/marathon.json.mustache
Updates Kafka tests to exercise the support as well
=> INFINITY-1806 Reenable documented support for custom ZK location for kafka

cli/commands.go
Trivial change to remove the last import of "log".
=> [INFINITY-1732] Remove last instance of using log for output.

sdk/scheduler/src/main/java/com/mesosphere/sdk/dcos/Capabilities.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/validation/CapabilityValidator.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/dcos/CapabilitiesTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/validation/CapabilityValidatorTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/DefaultCapabilitiesTestSuite.java, sdk/scheduler/src/test/resources/valid-secrets-env.yml, sdk/scheduler/src/test/resources/valid-secrets.yml, sdk/testing/src/main/java/com/mesosphere/sdk/testing/BaseServiceSpecTest.java
Add Secrets Validator for PodSpec.
=> [INFINITY-1866] Add error messages if Secret is not supported for DC/OS version

tools/airgap_linter.py, tools/build_framework.sh
Create new airgap linting tool.
Hook it into the framework build process.
This will fail until #1170 merges.
=> [INFINITY-1858 ] Lint frameworks for URIs / docker images outside of resource.json

testing/sdk_install.py, testing/sdk_utils.py
This reverts commit f0a159709fcd9469e06b8c55d17e220871503b53.
=> Revert "[INFINITY-1778] Insulate sdk_install from failures (#1130)"

cli/commands/update.go, cli/commands/update_test.go
The plan name we should always show is apparently always deploy.
=> [INFINITY-1872] Plan name should always default to deploy.

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultSecretSpec.java
key.pem and .key are valid files
=> Allow file paths with . for Secrets; for example: key.pem or .key

frameworks/helloworld/tests/test_soak.py
`soak_secrets_update` and `soak_secrets_alive` are working. Also verified in a separate cluster with `secrets/hello-world` installed.
=> [SDK] Refactor hello world soak test

frameworks/cassandra/tests/test_overlay.py, frameworks/elastic/tests/test_overlay.py, frameworks/hdfs/tests/test_overlay.py, frameworks/helloworld/tests/test_overlay.py, frameworks/helloworld/tests/test_resource_refinement.py, frameworks/kafka/tests/test_overlay.py, frameworks/template/tests/test_overlay.py, testing/sdk_utils.py
=> Dont run resource refinement tests pre 1.10

frameworks/cassandra/tests/test_overlay.py, frameworks/cassandra/tests/test_sanity.py, frameworks/elastic/tests/test_overlay.py, frameworks/elastic/tests/test_shakedown.py, frameworks/hdfs/tests/test_overlay.py, frameworks/hdfs/tests/test_shakedown.py, frameworks/helloworld/tests/test_overlay.py, frameworks/kafka/tests/test_overlay.py, frameworks/kafka/tests/test_sanity.py, frameworks/template/tests/test_overlay.py, testing/sdk_utils.py
=> Skip metrics tests in 1.8 clusters.

test.sh
Streamline and update test.sh
https://jira.mesosphere.com/browse/INFINITY-1936
Based on INFINITY-1884 (ie, requires the new pytest-fixture method of stub-universe configuration).
=> make test.sh use pytest directly

frameworks/elastic/tests/test_overlay.py
- Replaced * import with individual items
- PEP-8 linting
=> [ELASTIC-104] Add Retry to test_indexing

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/AbstractStep.java
See surrounding code where locking is used
=> Lock AbstractStep.setStatus()

frameworks/cassandra/build.sh, frameworks/elastic/build.sh, frameworks/hdfs/build.sh, frameworks/helloworld/build.sh, frameworks/kafka/build.sh, frameworks/template/build.sh, tools/build_framework.sh, tools/build_go_exe.sh
Enable sane cli development cycles with a faster cli build iteration.
=> [INFINITY-1989] Add framework flag to just build the cli.

frameworks/helloworld/tests/test_secrets.py
dcos-enterprise PR#1121 is merged
=> [DCOS-17370] Enable test for DCOS_SPACE authorization

frameworks/helloworld/tests/test_soak.py
PS: CI does not run anything in frameworks/helloworld/tests/test_soak.py
=> Fix python environment in test

frameworks/kafka/tests/test_overlay.py
=> [INFINITY-1794][Kafka] Re-enabled overlay tests for strict

frameworks/elastic/tests/test_overlay.py
All overlay tests passed in CI
=> [INFINITY-1794][Elastic] Re-enabled overlay tests for strict

frameworks/cassandra/tests/test_backup_and_restore.py, frameworks/cassandra/tests/test_overlay.py
=> [INFINITY-1794][Cassandra] Re-enabled overlay tests for strict

frameworks/helloworld/tests/conftest.py, frameworks/helloworld/tests/test_canary_strategy.py, frameworks/helloworld/tests/test_discovery.py, frameworks/helloworld/tests/test_executor_volumes.py, frameworks/helloworld/tests/test_multistep_plan.py, frameworks/helloworld/tests/test_overlay.py, frameworks/helloworld/tests/test_placement.py, frameworks/helloworld/tests/test_recovery.py, frameworks/helloworld/tests/test_resource_refinement.py, frameworks/helloworld/tests/test_sanity.py, frameworks/helloworld/tests/test_secrets.py, frameworks/helloworld/tests/test_sidecar.py, frameworks/helloworld/tests/test_soak.py, frameworks/helloworld/tests/test_taskcfg.py, frameworks/helloworld/tests/test_uninstall.py, frameworks/helloworld/tests/test_web_url.py, frameworks/helloworld/universe/config.json
Create a v1 test (so that we have something that fails in strict)
=> [INFINITY-1968] Switch default to v0 for mesos api in HW

frameworks/helloworld/tests/test_soak.py
Installed dcos-enterprise-cli package in order for "dcos security" command to be available.
=> [INFINITY-1921] In Secrets soak test: installed dcos-enterprise-cli package

testing/sdk_install.py
Uninstall can fail if Cosmos can't talk to Marathon when the uninstall is initiated. This can cause test cleanups to leak. 
I've added a retry that reattempts uninstall if the error encountered contains "marathon".
Ideally, I'd just retry on any 5XX response, but Cosmos returns a 400 :/
=> [INFINITY-2186] Add retry to uninstall for marathon flakes

cli/commands.go, cli/commands/config.go, cli/commands/debug.go, cli/commands/state.go, cli/commands/update.go
* Move the config and state subcommands under a new debug subcommand
=> [INFINITY-1977] Clarify purpose in description of SDK CLI config and state subcommands

frameworks/cassandra/universe/marathon.json.mustache, frameworks/cassandra/universe/resource.json
Placeholder PR until an amend to link to prod bucket
=> [INFINITY-2052] Upgrade C*

docs/pages/tutorials/secrets-tutorial.md
```
- ```$ dcos hello-world pod list
+ ```
+ $ dcos hello-world pod list
```
=> Fix typos in Secrets tutorial

frameworks/kafka/universe/config.json
Addressing here what merge conflict removed in PR #1413
=> Follow up JSON file style fixes

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java
This attempts to avoid resources from failed initial launches.
=> Fix uninstall empty resources

sdk/scheduler/src/main/java/com/mesosphere/sdk/dcos/auth/ServiceAccountIAMTokenProvider.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/dcos/http/CustomRedirectStrategy.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStage.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/dcos/http/CustomRedirectStrategyTest.java
Fixes https://jira.mesosphere.com/browse/DCOS-17992
=> tls: Follow redirects if URL for strict cluster is non-HTTPS

cli/commands/testdata/requests/update-configuration-replace.json, cli/commands/update.go, cli/commands/update_test.go, frameworks/helloworld/universe/package.json, test-runner.sh, testing/sdk_upgrade.py
Also fixes a logging issue that @mellenburg was able to debug. May synchronize CI logs?
=> INFINITY-2204 Test new upgrade flow in hello-world

frameworks/helloworld/tests/test_tls.py, frameworks/kafka/tests/test_tls.py, testing/sdk_install.py
https://jira.mesosphere.com/browse/DCOS-18083
=> testing: Allow to override service account name and secret name in STRICT security mode

frameworks/helloworld/tests/test_soak.py, testing/sdk_upgrade.py
Installed hello-world CLI since it is now needed by upgrade test.
=> [INFINITY-1779] Exercise "new upgrade" flow in hello-world Soak upgrade test

docs/pages/developer-guide.md, docs/pages/operations-guide.md, docs/pages/tutorials/secrets-tutorial.md
- Move secrets section to Developers Guide
- Update links in secrets-tutorial.md
- Keep some portion in Operations Guide to explain authorization briefly
=> [NFINITY-2251] Move secrets in operations-guide.md to developers-guide.md

frameworks/helloworld/tests/test_recovery.py
1. Make the test a sanity test
2. Fix up sdk_cmd import to new style.
=> Graceful Shutdown Test Change

tools/release_builder.py
zipfile expects a seekable file-like object
=> Fix release script for .zip universes

conftest.py
https://jira.mesosphere.com/browse/INFINITY-2249
=> fetch rotated task logs on failure

sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorLocker.java
- Don't log "retrying" when we're not going to retry again
- Log when we succeeded
=> INFINITY-1618 Improve curator lock logging

tools/universe_builder.py
The rest of the changes are due to pep8 auto styling edits.
=> [INFINITY-2284] Up JRE from 131 to 144

frameworks/cassandra/tests/test_backup_and_restore.py
Will fix cassandra nightly failures: https://teamcity.mesosphere.io/viewLog.html?buildId=757984&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Cassandra_CompleteIntegrationTest
=> Fix broken import

frameworks/helloworld/tests/test_placement.py
Changed the tests to assert what the feature states, max_per and group_by placement rules provide an at most guarantee, not an exact match guarantee for the cardinality per host.
=> [INFINITY-2308] Fix flaky tests - helloworld placement

__init__.py, conftest.py, frameworks/cassandra/tests/__init__.py, frameworks/cassandra/tests/conftest.py, frameworks/elastic/tests/__init__.py, frameworks/hdfs/tests/__init__.py, frameworks/helloworld/tests/__init__.py, frameworks/kafka/tests/__init__.py, frameworks/template/tests/__init__.py, testing/sdk_utils.py
Need to update TeamCity configuration to take `*_slaves.json` and `*_state.json` as artifacts.
=> get additional mesos and cassandra info on failure

frameworks/cassandra/tests/test_sanity.py, frameworks/elastic/tests/test_sanity.py, frameworks/hdfs/tests/test_sanity.py, frameworks/kafka/tests/test_sanity.py, testing/sdk_cmd.py, testing/sdk_metrics.py, testing/sdk_repository.py
Tested this with HDFS (journal-0) and saw the stats being correctly emitted.
Majority of the changes are cosmetic due to pep8 auto styling.
=> [INFINITY-2301] Verify metrics reporting via correct container ID

sdk/bootstrap/ip.go, sdk/bootstrap/ip_test.go, sdk/bootstrap/main.go
1. Fix logic in container IP lookup.
2. Enhance logging in container IP lookup and assignment.
=> [INFINITY-23222] Fix bootstrap networking shim.

sdk/bootstrap/ip.go, sdk/bootstrap/ip_test.go, sdk/bootstrap/main.go
1. Fix logic in container IP lookup. (#1515)
2. Enhance logging in container IP lookup and assignment.
=> [INFINITY-23222] Fix bootstrap networking shim - backport

frameworks/helloworld/tests/test_recovery.py
* Fix up import, make test a sanity test
* CLI call changed
* Move setup so service is installed with correct kill policy
=> Graceful Shutdown Test Change (#1465) - backport

frameworks/kafka/docs/upgrade.md
=> [INFINITY-2236] Explain Kafka upgrade in strict mode 

frameworks/helloworld/tests/test_placement.py
This is a backport to fix the helloworld placement tests (#1498)
@paegun @benclarkwood please review.
=> [INFINITY-2308] Fix flaky tests - helloworld placement (#1498)

docs/pages/operations-guide.md
* Provide, since it otherwise doesn't exist, Plan subcommand
documentation. Include cross-command (see also) bits where relevant.
=> [INFINITY-2099] Improve Plan subcommand documentation

tools/release_builder.py
Allows any permutation of a beta/non-beta stub universe => beta/non-beta release.
Automatically updates the package name and version to reflect beta state as needed. This handling is now done up-front to make things a bit easier to follow. Complains if a `-beta` version is provided with `BETA` mode disabled. Meanwhile package names are always updated to reflect beta status as needed.
=> INFINITY-2336 Release builder fixes to beta vs non-beta handling

frameworks/hdfs/tests/test_sanity.py
INFINITY-2275: hdfs - replace import-time cluster actions
=> hdfs - replace import-time cluster actions

frameworks/template/tests/test_sanity.py
INFINITY-2278: template - replace import-time cluster actions
=> template - replace import-time cluster actions

frameworks/kafka/tests/test_sanity.py
INFINITY-2277: kafka - replace import-time cluster actions
=> kafka - replace import-time cluster actions

frameworks/helloworld/tests/config.py, frameworks/helloworld/tests/test_placement.py, frameworks/helloworld/tests/test_sanity.py
INFINITY-2276: helloworld - replace import-time cluster actions
=> helloworld - replace import-time cluster actions

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanCoordinator.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManagerTest.java
This is a pure refactor with no functional changes expected.
=> Decouple candidate generation from the offer cycle

frameworks/cassandra/universe/package.json, frameworks/elastic/build-kibana.sh, frameworks/elastic/universe-kibana/package.json, frameworks/elastic/universe/package.json, frameworks/hdfs/universe/package.json, frameworks/helloworld/build.sh, frameworks/helloworld/universe/package.json, frameworks/kafka/universe/package.json, frameworks/template/build.sh, frameworks/template/universe/package.json, tools/universe_builder.py
* Add templates for documentation-path
* Add templates for issues-path
* Update packaging and build scripts
=> DCOS-2106: Update post install documentation link.

frameworks/elastic/docs/connecting.md, frameworks/elastic/docs/install.md, frameworks/elastic/docs/managing.md, frameworks/elastic/docs/version_policy.md, frameworks/hdfs/docs/api-reference.md, frameworks/hdfs/docs/connecting-clients.md, frameworks/hdfs/docs/install.md, frameworks/hdfs/docs/managing.md, frameworks/hdfs/docs/quick-start.md, frameworks/hdfs/docs/uninstall.md, frameworks/kafka/docs/configure.md, frameworks/kafka/docs/index.md, frameworks/kafka/docs/limitations.md, frameworks/kafka/docs/quick-start.md, frameworks/kafka/docs/uninstall.md
* Remove remaining spurious feature_maturity flags.
* Remove feature maturity flag where it is preview.
* Remove feature maturity flag where it is experimental.
=> Remove feature maturity flag

frameworks/cassandra/universe/package.json, frameworks/hdfs/universe/package.json, frameworks/kafka/universe/package.json
Elastic and Kibana are already marked as selected.
=> Set Mag7 as selected in stable branch

frameworks/cassandra/universe/package.json, frameworks/elastic/build-kibana.sh, frameworks/elastic/universe-kibana/package.json, frameworks/elastic/universe/package.json, frameworks/hdfs/universe/package.json, frameworks/helloworld/build.sh, frameworks/helloworld/universe/package.json, frameworks/kafka/universe/package.json, frameworks/template/build.sh, frameworks/template/universe/package.json, tools/universe_builder.py
* backport changes from #1573 to 0.30.X branch
=> [DOCS-2106] Update post-install links for packages

frameworks/cassandra/docs/limitations.md, frameworks/elastic/docs/limitations.md, frameworks/hdfs/docs/limitations.md, frameworks/kafka/docs/limitations.md
Overwrites whatever was there before since it's probably out of date anyway
=> BACKPORT of limitations changes to 0.30.x

tools/build_framework.sh, tools/create_service_account.sh
(Backporting of fixes from k8s)
=> Fix disabling framework bits, and support parameters in create_service_account

frameworks/cassandra/docs/support.md, frameworks/elastic/docs/support.md, frameworks/hdfs/docs/support.md, frameworks/kafka/docs/support.md
* Backport version-policy.md >> support.md.
=> [NFINITY-2394] Ensure previous version-policy.md content is present

testing/sdk_jobs.py
=> INFINITY-2174 Use --json form of 'job run' command to get run ID

conftest.py
also try/catch all to avoid raising an
error within pytest
=> Dont collect completed logs

docs/pages/developer-guide.md
=> Backport INFINITY-2418 Dev guide plans fix

tools/airgap_linter.py
- make it aware of VIPs
- Make it not fail on mesos-dns addresses with ports
=> [INFINITY-2391] Enhance airgap linter to reduce false positives

sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/PodTestUtils.java
This is at the root of my `.equals()` pain.
=> Use real ServiceSpec objects for testing

frameworks/cassandra/docs/disaster-recovery.md, frameworks/cassandra/docs/quick-start.md, frameworks/cassandra/src/main/dist/svc.yml
Reverts mesosphere/dcos-commons#1658
=> Revert "Exit on restore-snapshot failure in Cassandra"

frameworks/cassandra/universe/package.json, frameworks/elastic/universe-kibana/package.json, frameworks/elastic/universe/package.json, frameworks/hdfs/universe/package.json, frameworks/helloworld/universe/package.json, frameworks/kafka/universe/package.json
Merge pull request #1643 from mesosphere/INFINITY-2375-update-post-install-notes.
[INFINITY-2375] Update postInstall notes.
@loren I also removed a beta notice from elastic, I assume that this is in order for 0.30.X?
=> [INFINITY-2375] Backport update of postinstall notes.

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DeploymentStep.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DeploymentStepTest.java
Unit tests fail on `master` pass on this PR
=> [INFINITY-2467] Fix incoherent Step status

frameworks/helloworld/universe/marathon.json.mustache
Reduces the scheduler footprint so we can run on m4.large
=> Reduce HW scheduler CPU to match others. (#1682)

testing/sdk_utils.py
* Tweak evaluation function
* Missing function invocation
* Update sdk_install.install parameter ordering
* Also set service name in install fixture.
* Fix "test", but then run into another issue and disable it for now. Ticket opened.
=> Fix EE check (#1599)

frameworks/hdfs/docs/api-reference.md, frameworks/hdfs/docs/install.md, frameworks/hdfs/docs/managing.md, frameworks/hdfs/docs/quick-start.md, frameworks/hdfs/docs/uninstall.md
https://jira.mesosphere.com/browse/DCOS-17877
=> Changes based on Marco's testing

frameworks/helloworld/tests/test_tls.py, tools/dcos_login.py
Login sporadically flakes out if attempted directly after deployment time
=> Retry login for up to 2 minutes

frameworks/elastic/tests/test_sanity.py
- Wait for recovery to begin and then wait for it to end
- Also moved `foldered_name` outside `try` in `configure_package` as it might get referenced in `finally` clause before it's initialized
=> [ELASTIC-149] Fix flaky pod replace tests

frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java, frameworks/template/src/test/java/com/mesosphere/sdk/template/scheduler/ServiceTest.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerRunner.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/ClusterState.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/Expect.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/Send.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/SendOffer.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/SendTaskStatus.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java
Adds Expect implementation for unreserves, adds some javadocs, uses better function names
=> Fixes for scheduler test API before presentation

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
No such thing as a flaky test.
=> Fix plan processing before reconciliation is complete

frameworks/hdfs/tools/kdc.json, frameworks/hdfs/tools/krb5.conf
@benclarkwood This is taken from the old kerberos HDFS branch.
=> Added KDC marathon app def

frameworks/elastic/universe/config.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mesosphere/dcos-commons/1761)
=> Add base64 encoding mediatype to elastic custom_yaml config

cli/commands/debug.go, cli/commands/pods_test.go, docs/pages/developer-guide.md, docs/pages/operations-guide.md, frameworks/helloworld/tests/test_recovery.py, sdk/scheduler/src/main/java/com/mesosphere/sdk/api/PodResource.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DeploymentStep.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/state/GoalStateOverride.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/api/PodResourceTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DeploymentStepTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/state/StateStoreTest.java
Docs fixes and whatever else comes up following PR #1763
=> INFINITY-2584/2596: Rename stop to pause, and followup fixes from PR 1763

frameworks/helloworld/tests/test_recovery.py, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DeploymentStep.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/ParentElement.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Status.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/state/GoalStateOverride.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/ExecutorEvaluationStageTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/LaunchEvaluationStageTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/NamedVIPEvaluationStageTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/PlacementRuleEvaluationStageTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStageTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStageTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStageTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DeploymentStepTest.java
This PR isn't perfect, but I wanted to get it out so people can comment.  It passes @nickbp 's integration tests.  I'll add some unit tests and rebase on master.
=> [INFINITY-2016] Override commands for pause a pod

test.sh
This PR adds an interactive mode to `test.sh`, meaning one can run:
```bash
$ ./test.sh -i
```
to drop into a docker container which can be used as a development environment.
Some things that may make this more useful:
=> Add an interactive mode to test.sh

tools/release_builder.py
Updates the release script to upload beta vs GA releases according to the following index ranges:
- ("Legacy": 0-999)
- Beta: 1000-9999
- GA: 10000-20000
(to give scale, the largest index right now is kafka at 42)
The caller can also manually specify a desired index using a new RELEASE_INDEX envvar.
This replaces the prior scheme of placing beta releases under a separate 'beta-' package name.
TODO: Our stub universe builds should also remove their current `beta-` prefixes, but for the short term there's no harm in leaving them in:
```
dcos-commons/frameworks$ grep -R "beta-" * | wc -l
227
```
(mostly from docs)
=> INFINITY-2653 Implement index ranges for GA vs beta releases

frameworks/kafka/src/main/dist/svc.yml, frameworks/kafka/universe/marathon.json.mustache, frameworks/kafka/universe/resource.json
Update to 1.0.0.
Update readiness check for new log line format.
=> [KAF-383] Update to 1.0.0.

testing/sdk_auth.py
base64-encoding currently breaks in the auth test module if the OS `base64` binary version is different from the one in the CI docker image. This PR removes this dependency.
=> Update base64 encoding in auth test module

test_requirements.txt, testing/sdk_jobs.py
Updates the mesosphere/dcos-commons:latest image to actually work
=> Bump pytest

frameworks/elastic/src/main/java/com/mesosphere/sdk/elastic/scheduler/Main.java, frameworks/hdfs/src/main/dist/core-site.xml, frameworks/hdfs/src/main/dist/hdfs-site.xml, frameworks/hdfs/src/main/dist/krb5.conf, frameworks/hdfs/src/main/dist/svc.yml, frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/Main.java, frameworks/hdfs/src/test/java/com/mesosphere/sdk/hdfs/scheduler/ServiceTest.java, frameworks/hdfs/tests/config.py, frameworks/hdfs/tests/test_auth.py, frameworks/hdfs/tests/test_tls.py, frameworks/hdfs/universe/config.json, frameworks/hdfs/universe/marathon.json.mustache, sdk/scheduler/src/main/java/com/mesosphere/sdk/config/TaskEnvRouter.java, testing/sdk_auth.py, tools/kdc.py
This PR cleans up some security configuration revolving Kerberos, in overlap with properly configuring the service for authz testing.
=> [INFINITY-2693] Kerberized HDFS authz test

docs/pages/developer-guide.md, frameworks/cassandra/docs/limitations.md, frameworks/cassandra/docs/node-settings.md, sdk/common/src/main/java/com/mesosphere/sdk/offer/taskdata/EnvConstants.java, sdk/common/src/main/java/com/mesosphere/sdk/offer/taskdata/EnvUtils.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TaskPortLookup.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/TaskPortLookupTest.java
- There's already some region/zone docs, just needed some more for Cassandra.
- Add listing of freebie envvars that are automatically injected into tasks.
=> INFINITY-2758/CASS-658 Document 'free' task env, and rack behavior

frameworks/hdfs/tests/test_auth.py
Reenable the HDFS KDC-based tests.
=> [INFINITY-2815] Reenable HDFS kdc tests

build.gradle
=> Bump version to 0.32.0-SNAPSHOT

frameworks/kafka/docs/kerberos.md, frameworks/kafka/docs/ssl-auth.md, frameworks/kafka/src/main/dist/krb5.conf.mustache, frameworks/kafka/tests/auth.py, frameworks/kafka/tests/test_kerberos_auth.py, frameworks/kafka/tests/test_kerberos_authz.py, frameworks/kafka/tests/test_zookeeper_auth.py, frameworks/kafka/universe/config.json, frameworks/kafka/universe/marathon.json.mustache
This PR splits #1871 into a separate PR for Kafka.
=> [INFINITY-2583][INFINITY-2829] Ensure uniform security settings for Kafka

frameworks/cassandra/docs/service-settings.md, frameworks/cassandra/src/main/dist/cassandra.yaml, frameworks/cassandra/src/main/dist/svc.yml, frameworks/cassandra/src/test/java/com/mesosphere/sdk/cassandra/scheduler/ServiceTest.java, frameworks/cassandra/tests/test_tls.py, frameworks/cassandra/universe/config.json, frameworks/cassandra/universe/marathon.json.mustache
The PR splits #1871 into a separate PR for Cassandra
=> [INFINITY-2583][INFINITY-2832] Ensure uniform security settings for Cassandra

frameworks/elastic/docs/install.md, frameworks/elastic/src/main/dist/elasticsearch.yml, frameworks/elastic/src/main/dist/svc.yml, frameworks/elastic/tests/test_tls.py, frameworks/elastic/universe-kibana/marathon.json.mustache, frameworks/elastic/universe/config.json, frameworks/elastic/universe/marathon.json.mustache
This PR splits #1871 into a separate PR for Elastic.
=> [INFINITY-2583][INFINITY-2831] Ensure uniform security settings for Elastic

frameworks/cassandra/universe/package.json, frameworks/elastic/universe/package.json, frameworks/hdfs/universe/package.json, frameworks/helloworld/tests/test_placement.py, frameworks/helloworld/universe/package.json, frameworks/kafka/universe/package.json
This reverts commit b28736a2870449cbfcdf72415d73df4fcb20c2a2.
=> Revert "Set min version to 1.10 (#1932)"

frameworks/elastic/universe/config.json, frameworks/template/universe/config.json
=> INFINITY-2769: Default to unique hostname constraint for Elastic.

frameworks/kafka/docs/kerberos.md, frameworks/kafka/docs/ssl-auth.md
Some minor doc fixes to the Kafka Kerberos and TLS docs found while creating mesosphere/confluent#89 for https://jira.mesosphere.com/browse/INFINITY-2833
=> [INFINITY-2833] Minor fixes to kerberos and TLS docs for kafka

frameworks/kafka/src/main/dist/svc.yml, frameworks/kafka/tests/test_sanity.py, frameworks/kafka/universe/marathon.json.mustache, frameworks/kafka/universe/resource.json
Update readiness check for new log line format.
=> [KAF-392] Update to 1.0.0. (#1852)

frameworks/hdfs/tests/test_racks.py, testing/sdk_fault_domain.py
`us-west-2c` => `aws/us-west-2c`
=> Catch up to DC/OS changing fault domains on AWS

build.sh
This is a follow-up PR to #1887 (and should have been included there)
The build step for the SDK can now be enabled correctly.
=> [INFINITY-2700] Add option to build.sh to run golang tests

frameworks/elastic/tests/config.py, frameworks/elastic/tests/test_overlay.py, frameworks/hdfs/tests/config.py, frameworks/hdfs/tests/test_overlay.py, frameworks/helloworld/tests/test_canary_strategy.py, frameworks/helloworld/tests/test_overlay.py, frameworks/helloworld/tests/test_sanity.py, frameworks/helloworld/tests/test_sidecar.py, frameworks/helloworld/tests/test_taskcfg.py, frameworks/kafka/tests/test_sanity.py, frameworks/kafka/tests/test_utils.py, testing/sdk_jobs.py, testing/sdk_marathon.py, testing/sdk_metrics.py, testing/sdk_plan.py, testing/sdk_tasks.py
do not use shakedown.wait_for as it is a more
limited and less expressive API
=> Refactor to use retrying.retry

docs/pages/developer-guide.md
Had something for the YAML reference, but lacked info in the dev guide.
=> INFINITY-2867 Add essential task documentation to dev guide

docs/pages/developer-guide.md, docs/pages/operations-guide.md, docs/pages/reference/yaml-reference.md, frameworks/cassandra/docs/managing.md, frameworks/cassandra/docs/node-settings.md, frameworks/cassandra/docs/service-settings.md, frameworks/cassandra/tests/test_racks.py, frameworks/elastic/docs/install.md, frameworks/elastic/tests/test_rack_awareness.py, frameworks/hdfs/docs/install.md, frameworks/kafka/README.md, frameworks/kafka/docs/install.md, frameworks/kafka/tests/test_rack_awareness.py, frameworks/template/docs/managing.md
I went through the documentation and code looking for uses of the old syntax for placement constraints. I think I got them all.
=> Update *every* placement constraint reference.

test.sh
This PR changes the expectation that a directory containing an AWS `credentials` file be provided to `test.sh` to a complete path to the file be provided.
This fixes #2027 reported by @seglo.
I have tested this locally, and `test.sh` still works as expected. @seglo confirms that this also works on Jenkins.
=> Require complete AWS credentials file path

frameworks/helloworld/tests/test_placement.py
This is a slightly interesting failure case.  The test which is causing a problem is explicitly violating our write ahead log (WAL) style bookkeeping.  The order of operations is as follows:
1. Write down all the operations we're about to perform in ZK
1. Perform operations
This test performs a [replace operation](https://github.com/mesosphere/dcos-commons/compare/fix_placement_tests?expand=1#diff-21a8119948b3209e78698f3b37f18d6aR273).  We see this in the logs.
```
INFO  2018-01-04 20:59:28,924 [pool-7-thread-1] com.mesosphere.sdk.scheduler.recovery.DefaultRecoveryPlanManager:createStep(322): Creating step: hello-0:[server](PERMANENT)
INFO  2018-01-04 20:59:28,925 [pool-7-thread-1] com.mesosphere.sdk.scheduler.recovery.DefaultRecoveryStep:setStatus(65): hello-0:[server]: changed status …
```
=> Fix WAL violation in test timing

frameworks/cassandra/docs/limitations.md
We don't use a docker container anymore. Dropping limitation.
=> Remove documentation of removed limitation

test.sh
Revert to previous behavior of passing -i to docker run, but also introduce a new flag (--headless) to enable the new behavior.
This is a tweak of: #2013.
That unintentionally returned the fun docker behavior of normal, human runs of test.sh bleeding docker containers since the interrupt isn't actually sent to STDIN.
=> Alter test.sh behavior around -i.

frameworks/hdfs/src/main/dist/svc.yml, frameworks/hdfs/universe/config.json, frameworks/hdfs/universe/marathon.json.mustache
=> [INFINITY-2783] HDFS: Make kerberos debug a configurable option with default false

testing/sdk_marathon.py
Upstreams a change made elsewhere.
=> Add force option to marathon update

tools/release_builder.py, tools/universe/package_publisher.py
- Release GAs at every 100 indexes by default, leaving space for hotfixes
- Release Betas sequentially (no index skipping)
- Support manual RELEASE_INDEX value for (GA) hotfixes
=> INFINITY-3007: Customized release indexing

docs/pages/tutorials/kafka-tutorial.md, frameworks/cassandra/tests/test_zzzrecovery.py, frameworks/helloworld/tests/test_taskcfg.py, frameworks/helloworld/tests/test_zzzrecovery.py, testing/sdk_tasks.py
Handle the case where multiple tasks are colocated on the host being shut down. Replace em all.
=> INFINITY-3026: Reenable shutdown test

frameworks/cassandra/tests/test_zzzrecovery.py, sdk/scheduler/src/main/java/com/mesosphere/sdk/http/PodResource.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/NotRule.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/DefaultTaskFailureListener.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/TaskFailureListener.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/http/PodResourceTest.java
Clean up placement constraint so that it doesn't block the shutdown host test
=> INFINITY-3041: Clean up placement constraint after test, improve logging

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
When determining whether we should reuse an executor we include tasks which are currently running, but are part of the current `PodInstanceRequirement`.  That means that we are actively trying to kill those tasks and attempting to reuse one of those executors is a bad idea.
It's not a fatal idea, as eventually we stop trying to reuse that executor, but it potentially wasted a whole cycle of offers.
=> Avoid attempting to reuse an executor which is about to be killed

conftest.py, frameworks/cassandra/tests/conftest.py, frameworks/elastic/tests/conftest.py, frameworks/hdfs/tests/conftest.py, frameworks/helloworld/tests/conftest.py, frameworks/kafka/tests/conftest.py, frameworks/template/tests/conftest.py, testing/sdk_cmd.py, testing/sdk_diag.py, testing/sdk_install.py, testing/sdk_plan.py, testing/sdk_utils.py
- Includes executor AND agent logs
- Much faster
- Much less flaky
Sample run:
```
[2018-01-26 01:27:50,597|build.conftest|INFO]: Test test_task_dns_prefix_points_to_all_tasks failed in call phase.
[2018-01-26 01:27:50,597|build.conftest|INFO]: Fetching logs for 3 tasks launched in this suite since last failure: hello-0-once__89bee575-fb8e-4930-9c36-ab150c394bfd, hello-0-server__f39b85d0-b68e-46c3-a35c-9ff0a8114d62, hello-world.d96e95ba-0237-11e8-b2f2-deead5f2b92b
[2018-01-26 01:27:50,756|sdk_cmd|INFO]: Got 200 for GET /mesos/tasks
[2018-01-26 01:27:50,935|sdk_cmd|INFO]: Got 200 for GET /slave/9eddb76d-3c78-4b50-8170-38d95060aa49-S4/files/debug
[2018-01-26 01:27:50,936|build.conftest|INFO]: Searching 2 paths for task Task[task_id=hello-0-server__f39b85d0-b68e-46c3-a35c-9ff0a8114d62 …
```
=> INFINITY-2998 Fetch logs using Mesos files API

conftest.py, frameworks/cassandra/tests/conftest.py, frameworks/elastic/tests/conftest.py, frameworks/hdfs/tests/conftest.py, frameworks/helloworld/tests/conftest.py, frameworks/kafka/tests/conftest.py, frameworks/template/tests/conftest.py, testing/sdk_cmd.py, testing/sdk_diag.py, testing/sdk_install.py, testing/sdk_plan.py, testing/sdk_utils.py
(backport of #2145)
- Includes executor AND agent logs
- Much faster
- Much less flaky
=> INFINITY-2998 Fetch logs using Mesos files API (backport)

frameworks/cassandra/src/test/java/com/mesosphere/sdk/cassandra/scheduler/ServiceTest.java, frameworks/elastic/src/test/java/com/mesosphere/sdk/elastic/scheduler/ServiceTest.java, frameworks/hdfs/src/test/java/com/mesosphere/sdk/hdfs/scheduler/ServiceTest.java, frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/scheduler/KafkaZoneValidator.java, frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/scheduler/Main.java, frameworks/kafka/src/test/java/com/mesosphere/sdk/kafka/scheduler/ServiceTest.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/ConfigValidatorUtils.java
1. Factor out zone validation test logic
1. Add zone validation to services
1. Add zone validation tests to services
=> Complete zone validation for all mono-repo services

frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/CassandraZoneValidator.java, frameworks/elastic/src/main/java/com/mesosphere/sdk/elastic/scheduler/ElasticZoneValidator.java, frameworks/elastic/src/main/java/com/mesosphere/sdk/elastic/scheduler/Main.java, frameworks/elastic/src/test/java/com/mesosphere/sdk/elastic/scheduler/ServiceTest.java, frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/HDFSZoneValidator.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/validation/ZoneValidator.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/validation/ZoneValidatorTest.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/Expect.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java
This is the first backport PR for fixing zone validation.
=> Fix zone validation and add validation to Elastic (#2165)

frameworks/cassandra/src/test/java/com/mesosphere/sdk/cassandra/scheduler/ServiceTest.java, frameworks/elastic/src/test/java/com/mesosphere/sdk/elastic/scheduler/ServiceTest.java, frameworks/hdfs/src/test/java/com/mesosphere/sdk/hdfs/scheduler/ServiceTest.java, frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/scheduler/KafkaZoneValidator.java, frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/scheduler/Main.java, frameworks/kafka/src/test/java/com/mesosphere/sdk/kafka/scheduler/ServiceTest.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/ConfigValidatorUtils.java
* Refactor zone validation testing
* Add Cassandra zone validation tests
* Add HDFS zone validation tests
* Add Kafka zone validation
=> Complete zone validation for all mono-repo services (#2168)

frameworks/hdfs/src/main/dist/hdfs-site.xml, frameworks/hdfs/universe/config.json, frameworks/hdfs/universe/marathon.json.mustache
A few settings are currently not exposed, as they must have been missed earlier when most settings became exposed.
This PR exposes these missed settings.
=> [HDFS-433] Add missing HDFS settings

frameworks/kafka/tests/test_zookeeper.py
sdk-0.40 backport PR for #2167
=> [INFINITY-3067] Fix zookeeper tests on Open

frameworks/helloworld/universe/package.json
PR to backport #2185 to 0.30.X
=>  [INFINITY-3076] Fix uninstall documentation link in hello-world postUninstallNotes.

frameworks/helloworld/universe/package.json
=> [INFINITY-3076] Fix uninstall documentation link in hello-world postUninstallNotes

docs/README.md, docs/pages/_includes/services/api-reference.md, docs/pages/_includes/services/install.md, frameworks/cassandra/docs/install.md, frameworks/cassandra/docs/node-settings.md, frameworks/cassandra/docs/service-settings.md, frameworks/elastic/docs/install.md, frameworks/hdfs/docs/install.md, frameworks/kafka/docs/install.md, frameworks/template/docs/install.md
=> INFINITY-3081 Cleanup of install docs (#2209)

docs/generate.sh, docs/pages/_config.yml, docs/pages/_layouts/layout.pug.html
=> INFINITY-3141 Fix redirects (#2225)

frameworks/hdfs/docs/install.md
=> INFINITY-3122 Fix HDFS documentation of service.name (#2232)

docs/pages/developer-guide.md, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanCustomizer.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/UninstallSchedulerTest.java
Backports the changes from #2214 plus #2223 that fixes a small typo in the docs.
=> [INFINITY-3113] Backport

frameworks/cassandra/src/main/dist/svc.yml, frameworks/cassandra/universe/marathon.json.mustache
Remove SCHEDULER_URI from Cassandra svc.yml
https://jira.mesosphere.com/browse/INFINITY-3146
=> Fixed Scheduler URI

frameworks/cassandra/src/main/dist/s3config.json, frameworks/cassandra/src/main/dist/svc.yml
=> CASSANDRA-672 Remove unused s3config.json (#2224)

cli/client/http.go
BACKPORT of #2241 
Use Go's `http.ProxyFromEnvironment` when performing requests to honor these envvars automatically, and align with the main DC/OS CLI's behavior.
=> INFINITY-3153 Support HTTP[S]_PROXY/NO_PROXY envvars (#2241)

sdk/scheduler/src/main/java/com/mesosphere/sdk/http/PodResource.java
Previously, if an un-prepared task was paused, the logic for returning that task's state would deem it `PAUSING`, and then `STARTING` when resumed. Since unprepared tasks have never been run and aren't slated to run, their task state in statuses should remain as `<UNKNOWN>`.
=> Fix reporting of state for overridden tasks that are not pending

frameworks/cassandra/src/main/dist/svc.yml, frameworks/cassandra/universe/marathon.json.mustache
=> Backport fix scheduler uri

tools/release_builder.py
Manually verified that this has the expected effect on the ouput package JSON.
=> Add UPGRADES_FROM envvar to release builder to allow upgrade/downgrade in soak

frameworks/helloworld/src/main/dist/examples/pod-mount-volume.yml, frameworks/helloworld/tests/test_mount_volumes.py, test_requirements.txt, tools/create_testing_volumes.py, tools/enable_mount_volumes.py
This test ensures mount volumes on shared executors and on individual tasks work.  It is currently blocked by DCOS-21261.
=> [INFINITY-3173] Add a mount volume test for hello-world

frameworks/cassandra/universe/resource.json, frameworks/elastic/universe/resource.json, frameworks/hdfs/universe/resource.json, frameworks/helloworld/universe/resource.json, frameworks/kafka/universe/resource.json
Ref:
https://jira.mesosphere.com/browse/INFINITY-3191
https://github.com/mesosphere/universe/pull/1711/files
=> Fix images infinity 3191

frameworks/kafka/docs/limitations.md, frameworks/kafka/tests/auth.py, frameworks/kafka/tests/conftest.py, frameworks/kafka/tests/test_toggle_security.py
This is a backport of #2137 and #2268.
[INFINITY-3035] Add test and documentation to toggle kafka security settings
=> [INFINITY-3035] Add test for toggling Kafka security settings

frameworks/cassandra/universe/resource.json, frameworks/elastic/universe/resource.json, frameworks/hdfs/universe/resource.json, frameworks/helloworld/universe/resource.json, frameworks/kafka/universe/resource.json
* Changed Image Download Source
* Removed beta
=> Fix images infinity 3191 (#2267)

tools/release_builder.py
This PR adds support for overriding the package name using an environment variable `PACKAGE_NAME`.
The default behaviour (in terms of getting the package name from the stub universe URL) remains the same.
=> [INFINITY-2835] Allow package name to be overridden with an envvar

docs/pages/_includes/services/common-operations.md, docs/pages/_includes/services/install2.md, docs/pages/_includes/services/overview.md
I also fixed instances of the old placement constraint syntax.
=> INFINITY-3154: Fix a couple of broken hash URL links.

tools/release_builder.py
=> [INFINITY-2835][BACKPORT] Allow package name to be overridden with a PACKAGE_NAME environment variable.

docs/pages/_includes/services/security-transport-encryption-clients.md, frameworks/cassandra/docs/security.md, frameworks/hdfs/docs/security.md, frameworks/kafka/docs/security.md
Resolves the last open edits from the previous PRs #2216, #2293.
=> [INFINITY-2977] Final security documentation edits

docs/pages/developer-guide.md
Prompted by this questions: https://mesosphere.slack.com/archives/C07PM5KHQ/p1519298500000094
This PR also fixes a badly formatted markdown nested list.
=> INFINITY-3248: Add note that custom auxiliary plans don't require additional resources.

docs/pages/developer-guide.md
Add note that custom auxiliary plans don't require additional resources.
=> [INFINITY-3248] Backport #2295 (mesosphere/INFINITY-3248-resource-sets-docs)

frameworks/hdfs/docs/install.md
This PR cleans up the discussion on HDFS service settings. I will create a ticket to track the improvement of the service docs in general for the service settings.
=> [INFINITY-3127] Cleanup HDFS service settings docs

frameworks/hdfs/docs/install.md
This is a clean backport of #2304
=> [INFINITY-3127][BACKPORT] update hdfs service docs

frameworks/hdfs/tests/config.py, frameworks/hdfs/tests/test_active_directory_auth.py, frameworks/hdfs/tests/test_overlay.py, frameworks/hdfs/tools/hdfsclient.json
This is a clean backport of #2327
=> [INFINITY-3285][BACKPORT] Fix HDFS tests using client docker container

frameworks/kafka/docs/limitations.md
=> [KAF-410] Document topic command security limitation (#2324)

frameworks/helloworld/tests/test_zzzrecovery.py
This is a clean backport of #2303.
=> [INFINITY-3047][BACKPORT] Re-enable tests that were blocked on a Mesos regression.

docs/pages/_data/services/cassandra.yml, docs/pages/_data/services/elastic.yml, docs/pages/_data/services/hdfs.yml, docs/pages/_data/services/kafka.yml, docs/pages/_includes/services/security-configure-transport-encryption.md, docs/pages/_includes/services/security-kerberos-ad.md, docs/pages/_includes/services/security-service-keytab.md, docs/pages/_includes/services/security-transport-encryption-lead-in.md, frameworks/cassandra/docs/security.md, frameworks/elastic/docs/security.md, frameworks/hdfs/docs/security.md, frameworks/kafka/docs/security.md
Update templates and security.md's to the right format for docs-site.
=> Refactor security docs for docs site

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManager.java
This is hacky.  I know it's hacky.  It works and we're short on time and it's a small change.   We need to do a redesign of recovery.  This approach is at the end of its rope.
=> Fix failure escalation detection

frameworks/kafka/build.sh, frameworks/kafka/src/test/java/com/mesosphere/sdk/kafka/scheduler/ServiceTest.java, frameworks/kafka/universe/marathon.json.mustache, frameworks/kafka/universe/resource.json, frameworks/kafka/versions.sh
Backport of https://github.com/mesosphere/dcos-commons/pull/2339
=> [BACKPORT] Derive Kafka version from a single source.

frameworks/hdfs/src/main/dist/svc.yml, frameworks/hdfs/tests/test_sanity.py
This is based on the commit made in #2351 to include the fix and allow passing of added tests in CI.
=> Journal node replace integration tests

frameworks/cassandra/universe/package.json, frameworks/hdfs/universe/package.json, frameworks/kafka/universe/package.json
Release builder handles making betas NOT selected.
=> Make packages selected.

frameworks/cassandra/universe/package.json, frameworks/hdfs/universe/package.json, frameworks/kafka/universe/package.json
Release builder handles making betas NOT selected.
=> Make packages selected. (#2356)

frameworks/helloworld/tests/test_multistep_plan.py, frameworks/helloworld/tests/test_resource_refinement.py, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceCleaner.java
Adds an integration test covering the work in #2363
=> [INFINITY-3331] Add integration test

testing/sdk_repository.py
* Make STUB_UNIVERSE_URL parsing more robust.
* Improve logging.
* Fail when repo can't be added.
* Python3.
* Add return statement
=> [INFINITY-3321] Kibana CI install failure (#2361)

frameworks/elastic/tests/config.py, frameworks/elastic/tests/test_sanity.py, frameworks/elastic/universe-kibana/marathon.json.mustache
[ELASTIC-175] Make X-Pack install successfully.
Backport of #2348
=> [ELASTIC-175] Backport Kibana fix

tools/publish_aws.py, tools/universe/package_builder.py, tools/universe/package_manager.py
This PR addresses some issues in dry run detected in a non-mono-repo framework.
=> [INFINITY-3329] Fix dryrun for package version and md5 hash

frameworks/kafka/tests/config.py, frameworks/kafka/tests/test_active_directory_zookeeper_auth.py, frameworks/kafka/tests/test_zookeeper.py, frameworks/kafka/tests/test_zookeeper_auth.py
=> [INFINITY-3328] Remove stub from ZooKeeper tests (#2359)

frameworks/hdfs/tests/test_kerberos_auth.py
=> [BACKPORT] Backport infinity 3366 skip kerberos test on 1.9

frameworks/elastic/tests/config.py
Backport of https://github.com/mesosphere/dcos-commons/pull/2390
=> [ELASTIC-179][BACKPORT] Fix Kibana command on 1.9 with localized change. (#2390)

frameworks/kafka/tests/test_zookeeper.py
Retry the log check in case reresolution occurs very quickly.
=> [INFINITY-3363] Add retry on re-resolution test

frameworks/helloworld/tests/test_region_awareness.py
@mrbrowning please review this. It fixes and issue with #2396. Sorry if I jumped the gun there.
I am running the nightlies here: https://teamcity.mesosphere.io/viewLog.html?buildId=1012075&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Sdk_Stri_DcOs111Strict
=> Correct JSON boolean

frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/CassandraSeedUtils.java, frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/Main.java, frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/Main.java, frameworks/helloworld/src/main/dist/custom_tld.yml, frameworks/helloworld/tests/test_custom_service_tld.py, frameworks/helloworld/universe/config.json, frameworks/helloworld/universe/marathon.json.mustache, frameworks/kafka/tests/auth.py, frameworks/kafka/tests/test_ssl_kerberos_custom_domain_auth.py, frameworks/kafka/universe/config.json, frameworks/kafka/universe/marathon.json.mustache, sdk/scheduler/src/main/java/com/mesosphere/sdk/http/EndpointUtils.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/http/EndpointsResource.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStage.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/security/CertificateNamesGenerator.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/http/EndpointUtilsTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/http/EndpointsResourceTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStageTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/security/CertificateNamesGeneratorTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/security/TLSArtifactsGeneratorTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/SchedulerConfigTestUtils.java, sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java, testing/sdk_hosts.py
Backport SDK level changes. (#2405)
Backport Kafka specifc changes (#2411)
=> [INFINITY-3363] Backport changes to allow Kafka to have a custom domain.

docs/pages/developer-guide.md
Add docs of SERVICE_TLD envvar behavior
=> [INFINITY-3363] Rough draft docs of custom TLD

frameworks/kafka/tests/test_zookeeper.py
=> [INFINITY-3363] Skip ZooKeeper reresolution test (#2418)

frameworks/hdfs/src/main/dist/svc.yml, frameworks/hdfs/universe/config.json, frameworks/hdfs/universe/marathon.json.mustache
=> INFINITY-3451: Backport INFINITY-3115 to sdk-0.40

tools/universe/package_builder.py
Backport https://github.com/mesosphere/dcos-commons/pull/2447
=> Bump libmesos bundle version

docs/README.md, frameworks/cassandra/README.md, frameworks/elastic/README.md, frameworks/hdfs/README.md, frameworks/helloworld/README.md, frameworks/template/README.md, govendor/README.md, testing/README.md
Clean up some dead links and old information preceding the docs migration
=> INFINITY-3480 Spring cleaning of auxiliary READMEs

Dockerfile, tools/distribution/UPDATING.md, tools/distribution/init
This is a straight backport #2427.
=> Add updating md (#2427)

frameworks/helloworld/src/main/java/com/mesosphere/sdk/helloworld/scheduler/Main.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultPodSpec.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/TaskUtilsTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/NamedVIPEvaluationStageTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStageTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStageTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/AgentRuleTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/AndRuleTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/AttributeRuleTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/HostnameRuleTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/NotRuleTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/OrRuleTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/RoundRobinByAttributeRuleTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultStepFactoryTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DeploymentStepTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/PlanUtilsTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/PodInstanceRequirementTestUtils.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/strategy/CanaryStrategyTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/validation/ZoneValidatorTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/PodTestUtils.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/TestPodFactory.java
Builder constructors should require all mandatory fields
=> Fix the DefaultPodSpec.Builder

test_requirements.txt
includes an update to create coreOS onprem clusters
=> Bump dcos-launch revision

conftest.py, frameworks/cassandra/tests/conftest.py, frameworks/elastic/tests/conftest.py, frameworks/hdfs/tests/conftest.py, frameworks/helloworld/README.md, frameworks/helloworld/tests/conftest.py, frameworks/kafka/tests/conftest.py, frameworks/kafka/universe/config.json, frameworks/template/tests/conftest.py, test.sh, testing/sdk_cmd.py, testing/sdk_package_registry.py, testing/sdk_repository.py, testing/sdk_security.py, testing/sdk_tasks.py, testing/sdk_utils.py, tools/ci/test_runner.sh
Addresses [INFINITY-3486](https://jira.mesosphere.com/browse/INFINITY-3486)
- Add `PACKAGE_REGISTRY_ENABLED` in docker run environment and set it to `true`.
- Add `PACKAGE_REGISTRY_STUB_URL` to parameters. Pass it to docker run.
~~Check partner repo changes~~ None applicable as of now. We can make some changes in future.
~~Create ticket to clean up stub universe for package registry~~ [INFINITY-3510](https://jira.mesosphere.com/browse/INFINITY-3510)
=> Add package registry option in stub universe tooling

build.gradle
```
$ ./gradlew dependencyUpdates
Parallel execution is an incubating feature.
:dependencyUpdates
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-all/maven-metadata.xml
Download https://jcenter.bintray.com/junit/junit/maven-metadata.xml
Download https://jcenter.bintray.com/com/github/stefanbirkner/system-rules/maven-metadata.xml
Download https://jcenter.bintray.com/org/mockito/mockito-all/maven-metadata.xml
Download https://jcenter.bintray.com/org/awaitility/awaitility/maven-metadata.xml
Download https://jcenter.bintray.com/io/dropwizard/dropwizard-core/maven-metadata.xml
Download https://jcenter.bintray.com/io/dropwizard/dropwizard-client/maven-metadata.xml
Download https://jcenter.bintray.com/io/dropwizard/dropwizard-jackson/maven-metadata.xml
Download …
```
=> Install gradle-versions-plugin.

build.gradle
Released 0.42.1 from Jenkins, now bumping up SNAPSHOT to be latest for branch.
=>  Bump to 0.42.2-SNAPSHOT

testing/sdk_auth.py, testing/sdk_utils.py, tools/kdc/kdc.py
@nickbp this adds the `persist` flag (False by default) that should allow your changes to proceed.
=> Fix KDC persistence for Testing

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java
=> Expose additional subtypes for Jackson in ScheduleBuilder

frameworks/helloworld/src/main/java/com/mesosphere/sdk/helloworld/scheduler/DecomissionCustomizer.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkRunner.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerRunner.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/decommission/DecommissionPlanFactory.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/multi/MultiServiceEventClient.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/http/types/PlanInfoTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/AbstractSchedulerTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/SchedulerBuilderTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/UninstallSchedulerTest.java
As discussed on Slack - feedback really appreciated!
=> Fix up plan customization for multiservice schedulers and enable further plan customization based on existing tasks

frameworks/cassandra/src/main/dist/svc.yml
Added plans backup-minio and restore-minio (Request #9012 Cassandra Backup to an internal S3 Storage)
=> DCOS_CASSANDRA-60 Backup to S3 compatible object storage server

frameworks/cassandra/src/main/dist/cassandra.yaml, frameworks/cassandra/universe/config.json, frameworks/cassandra/universe/marathon.json.mustache
https://jira.mesosphere.com/browse/DCOS-37792
=> [DCOS-37792] Configurable disk_failure_policy.

frameworks/cassandra/src/main/dist/cassandra.yaml, frameworks/cassandra/universe/config.json, frameworks/cassandra/universe/marathon.json.mustache
=> [DCOS-37792][BACKPORT] Configurable disk_failure_policy.

frameworks/kafka/tests/test_tls.py, testing/security/cipher_suites.py
- Don't blow up if we don't have the RFC name for an OpenSSL cipher.
- Warn us when OpenSSL includes new ciphers.
=> [DCOS-37811] Fix Kafka cipher test flakes

frameworks/kafka/tests/test_tls.py, testing/security/cipher_suites.py
Clean backport of https://github.com/mesosphere/dcos-commons/pull/2518.
=> [BACKPORT][DCOS-37811] Fix Kafka cipher test flakes.

frameworks/elastic/tests/config.py, frameworks/elastic/tests/test_overlay.py, frameworks/elastic/tests/test_sanity.py, frameworks/elastic/tests/test_tls.py, frameworks/hdfs/tests/test_tls.py
Backport of https://github.com/mesosphere/dcos-commons/pull/2349
=> [ELASTIC-172][BACKPORT] Add test that verifies that Kibana works against an ES cluster with TLS.

tools/publish_aws.py
We use this in Kubernetes builds to publish our nightly builds to predictable paths. We have a local update for it, but adding this to dcos-commons would simplify our upgrade process and lessen the chances of us breaking our nightly pipeline on upgrade.
=> make S3 dir name configurable via env var in same fashion as s3 bucket and path

frameworks/kafka/src/test/java/com/mesosphere/sdk/kafka/scheduler/ServiceTest.java, frameworks/kafka/universe/resource.json, frameworks/kafka/versions.sh
Updating kafka base tech from kafka 1.0.0 to kafka 1.1.0
=> Update kafka 1.1.0

frameworks/kafka/src/test/java/com/mesosphere/sdk/kafka/scheduler/ServiceTest.java, frameworks/kafka/versions.sh
Reverts mesosphere/dcos-commons#2509
cc @samvantran @mpereira
=> [DCOS-38318] Revert "Update kafka 1.1.0"

frameworks/elastic/tests/test_sanity.py, frameworks/elastic/tests/test_tls.py, testing/sdk_utils.py
https://issues.apache.org/jira/browse/MESOS-9008
=> DCOS-38238: Temporarily disable tests that are failing due to Mesos Fetcher regression.

sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/ReviveManager.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/framework/ReviveManagerTest.java
Address [DCOS-38469](https://jira.mesosphere.com/browse/DCOS-38469)
=> [DCOS-38469] Call suppress again on receiving an offer when we are suppressed

tools/airgap_linter.py, tools/build_go_exe.sh
Clean backport of https://github.com/mesosphere/dcos-commons/pull/2540.
=> [DCOS-37673][BACKPORT] Upstream buildchain modifications from edgelb.

Dockerfile, test_requirements.txt
https://jira.mesosphere.com/browse/DCOS-38633
fix: https://github.com/dcos/dcos-launch/commit/af3087cc45b51797de02002dc8119b3ecd90ddb9
=> Update dcos-launch version

docs/pages/developer-guide.md
Should we remove the "Pre-requisites" section too for now?
=> Remove "getting started" section.

test_requirements.txt
See https://github.com/dcos/dcos-launch/pull/162
=> [TOOLS] Update dcos_launch to latest SHA

frameworks/helloworld/tests/test_mono_to_multi_migrate.py, testing/sdk_upgrade.py, testing/sdk_utils.py
Address [DCOS-39979](https://jira.mesosphere.com/browse/DCOS-39979)
=> DCOS-39979 Fix test_mono_to_multi_upgrade failures in 1.10 Open Cluster

.pre-commit-config.yaml, frameworks/helloworld/tests/test_placement.py, frameworks/helloworld/universe/config.json, frameworks/helloworld/universe/marathon.json.mustache, testing/sdk_tasks.py
Tests for [DCOS-38727](https://jira.mesosphere.com/browse/DCOS-38727)
=> DCOS-38727 Add marathon constraints on helloworld scheduler

frameworks/kafka/tests/auth.py
Extracted the failure detection from #2636 to better track the changes.
=> [DCOS-39710] Investigate kafka acl test failures

frameworks/helloworld/tests/test_taskcfg.py
* Wait for deploy plan to kick off before checking for task state for taskcfg test.
=> DCOS-40376 Backport Wait for deploy plan to kick off before checking task state in taskcfg.

testing/sdk_plan.py
DCOS-41603 shows a case where a threshold of 2 failure is much too
strict.
=> [DCOS-41604, DCOS-41603] Fix cryptic message and relax failed tasks threshold.

frameworks/helloworld/tests/test_sanity.py
Can lead to extra restarts if the scheduler comes back and thinks a task isn't ready, causing failures in `check_tasks_not_updated` calls.
=> DCOS-42328 Ensure readiness checks have passed before triggering another change

test.sh
This PR updates `test.sh` with the one from `master` to fix integration with `edge-lb`.
This replaces #2693
=> Fix bugs in test.sh for edge-lb (#2696)

frameworks/hdfs/tests/test_default_kerberos_setup.py
This PR is a follow up for #2682 and is an attempt to unblock #2702. The changes are:
* Use a non-folderd service name for the test added in #2682 
* Include a `try-finally` block to prevent this test from affecting other tests if possible.
There is a mismatch in the security (service account) tooling between the `master` and `sdk-0.40` branches and this is a simple workaround.
Once this is merged, these changes can be included in #2702.
=> [DCOS-42818] Use non-foldered name for HDFS kerberos test

build.gradle
See also https://github.com/mesosphere/dcos-commons/releases/tag/0.54.0
=> Bump snapshot version to 55 following release of 0.54.0

frameworks/helloworld/src/main/dist/pod-profile-mount-volume.yml, frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java, frameworks/helloworld/tests/test_profile_mount_volumes.py, frameworks/helloworld/universe/config.json, frameworks/helloworld/universe/marathon.json.mustache, sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java, tools/create_testing_volumes.py
This PR adds an integration test for #2707. Changes include:
* Added a `hello.volume_profile` option to the Hello World service.
* Added an example YAML to test profile mount volumes.
* Created an additional MOUNT volume with profile "xfs" on every agent for the test.
=> [DCOS-40332] Integration tests for local profile volume support.

tools/build_package.sh
Hey,
Just stumbled upon this and thought it might help, feel free to dismiss if I'm on the wrong track here.
=> Add .dcos as publish option

Dockerfile, Dockerfile.base, renovate.json, tools/kdc/Dockerfile
Make sure it can manage the dockerfiles.
=> [DCOS-42575] Turn on renovatebot support.

sdk/bootstrap/main.go, sdk/bootstrap/main_test.go
Partial backport of #2748 (Refer the actual PR for more details).
=> [DCOS-44605] [Backport] Filter sensitive environment keys when printing to stdout/stderr

gradle/checkstyle/README.md, test.sh, testing/sdk_package_registry.py
Should be good to merge once https://github.com/mesosphere/dcos-enterprise/pull/3776 is merged.
=> [DCOS-43952] [TOOLS] Install readwrite registry from bootstrap registry

frameworks/helloworld/src/main/dist/pod-profile-mount-volume.yml, frameworks/helloworld/tests/test_profile_mount_volumes.py, frameworks/helloworld/universe/config.json, frameworks/helloworld/universe/marathon.json.mustache
This PR makes the pod-profile-mount-volume yaml configurable through `service.test_profile_volume` so it can be customized for soaking.
=> Made pod-profile-mount-volume service yaml more configurable.

tools/diagnostics/agent.py, tools/diagnostics/config.py, tools/diagnostics/service_bundle.py
Also:
- Show helpful message in the logs.
- Add TODO to code.
=> [DIAGNOSTICS] Don't raise exception when there's a missing agent.

tools/diagnostics/CHANGELOG.md, tools/diagnostics/create_service_diagnostics_bundle.sh
This fixes https://jira.mesosphere.com/browse/COPS-4366.
=> [DIAGNOSTICS] Release SDK Diagnostics v0.2.1.

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStage.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStageTest.java
=> DCOS-47365: Ensure port-range is an inclusive range.

tools/diagnostics/README.md, tools/diagnostics/service_bundle.py
- Adds new debug endpoints.
- Uses sdk_cmd.service_request instead of sdk_cmd.marathon_task_exec which didn't work on the endpoints.
- Fixes from previous PR #2915
=> DCOS-47532: Update SDK Diagnostic bundle to add new debuggability endpoints.

tools/universe/package_manager.py
See https://jira.mesosphere.com/browse/DCOS-49600 for why this is needed.
=> [DCOS-49600] Remove DryRunPackages

frameworks/hdfs/tests/config.py
I found that this helper is never used in the whole of this repository, so I removed it.
=> Remove unused helper 'get_kerberized_hdfs_client_app'

tools/airgap_linter.py, tools/ci/checks/run_pre_commit.sh, tools/create_testing_volumes.py, tools/dcos_login.py, tools/print_package_tag.py, tools/publish_aws.py, tools/publish_dcos_file.py, tools/publish_http.py, tools/release_builder.py, tools/save_properties.py, tools/universe/package.py, tools/universe/package_builder.py, tools/universe/package_manager.py, tools/universe/package_publisher.py, tools/universe/s3_uploader.py, tools/update_config_json.py, tools/validate_pip_freeze.py
This is a subset of #2979.
Please see the description there for more information.
I split it out as requested to allow for easier reviews.
=> Add mypy type hints to the 'tools' directory

tools/airgap_linter.py, tools/ci/checks/run_pre_commit.sh, tools/create_testing_volumes.py, tools/dcos_login.py, tools/print_package_tag.py, tools/publish_aws.py, tools/publish_dcos_file.py, tools/publish_http.py, tools/release_builder.py, tools/save_properties.py, tools/universe/package.py, tools/universe/package_builder.py, tools/universe/package_manager.py, tools/universe/package_publisher.py, tools/universe/s3_uploader.py, tools/update_config_json.py, tools/validate_pip_freeze.py
Reverts mesosphere/dcos-commons#2988 due to https://jira.mesosphere.com/browse/DCOS-50694
=> [DCOS-50694] Revert "Add mypy type hints to the 'tools' directory"

frameworks/cassandra/tests/config.py, frameworks/cassandra/tests/test_racks.py, testing/sdk_utils.py
Instead of checking against single region "us-west", added checks against all the valid regions.
=> [DCOS-49667] Fix test_rack to test against the region it was deployed in

Dockerfile.base
This is needed by https://github.com/mesosphere/dcos-commons/pull/2987
=> Install pkg-config required by pycairo pip

renovate.json
See https://renovatebot.com/docs/configuration-options/#updatenotscheduled
=> Disable renovatebot during weekdays

frameworks/cassandra/tests/config.py, frameworks/cassandra/tests/conftest.py, frameworks/cassandra/tests/nodetool.py, frameworks/cassandra/tests/test_backup_and_restore.py, frameworks/cassandra/tests/test_nodetool.py, frameworks/cassandra/tests/test_overlay.py, frameworks/cassandra/tests/test_racks.py, frameworks/cassandra/tests/test_sanity.py, frameworks/cassandra/tests/test_tls.py, frameworks/cassandra/tests/test_toggle_tls.py, frameworks/cassandra/tests/test_zzzrecovery.py
This is part of https://jira.mesosphere.com/browse/DCOS-48816.
=> Add type hints for cassandra framework

changelog.md, docs/reference/swagger-api/swagger-spec.yaml
Update documentation for newly added service status codes.
Backfill previous entries in changelog.
JIRA Ticket: [DCOS-49197](https://jira.mesosphere.com/browse/DCOS-49197)
=> SDK Service Status Codes Documentation Update

Jenkinsfile.dcos-commons
Needs tag discovery to be enabled to be active:
https://jenkins.io/blog/2018/05/16/pipelines-with-git-tags/
=> Build and push docker image on release tags too.

Jenkinsfile.dcos-commons
Now that it works as expected for the base image.
=> [DCOS-53417] Set sensible name for main image check job

build.gradle
I was under impression that doing this is a part of the release checklist?
Please merge this if it LGTY
=> Bump version to 0.56.1-SNAPSHOT post release

frameworks/cassandra/universe/package.json, frameworks/elastic/universe/package.json, frameworks/hdfs/universe/package.json
Changed the minDcosReleaseVersion parameter to 1.11 and postUninstallNotes parameter.
https://jira.mesosphere.com/browse/DCOS-53865
=> Set minDcosReleaseVersion parameter to 1.11.

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/RLimitSpec.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/RLimitSpecTest.java
Fix previous bugs with setting `RLIMIT_INFINITY` which was incorrectly set.
JIRA: DCOS-54802
=> [DCOS-54802] Add fixes for proper RLIMIT_INFINITY support.

CONTRIBUTING.md, README.md, build.gradle, changelog.md, docs/README.md, docs/generate.sh, docs/pages/developer-guide.md, docs/pages/faq.md, docs/pages/yaml-reference.md, tools/airgap_linter.py, tools/pip/setup.py, tools/universe/package_publisher.py
Resolves [DCOS-51992](https://jira.mesosphere.com/browse/DCOS-51992)
Audited the files to remove Non-HTTPS resources and references by replacing them with HTTPS ones.
The links were manually checked by browsing their https equivalent and replacing them in place.
=> [DCOS-51992] Auditing and changing Non-HTTPS resources & references to HTTPS

frameworks/cassandra/alerts/README.md, frameworks/cassandra/alerts/cassandra-rules.yml
Resolves [DCOS-52832](https://jira.mesosphere.com/browse/DCOS-52832)
Manually testing
=> [DCOS-52832] Add alerts as part of dcos-monitoring's alertmanager for Cassandra

tools/ci/launch_cluster.sh, tools/ci/test_runner.sh
The first parameter to `/venvs.sh` is the name of the virtual environment, and the rest are the command itself to be run in that virtual environment.
=> [HOTFIX][TOOLS] dcos-launch is supposed to be duplicated there.

build_output.txt, frameworks/cassandra/universe/config.json, frameworks/elastic/universe/config.json, frameworks/hdfs/universe/config.json
Cassandr, Elastic and HDFS config refactorings
=> Dcos 52817 use enum wherever possible in all fw configs

build_output.txt
I believe this was added mistakenly from #3098
=> [CLEANUP] Delete unnecessary files

frameworks/hdfs/src/main/dist/svc.yml, frameworks/hdfs/universe/config.json, frameworks/hdfs/universe/marathon.json.mustache
This branch contains the code which supports adding DSS volume profiles to Hdfs framework.
=> [DCOS-54752] Add DSS volume profile support

frameworks/cassandra/src/main/dist/svc.yml, frameworks/cassandra/tests/config.py, frameworks/cassandra/tests/test_auth.py
Fixes [DCOS-55533](https://jira.mesosphere.com/browse/DCOS-55533)
Manually tested
=> DCOS-55533 [Cassandra] fix restore and backup with authentication/authorization enabled

frameworks/cassandra/universe/config.json
Noticed via https://github.com/mesosphere/universe/pull/2326/ in https://teamcity.mesosphere.io/viewLog.html?buildId=2037552&buildTypeId=Oss_Universe_Ci&guest=1 
Looks this was added via #3098
=> [Cleanup] Remove unwanted characters from cassandra's config.json

sdk/scheduler/src/main/java/com/mesosphere/sdk/config/DefaultConfigurationUpdater.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/DefaultConfigValidators.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/ServiceRoleCannotChangeOnIncompleteDeployment.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkConfig.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkRunner.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultResourceSet.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/NamedVIPSpec.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/PortSpec.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/framework/FrameworkRunnerTest.java
- Add support for changing of roles via `pod replace` operations.
=> [WIP] SDK - Change Roles via Pod-Replace

Jenkinsfile.dcos-commons, Jenkinsfile.dcos-commons-base
=> [DCOS-55083] Pass more params to setBuildStatus to fix status checks

Jenkinsfile.dcos-commons, Jenkinsfile.dcos-commons-base
See [DCOS-57125](https://jira.mesosphere.com/browse/DCOS-57125) for more details
=> [DCOS-57125] Add --squash to docker build command to reduce CI runtime

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultHostVolumeSpec.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/HostVolumeSpec.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawHostVolume.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/VerifyHostVolumePathTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultServiceSpecTest.java, sdk/scheduler/src/test/resources/valid-host-volume.yml, sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java
mode was previously defaulted to RW, now a user can pass RO to override this
=> Allow configuration of the host volume mode

testing/sdk_networks.py
Copied from this PR: https://github.com/mesosphere/spark-build/pull/468
=> Add helper methods to sdk_networks to get task IP & subnet

tools/ci/checks/run_pre_commit.sh
Related data-services-ci PR: https://github.com/mesosphere/data-services-ci/pull/72
=> [TOOLS] Fix run_pre_commit script for submodule-based projects.

conftest.py, frameworks/helloworld/tests/test_quota_deployment.py, frameworks/helloworld/tests/test_quota_downgrade.py, frameworks/helloworld/tests/test_quota_upgrade.py, frozen_requirements.txt, testing/sdk_marathon.py
Isolate cause of test-failures.
=> WIP DNM: Sdk quota isolate si failures

Dockerfile.base
=> Bump to jdk11 in Dockerfile.base

tools/distribution/copy-files
Added `run_container.sh` to the list of files which are being copied to the target folders.
=> Added run_container.sh to copy files list.

frameworks/hdfs/universe/marathon.json.mustache, frameworks/hdfs/universe/resource.json
Resolves [DCOS-59202](https://jira.mesosphere.com/browse/DCOS-59202)
=> [DCOS-59202][HDFS] Update base-tech to v3.2.1

build.gradle
Setting this back to what it should be now that DCOS-58875 is done.
cc @mediapills
=> Set version to match the policy.

tools/release_builder.py
- Added  package name loader from the stub universe URL
=> [DCOS-29593] Use introspection of stub universe JSON to determine package name

testing/sdk_plan.py, testing/sdk_tasks.py
dcos-history service was recently removed via mesosphere/dcos-enterprise/pull/6695 
Related JIRA [DCOS-58529](https://jira.mesosphere.com/browse/DCOS-58529)
=> Remove usage of dcos-history-service

changelog.md
https://github.com/mesosphere/dcos-commons/releases/tag/0.57.2
=> Add changelog entry for 0.57.2

tools/build_package.sh, tools/publish_azure.py, tools/universe/__init__.py, tools/universe/azure_uploader.py
Added a python script to publish the universes from Azure blob storage
=> Added new publisher for azure blob storage

tools/publish_azure.py
Fix for the Azure Blob Storage Publisher.
Incomplete uri fixed
=> Azure URIs fixed

renovate.json
- Run renovate bot only once a month.
- Add more reviewers.
=> Update Renovate Bot Frequency

frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/CassandraRecoveryPlanOverrider.java, frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/HdfsRecoveryPlanOverrider.java, frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/TaskUtils.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluationUtils.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanUtils.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManager.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/RecoveryStep.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/constrain/AllLaunchConstrainer.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/constrain/LaunchConstrainer.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/constrain/TestingLaunchConstrainer.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/constrain/TimedLaunchConstrainer.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/constrain/UnconstrainedLaunchConstrainer.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultServiceSpec.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManagerTest.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/recovery/TimedLaunchConstrainerTest.java
This reverts commit 6cc9bf01 "Remove launch constrainer for SDK 60 (#3165) (#3176)"
=> Revert "Remove launch constrainer for SDK 60 (#3165) (#3176)"

frozen_requirements.txt
=> Revert PR #3287 due to dependency on pytest-dcos

frameworks/cassandra/universe/config.json, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ExternalVolumeProviderFactory.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/NetAppVolumeProvider.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PortworxVolumeProvider.java, sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java, sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/ReplacementFailurePolicyTest.java
* Adds a class for NetApp External Volume Provider
* Adds driver options parameter in `PodInfoBuilder`
=>  Adds a class to support Netapp driver for External Storage
