mesosphere/dcos-commons

build.gradle

Without these lines there were compiler errors about missing missing zookeeper.
`package org.apache.zookeeper does not exist`

Missing Zookeeper gradle dependency

---

build.gradle
src/main/java/org/apache/mesos/state/CuratorStateStore.java
src/main/java/org/apache/mesos/state/StateStore.java
src/test/java/org/apache/mesos/state/CuratorStateStoreTest.java

This allows the whole state store to be iterated over for retrieval of
all information

Add fetchExecutorNames to StateStore interface

---

build.gradle
src/main/java/org/apache/mesos/offer/ResourceCleaner.java
src/main/java/org/apache/mesos/state/StateStore.java
src/test/java/org/apache/mesos/offer/ResourceCleanerTest.java

Users shouldn't be concerned with the extraction of resource and
persistence IDs.  They should also be able to leverage the StateStore
interface

Change construction options for the ResourceCleaner

---

build.gradle

Provides a root-level percentage in stdout, as well as a per-package/class report in build/jacoco/index.html

Add test coverage to output of 'gradle check'

---

build.gradle
src/main/java/org/apache/mesos/offer/MesosResourcePool.java
src/main/java/org/apache/mesos/offer/OfferEvaluator.java
src/test/java/org/apache/mesos/offer/OfferEvaluatorTest.java

Updating a mount volume resource requirement cannot result in additional RESERVE or
UNRESERVE Operations.  However, it must be validated that the new
requirement is still met.

Fix mount volume update

---

src/main/java/org/apache/mesos/state/CuratorStateStore.java
src/test/java/org/apache/mesos/state/CuratorStateStoreTest.java

- Bug: Don't return the Framework ID as an executor name (test added)
- Nit: Have the underlying curator interface be a member rather than
a superclass
- Nit: Cleanup to logging, use slf4j's built-in formatting
- Nit: Various tweaks/additions to comments

Nitpicks and one bug fix for CuratorStateStore

---

.gitignore
build.gradle
src/main/java/org/apache/mesos/state/CuratorStateStore.java
src/main/java/org/apache/mesos/state/StateStore.java
src/test/java/org/apache/mesos/state/CuratorStateStoreTest.java

When a TaskStatus is reported by Mesos the Executor name is not readily
available.  The requirement of providing the Executor name has been
removed.

Improve StateStore interface

---

build.gradle
src/main/java/org/apache/mesos/executor/ExecutorUtils.java
src/main/java/org/apache/mesos/offer/ExecutorRequirement.java
src/main/java/org/apache/mesos/offer/InvalidRequirementException.java
src/main/java/org/apache/mesos/offer/OfferRequirement.java
src/main/java/org/apache/mesos/offer/TaskRequirement.java
src/main/java/org/apache/mesos/offer/TaskUtils.java
src/main/java/org/apache/mesos/protobuf/ExecutorInfoBuilder.java
src/main/java/org/apache/mesos/scheduler/plan/api/BlockInfo.java
src/main/java/org/apache/mesos/state/CuratorStateStore.java
src/main/java/org/apache/mesos/state/StateStore.java
src/test/java/org/apache/mesos/executor/ProcessTaskTest.java
src/test/java/org/apache/mesos/offer/ExecutorRequirementTest.java
src/test/java/org/apache/mesos/offer/OfferEvaluatorTest.java
src/test/java/org/apache/mesos/offer/OfferRequirementTest.java
src/test/java/org/apache/mesos/offer/ResourceTestUtils.java
src/test/java/org/apache/mesos/offer/TaskRequirementTest.java
src/test/java/org/apache/mesos/scheduler/plan/DefaultStageSchedulerTest.java
src/test/java/org/apache/mesos/state/CuratorStateStoreTest.java

- TaskInfo requirements:
- must have a name
- if task id is non-empty, it must align with the name
- if executor is provided, it must have a name (only at StateStore)
- ExecutorInfo requirements:
- must have a name
- if executor id is non-empty, it must align with the name
- TaskStatus requirements (only at StateStore):
- must have a valid/parseable task id
- must have a valid/parseable executor id

Require valid names/ids in data passed to OfferEvaluator/StateStore

---

build.gradle
src/main/java/org/apache/mesos/state/CuratorStateStore.java

Having CuratorStateStore scan the root directly causes it to
misinterpret data which was put there by other sources, eg
CuratorConfigStore's [fwkname]/Configurations/[confid]/.
To CuratorStateStore, this path would look like an execName of
"Configurations" and a taskName of "[confid]".
This also allows us to remove CuratorStateStore's check to avoid
listing the FrameworkID file as an executor name.

Move task state into a 'Tasks' subdir

---

build.gradle
src/main/java/org/apache/mesos/config/CuratorConfigStore.java
src/main/java/org/apache/mesos/offer/ExecutorRequirement.java
src/main/java/org/apache/mesos/offer/OfferAccepter.java
src/main/java/org/apache/mesos/offer/OfferRequirement.java
src/main/java/org/apache/mesos/offer/ResourceCleaner.java
src/main/java/org/apache/mesos/state/CuratorStateStore.java
src/main/java/org/apache/mesos/state/StateStore.java
src/test/java/org/apache/mesos/offer/ResourceCleanerTest.java
src/test/java/org/apache/mesos/state/CuratorStateStoreTest.java

Consistently getting an executor id is a surprisingly difficult exercise. Switch to a flatter structure where we just require that distinct tasks have unique task names.
This also simplifies things a bit for the developer -- they now only need to think about task names; 'execName' is gone.

Remove Executor Name from task paths

---

src/main/java/org/apache/mesos/offer/OfferAccepter.java

This is needed so that frameworks (e.g., dcos-cassandra-service) can customize the filter.refuse_seconds when they accept offers.

Add an accept function with customizable filters in OfferAccepter

---

build.gradle
src/main/java/org/apache/mesos/offer/OfferEvaluator.java
src/test/java/org/apache/mesos/offer/OfferEvaluatorTest.java

Tasks in the same OfferRequirement should all share the same Executor
and therefore ExecutorIDs

Fix ExecutorId alignment

---

build.gradle
src/main/java/org/apache/mesos/executor/ProcessTask.java
src/main/java/org/apache/mesos/offer/OfferEvaluator.java
src/test/java/org/apache/mesos/offer/OfferEvaluatorTest.java

If an OfferRequirement was not satisfied on the first Offer, all Offers were being rejected.  The test included here failed without the provided fix.  The rest of the change is refactoring of test code for clarity.

Fix offer evaluation loop bug.

---

build.gradle
src/main/java/org/apache/mesos/scheduler/plan/DefaultStageManager.java
src/main/java/org/apache/mesos/state/CuratorStateStore.java
src/main/java/org/apache/mesos/state/StateStore.java
src/main/java/org/apache/mesos/state/StateStoreUtils.java
src/main/java/org/apache/mesos/state/api/PropertyDeserializer.java
src/main/java/org/apache/mesos/state/api/StateResource.java
src/test/java/org/apache/mesos/executor/CustomExecutorTest.java
src/test/java/org/apache/mesos/state/CuratorStateStoreTest.java

May be optionally supported by individual frameworks (by either providing or omitting the PropertyDeserializer). Adds a new /properties endpoint to StateResource to match.
Also:
- Refrain from throwing an error when listing or clearing Properties that aren't available (mirroring current task list/clear behavior)
- Set some noisy logs as 'debug'

Add support for viewing Properties data, add 1MB value requirement

---

build.gradle
src/main/java/org/apache/mesos/dcos/Capabilities.java
src/main/java/org/apache/mesos/dcos/DcosCluster.java
src/main/java/org/apache/mesos/dcos/DcosVersion.java
src/main/java/org/apache/mesos/offer/OfferEvaluator.java
src/test/java/org/apache/mesos/dcos/CapabilitiesTest.java
src/test/java/org/apache/mesos/dcos/DcosClusterTest.java
src/test/java/org/apache/mesos/dcos/DcosVersionTest.java
src/test/java/org/apache/mesos/dcos/MockDcosCluster.java

In order to make decisions regarding whether or not to attempt to use a particular feature it is necessary to know whether a particular version of DC/OS supports the feature.  The code here exposes the first example of determining whether a capability (named VIPs) is supported.

Add DCOS Cluster Capabilities

---

.gitignore
build.sh
cli/README.md
cli/_example/.gitignore
cli/_example/build-all.sh
cli/_example/main.go
cli/commands.go
cli/http.go
cli/response.go
cli/runcli.go
gradle.properties

The current Python-based CLI modules are very simple (thin convenience wrappers around HTTP endpoints), but building Python binaries is very complicated/brittle. To resolve this, let's use a language that's trivial to cross-compile.
Includes:
- Helpers for:
- Querying the service (with auth token/url automatically pulled from 'dcos config')
- Pretty-printing data
- Implementations of all common scheduler HTTP endpoints (e.g. plan/config/state)
- Easy for developers to add custom commands for implementation-specific endpoints.
- 'Example' CLI module which adds an `echo` command on top of the common commands, as a sample of what a framework developer would do.
- Sample `build.sh` for building Lin/Win/Mac binaries from any system which has go tools installed (see README)

Implement a Go-based CLI module SDK

---

cli/commands.go
cli/http.go
cli/runcli.go

New EE systems have custom-generated TLS certs

Allow unverified TLS certs, reuse err handling for 'plan show'

---

cli/_example/main.go
cli/commands.go
cli/http.go

CLI will be using the existing 'core.ssl_verify' config param to point to any custom cert
Also: Make common actions public to allow implementors to reuse them, useful for e.g. aliasing a different command to 'plan show'.

Finish TLS cert config handling, misc interface improvements

---

build.gradle
docs/automatic-repair.md
src/main/java/org/apache/mesos/config/RepairConfiguration.java
src/main/java/org/apache/mesos/scheduler/repair/RepairOfferRequirementProvider.java
src/main/java/org/apache/mesos/scheduler/repair/RepairResource.java
src/main/java/org/apache/mesos/scheduler/repair/RepairScheduler.java
src/main/java/org/apache/mesos/scheduler/repair/RepairStatus.java
src/main/java/org/apache/mesos/scheduler/repair/TaskFailureListener.java
src/main/java/org/apache/mesos/scheduler/repair/constrain/AllLaunchConstrainer.java
src/main/java/org/apache/mesos/scheduler/repair/constrain/LaunchConstrainer.java
src/main/java/org/apache/mesos/scheduler/repair/constrain/TestingLaunchConstrainer.java
src/main/java/org/apache/mesos/scheduler/repair/constrain/TimedLaunchConstrainer.java
src/main/java/org/apache/mesos/scheduler/repair/constrain/UnconstrainedLaunchConstrainer.java
src/main/java/org/apache/mesos/scheduler/repair/monitor/FailureMonitor.java
src/main/java/org/apache/mesos/scheduler/repair/monitor/NeverFailureMonitor.java
src/main/java/org/apache/mesos/scheduler/repair/monitor/TestingFailureMonitor.java
src/main/java/org/apache/mesos/scheduler/repair/monitor/TimedFailureMonitor.java
src/main/java/org/apache/mesos/state/StateStore.java
src/test/java/org/apache/mesos/scheduler/RepairSchedulerTest.java

This PR implements a new scheduler called `RepairScheduler`. This helps frameworks handle failure & restarts for persistent-disk based applications.
This is implementation complete, but still needs tests that do not depend on the proprietary libraries they were originally developed against.

Automatically repairing scheduler implementation

---

src/main/java/org/apache/mesos/dcos/Capabilities.java
src/main/java/org/apache/mesos/dcos/DcosVersion.java
src/test/java/org/apache/mesos/dcos/CapabilitiesTest.java
src/test/java/org/apache/mesos/dcos/DcosClusterTest.java

Stays pretty strict for now, supporting only '-dev', and only on the second element.
Moves version element extraction upstream in case other utils need it someday.

Fix version check for case of "1.8-dev"

---

build.gradle
src/main/java/org/apache/mesos/scheduler/plan/Block.java
src/main/java/org/apache/mesos/scheduler/plan/DefaultInstallStrategy.java
src/main/java/org/apache/mesos/scheduler/plan/DefaultStageManager.java
src/main/java/org/apache/mesos/scheduler/plan/DefaultStageStrategy.java
src/main/java/org/apache/mesos/scheduler/plan/PhaseStrategy.java
src/main/java/org/apache/mesos/scheduler/plan/Stage.java
src/main/java/org/apache/mesos/scheduler/plan/Status.java
src/main/java/org/apache/mesos/scheduler/plan/api/CurrentlyActiveInfo.java
src/main/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryRequirement.java
src/main/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryScheduler.java
src/main/java/org/apache/mesos/scheduler/recovery/RecoveryRequirement.java
src/main/java/org/apache/mesos/scheduler/recovery/RecoveryRequirementProvider.java
src/main/java/org/apache/mesos/scheduler/recovery/RecoveryRequirementUtils.java
src/main/java/org/apache/mesos/scheduler/recovery/constrain/AllLaunchConstrainer.java
src/main/java/org/apache/mesos/scheduler/recovery/constrain/LaunchConstrainer.java
src/main/java/org/apache/mesos/scheduler/recovery/constrain/TestingLaunchConstrainer.java
src/main/java/org/apache/mesos/scheduler/recovery/constrain/TimedLaunchConstrainer.java
src/main/java/org/apache/mesos/scheduler/recovery/constrain/UnconstrainedLaunchConstrainer.java
src/test/java/org/apache/mesos/scheduler/plan/DefaultStageManagerTest.java
src/test/java/org/apache/mesos/scheduler/plan/DefaultStageSchedulerTest.java
src/test/java/org/apache/mesos/scheduler/plan/DefaultStageStrategyTest.java
src/test/java/org/apache/mesos/scheduler/plan/TestBlock.java
src/test/java/org/apache/mesos/scheduler/plan/api/CurrentlyActiveInfoTest.java
src/test/java/org/apache/mesos/scheduler/plan/api/StageInfoTest.java
src/test/java/org/apache/mesos/scheduler/plan/api/StageResourceTest.java
src/test/java/org/apache/mesos/scheduler/recovery/RecoverySchedulerTest.java
src/test/java/org/apache/mesos/scheduler/recovery/TimedLaunchConstrainerTest.java

The RecoveryScheduler was throttling recovery operations regardless of
whether they were in reaction to a permanent or transient failure.  Only
destructive permanent recovery operations should be throttled.

Fix recovery throttling defect.

---

acme-scheduler-example/src/dist/conf/scheduler.yml
acme-scheduler-example/src/main/java/org/apache/mesos/acme/config/AcmeConfiguration.java
acme-scheduler-example/src/main/java/org/apache/mesos/acme/config/DropwizardConfiguration.java
acme-scheduler-example/src/main/java/org/apache/mesos/acme/config/ServiceConfiguration.java

JSON properties should always be in snake case for consistency. Only the Acme scheduler example is affected here.

Move serialized object members to snake_case

---

acme-scheduler-example/src/main/java/org/apache/mesos/acme/scheduler/AcmeScheduler.java
build.gradle
src/main/java/org/apache/mesos/curator/CuratorStateStore.java
src/main/java/org/apache/mesos/reconciliation/DefaultReconciler.java
src/main/java/org/apache/mesos/reconciliation/Reconciler.java
src/main/java/org/apache/mesos/scheduler/plan/ReconciliationBlock.java
src/main/java/org/apache/mesos/scheduler/plan/ReconciliationPhase.java
src/main/java/org/apache/mesos/state/StateStore.java
src/test/java/org/apache/mesos/executor/HealthCheckHandlerTest.java
src/test/java/org/apache/mesos/executor/ProcessTaskTest.java
src/test/java/org/apache/mesos/reconciliation/DefaultReconcilerTest.java
src/test/java/org/apache/mesos/scheduler/plan/DefaultStageManagerTest.java
src/test/java/org/apache/mesos/scheduler/plan/ReconciliationBlockTest.java
tools/launch_ccm_cluster.py

To ensure that task statuses are all coming from a single source of truth, this alters the `Reconciler` interface so that the `start()` method no longer accepts a list of `TaskStatus` protos. Instead, it is expected that the implementing class will accept a `TaskStatusProvider` in its constructor, which it will consult to fetch a collection of all task statuses currently known by the scheduler. To this end, the `StateStore` interface now extends the `TaskStatusProvider` interface with its `getTaskStatuses()` method. All default implementations of these interfaces now reflect the new semantics.

Supply Reconciler with TaskStatusProvider in constructor and remove from arguments in start method

---

cli/commands.go
cli/http.go

Nothing that should break compatibility for current API users,
effectively adding hooks into existing code

Allow access to configured service name, and split url vs request creation

---

cli/commands.go
cli/http.go
cli/response.go

Fetches the CLI TLS setting once and then caches it.

Expose printing json bytes, and have explicit enum for TLS auth modes

---

.gitignore
tools/README.md
tools/ci_upload.py
tools/github_update.py
tools/launch_ccm_cluster.py
tools/run_tests.py

Bootstraps/runs both shakedown and dcos-tests, the latter notably without a docker image for the CLI.

Switch to WORKSPACE, get run_tests.py to actually work

---

src/test/java/org/apache/mesos/executor/HealthCheckHandlerTest.java
src/test/java/org/apache/mesos/scheduler/DefaultSchedulerTest.java

1. The DefaultSchedulerTest had a race.  It's possible Offers are
accepted, and the test validates their contents and then tries to
validate Block state before the Block has been called back alerting it
to the success or failure of it's launch.
2. Hard to say why the HealthCheck testSuccess was failing.  There was a
shared threadpool for all tests with a single thread.  Perhaps this was
causing trouble as it dealth with handling failed threads and starting
new ones.  In practice the HealthCheck threadpool should be
substantially larger than 1, and probably dynamically sized so each
health-check has it's own Thread.  I have given each test it's own
single threaded thread pool now.

Fix test flakes

---

src/main/java/org/apache/mesos/executor/HealthCheckHandler.java
src/main/java/org/apache/mesos/executor/HealthCheckStats.java
src/test/java/org/apache/mesos/executor/HealthCheckHandlerTest.java

I was able to repro the failure in INFINITY-503.
ScheduledExecutorService threadpools weren't being cleaned up for each
test.  If you run enough of them it appears you run out of resources and
health checks aren't scheduled.
@nickbp:  I reproed by looping 1000 times inside the testSuccess test with a new `scheduledExecutorService` each time simulating the test behavior of `beforeEach()`.  I found another test failure too.  You'll never be able to assert that `consecutiveSuccesses == totalSuccesses` as  you can't access them transactionally from outside the class.

Fixed the HealthCheck successTest

---

src/main/java/org/apache/mesos/dcos/DcosCluster.java

The developer doesn't have any control over these URIs, any exceptions thrown about URI processing is due to a bug in the library.
Note that the IOException when actually *contacting* the cluster is left as-is. This is only for parsing the constant URI strings themselves.

Switch to unchecked exception for internal URIs

---

tools/README.md
tools/dcos_login.py

- Use CLUSTER_URL when provided
- When 'print' is specified, print the result without saving to CLI
- Rename DCOS_TOKEN to CLUSTER_AUTH_TOKEN for consistency with
CLUSTER_URL

Support standalone login without DC/OS CLI

---

tools/dcos_login.py
tools/launch_ccm_cluster.py

login() was expected by run_tests.py, removing it would cause that to break

Re-add login() function, include token in CCM cluster output

---

src/main/java/org/apache/mesos/scheduler/plan/Block.java
src/main/java/org/apache/mesos/scheduler/plan/DefaultBlock.java
src/main/java/org/apache/mesos/scheduler/plan/DefaultPlanScheduler.java
src/main/java/org/apache/mesos/scheduler/plan/ReconciliationBlock.java
src/test/java/org/apache/mesos/scheduler/plan/DefaultBlockTest.java
src/test/java/org/apache/mesos/scheduler/plan/DefaultPlanSchedulerTest.java
src/test/java/org/apache/mesos/scheduler/plan/ReconciliationBlockTest.java
src/test/java/org/apache/mesos/scheduler/plan/TestBlock.java

The Optional portion adds no value.  An empty Collection communicates
the same meaning.

Remove Optional portion of updateOfferStatus

---

cli/http.go

Main CLI seems to be permissive of this situation, so for convenience lets be permissive of it as well.

Trim any trailing '/#/' from DCOS URLs

---

build.gradle
src/main/java/org/apache/mesos/offer/TaskUtils.java
src/main/java/org/apache/mesos/reconciliation/DefaultReconciler.java
src/main/java/org/apache/mesos/scheduler/DefaultScheduler.java
src/main/java/org/apache/mesos/scheduler/DefaultTaskKiller.java
src/main/java/org/apache/mesos/scheduler/TaskKiller.java
src/main/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryScheduler.java
src/main/java/org/apache/mesos/scheduler/recovery/monitor/DefaultFailureMonitor.java
src/main/java/org/apache/mesos/scheduler/recovery/monitor/TimedFailureMonitor.java
src/main/java/org/apache/mesos/state/StateStore.java
src/test/java/org/apache/mesos/curator/CuratorStateStoreTest.java
src/test/java/org/apache/mesos/scheduler/recovery/RecoverySchedulerTest.java

* Tasks which were in the state `TASK_LOST`, weren't being handled properly by destructive killing.  They weren't getting marked as permanently failed because they were being detected as not needing to be killed because they weren't `TASK_RUNNING`.
* There was also a conflation between Tasks being in states which required recovery and being in a terminal state.  These have been clarified.
* Integration tested by having Kafka consume this change, terminated a AWS instance, had a Broker go to TASK_LOST.  `dcos kafka broker replace <id>` worked as expected.  It did not work as expected before this change.
* It also appears that `dcos kafka broker replace <id>` while suppressed was broken.  So the TaskKiller now takes a SchedulerDriver so it can work anytime, even without an Offer cycle. …

Reliably, destructively, replace Tasks

---

src/main/java/org/apache/mesos/offer/MesosResourcePool.java
src/main/java/org/apache/mesos/offer/OfferEvaluator.java
src/main/java/org/apache/mesos/offer/ResourceUtils.java
src/test/java/org/apache/mesos/offer/OfferEvaluatorTest.java

Mesos will not accept a `TaskInfo` that both has its own `CommandInfo` as well as an `ExecutorInfo` with a `CommandInfo`. We end up in violation of this when setting dynamic port requirements on both our tasks and our executors, since those ports are stored as in environment variables on `TaskInfo.CommandInfo` and `TaskInfo.ExecutorInfo.CommandInfo`, respectively. To work around this case generally, we already have the capability of supplying a serialized `CommandInfo` in the `TaskInfo`'s `data` field, so this change causes the `OfferEvaluator` to check for a `TaskInfo` that has both `CommandInfo` fields, and, if so, moves the task's `CommandInfo` to its `data` field.

Ensure that TaskInfo has command in data field when executor has command set

---

src/main/java/org/apache/mesos/executor/CustomExecutor.java
src/main/java/org/apache/mesos/offer/OfferEvaluator.java
src/main/java/org/apache/mesos/offer/ResourceUtils.java
src/main/java/org/apache/mesos/offer/TaskUtils.java
src/test/java/org/apache/mesos/executor/ProcessTaskTest.java
src/test/java/org/apache/mesos/offer/OfferEvaluatorTest.java
src/test/java/org/apache/mesos/testutils/TaskTestUtils.java
src/test/java/org/apache/mesos/testutils/TestConstants.java

TaskInfos may not simultaneously have CommandInfo and ExecutorInfo fields.  That doesn't make sense and there is [a ticket with a shepherd to fix it on the Mesos side](https://issues.apache.org/jira/browse/MESOS-6294).
In the mean time we had been serializing the CommandInfo when a custom Executor is used and putting it in the data field.  However, this overwrites anything that was in the data field.  So one more level of encapsulation is needed.  I am reusing the ExecutorInfo protobuf for this as it's the smallest protobuf with both CommandInfo and data fields.
So, when a TaskInfo with both CommandInfo and ExecutorInfo is encountered, the necessary information is serialized and encapsulated in an ExecutorInfo (in the data field) on the Scheduler side.  The deserialization operation is …

Serialize and deserialize TaskInfos with custom Executors and data fields

---

build.gradle

Useful for embedding test builds in scheduler jars for manual testing
Used when testing placement contraints. Only exercised if the user
specifically does `./gradlew shadowjar`

Add support for building shadow jars

---

src/main/java/org/apache/mesos/offer/TaskUtils.java

No effective change to logic (I assume this is correct?), just makes the case more explicit

Explicitly add TASK_LOST as non-terminal

---

src/main/java/org/apache/mesos/offer/MesosResourcePool.java

If the resource is `null`, Java complains since `Optional`'s `.of` can't encapsulate a `null` value.
```
INFO  [2016-10-05 02:18:34,282] org.apache.mesos.scheduler.recovery.DefaultRecoveryScheduler: Preparing to launch task
INFO  [2016-10-05 02:18:34,282] org.apache.mesos.offer.MesosResourcePool: Retrieving reserved resource
ERROR [2016-10-05 02:18:34,282] com.mesosphere.dcos.kafka.scheduler.KafkaScheduler: Unexpected exception encountered when processing offers
! java.lang.NullPointerException: null
! at java.util.Objects.requireNonNull(Objects.java:203) ~[na:1.8.0_91]
! at java.util.Optional.<init>(Optional.java:96) ~[na:1.8.0_91]
! at java.util.Optional.of(Optional.java:108) ~[na:1.8.0_91]
! at org.apache.mesos.offer.MesosResourcePool.consumeReserved(MesosResourcePool.java:186) …
```

Eliminate NullPointerException on processing offers

---

src/main/java/org/apache/mesos/scheduler/plan/RandomRecoveryStrategy.java
src/test/java/org/apache/mesos/scheduler/plan/RandomRecoveryStrategyTest.java

Ensuring that `RandomRecoveryStrategy` works well with mostly and all `COMPLETED` blocks.

Ensure RandomRecoveryStrategy doesn't cause starvation

---

cli/runcli.go

The CLI modules need to call into 'dcos' to retrieve config settings.
To keep this straightforward, the modules assume that 'dcos' is
present in the PATH. This handling detects when that isn't the case,
and provides available options for solving it.
Fixes issue #176

Provide better error when 'dcos' isn't in PATH

---

src/main/java/org/apache/mesos/scheduler/DefaultScheduler.java

"Framework has been removed" isn't exactly the most intuitive error for describing what's really going on. Bridge the gap.
Solves issue #177

Provide instructions in the common newbie case of leftover ZK/resources

---

src/main/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryPlanManager.java
src/test/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryPlanManagerTest.java

Original code does not filter dirtied assets correctly. Assuming there are tasks A, B and C, that need recovery, and dirtied assets are A and C, the original code returns tasks B, C, A, B, instead of expected task B only.
This issue appeared during cluster update (such as increasing cpus/mem requirements, or changing command) with custom scheduler based on DefaultScheduler. Cluster update seems broken in this version of dcos-commons, when DefaultScheduler is used, and more fixes could be required.

Fix filtering terminated tasks

---

tools/github_update.py

cc @nickbp 
explicitly adding GITHUB_DISABLE shouldn't be necessary.  The update script should be smart enough to know when it can and can't update.

make github update optional

---

tools/release.sh

It'll technically includes `release.sh` itself but whatever

Include shell scripts in tools release tgz

---

examples/reference/src/main/java/com/mesosphere/sdk/reference/scheduler/Main.java
sdk/core/src/main/java/org/apache/mesos/offer/DefaultOfferRequirementProvider.java
sdk/core/src/main/java/org/apache/mesos/offer/TaskUtils.java
sdk/core/src/main/java/org/apache/mesos/scheduler/plan/DefaultBlockFactory.java
sdk/core/src/main/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryPlanManager.java
sdk/core/src/main/java/org/apache/mesos/specification/DefaultService.java
sdk/core/src/main/java/org/apache/mesos/specification/DefaultTaskSet.java
sdk/core/src/main/java/org/apache/mesos/specification/DefaultTaskSpecification.java
sdk/core/src/main/java/org/apache/mesos/specification/TaskSpecification.java
sdk/core/src/test/java/org/apache/mesos/offer/DefaultOfferRequirementProviderTest.java
sdk/core/src/test/java/org/apache/mesos/specification/CustomTaskSetTest.java
sdk/core/src/test/java/org/apache/mesos/specification/TestTaskSetFactory.java
sdk/core/src/test/java/org/apache/mesos/specification/TestTaskSpecification.java
sdk/core/src/test/java/org/apache/mesos/testutils/TaskTestUtils.java
sdk/core/src/test/java/org/apache/mesos/testutils/TestConstants.java

The existing `DefaultTaskSpecification` does not provide appropriate entry points for running containers as tasks. This PR proposes an updated `TaskSpecification` interface.
cc @gabrielhartmann

Add ContainerInfo for TaskSpecification

---

sdk/scheduler/src/main/java/org/apache/mesos/config/validate/TaskSetsCannotShrink.java
sdk/scheduler/src/main/java/org/apache/mesos/config/validate/TaskVolumesCannotChange.java
sdk/scheduler/src/test/java/org/apache/mesos/config/validate/TaskSetsCannotShrinkTest.java
sdk/scheduler/src/test/java/org/apache/mesos/config/validate/TaskVolumesCannotChangeTest.java

- TaskSetsCannotShrink: disallows shrinking a deployment
- TaskVolumesCannotChange: disallows changes to VolumeSpecs

Add default config validators (and associated tests)

---

sdk/scheduler/src/main/java/org/apache/mesos/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryPlanManager.java
sdk/scheduler/src/main/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryStep.java

* Allow children of the DefaultScheduler to specify custom RecoveryRequirementProvider (Allows Kafka to start using the the DefaultScheduler)
* Fixed bug where the DefaultOfferRequirementProvider was being used as the RecoveryRequirementProvider.
* Reorganized member variables so they're grouped together a little sanely.

Allow custom RecoveryRequirementProvider

---

sdk/scheduler/src/main/java/org/apache/mesos/scheduler/plan/DefaultStepFactory.java
sdk/scheduler/src/test/java/org/apache/mesos/scheduler/recovery/DefaultRecoveryPlanManagerTest.java

Looks like #256 had a few stale names that reverted the rename. This reverts the revert.

Fix stale rename of Step to Block

---

examples/reference/build.sh

At the moment scheduler.zip isn't being built when running build.sh

Include gradle call in reference scheduler's build.sh

---

examples/reference/integration/tests/test_utils.py
frameworks/hdfs/integration/tests/test_utils.py
gradle/quality.gradle
sdk/scheduler/src/main/java/org/apache/mesos/offer/ExecutorRequirement.java
sdk/scheduler/src/main/java/org/apache/mesos/offer/MesosResource.java
sdk/scheduler/src/main/java/org/apache/mesos/offer/NamedVIPPortRequirement.java
sdk/scheduler/src/main/java/org/apache/mesos/offer/OfferEvaluator.java
sdk/scheduler/src/main/java/org/apache/mesos/offer/RequirementUtils.java
sdk/scheduler/src/main/java/org/apache/mesos/offer/ResourceUtils.java
sdk/scheduler/src/main/java/org/apache/mesos/offer/TaskRequirement.java
sdk/scheduler/src/test/java/org/apache/mesos/offer/MesosResourcePoolTest.java
sdk/scheduler/src/test/java/org/apache/mesos/offer/NamedVIPPortRequirementTest.java
sdk/scheduler/src/test/java/org/apache/mesos/offer/OfferEvaluatorTest.java
sdk/scheduler/src/test/java/org/apache/mesos/testutils/TestConstants.java

Similar to the `DynamicPortRequirement` class, the solution for adding this functionality involves tracking named-VIP-ports as a separate type of resource from regular the `ResourceRequirement` list. Although this involves changing many method signatures, it's preferable to blending this logic in with regular resource accounting with excessive branching. Ultimately, this logic will be encapsulated by an upcoming change to the `OfferEvaluator` which will introduce a pipeline of resource requirement/`TaskInfo` modification stages. Note that the final consequence of this change from Mesos' perspective is that either the `TaskInfo` or the `ExecutorInfo` will have a `DiscoveryInfo` attached, with a hostname and `Port` resource labeled with the intended service address.

Add static VIP support in task and executor requirements

---

cli/commands.go
frameworks/hdfs/cli/dcos-hdfs/main.go

Commands affected:
- hdfs node list
- hdfs state status datanode-0
- hdfs state task datanode-0
- hdfs node restart datanode-0 (affects only HDFS)
- hdfs node replace datanode-0 (affects only HDFS)

Fixed HDFS and common CLI pointing to incorrect endpoints.

---

examples/reference/integration/tests/test_sanity.py
examples/reference/integration/tests/test_upgrade.py
examples/reference/integration/tests/test_utils.py

0. - (After normal test tools have already automatically added the infinity-artifacts stub universe...)
1. - Add the master custom universe at index 0
2. - Install data-store master build
4. - Upgrade data-store to infinity-artifacts build
5. - Verify that rollout occurred as expected, and that upgraded data-store is healthy

Added package upgrade test.

---

build.sh
test.sh
tools/build_cli.sh
tools/build_framework.sh

By default OSX doesn't have:
- -T flag for `ln`
- `realpath`

Fixes for mac builds

---

.gitignore
README.md
get-dcos-docker.sh
tools/publish_http.py
tools/vagrant/.gitignore
tools/vagrant/Vagrantfile
tools/vagrant/build-dcos-docker.sh
tools/vagrant/metadata.json

Upside(s):
- Environment creation is much simpler, mainly consisting of convenince logic surrounding a plain ol' `vagrant up` command.
Downside:
- Current up-front image download approaches 5GB (many easy optimizations left to be made by DC/OS). This is ameliorated somewhat by the USB-stick option.
Main changes:
- Adds new `get-dcos-docker.sh` and updates quickstart to use it. This replacement for `build-dcos-docker.sh` just grabs the latest version of the uploaded package. Supports passing a local path to the package using a `BOX_PATH` envvar (USB stick support).
- Moves `build-dcos-docker.sh` into `tools/vagrant/` while adding some automation around creating box packages. This tool should now only be needed when the box package needs an update.

Use a pre-built/uploaded VM image, instead of requiring DIY builds

---

tools/build_cli.sh
tools/vagrant/Vagrantfile
tools/vagrant/build-dcos-docker.sh
tools/vagrant/metadata.json

- Use uncached metadata.json as the .box is still moving quickly. Want changes to deploy sooner than ~24h
- Bump .box image: includes fixes in image builder (especially refraining from wiping `/usr/src` which is needed)
- Fix regressions in image builder and add steps to upload
- Path in build_cli.sh was still broken for OSX (no `realpath`)

Fix/bump image, use uncached metadata.json

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/constrain/MarathonConstraintParser.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/constrain/MarathonConstraintParserTest.java

Ended up just hand-coding the splitter, as guava Splitter doesn't do this.

Constraints: support backslash-escaped commas/colons in regexes

---

cli/commands.go
frameworks/helloworld/README.md
frameworks/helloworld/src/main/dist/svc.yml

* removing 'health' command from cli.  no admin/healthcheck  in com.mesosphere.sdk.api
./dcos-hello-world-darwin hello-world health
HTTP GET Query for http://35.164.209.100/service/hello-world/admin/healthcheck failed: 404 Not Found
*   updated README.md, added a note about api-port
*  api-port is dynamically set by Marathon.  In yml file, it should be “api-port: {{PORT0}}”
Marathon dynamically selects a port, and pass this info to the framework, so framework can start the service on that selected port.

a quick fix for cli, update in README, and removal of 'health' command in cli 

---

cli/commands.go
frameworks/helloworld/cli/dcos-hello-world/main.go
frameworks/kafka/cli/dcos-kafka/main.go
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/EndpointsResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/types/EndpointProducer.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/NamedVIPPortRequirement.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/api/EndpointsResourceTest.java

Common replacement for framework-specific `/connections` endpoints and CLI commands currently implemented by Cassandra/Kafka/HDFS.
The built-in `TaskInfo` search relies on the presence of `DiscoveryInfo`s containing the relevant port information (something that `hello-world` currently doesn't do -- as its tasks don't serve any requests). If the `DiscoveryInfo` has VIP label information, that is automatically included as well, otherwise the endpoints returned will just be based on the information in the base `DiscoveryInfo`.
In addition to the built-in `DiscoveryInfo` lookup, framework authors may also provide their own custom endpoint content (e.g. Kafka's zk path, or HDFS' xml files).

Add 'endpoints' endpoint

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java

Align with ReplacementFailurePolicy's use of milliseconds.
(Fixes bug #379)

Fix units for recovery time values

---

cli/commands.go
frameworks/hdfs/cli/dcos-hdfs/main.go
frameworks/helloworld/cli/dcos-hello-world/main.go

Per-project repos no longer invoke it in master, so add a timeline for removal.
Its use can cause the addition of unsupported commans when a repo invokes it but hasn't started using the new 'endpoints' endpoint. To avoid situations like this in the future it's preferable that callers explicitly add the CLI sections they know they support.

Semi-formally deprecate 'HandleCommonArgs'

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorStateStore.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/reconciliation/DefaultReconciler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java

This change stops aggressively reviving which was interfering with Mesos's ability to merge fragmented offers.

Stop agressively reviving offers.

---

frameworks/helloworld/integration/tests/test_sanity.py
frameworks/helloworld/integration/tests/test_sidecar.py
frameworks/helloworld/integration/tests/test_utils.py
frameworks/helloworld/src/main/dist/sidecar.yml
frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache
sdk/common/src/main/java/com/mesosphere/sdk/offer/CommonTaskUtils.java
sdk/common/src/main/java/com/mesosphere/sdk/offer/Constants.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/PlansResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/TaskUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultTaskKiller.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanCoordinator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanFactory.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanCoordinator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/StrategyFactory.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultPlanGenerator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawPhase.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawPlan.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/api/PlansResourceTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/OfferAccepterTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/TaskUtilsTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanCoordinatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanManagerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultPlanGeneratorTest.java
sdk/scheduler/src/test/resources/partial-manual-plan.yml

Any number of plans may be defined.  All plans apart from the "deploy" plan are initialized in an interrupted state.  The PlanResource now has endpoints for starting arbitrary plans.  These plans may refer to tasks which should be launched in already running pod instances (executors).  These two features allow for the execution of sidecar plans.
One may verify this by deploying the hello-world service with `sidecar.yml` and starting the sidecar plan.  Integration tests are included which exercise deployment and execution of the sidecar plan.

Sidecar Plans

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultServiceSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultServiceSpecTest.java
sdk/scheduler/src/test/resources/dynamic-port.yml
sdk/scheduler/src/test/resources/dynamic-vip-port.yml
sdk/scheduler/src/test/resources/full-manual-plan.yml
sdk/scheduler/src/test/resources/invalid-pod-name.yml
sdk/scheduler/src/test/resources/invalid-replacement-failure-policy.yml
sdk/scheduler/src/test/resources/invalid-resource-set-name.yml
sdk/scheduler/src/test/resources/invalid-rlimit-name.yml
sdk/scheduler/src/test/resources/invalid-task-name.yml
sdk/scheduler/src/test/resources/invalid-task-resources.yml
sdk/scheduler/src/test/resources/invalid.yml.mustache
sdk/scheduler/src/test/resources/multiple-dynamic-port.yml
sdk/scheduler/src/test/resources/multiple-port-with-finished.yml
sdk/scheduler/src/test/resources/multiple-task.yml
sdk/scheduler/src/test/resources/named-vip.yml
sdk/scheduler/src/test/resources/partial-manual-plan.yml
sdk/scheduler/src/test/resources/recovery-plan-manager-test.yml
sdk/scheduler/src/test/resources/resource-set-seq.yml
sdk/scheduler/src/test/resources/single-port.yml
sdk/scheduler/src/test/resources/single-task.yml
sdk/scheduler/src/test/resources/valid-customzk.yml
sdk/scheduler/src/test/resources/valid-minimal-health.yml
sdk/scheduler/src/test/resources/valid-multiple-ports.yml
sdk/scheduler/src/test/resources/valid-simple.yml

This PR makes configuration of zookeeper connection string optional for both YAML and Java interfaces. By default, the value of zookeeper connection string is "master.mesos:2181". This value can be over-ridden in the YAML interface via:
```yaml
...
zookeeper: custom.master.mesos:2181
...
```
or in Java interface via:
```java
new DefaultService(DefaultServiceSpec.newBuilder()
.zookeeperConnection("custom.master.mesos:2181")
```

Make zookeeper connection string optional

---

frameworks/hdfs/integration/tests/test_data_integrity.py

Increased the timeout because the hdfs read / write were timing out in Jenkins tests.

Increased hdfs read / write timeout to 5 minutes

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/api/types/RestartHook.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java

Allows developers to specify custom teardown logic when 'pod restart' and/or 'pod replace' is invoked.

Add ability to provide custom RestartHook to DefaultScheduler.Builder

---

frameworks/helloworld/integration/tests/test_web_url.py
frameworks/helloworld/src/main/dist/examples/web-url.yml
frameworks/helloworld/src/main/resources/examples/web-url.yml
frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceSpecTest.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultService.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultServiceSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/ServiceSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawServiceSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java

This is needed for the consumption of proxylite as a custom
proxy to multiple service APIs (e.g. the Scheduler API and Kibana)
Proxylite is a container under development which is deployable as a pod
in each service which will provide routing through admin router to 
framework author specified HTTP endpoints.

Add web-url to ServiceSpec

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/AbstractStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Element.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Status.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Step.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanManagerTest.java

-Plan and Phase return WAITING, if interrupted and not completed.
-IN_PROGRESS status only for plans and phases
DefaultPlan and DefaultPhase used to check if interrupted in getStatus. That is omitted when we remove Element.setStatus. Putting back this feature in PlanUtils.getStatus (only Plan and Phase call PlanUtils.getStatus)!

return WAITING in Plan and Phase, if interrupted and not completed.

---

build.gradle
frameworks/hdfs/build.gradle
frameworks/hdfs/build.sh
frameworks/helloworld/build.gradle
frameworks/helloworld/build.sh
frameworks/kafka/build.gradle
frameworks/kafka/build.sh
sdk/executor/build.gradle

`./gradlew build` works now, so you don't have to clean all the time
All the subprojects have isolated build directories.
They continue to work for building Universe packages and uploading binaries.

Fix the build

---

docs/pages/tutorial.md

I was told that https should not be used here.

fix link for dcos slack

---

frameworks/hdfs/universe/config.json
frameworks/hdfs/universe/marathon.json.mustache
frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache
frameworks/kafka/universe/config.json
frameworks/kafka/universe/marathon.json.mustache
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java

Additionally, simplify generic prefixes on Scheduler cmds

Extend, not override LD_LIBRARY_PATH

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStage.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProviderTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStageTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/ServiceSpecTestUtils.java
sdk/scheduler/src/test/resources/valid-port-healthcheck.yml
sdk/scheduler/src/test/resources/valid-port-readinesscheck.yml

Both health checks and readiness checks will now get all the env vars of the task they are associated with.
/cc: @loren

All task env-vars including ports are now also available on health and readiness checks

---

frameworks/hdfs/integration/tests/test_upgrade.py

Fixed the install() call in upgrade-downgrade test. It should pass the package_version directly through the package_version param.

Fixed specifying package version in downgrade test

---

frameworks/helloworld/src/main/dist/svc.yml
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStage.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ResourceEvaluationStage.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStage.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/ResourceCleanerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorBaseTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorVolumesTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/ResourceTestUtils.java
sdk/scheduler/src/test/resources/multi-volume.yml

The main error was a failure to differentiate disk resouces on container
path.  Other resources may be safely differentiated based on name (e.g.
cpu, mem).  However disk resources must be further compared with
reference to their container path.

Fix multi-volume support

---

sdk/common/src/main/java/com/mesosphere/sdk/offer/CommonTaskUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorStateStore.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/state/PersistentOperationRecorder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/state/StateStoreCache.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/state/StateStoreCacheTest.java

StateStoreCache was not unpacking TaskInfo for fetch calls, which was causing problems elsewhere in `PortEvaluationStage` class (kind of like butterfly effect). More specifically, PortEvaluationStage expects certain env vars in TaskInfo's CommandInfo proto which are only available once the TaskInfo it belongs to is unpacked.
This PR does following:
1. Makes StateStoreCache unpack TaskInfo for fetch calls just like CuratorStateStore
2. Adds corresponding tests inside StateStoreCacheTest
3. Minor fix to a logging statement.
cc: @loren

Making StateStoreCache's fetchXXX similar to CuratorStateStore

---

frameworks/helloworld/universe/config.json

Configuring default value of `mesos_api_version` property to `V1`, so that it uses HTTP by default.

Configuring hello-world to use V1 HTTP API by default

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLServiceSpecFactory.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultServiceSpecTest.java
sdk/scheduler/src/test/resources/invalid-duplicate-count.yml
sdk/scheduler/src/test/resources/invalid-pod-name.yml
sdk/scheduler/src/test/resources/invalid-task-name.yml
sdk/scheduler/src/test/resources/invalid-volume-and-volumes.yml

- Specified 'memory' or 'count' twice? That's an error
- Also an explicit check disallowing both 'volume' and 'volumes' at once

Raise an error if any field has duplicates in the yaml

---

frameworks/hdfs/src/main/dist/svc.yml
frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/Main.java
frameworks/hdfs/src/test/java/com/mesosphere/sdk/hdfs/scheduler/ServiceSpecTest.java
frameworks/hdfs/universe/marathon.json.mustache
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/EndpointsResource.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/api/EndpointsResourceTest.java

Output looks like this:
```bash
$ dcos hdfs endpoints
[
"hdfs-site.xml",
"core-site.xml"
]
```
```bash
$ dcos hdfs endpoints hdfs-site.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
<property>
<name>dfs.nameservice.id</name>
<value>hdfs</value>
</property>
<property>
<name>dfs.nameservices</name>
<value>hdfs</value>
</property>
<property>
<name>dfs.ha.namenodes.hdfs</name>
<value>name-0-node,name-1-node</value>
</property>
<property>
<name>dfs.namenode.http-address.hdfs.name-0-node</name>
<value>name-0-node.hdfs.mesos:9002</value>
</property>
<property>
<name>dfs.namenode.rpc-address.hdfs.name-0-node</name>
<value>name-0-node.hdfs.mesos:9001</value>
</property>
<property> …
```

[HDFS] Expose hdfs-site.xml and core-site.xml through Endpoints endpoint.

---

frameworks/helloworld/src/main/dist/examples/parameterized-plan.yml
frameworks/helloworld/src/main/resources/examples/parameterized-plan.yml
frameworks/helloworld/tests/test_parameterized_plan.py
frameworks/helloworld/tests/test_sidecar.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/PlansResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/OfferRequirementProvider.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DeploymentStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Element.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/ParentElement.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PodInstanceRequirement.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Step.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/api/PlansResourceTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProviderTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStageTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanManagerTest.java
testing/sdk_plan.py

This change allows plans to keep parameters, which are subject to change over their lifetimes, and which are propagated to all `Phase`s and `Step`s belong to them. It is ultimately up to the `Step` instances at the leaves of a `Plan` what it wants to do with those parameters -- `DeploymentStep` will make sure to incorporate them as environment variables into the `PodInstanceRequirement` returned by `start()`, for example (`PodInstanceRequirement` now has a `environment` member, which extends the environments of all tasks contained by it). This allows sidecar plans to have parameters that are only supplied when the `{plan}/start` endpoint is invoked (via JSON in the POST request body), which is useful for e.g. backup operations that may have a changing or unknown-at-install-time backup …

Enable the propagation of additional envvars to tasks at plan start

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultPlanGenerator.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultPlanGeneratorTest.java
sdk/scheduler/src/test/resources/custom-phases.yml

Omitting a `default` element in the `steps` section of a custom plan should indicate that only explicitly designated pod instances have steps generated for them.

Require `default` step to get `default` behavior

---

docs/pages/dev-guide/developer-guide.md
frameworks/helloworld/src/main/dist/examples/cni.yml
frameworks/helloworld/src/main/dist/svc.yml
frameworks/helloworld/src/main/resources/examples/cni.yml
frameworks/helloworld/tests/test_networking.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/ContainerSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultContainerSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultNetworkSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/NetworkSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawContainer.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawNetwork.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java

This change adds a new field under `container` in each pod called `networks` that allows the user to specify which overlay networks to join by name:
```
container:
networks:
dcos: {}
```
An empty dictionary must be passed for the body right now, due to the fact that we only currently support joining networks by name, but was designed this way to allow backwards-compatible addition of e.g. port mappings in the future.
This was tested by creating a container that joins the `dcos` virtual network included by default in DC/OS installs and verifying that the IP for interface eth0 is in the 9.0.0.0/24 subnet.

Add support for joining overlay networks with CNI

---

tools/create_service_account.sh
tools/launch_ccm_cluster.py

Fixed the create_service_account.sh script. For strict mode, you have to set core.dcos_url, core.dcos_acs_token, inside that script. So, I added them as arguments, and they're set inside the script.

Set cluster configs if necessary in create_service_account.sh

---

tools/setup_permissions.sh

In setup_permissions.sh, the CI job doesn't have a dcos binary, so it uses the CLUSTER_URL and CLUSTER_AUTH_TOKEN env vars to authenticate.

Fix setup_permissions.sh in CI environment

---

tools/launch_ccm_cluster.py

Many new integration tests have recently been added causing increased test duration which is exceeding cluster duration.

[CI] Increase cluster duration

---

frameworks/helloworld/tests/test_sanity.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java

Configuration updates for pods with multiple volumes don't work due to a map key collision on the resource name: `disk`.

[SDK] Fix config updates of multi-disk pods

---

frameworks/helloworld/tests/test_sanity.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanScheduler.java

Tasks should be killed based on whether a resource-set is being consumed by a task from their pod already, not based on task name.

[SDK] Kill tasks based on resource-sets

---

frameworks/hdfs/src/main/dist/svc.yml

If it is going to exist it must be configurable
I'm not convinced it should exist, seems dangerous

[HDFS] Remove name-node health-check

---

tools/launch_ccm_cluster.py

Made sure the stdout redirect is applied in the subprocess call to create_service_account.sh. Previously, the output from the shell script was still appearing in stdout.

Fixed the stdout redirect in launch_ccm_cluster.py

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultStepFactory.java

Resolves https://jira.mesosphere.com/browse/INFINITY-962
On scheduler restart, permanently failed tasks were incorrectly being picked up by the deployment plan which doesn't have the correct logic for dealing with permanent failures.

[SDK] Fix failed tasks being recovered by deploy plan

---

cli/response.go

Go's JSON library doesn't know what `\v` means. Instead of returning an error for the whole command, just log a complaint to stderr.

Be more permissive of unknown characters in JSON responses

---

test.sh

At the moment, each successive test run hides the result of prior runs in github

Use per-service 'test:<fwk>' github label instead of default 'test:shakedown' each time

---

docs/pages/dev-guide/developer-guide.md

See https://mesosphere.github.io/dcos-commons/dev-guide/developer-guide.html, where all the examples have had any mustache templates replaced with empty strings
In theory this should fix it, per http://stackoverflow.com/questions/11042926/how-does-one-use-a-literal-in-a-mustache-template

Refrain from running mustache {{ }} templates in dev guide

---

docs/pages/dev-guide/developer-guide.md

Other fix didn't work, but this one does (manually verified locally): http://www.digiguru.co.uk/blog/2015/03/31/how-to-output-mustache-templates-in-a-jekyll-site.html
Other changes are just cleaning up trailing whitespace.

Different fix for allowing mustache within dev guide

---

build.gradle

Fetch RC1 from Maven Central instead of SNAPSHOT from the less available repository.apache.org to make CI work more reliably.

Use Mesos 1.2.0-rc1 instead of SNAPSHOT

---

frameworks/cassandra/tests/test_shakedown.py
frameworks/elastic/tests/config.py
frameworks/elastic/tests/test_shakedown.py
frameworks/hdfs/tests/test_alternate_name.py
frameworks/helloworld/tests/test_networking.py
frameworks/helloworld/tests/test_parameterized_plan.py
frameworks/helloworld/tests/test_sanity.py
frameworks/helloworld/tests/test_sidecar.py
frameworks/helloworld/tests/test_taskcfg.py
frameworks/helloworld/tests/test_web_url.py
frameworks/kafka/tests/test_sanity.py
frameworks/prototype/tests/test_sanity.py
frameworks/proxylite/tests/test_sanity.py
frameworks/template/tests/test_sanity.py
test.sh
testing/sdk_utils.py

- Removed unneeded imports
- Deleted duplicate setup_module method in prototype framework

Added teardown_module to uninstall/janitor frameworks after tests run

---

sdk/bootstrap/main.go
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java

Some Docker images may start in a custom working directory, in which case an explicit `$MESOS_SANDBOX` is needed:
- Executor path (construction of tasks in scheduler)
- Path to downloaded templates (`bootstrap`'s template logic)

Explicitly mention $MESOS_SANDBOX for custom pwd compat

---

test.sh

https://jira.mesosphere.com/browse/INFINITY-1037
I didn't add the --raw-output to the .id line, because it's an integer and thus won't have quotes.  Of course maybe that will be false in the future?

Drop unwanted embedded quotes that break scripts in some circumstances.

---

.gitignore
sdk/bootstrap/build.sh
tools/build_cli.sh
tools/build_go_exe.sh
tools/pythoncli/setup.py

Adds a common `build_go_exe.sh` script which implements caching logic to avoid unnecessary rebuilds of go executables. This is done by comparing the SHA1 of a native/local build (faster than cross-builds) to detect changes in the go build artifact.
This script is now used for building per-service CLI executables as well as the common `bootstrap` executable.
As a result, rebuilding a service goes from ~40s to ~5s (plus the following artifact upload, which mainly depends on bandwidth)

Faster service rebuilds via caching of go artifacts

---

tools/launch_ccm_cluster.py

Log the actual url that launch_ccm_cluster.py is using, and whether we're taking it from the environment (thus ignoring other logged values).

Ccm cluster launch log template url

---

test.sh
testing/sdk_install.py

Changes required to get integration tests passing in strict mode: 
- Added calls to setup_permissions.sh in test.sh
- Used CLUSTER_CREATED shell variable to avoid conflict in CI (which defines CLUSTER_ID variable), when deciding to delete a cluster
- Ported Mehmet’s fix of dictionary merge function used by integration tests, see [Kafka #345](https://github.com/mesosphere/dcos-kafka-service/pull/345)

[TESTS][INFINITY-1042] Changes to get Framework CI Tests to pass in strict mode

---

sdk/common/src/main/java/com/mesosphere/sdk/testutils/TaskTestUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/NamedVIPEvaluationStage.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/NamedVIPEvaluationStageTest.java

`NamedVIPEvaluationStage` was using the wrong criterion to determine whether a VIP for a given port was already set on the `DiscoveryInfo` (i.e. whether a VIP label existed on the `DiscoveryInfo` itself rather than on a particular `Port`) leading it to unnecessarily re-add those port definitions on task restart.

[SDK][INFINITY-966] Correctly reuse existing VIP port on discovery info after task restart

---

docs/pages/dev-guide/developer-guide.md
frameworks/proxylite/src/main/dist/svc.yml
frameworks/proxylite/src/main/docker/files/configure.py
frameworks/proxylite/src/main/docker/files/haproxy.cfg.raw

Previously HAProxy was not re-resolving dns addresses, leaving it pointing to stale and potentially incorrect backends. This change re-resolves dns on a 2 second interval.

proxylite: Fix bug with stale backends

---

frameworks/kafka/src/main/dist/server.properties.mustache
frameworks/kafka/src/main/dist/svc.yml
frameworks/kafka/src/test/java/com/mesosphere/sdk/kafka/scheduler/ServiceSpecTest.java
frameworks/kafka/universe/config.json
frameworks/kafka/universe/marathon.json.mustache
frameworks/kafka/universe/package.json

Update universe and yaml to change repo name to kafka. 
Originally it was *kafka*. We later set its name to *apache-kafka* (to differentiate from confluent-kafka).
Role, principle, etc are based on this name. 
To be compatible with all other frameworks and to have the same name with the framework directory (frameworks/kafka), want to change name back to *kafka*.
PS: Description is always "Apache Kafka".

[KAFKA] Change repo name to kafka for compatability

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

Invalid config updates cause DefaultScheduler to throw an uncaught IllegalStateException. The scheduler dies and repeatedly gets restarted.
- DefaultScheduler now just logs the warning and re-launches prior valid config

[ELASTIC-53] Invalid config updates cause IllegalStateException

---

tools/build_go_exe.sh
tools/publish_aws.py
tools/publish_http.py

- Darwin binary must not be UPX-encoded, or else it immediately produces `Killed: 9`
- Include all steps to reinstall a service in build output

[SDK] Fix Darwin CLI build, add uninstall instructions to build.sh footer

---

sdk/common/src/main/java/com/mesosphere/sdk/testutils/TestConstants.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/PodsResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorStateStore.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/api/PodsResourceTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/curator/CuratorStateStoreTest.java

It is possible in some failure scenarios for TaskInfo and TaskStatus
objects regarding the same Task to have inconsistent TaskIDs.  This
breaks dependent logic that assumes TaskInfo and TaskStatus for the
same Task will share a TaskID.
TaskState is set to TASK_FAILED in the case of any detected inconsistency to
cause a restart of the Task and arrive at a categorically consistent state with Mesos.

[SDK][INFINITY-1058] Fix statestore inconsistencies on startup

---

cli/commands.go
frameworks/cassandra/cli/dcos-cassandra/main.go
frameworks/elastic/cli/dcos-elastic/main.go
frameworks/hdfs/cli/dcos-hdfs/main.go
frameworks/helloworld/cli/dcos-hello-world/main.go
frameworks/kafka/cli/dcos-kafka/main.go
frameworks/prototype/cli/dcos-prototype/main.go
frameworks/proxylite/cli/dcos-proxylite/main.go
frameworks/spark/cli/dcos-spark-standalone/main.go
frameworks/template/cli/dcos-template/main.go

Keeps old interfaces intact for a deprecation period to avoid breaking old or external builds

[CLI] Reduce CLI bootstrapping: remove custom description strings

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanCoordinator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Element.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/CanaryStrategy.java

Problem: After first continue request, first step should start in Canary. It was not starting any step till all required continues are received.
See commit descriptions:
* Fix Canary Strategy: return phase not interrupted, after first continue, till proceeded step is started.
* Remove isWaiting(). isWaiting() != isInterrupted(), WAITING is a special status, only used to show/print plan/phase/step details.

[SDK] Fix CanaryStrategy. Remove isWaiting()

---

tools/run_tests.py

Since generating junit xml output is optional; log that it's happening so we don't waste time troubleshooting it.  FYI: @nickbp @susanxhuynh 
INFINITY-1086

Log decision to generate xml to make jenkins analysis less impossible.

---

test.sh

Possibly this might be okay as a build parameter.
It's not okay to, on developer machines, leave the clusters running by default.  How are they expected to clean it up when the CLUSTER_URL can be easily lost?
cc: @colin-msphere @gabrielhartmann @loren @susanxhuynh

Test runs should not by default create clusters and not tear them down.

---

frameworks/kafka/universe/config.json

First mark as deprecated, then remove. PR #654

[KAFKA] Deprecated JMX and STATSD options in config.json

---

frameworks/elastic/tests/test_shakedown.py
frameworks/helloworld/tests/test_sanity.py
testing/sdk_test_upgrade.py

Added the following to the upgrade test:
- Check that the deployment finishes => this catches a failure in Elastic upgrades where the deployment never finishes.
- Check that all tasks have restarted => this catches an issue with Hello-world upgrades where the tasks are not restarted.
Elastic and hello-world upgrade tests will fail with this change.

[TESTS][INFINITY-1108] Added more validation in the upgrade test

---

frameworks/hdfs/tests/config.py
frameworks/hdfs/tests/test_shakedown.py

Better than HTTP exceptions. You can see spin time, and also view plan details (in console)

[HDFS] Use Cli, it already handles 503 status when querying for plans

---

sdk/executor/src/main/java/com/mesosphere/sdk/executor/CustomExecutor.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLServiceSpecFactory.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/OfferRequirementTestUtils.java

- Health check success shouldn't be logged as an error
- Allow java schedulers to customize env when rendering yaml. This allows a developer to apply logic to envvars for mustache templating, e.g. "false" -> "".

Small java fixes: Logging and custom env

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanCoordinator.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
sdk/scheduler/src/test/resources/valid-minimal-volume.yml

The SDK assumes that when generating operations to be performed on an Offer, that those operations will be successful.  Mesos does not provide feedback for any operation other than LAUNCH.  Typically the initial deployment of a pod involves operations like:
```
RESERVE
RESERVE
CREATE
LAUNCH
```
It's possible (and sometimes occurs that an operation can fail).  Typically the failed operation is CREATE.  The scheduler doesn't currently support automatic recovery from this kind of failure.  However the `dcos <service> pods replace <pod>` method should work. It doesn't.  This PR fixes that bug.
The problem was that when marking a pod failed, the clearing of persistence information on the `Persistence` element of the `DiskInfo` did not accord with what was expected in `ResourceRequirement` to …

[INFINITY-1153] Fix pod replacement failure during deployment

---

tools/universe_builder.py

A user encountered this interpreting `{{sha256:myfile}} ... {{someothertag}}` as `myfile }} ... {{someothertag` instead of `myfile`

[SDK] Be explicitly non-greedy when consuming sha256 tags

---

test.sh

The framework tests manually added the dcos binary before invoking test.sh, but this is just ridiculous.  If test.sh purports to support SECURITY=strict, then it should work.

[INFINITY-1164] strict mode tests fail when dcos bin missing

---

release.sh
tools/build_publishable.sh
tools/release_artifacts.sh

Adds additional scripts to upload versioned bootstrap.zip and executor.zip as part of the release process. These artifacts are meant to be consumed by frameworks, especially, the ones that reside outside the monorepo.

Versioned artifacts

---

frameworks/elastic/src/main/dist/svc.yml
frameworks/elastic/tests/config.py
frameworks/elastic/tests/test_shakedown.py

- Give the cluster a few seconds to elect a new master before failing the health check
- Rewrote shakedown test to expect immediate re-election or fail

[ELASTIC-56] Bouncing the elected master node brings the whole cluster down

---

frameworks/cassandra/universe/config.json

It's already defined in another stanza below, with the more forgiving timeout of `86400000`. This was causing the last node to fail to deploy.

Remove merge conflict with bad streaming socket timeout

---

build.sh
tools/github_update.py

- Status reset: Github doesn't allow removing old statuses, only updating statuses. Therefore we just set all non-`velocity` statuses as pending in github if a build is retriggered (via 'retest this please'). Note that this doesn't fix things in all situations: If the old build is still running in jenkins then it can still override the reset-to-pending with additional updates.
- Timers: Stores a timestamp against the operation name when a step calls `pending`, then compares that timestamp when `failed` or `success` is called for that same operation name. End result is we can log duration for each operation.

[INFINITY-1128] Reset github statuses on retest, and calculate/emit operation duration

---

frameworks/cassandra/src/main/dist/cassandra.yaml

This was again causing non-seed nodes to fail to deploy.

Fix double entry of socket timeout in cassandra.yaml

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/OfferAccepter.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/OfferAccepterTest.java

Placeholder tasks which are used to fill out the footprint
of pods shouldn't be recorded.

[SDK][INFINITY-1241] Fix operation recording

---

test.py
test.sh
tools/cli_install.py
tools/launch_ccm_cluster.py
tools/run_tests.py

@susanxhuynh & @nickbp I'd appreciate your comments.
* Extract cli download to separate module.
* Expose as script in case shell needs it (I don't need that now) -- also enables easy testing
* Update cli atomically in case of goofy redownload while running
* Automatically get the right version for the cluster
* launch_ccm_cluster fetches dcos cli itself if required.

[INFINITY-1171]Centralize cli downloading in our scripts.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorStateStore.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/OfferAccepter.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/OfferAccepterTest.java

The reverted commit was not recording Task's filling out the pod footprint was causing those resources to be `UNRESERVE`d.  They must be recorded, however the `TaskStatus`es with empty TaskIDs should not be recorded.  The original bug of failing StateStore validation on Scheduler restart is fixed.

[SDK] Fix footprint reservation calculation

---

frameworks/elastic/tests/test_shakedown.py

Re-enabled Elastic upgrade-downgrade test, passing now since we are two releases past the breaking change.

[TEST][ELASTIC][INFINITY-1215] Re-enabled Elastic upgrade-downgrade test

---

frameworks/hdfs/universe/package.json

Restoring the HDFS preInstallNotes to the exact wording and ordering as currently appears in Universe.
See Ravi's comment's here: https://github.com/mesosphere/universe/pull/1062

[HDFS-447] Restoring the HDFS preInstallNotes to the exact wording as in Universe

---

frameworks/helloworld/src/main/dist/svc.yml
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/UnreserveOfferRecommendation.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/UnreserveOfferRecommendationTest.java

1. Deployed `hello-world` with MOUNT volumes with just enough machines for it to fit. 
1. Replaced a node and verified that it couldn't get rescheduled because it was generating an invalid UNRESERVE operation
1. Upgraded to this fix.
1. Success
Also matches code from Marathon now: https://github.com/mesosphere/marathon/blob/9dab2704f27243825cbd252588d3476ce980d9bb/src/main/scala/mesosphere/marathon/core/launcher/InstanceOp.scala#L76

[INFINITY-1318] Fix UNRESERVE of MOUNT volume disk resource

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java

Always reviving after a registration event, guarantees we can force revival by restarting the scheduler.  It also makes the suppressed property set once a Scheduler is active to avoid a 404 when checking the suppressed property.

[SDK] Revive on registration always

---

frameworks/cassandra/tests/test_recovery_shutdown.py
frameworks/elastic/tests/config.py
frameworks/hdfs/tests/test_shakedown.py
frameworks/helloworld/tests/test_networking.py
frameworks/helloworld/tests/test_parameterized_plan.py
frameworks/helloworld/tests/test_sanity.py
frameworks/helloworld/tests/test_sidecar.py
frameworks/helloworld/tests/test_taskcfg.py
frameworks/helloworld/tests/test_web_url.py
frameworks/kafka/tests/test_shakedown_basics.py
frameworks/kafka/tests/test_shakedown_endpoint_port.py
frameworks/kafka/tests/test_shakedown_port.py
frameworks/kafka/tests/test_shakedown_upgrade.py
test.py
testing/sdk_cmd.py
testing/sdk_install.py
testing/sdk_spin.py
testing/sdk_tasks.py
testing/sdk_test_upgrade.py
testing/sdk_utils.py
tools/run_tests.py

After a few failed experiments, the working pattern is to just ask python not to buffer output.  Since test.py is already running run_tests.py with the same file as fd 1 and 2, this should provide a reliable linear stream of events.   That's a very small change.
The much larger linecount change is the move from print to a dedicated "this is test output" function.  I'm not married this.  But I wanted to move away from print inline everywhere since that's a growing problem.  
I can also decouple the test.py fix, though given the pace of my reviews and merges I'm not excited about it.

[Infinity-1311] test output stderr

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java

It looks like the intention here was to allow these values to be set or "empty" as they are initially. However, `Optional.of` does a null check which prevents a consumer from clearing these values once they are set.
The use case for clearing is a class using `DefaultScheduler` that wants to remove the default config validators.
Current workaround is
```
DefaultScheduler.Builder builder =
DefaultScheduler.newBuilder(serviceSpecWithCustomizedPods(rawServiceSpec))
.setPlansFrom(rawServiceSpec)
.setConfigValidators(Collections.emptyList());
```

Allows optional values to be cleared

---

docs/pages/developer-guide.md
tools/configure_test_cluster.py
tools/launch_ccm_cluster.py
tools/requirements.txt
tools/venvutil.py

The nightly external repo tests are broken due to a lack of this change, so I'd like to merge it tonight or at least tomorrow (the alternative is to back out @benclarkwood s mesos master configuration again)
I'll be changing run_tests.py to use venvutil.py to remove the redundancy asap.

[INFINITY-1321] Drop requirements.txt because the toolszip doesn't handle it, it's also weird where it is

---

build.gradle
release.sh
tools/launch_ccm_cluster.py

This automates the process for creating a new release of the SDK (jars for now, other bits soon)
- `release.sh -r snapshot`: Publish build of current master (what current release.sh does)
- `release.sh -r 1.2.3`: Create/push 1.2.3 tag (with build.gradle updated), then publish build of 1.2.3
- Escape hatch if a tag already exists (e.g. build flaked after creating the tag on prior attempt): '-f' to force override
Policy changes:
- Master only has SNAPSHOT versions, never release versions.
- Release versions are created against release tags.
TODO:
- Once script is available, create manually-invoked jenkins job with parameters: version string and force checkbox

[INFINITY-1305] Automate SDK releases against tags

---

frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/tests/config.py
frameworks/cassandra/tests/test_backup.py
frameworks/cassandra/tests/test_maintenance_plans.py

This brings the SDK Cassandra plan coverage up to par with `dcos-cassandra-service`, which tests cleanup and repair plans for successful completion.

Add tests for remaining cassandra sidecar plans

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStage.java

New messages look like this:
```
PASS(VolumeEvaluationStage): Satisfied requirements for ROOT volume 'hello-container-path'
```
```
FAIL(VolumeEvaluationStage): Failed to satisfy requirements for ROOT volume 'hello-container-path': name: "disk" type: SCALAR ...
```

Improve PASS/FAIL logs for volumes

---

frameworks/helloworld/tests/test_sanity.py

Should have been re-enabled when [INFINITY-1114](https://jira.mesosphere.com/browse/INFINITY-1114) was closed.

[INFINITY-1354] Re-enable upgrade downgrade test for Hello World

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java

[Scheduler documentation](http://mesos.apache.org/documentation/latest/app-framework-development-guide/)
```
/*
* Invoked when an offer is no longer valid (e.g., the slave was
* lost or another framework used resources in the offer). If for
* whatever reason an offer is never rescinded (e.g., dropped
* message, failing over framework, etc.), a framework that attempts
* to launch tasks using an invalid offer will receive TASK_LOST
* status updates for those tasks (see Scheduler::resourceOffers).
*/
virtual void offerRescinded(SchedulerDriver* driver, const OfferID& offerId);
```
There is one case in which attempting to launch a Task and receiving a `TASK_LOST` is a problem.  That is the very first launch of a Task.  This is already a problem for us in the case where we generate a set of …

[HDFS-441] Warn on offer rescind instead of exit

---

frameworks/elastic/tests/test_soak.py
frameworks/helloworld/tests/test_soak.py
testing/sdk_test_upgrade.py

Added upgrade-downgrade tests to run in soak cluster, for hello-world and Elastic.
Differences from the CI upgrade-downgrade test:
- In the soak cluster, we assume that the Universe version of the framework is already installed.
- Also, we assume that the Universe is the default repo and the stub repos are already in place,
so we don't need to add or remove any repos.
These tests run in a metronome job inside the soak cluster. For metronome job config, see: https://github.com/mesosphere/soak-cluster-configurations/pull/71

[TESTS][INFINITY-1238] Added upgrade-downgrade tests to run in soak cluster

---

tools/init_paths.sh
tools/release.sh

This script always was `cd`ing into dcos-commons/tools, but probably due to copy&paste, claimed to be `cd`ing into the root.  When mohit introduced init_paths.sh, this meant the script no longer worked.  I "fixed" it to not assume init_paths was in the current directory, but that was not the full fix, as now the tools zip contained dcos-commons/*.py and sh, instead of dcos-commons/tools/*.py & sh.
As a bonus, bother to be space-in-path safe in init-paths.sh.  Someone is going to make another jenkins job with a space sooner or later, and there are failures elsewhere, but there's no point in failing here.  (If i was spending more time on this, maybe I'd make a fail-fast on spaces)

[INFINITY-1364] toolsreleasesh broken by initpaths

---

frameworks/kafka/universe/config.json

From Confluent documentation and best practices with Kafka:  What I get is that Kafka uses heap very efficiently. Kafka also likes page cache. For example recommendation for a 32G machine is 5G heap max. I would say one should not set more than 4G heap anyway. Here we set defaults. User should change those options in config.json. If you have bigger messages, you may need more heap. You may want to use more memory to benefit from page cache, etc.

[KAFKA] Change heap default to 512MB

---

tools/configure_test_cluster.py
tools/launch_ccm_cluster.py
tools/venvutil.py

I have a theory, mentioned in the jira, that this is a known problem with ensurepip, that it can shortcircuit with "I already have pip!"   Indeed, the spark job is different in that it explicitly downloads pip before launch_ccm_cluster.py ever runs.
This suggests a few possible workarounds.
1 - update the spark code that explicitly downloads a fairly old version of pip for python2 to use python3 and/or venvutil (not certain to work)
2 - drop the downloaded pip off the path before invoking launch_ccm_cluster
3 - have venvutil sniff for pip on the PATH and editing it out if present (seems wrong)
4 - explicitly tell pip to install the packages into the venvutil (what I'm trying here).
Also in this change I'm including a bunch of logging to try to find out if I'm wrong.
-----
Update: what i'm …

[SPARK-448] Shotgun approach to spark venvutil problem; logging + attempted workaround.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java

Xmx and Xms are set to 128M for custom executor.

[SDK] Set Xms/Xmx options before launching custom executor

---

tools/release_builder.py

```
DRY_RUN=true ./release_builder.py 1.2.3-4.5.6 https://infinity-artifacts.s3.amazonaws.com/autodelete7d/dse/20170420-125119-vgaUjTaR1Laj7oNW/stub-universe-dse.zip
```
The above command maintained the ordering defined in `dse-private`.  @mohitsoni:  Thanks for finding the solution.  I'm just submitting the PR and validating.

[INFINITY-1382] Maintain Universe package elements order

---

frameworks/kafka/README.md

This is the initial update for new README.md (new Kafka service guide based on new template). Please change as necessary.
README.md template mentions  ‘node’. This can be confusing for Kafka. In Kafka, we have broker tasks only. You can run multiple brokers on the same Mesos node.

[KAFKA] Update README.md based on template

---

testing/sdk_cmd.py

Same as in dcos-kafka-service; an empty response is false, but still OK.  So accept anything that's not an exception.

[KAF-326] Use new spinner; accept empty 200 success.

---

frameworks/kafka/universe/config.json
test.py
test.sh
tools/cli_install.py
tools/configure_test_cluster.py
tools/run_tests.py

This is essentially a step towards cleaning up how temp dirs and the dcos cli are managed across test runs.
Here we have one working dir for the whole run, and download the cli once (though it's copied a few times).  
It's not exciting alone, but it felt like a necessary preamble to gathering diagnostics on test failure; since we have to do that in test.py  (or test.sh) to make it make sense, which means we need the dcos cli ensured available at that level (the alternative is to just increase the undesirable action pile in CI).

[INFINITY-1370] Download cli once and only once in test.sh & test.py

---

frameworks/hdfs/tests/test_shakedown.py
testing/sdk_plan.py
testing/sdk_tasks.py

Fix intermittent failure in test_kill_all_journalnodes()
- NN's actually do fail when JN's are restarted (https://community.cloudera.com/t5/Storage-Random-Access-HDFS/Namenode-failovered-when-a-JournalNode-restart/m-p/51177)
- Ensure deploy/recovery plans are COMPLETE before querying for updated task IDs
- Remove unneeded checks around zkfc_ids (there are none)
- Replaced `service_plan_complete()/service_cli()` methods with calls to helpers in `sdk_plan`
- Added `get_recovery_plan()` helper to `sdk_plan`
- Included old/current task lists in assertion failure message in `check_tasks_not_updated()`
- DRY up calls to `check_healthy()`

Fix intermittent HDFS shakedown test failure

---

docs/pages/developer-guide.md
docs/pages/yaml-reference.md
frameworks/helloworld/src/main/dist/examples/executor_volume.yml
frameworks/helloworld/src/main/resources/examples/executor_volume.yml
frameworks/helloworld/tests/test_executor_volumes.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultOfferRequirementProvider.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ExecutorRequirement.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultPodSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/PodSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawPod.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/OfferRequirementTestUtils.java
sdk/scheduler/src/test/resources/valid-exhaustive.yml

After moving to task groups, volumes defined on individual task groups will not be visible between other task groups in the same pod. This change allows volumes to be defined at the pod level so that they are attached to the `ExecutorInfo` on launch, which is the mandated method for sharing volumes between task groups in the same pod.

Add volumes to executor

---

new-standalone-service.sh

It's using 0.12.0 as we speak.

Use version 0.15.0 in standalone service generation script.

---

tools/configure_test_cluster.py

modify_master is failing in test runs.  Disable it until we can solve why it
is not working and/or reimplement via a mechanism that doesn't break.

[INFINITY-1439] Disable modify_master in strict mode.

---

cli/commands.go
cli/commands_test.go
docs/pages/developer-guide.md
frameworks/cassandra/build.sh

Manually verified that this works as expected with single and multi-parameter plans.

Use repeated -p parameter for specifying plan envvars

---

tools/publish_aws.py
tools/publish_http.py
tools/release_builder.py
tools/universe_builder.py

Code for building stub universes is switched entirely to the json format. The release builder, meanwhile, still supports both old zips and new jsons for now. The json file now being produced is identical in usage to the prior zip file (`dcos package repo add http://arrl.org/foo.json`, etc...)
Other notable changes:
- Fixes a nasty bug in `release_builder` which would allow always overwriting AWS data (bool('false') => True)
- Adds support in `publish_aws` and `publish_http` for the bizarre universe content type that Cosmos requires for these json files.
- Breaks out the universe version in `universe_builder` to allow easier switching to v4 later.
- Misc formatting fixes that pylint complained about

Update tooling to use drop-in stub universe json format

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceCleaner.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/ResourceCleanerTest.java

If a task is permanently failed, it's resources should not be considered "expected," so they can be cleaned up.

[INFINITY-1380] Fix cleaning of resources for permanently failed tasks.

---

frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/tests/config.py
frameworks/cassandra/tests/test_soak.py

This change includes commits from the Azure branch, will rebase on that PR going through. Relevant changes are in `frameworks/cassandra/tests/test_soak.py` and `frameworks/cassandra/tests/config.py`.

Add test to exercise migration from dcos-cassandra-service

---

test.py

Sometimes CCM fails to accept the trigger-stop http request.  This has occurred due to CCM bugs as well as network connectivity problems.  We don't care about either.

[INFINITY-1352] Dont fail tests on CCM teardown fail.

---

frameworks/elastic/tests/test_shakedown.py
frameworks/elastic/tests/test_soak.py
frameworks/helloworld/tests/test_sanity.py
frameworks/helloworld/tests/test_soak.py
testing/sdk_test_upgrade.py

Modified the upgrade/downgrade integration test to work with services that have beta packages in the Universe. Now the integration test will install the beta- package, if specified, rather than the non-beta package.
- The main change was to add additional parameters to the upgrade_downgrade() method so that the caller can specify different values for (1) Universe package name, (2) test package name, and (3) service name.
- For example, for Elastic, (1) Universe package name = `beta-elastic`, (2) test package name = `elastic`, and (3) service name = `elastic`.
- Before this change, all three names were always the same value, so there was no need to distinguish.

Modify the upgrade integration test to work with beta packages

---

tools/release_builder.py

The package name in beta packages was incorrect because it was derived from the directory path. Fixed by getting it from `package.json` instead.
Dry run output looks correct now (for fake version 1.2.3):
`
Switched to a new branch 'automated/release_beta-kafka_1.2.3-4.5.6-beta_IjbnzQ'
commit bc17a039130df1c26775cb5491bee1a7394d5cde
Author: release_builder.py <jenkins@mesosphere.com>
Date:   Tue May 16 08:48:57 2017 -0700
Release kafka 1.2.3-4.5.6-beta (automated commit)
Changes since revision 1:
0 files added: []
0 files removed: []
4 files changed:
`

Fix release_builder.py package name in beta packages

---

frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/Main.java
frameworks/hdfs/src/test/java/com/mesosphere/sdk/hdfs/scheduler/ServiceSpecTest.java

This envvar is already included automatically in all tasks

HDFS: Don't manually provide FRAMEWORK_NAME envvar

---

test.py

Seems hdfs-role was never validated by the tests, only hdfs2-role,
so this error wasn't caught.

[INFINITY-1588] Correct created role name.

---

frameworks/elastic/build.sh
test.py
tools/cli_install.py
tools/fwinfo.py
tools/run_tests.py

This does a couple things:
* elastic build.sh calls build-kibana.sh
* elastic build.sh arranges to augment its url file with the second url
* test.py handles providing both urls over to run_tests.py
* run_tests.py in turn handles adding both stub_universe definitions to the cluster, so that they can be installed.

Elastic ga2 mult package per framework

---

frameworks/proxylite/universe/package.json

This has been true for a while, but now that we're trying to test on 1.8,
making it explicit is important.

[INFINITY-1619] proxylite requires 1.9.

---

sdk/scheduler/build.gradle

Upgrades `mesos-http-adapter` to version `0.4.1`. Please see release notes for more details:
https://github.com/mesosphere/mesos-http-adapter/releases/tag/0.4.1

Upgrade http adapter to 0.4.1

---

frameworks/helloworld/src/main/dist/examples/cni.yml
frameworks/helloworld/src/main/dist/examples/discovery.yml
frameworks/helloworld/src/main/dist/examples/executor_volume.yml
frameworks/helloworld/src/main/dist/examples/gpu_resource.yml
frameworks/helloworld/src/main/dist/examples/marathon_constraint.yml
frameworks/helloworld/src/main/dist/examples/parameterized-plan.yml
frameworks/helloworld/src/main/dist/examples/plan.yml
frameworks/helloworld/src/main/dist/examples/sidecar.yml
frameworks/helloworld/src/main/dist/examples/simple.yml
frameworks/helloworld/src/main/dist/examples/taskcfg.yml
frameworks/helloworld/src/main/dist/examples/uri.yml
frameworks/helloworld/src/main/dist/examples/web-url.yml
frameworks/helloworld/src/main/dist/svc.yml
test.py
testing/sdk_install.py
tools/fwinfo.py

1 - We were not allowing the install-time selection of service-account/principal to work in the examples/*.yml test configurations.
2 - We were creating the wrong role name due to problems with the helloworld/hello-world service name.

[INFINITY-1606][INFINITY-1616] strict mode failures in helloworld

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/api/JettyApiServer.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/api/JettyApiServerTest.java

* fixed jetty api server test use of bind any ip address (0.0.0.0) as the address that the client performs the http get against, but should be localhost (127.0.0.1 or ::1 or ...)
* 0.0.0.0 is not universally hacked to be treated equivalent to proper loopback addresses, but it may be, i.e. on various linux distros that prefer UX over universally correct implementation.
* made the test ~properly threaded where properly is not using a busy wait.

Fixed JettyApiServerTest use of bind any address as loopback

---

sdk/bootstrap/main.go

Line numbers were wrong, and not very useful. Just show the full diff in a more readable format.
Was already looking at Go stuff and realized this would be easy to fix..

Fix logged template diffs: no linenums, show better info

---

cli/client/http.go
cli/client/http_test.go

TrimRight will remove all characters in the cutset, the intended
behavior is to remove an exact substring, which is TrimSuffix

cli: Fix bug with url parse

---

docs/pages/developer-guide.md

- The unit test example link is broken currently. 
- The unit test example (HelloWorldServiceSpecTest.java) does not seem to exist in dcos-commons currently.

remove missing junit test link

---

frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/Main.java
frameworks/hdfs/src/test/java/com/mesosphere/sdk/hdfs/scheduler/ServiceSpecTest.java

Reverts #990 with some commentary on what's going on.
Scheduler is reproducing what the tasks do when rendering the xml connection files locally.

[HDFS-461] Revert #990: Include FRAMEWORK_NAME when rendering xml endpoints

---

frameworks/cassandra/README.md
frameworks/cassandra/src/main/dist/cassandra.yaml
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache

Before, the Cassandra "auto_snapshot" setting was set to "true". This PR makes the setting configurable, with a default setting of "false".

Make Cassandra "auto_snapshot" option configurable

---

test.py
tools/branch_changes.py
tools/fwinfo.py

As written, this implements INFINITY-1138 & INFINITY-1139.
Basically if only docs files are changed, no frameworks are built or tested.  (Unit tests still run because it doesn't seem worth turning them off;  short runtime and no false failures).
If only files in frameworks/<name> dirs are changed, then those frameworks are built and tested, not others.
If other files are changed, everything is built and tested.

[INFINITY-1138][INFINITY-1139] Don't run unnecessary pull-request tests.

---

frameworks/elastic/tests/config.py
frameworks/elastic/tests/test_shakedown.py
testing/sdk_marathon.py

- Wait for Marathon deployment with `RestartApplication` action to finish before returning from `update_app`

[INFINITY-1700][INFINITY-1693] Fixes race conditions in Shakedown tests

---

frameworks/helloworld/tests/test_discovery.py
test.py
tools/run_tests.py

This amounted to a *lot* less work than expected.
Unexpectedly (to me), almost all of our tests were already intended to perform cleanup (framework uninstall) on every test action.
Thus, this consists of:
* Add cleanup for the one test file that didn't have it.
* When test.py is run with --continue-on-error, invoke pytest without the --exitfirst flag.

[INFINITY-1659] enable run-all-tests

---

frameworks/cassandra/universe/config.json

The Cassandra "auto_snapshot" property was recently made configurable, with a default value of "false". This PR reverts the default value back to "true".

[CASSANDRA-622] Revert Cassandra "auto_snapshot" to default to "true"

---

docs/pages/developer-guide.md

* fixed sdk docs developer guide for health- and readiness-check, properly indenting the YAML to match the necessary level as a TaskSpec attribute.

Fix SDK Docs for health- and readiness-check, YAML indentation

---

frameworks/cassandra/src/main/dist/cassandra.yaml

The "listen_address" in cassandra.yaml was previously set to "{{TASK_NAME}}.{{SERVICE_NAME}}.autoip.dcos.thisdcos.directory". However this dns name can sometimes be invalid during a "replace" operation, since it may still be pointing to the original task host IP.
This PR changes the "listen_address" to be based on LIBPROCESS_IP instead.

[CASSANDRA-623] Fixed cassandra.yaml "listen_address" to use LIBPROCESS_IP

---

frameworks/kafka/tests/test_upgrade.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TaskResourceMapper.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/PortsSpec.java

As part of the very big refactor associated with resource reservation work, PortsSpec stopped being used.  However, we can't just remove it since it breaks upgrade from older versions of the framework that still used PortsSpec
This work detects situations where PortsSpec was used with more than one port, UNRESERVEs all those ports, and makes it clear that they must be re-reserved all within the confines of a single OfferEvaluation cycle.

[INFINITY-1734] Fix Deprecation of PortsSpec

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultSecretSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/VerifySecretFilePathTest.java

If file path (file keyword) starts with "/", user may not have permission outside of its SANDBOX.  Still can write to /tmp for example. 
We are enforcing file path to be relative to the SANDBOX (do not start with "/"). It can be NULL.
@Pattern(regexp = "([a-zA-Z0-9]+([a-zA-Z0-9_-]*[/\\\\]*)*)?")
```
pods:
pod_name:	
secrets:
secret_name1:
secret: hello-world/secret1              <secret path>
env-key: SECRET1_ENV                <environment variable name>
file: some/path/secret2_file             <file path>
```

[SDK] Add file path validation for Secrets

---

frameworks/kafka/src/main/dist/svc.yml

* added kafka readiness-check, ensuring that the starting and started log lines are in the kafka server.log log file.
* the majority of ways to check for readiness are written from the kafka client perspective. the use of the server.log file is IMO much preferable since the check is executing on the server, so should just bubble up to DC/OS the state of kafka readiness that was written to the server.log file.

KAF-353 - Add Kafka Readiness-Check, Using server.log

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ReserveOfferRecommendation.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorVolumesTest.java

See the JIRA.  I broke MOUNT volume resource reservation.  [Replaced the function that used to be there](https://github.com/mesosphere/dcos-commons/blob/c2068b3f66eccfd7cbadf0068a9ce2db8a8297cd/sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ReserveOfferRecommendation.java#L42-L55).
@susanxhuynh has validated it works on a real cluster with MOUNT volumes.
Extended the unit tests to prevent future regressions.

[INFINITY-1768] Fix disk resource reservation

---

docs/.gitignore
docs/pages/services/cassandra/limitations.md

* added manual process to replace a seed node in the Cassandra service.
* added TODO in docs gitignore to refine the ignoring of manually created documentation, i.e. the limitations for each version of each service.
NOTE: due to the inclusion of `docs/.gitignore`, despite being only a documentation change, the CI tests are being run.

CASSANDRA-612 Document Manual Cassandra Seed Node Replace

---

testing/sdk_package.py

- Changing from "dcos dcos package describe" -> "dcos package describe"
- This is because sdk_cmd.run_cli = shakedown.run_dcos_command() NOT shakedown.run_command()

change in testing/sdk_package 

---

frameworks/elastic/tests/config.py

Increase from 15 to 30 minutes as it's sometimes taking 14+ mins during Jenkins runs

[ELASTIC-97] Increase Kibana install timeout

---

sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

Verify that plan has completed before checking the expected results. Test suite has a 30 second per test timeout, so test will timeout despite infinite loop.

Improve robustness of DefaultSchedulerTest

---

tools/piputil.py
tools/run_tests.py

Confusion ensued from "requirements_txt" not being text, but a filename.  Handled partially but not fully.

[INFINITY-1787]Handle arg-provided requirements.txt to run-tests.py correctly.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/dcos/Capabilities.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceBuilder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/validation/CapabilityValidator.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/DefaultResourceCleanerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/MesosResourcePoolTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/ResourceBuilderTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/UnreserveOfferRecommendationTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/ExecutorEvaluationStageTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/LaunchEvaluationStageTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/NamedVIPEvaluationStageTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTestBase.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/PlacementRuleEvaluationStageTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStageTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStageTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/DefaultCapabilitiesTestSuite.java

This should be sufficient changes such that a one line change in `Capabilities` will enable resource refinement.
I tested this on `testing/master` and `testing/pull/1524` manually.

[INFINITY-1365] Prepare refine resources

---

frameworks/hdfs/universe/marathon.json.mustache
frameworks/hdfs/universe/resource.json

The update will take around 10 minutes as the tasks reconcile and the new HDFS stabilizes.

[HDFS-365] Upgrade HDFS to CDH 5.11.0

---

test.py
test.sh

- Foldered services are exercised as `/test/integration/svcname` which maps to a role of `test__integration__svcname-role`
- Removes `svcname2` role setup, as `grep -R 2 frameworks/*/tests/` shows that tests aren't installing a separate `2` instance anymore. Comments imply this was once the case in `dcos-hdfs-service` which is now long gone.

INFINITY-1793 Fix strict mode tests for foldered services (probably)

---

frameworks/cassandra/tests/config.py
frameworks/cassandra/tests/test_recovery.py

The table can flake out and never update (or did once, at least...), whereas nodetool is hopefully more consistent(?). Waits for the old node to disappear and a new node to appear with UN status.

INFINITY-1761 Use 'nodetool' instead of direct task lookup in cassandra node replace test

---

frameworks/hdfs/docs/api-reference.md
frameworks/hdfs/docs/configure.md
frameworks/hdfs/docs/connecting-clients.md
frameworks/hdfs/docs/install.md
frameworks/hdfs/docs/managing.md
frameworks/hdfs/docs/quick-start.md
frameworks/hdfs/docs/troubleshooting.md
frameworks/hdfs/docs/uninstall.md

https://jira.mesosphere.com/browse/INFINITY-1002
@triclambert I've updated the HDFS docs to better conform to the template. The following sections are missing, and there are a few sections (e.g., API reference) that don't appear on the template.
- Install > Node Settings
- Connecting Clients > Connecting Clients to Endpoints
- Managing > Updating Configuration > Resizing a Node
- Managing > Updating Configuration > Updating Placement Constraints
- Managing > Updating Configuration > Restarting a Node (currently in Troubleshooting)
- Managing > Updating Configuration > Replacing a Node (currently in Troubleshooting)
- Disaster Recovery
- Troubleshooting > Accessing Logs
- Troubleshooting > Accessing Metrics
- Limitations
- Support
- Changelog

modified HDFS docs for template, beta version commands

---

tools/publish_aws.py
tools/publish_http.py

Updates (re)install instructions so that users are not confused on when to run janitor or not.
This is the new output:
```
dcos package uninstall hdfs
- - - -
For 1.9 or older clusters only
dcos node ssh --master-proxy --leader "docker run mesosphere/janitor /janitor.py -r hdfs-role -p hdfs-principal -z dcos-service-hdfs"
- - - -
dcos package repo remove hdfs-aws
dcos package repo add --index=0 hdfs-aws https://infinity-artifacts.s3.amazonaws.com/autodelete7d/hdfs/20170623-131101-ev7MAymdnadIMmtc/stub-universe-hdfs.json
dcos package install --yes hdfs
```

[INFINITY-1840] Update build instructions for new uninstall

---

sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

Raise timeout on individual step installs.
Previously, the timeout was increased on the overall deployment completion

[INFINITY-1854] Flaky unit test

---

frameworks/helloworld/tests/test_secrets.py

SDK supports Secrets only for DC/OS 1.10

[SDK] Annotate Secrets tests for dcos 1.10

---

frameworks/cassandra/universe/package.json
frameworks/elastic/universe-kibana/package.json
frameworks/elastic/universe/package.json
frameworks/hdfs/universe/package.json
frameworks/kafka/universe/package.json
frameworks/template/universe/package.json
tools/release_builder.py

The current minDcosVersion handling was only in the release script because our stub-universe.zips were stuck on universe-2.x, which didn't understand this field and which would refuse to install packages that contained it. So at the time we omitted it from stub-universe.zips and just added it when releasing them to universe.
Now that we're on universe-3.x packages in the form of stub-universe.jsons, we can specify it explicitly in the source-controlled package files. This PR also updates the release tooling to require that it already be populated, as it should currently be AT LEAST 1.8 for SDK-based services (leaving the field unset means the package can be installed back to 1.6 IIRC).
TODO separately: Remove the option/envvar from the jenkins release job as this makes the option a noop.

INFINITY-1876 Specify minDcosVersion in package, not release script

---

frameworks/helloworld/tests/test_sanity.py
frameworks/helloworld/tests/test_upgrade.py

- If the test is run in test_sanity, it results in two hello-world instances being installed simultaneously: one with folders (from test_sanity) and one without (from the upgrade test run)
- Skip 2nd upgrade to test version in upgrade test run, as there aren't any followup tests which need the test version to be reinstalled

Move hello-world upgrade test into separate file

---

build.gradle
sdk/scheduler/src/test/java/com/mesosphere/sdk/state/PersistentLaunchRecorderTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/DefaultCapabilitiesTestSuite.java

This test would only fail when ordering was changed and would also
segfault the JVM. The segfault was due to an incompatibility with
gradle's native jansi module. This was fixed with explicitly importing
a newer module. The initial failure was due to
PeristentLaunchRecorderTest shadowing the beforeClass method of parent
DefaultCapabilities test suite. Parent classes were made final to avoid
future NPEs in other classes.

Patch for PersistentLaunchRecorderTest

---

tools/create_service_account.sh

Without this, I run into the following:
```
$ ./tools/create_service_account.sh
++ MODE=
++ '[' 0 -ge 2 ']'
++ '[' '!' 0 -eq 0 ']'
++ SERVICE_ACCOUNT_NAME=dcos_kubernetes
++ SECRET_NAME=dcos_kubernetes
++ echo Creating service account for account=dcos_kubernetes secret=dcos_kubernetes
Creating service account for account=dcos_kubernetes secret=dcos_kubernetes
++ echo Install cli necessary for security...
Install cli necessary for security...
++ dcos package install dcos-enterprise-cli --package-version=1.0.7
Installing CLI subcommand for package [dcos-enterprise-cli] version [1.0.7]
New command available: dcos security
++ echo Create keypair...
Create keypair...
++ dcos security org service-accounts keypair private-key.pem public-key.pem
Failed to execute script dcos-security
Traceback …
```

Fix encoding issues when creating service accounts with Python 3.

---

cli/client/cosmos.go
cli/client/cosmos_test.go
cli/client/print.go
cli/client/response.go
cli/client/testdata/output/bad-app-id.txt
cli/client/testdata/output/bad-json.txt
cli/client/testdata/output/bad-version-no-versions.txt
cli/client/testdata/output/bad-version.txt
cli/client/testdata/output/generic-error.txt
cli/client/testdata/responses/cosmos/1.10/enterprise/bad-app-id.json
cli/client/testdata/responses/cosmos/1.10/enterprise/bad-json.json
cli/client/testdata/responses/cosmos/1.10/enterprise/bad-version-no-versions.json
cli/client/testdata/responses/cosmos/1.10/enterprise/generic-error.json
cli/commands/testdata/output/package-versions.txt
cli/commands/update.go

I've corrected a bug that prevented Cosmos errors from being displayed and added some extra error handling that unpacks Cosmos JSON errors and displays them in a table. Also tidied up a couple of the JSON parsing functions to avoid unnecessary marshaling back and forth.

[INFINITY-1863] [INFINITY-1889] Add better handling for Cosmos JSON validation errors.

---

frameworks/cassandra/tests/test_overlay.py
frameworks/elastic/tests/test_overlay.py
frameworks/hdfs/tests/test_overlay.py
frameworks/helloworld/tests/test_overlay.py
frameworks/kafka/tests/test_overlay.py
frameworks/template/tests/test_overlay.py
testing/sdk_utils.py

Also, adds a utility to do this (as I can't get shakedown's built in marks to work)

Skip all overlay tests in 1.8.

---

frameworks/cassandra/tests/test_recovery.py
testing/sdk_utils.py

Work around dcos task exec differences in 1.9 and 1.10
Disable test for 1.8

Fix task exec issues in a test.

---

frameworks/helloworld/tests/test_secrets.py

We need to make sure integration tests with shadown.dcos_1_10 are not totally skipped...

[SDK] Avoid 'from X import *' in python integration tests

---

frameworks/hdfs/src/main/dist/svc.yml
frameworks/hdfs/tests/config.py
frameworks/hdfs/tests/test_overlay.py
frameworks/hdfs/tests/test_shakedown.py
frameworks/hdfs/universe/config.json
frameworks/hdfs/universe/marathon.json.mustache
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultReadinessCheckSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java
testing/sdk_marathon.py
testing/sdk_plan.py

The deployment plan now waits for the journal nodes to succeed their readiness check before proceeding to deploying the name nodes.

[HDFS-462] Add readiness check to journal nodes

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/TaskUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultTaskSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultTaskSpecTest.java

We weren't cloning ReadinessCheckSpec or DiscoverySpec for TaskSpec.  The test also caught that our `areDifferent` function was out of date.
Ran across this when cloning TaskSpecs for some other work.  Main changes are the DefaultTaskSpec.java, lines 90 and 92.

Fix TaskSpec cloning

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultSecretSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/VerifySecretFilePathTest.java

If using an image, user may need to set for example a cert file in /etc/... 
We need to allow file path starting with /

[INFINITY-1927] File path for Secrets can start with / if in a container

---

frameworks/helloworld/tests/test_recovery.py

Getting the task ips after doing the bump created a race condition where the task ips would be absent when checked (e.g. TASK_KILLED already).

Remove race condition in recovery test

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultServiceSpecTest.java
sdk/scheduler/src/test/resources/invalid-duplicate-ports.yml

Adds validation to a DefaultServiceSpec to check for duplicate port requests e.g.: 
```
ports:
aport:
port: 4444
bport:
port: 4444
```
will fail at compile time now.

[INFINITY-1696] PortSpec conflict validation

---

tools/airgap_linter.py

This should catch lines that contain `"id":`, which should just get JSON lines.

Airgap linter should ignore id lines in files.

---

testing/sdk_jobs.py

In 1.8, jobs run, does not appear to be reliably synchronous, causing flaky behavior.
See: https://teamcity.mesosphere.io/viewLog.html?buildId=707813&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Cassandra_DcOs18Permissive#testNameId-9174911189671957622

Guard against 1.8 flake.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultVolumeSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/VerifyVolumePathTest.java

Comparing with Secrets volumes: 
- container-path can start with / 
This will only work if running in an image (docker container), and have permission, for example user=root. If for example, there is no image, then task will fail - no absolute path.
-  container-path can be relative to Sandbox.
For example:  `someDir/anotherDir/secretFile`
Persistent Volumes: 
- container-path can not have ‘/‘ at all.  (Mesos requirement, see below for the code)
You can not have ` /someDir` (even if under docker image)
You can also not have `someDir/anotherDir`
I experimented with ROOT volumes but this looks a general pattern (including docker isolator).
- **mesos:/src/slave/containerizer/mesos/isolators/filesystem/linux.cpp#L628**
- **mesos:/src/slave/containerizer/docker.cpp#L473**
**PROBLEM:** If …

[INFINITY-2000] Persistent Volume container-path can not contain slash character

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/api/EndpointsResource.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/api/EndpointsResourceTest.java

Use the `TaskStatus` stored in the stateStore (which should be the last `TaskStatus` with a IP address) as a fall-back for when the current `TaskStatus` doesn't gave a IP address when fetching endpoints. 
Tested with a unit test.

[INFINITY-1782] get ip addresses from statestore

---

frameworks/elastic/src/main/dist/install-plugins.sh
frameworks/elastic/src/main/dist/svc.yml
frameworks/elastic/universe/marathon.json.mustache

I removed the `STATSD_PLUGIN` environment variable altogether as it's redundant. The new behavior is that the statsd plugin bits are downloaded for each elasticsearch task, and the versioned plugin is installed from its location in the sandbox using the `file://` protocol **if** we're running in an environment with statsd support.

[ELASTIC-109] Statsd resource ZIP downloaded twice

---

sdk/executor/src/test/java/com/mesosphere/sdk/executor/CustomExecutorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/TaskTestUtils.java

Executor used one thing, Scheduler used the rest.

Break down TaskTestUtils into non-common parts

---

sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/UserCannotChangeTest.java

Fixes the breakage caused by merging a commit which included `apiPort` after `apiPort` had been removed from the `ServiceSpec1`
https://github.com/mesosphere/dcos-commons/commit/19f5541d4b3db9a215913a9ff120e0d5b185f5a2

Fix apiPort breakage

---

build.gradle

This PR enables javadoc and sources artifacts generation and eventual installation.
```
$ ls ~/.m2/repository/mesosphere/scheduler/0.20.0-SNAPSHOT/
maven-metadata-local.xml              scheduler-0.20.0-SNAPSHOT.jar         scheduler-0.20.0-SNAPSHOT.zip
scheduler-0.20.0-SNAPSHOT-javadoc.jar scheduler-0.20.0-SNAPSHOT.pom
scheduler-0.20.0-SNAPSHOT-sources.jar scheduler-0.20.0-SNAPSHOT.tar
```
Note to reviewer(s): javadoc doesn't pass so I had to explicitly instruct Gradle to not fail on error, otherwise the build doesn't pass.

Build and eventually install javadoc and sources artifacts.

---

tools/piputil.py

Previous logic broke in soak-cluster used docker image which supplied python3 from python.org loaded in /usr/local on a debian base image.

[INFINITY-1932] Test for debian python, not debian OS.

---

frameworks/cassandra/tests/test_soak.py
frameworks/elastic/tests/test_soak.py
frameworks/elastic/tests/test_upgrade.py

A few packages got misnamed as a result of cleaning namespaces.

Fix package misname

---

sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/SchedulerApiServerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanCoordinatorTest.java

This PR fixes issues that came up running unit tests on a fresh environment. 
- A number of the tests in `DefaultPlanCoordinatorTest` were failing due to `leader.mesos` not being defined in my environment (thanks to @gabrielhartmann) for the quick fix suggestion.
- I'm not 100% happy with the solution of waiting a little longer for `SchedulerApiServerTest`, where the timeout was being triggered on my machine, but I couldn't come up with a better solution without taking a little more time. In theory, we would want to inject the dependency on the `JettyApiServer` in some way so that we can better control the behaviour and make the tests deterministic. I could also revert the changes to `SchedulerApiServerTest`.

Fix local tests

---

frameworks/cassandra/src/main/dist/svc.yml
frameworks/elastic/src/main/dist/svc.yml
frameworks/hdfs/src/main/dist/svc.yml
frameworks/helloworld/src/main/dist/examples/canary.yml
frameworks/helloworld/src/main/dist/examples/discovery.yml
frameworks/helloworld/src/main/dist/examples/executor_volume.yml
frameworks/helloworld/src/main/dist/examples/gpu_resource.yml
frameworks/helloworld/src/main/dist/examples/marathon_constraint.yml
frameworks/helloworld/src/main/dist/examples/multistep_plan.yml
frameworks/helloworld/src/main/dist/examples/overlay.yml
frameworks/helloworld/src/main/dist/examples/plan.yml
frameworks/helloworld/src/main/dist/examples/pre-reserved.yml
frameworks/helloworld/src/main/dist/examples/secrets.yml
frameworks/helloworld/src/main/dist/examples/sidecar.yml
frameworks/helloworld/src/main/dist/examples/simple.yml
frameworks/helloworld/src/main/dist/examples/taskcfg.yml
frameworks/helloworld/src/main/dist/examples/uri.yml
frameworks/helloworld/src/main/dist/examples/web-url.yml
frameworks/helloworld/src/main/dist/svc.yml
frameworks/kafka/src/main/dist/svc.yml
frameworks/template/src/main/dist/svc.yml
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/UserCannotChange.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawPod.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/UserCannotChangeTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

Now that we set the user on the framework itself, there's no need to have a separate user field on pod specs. This change depends on the default executor, so I'll rebase once that's merged.

[INFINITY-1953] Remove user field from pod specs

---

cli/commands/update.go

* for `dcos ≤service_name≥ update start --options=≤options_file≥` (update), added replace field w/i request w/ a value of `false` to match change in cosmos requiring the presence of this new field and the expected upgrade semantic expected (hash merge => replace).
NOTE: This PR does NOT extend the underlying `replace` field w/i the update request to the customer/user b/c this PR is a breakfix. Additionally, hash merge semantics cover >80% of the use cases for update where the uncovered region is for unsetting fields (use cases that are not currently in the area of exposure). An upcoming PR will extend the replace as well as add/update documentation to explain the difference, covered uses, and relation between the update command and describe command w/i this context.

[INFINITY-1912] Add dcos-commons cli support for update hash merge semantics

---

frameworks/helloworld/tests/test_soak.py

Encountered this error in soak tests:
`TypeError: '>=' not supported between instances of 'int' and 'str'`
Needed to convert string to int.

[INFINITY-1921] Fix type error (str -> int) in hello-world secrets soak tests

---

frameworks/helloworld/tests/test_recovery.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/DefaultConfigurationUpdater.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/dcos/DcosConstants.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/taskdata/TaskLabelReader.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerUtils.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/ConfigurationUpdaterTest.java
testing/sdk_tasks.py

The commons used in universe packages doesn't set the user, and Mesos interprets this as it should set user to root.
Upon an update from release to master, even overriding the default user from "nobody" to "root" doesn't work as the user-change validation fails since the comparison is actually null vs "root".
This fixes that by detecting if the user has been set.
This also adds resiliency to a hello-world test to prevent flakiness, as it also happened to be a blocker for this PR.

[INFINITY-2062][INFINITY-2069] Detect no user from previous service spec

---

frameworks/helloworld/tests/test_sanity.py

As discussed with @benclarkwood, this addressed a flaky test. Due to the presence of a second scheduler, a timeout could occur in `test_sanity.test_lock_teardown`.
This removes the second scheduler before terminating the test.

[INFINITY-2082] Remove second scheduler used for testing locking before end of test

---

frameworks/cassandra/docs/limitations.md
frameworks/cassandra/src/main/dist/cassandra.yaml
frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/Main.java
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/ServiceNameCannotContainDoubleUnderscores.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/TaskEnvCannotChange.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultServiceSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/PodSpecsCannotChangeNetworkRegimeTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/ServiceNameCannotContainDoubleUnderscoresTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/TaskEnvCannotChangeTest.java

- Brings back the DC/rack config options
- Adds `ignore_dc` option to have cassandra allow renames if needed

[INFINITY-2038] Reenable DC configuration options

---

frameworks/helloworld/tests/test_soak.py

In hello-world secrets soak test, installed hello-world CLI because it is used by the test.
@mbdcos This should be the last fix -- I tested this fix in my own cluster and the test passed.

[INFINITY-1921] In hello-world secrets soak test, installed hello-world CLI

---

frameworks/elastic/tests/config.py
frameworks/elastic/tests/test_shakedown.py
testing/sdk_install.py

- the default uninstall timeout of 120s is too short. Elastic and perhaps other FW's can take longer. Increasing to 15 minutes.
- Kibana should be uninstalled both as part of setup to make sure it's not already there, and teardown to make sure it isn't left around to potentially affect downstream tests.
- the default per-pytest timeout of 30 minutes is too short for test_xpack_toggle_with_kibana. Increasing to 1hr.
- The current test logic is not correct and I'm not sure how it ever works. In https://github.com/mesosphere/dcos-commons/blob/master/frameworks/elastic/tests/test_shakedown.py#L83-L86, we enable x-pack in elasticsearch, and then install kibana without x-pack and test integration between the two.

[INFINITY-2100] Improve stability of test_xpack_toggle_with_kibana

---

docs/pages/operations-guide.md

After switching to Default Executor, Absolute Path support for Secrets (supported only if there is a docker image) is dropped. All Secret files are relative to the SANDBOX.

[INFINITY-2085] Update Docs: Default Executor does not support Absolute Path for Secrets

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultSecretSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/VerifySecretFilePathTest.java

After switching to Default Executor, Absolute Path support for Secrets (supported only if there is a docker image) is dropped. All Secret files (similar to Volumes) are relative to the SANDBOX.
PS: We only have pod-level secrets. We do not have task-level secrets, dropped in the design phase

[INFINITY-2085] Default Executor does not support Absolute Path for Secrets

---

frameworks/cassandra/tests/config.py
frameworks/cassandra/tests/test_backup_and_restore.py
frameworks/cassandra/tests/test_overlay.py
frameworks/cassandra/tests/test_recovery.py
testing/sdk_install.py
testing/sdk_jobs.py
testing/sdk_plan.py
tools/setup_permissions.sh

This fixes the C* tests by setting the user properly for a strict mode cluster. Previously the jobs were failing because the writer couldn't be successful writing as "root".
This also:
- fixes a few utility names and prevents an exception from being thrown if it tries to remove C* jobs but none exist if the installation wasn't successful.
- extends the timeout for a node replace test as that commit got dropped in 
https://github.com/mesosphere/dcos-commons/pull/1370
This passes all C* strict clusters:
- 1.8: https://teamcity.mesosphere.io/viewLog.html?buildId=727876&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Cassandra_DcOs18Strict
- 1.9: https://teamcity.mesosphere.io/viewLog.html?buildId=727875&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Cassandra_DcOs19Strict
- master: …

[INFINITY-2131][INFINITY-2003][Cassandra] Fix C* strict tests

---

conftest.py

This fixture will output a file of the form "{test_name}_{scheduler_task_id}.log" for any test that fails. TeamCity will pickup and host all .log files

Add implicit fixture to capture scheduler logs

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DeploymentStep.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DeploymentStepTest.java

The deployment step should go back to PENDING on TASK_LOST.  I saw this in the wild and forced it back to PENDING with the `plan force-restart` command and it worked.  All other failure cases are handled this way, TASK_LOST should work the same way.

[INFINITY-2157] Reset to PENDING on TASK_LOST in DeploymentStep

---

frameworks/helloworld/src/main/dist/examples/pre-reserved.yml
frameworks/helloworld/tests/test_resource_refinement.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultResourceSet.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java

The role for all resources consuming pre-reserved resources should
conform to the `pre-reserved-role/service-role` pattern.  VolumeSpecs
generated from the pod level were not conformant.
For example the YAML below was generating a RESERVE operation with a role of `hello-world-role`, when it should have been `slave_public/hello-world-role`.
```yaml
hello:
pre-reserved-role: slave_public
count: {{HELLO_COUNT}}
placement: {{HELLO_PLACEMENT}}
volume:
path: pod-container-path
type: ROOT
size: {{HELLO_DISK}}
```
Additionally, the resource refinement test wasn't really exercising resource refinement, which is now fixed.

[INFINITY-2135] Fix resource refinement on pod level volumes

---

frameworks/kafka/tests/test_utils.py

The restarting all pods test was not waiting to see the pods reached `RUNNING`. Fixed.

[INFINITY-2137] Flaky kafka pod replace test

---

tools/ccm_extend.py

Test builds failing when it can't find `os.exit()`:
https://teamcity.mesosphere.io/viewLog.html?buildId=736906&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Hdfs_BuildAndTestPr

sys.exit not os.exit

---

sdk/scheduler/build.gradle
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/TemplateUtils.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/yaml/TemplateUtilsTest.java
sdk/scheduler/src/test/resources/test-render-inverted.yml

The environment for mustache rendering should not consist entirely of
strings, but boolean objects in the case of "true" or "false" values

Fix inverted section mustache rendering

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStage.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStage.java

There were errors in PortEvaluationStage and VolumeEvaluationStage
logging which had a mixture of "previously reserved" messages and
inconsistent resource IDs.

Fix evaluation stage logging

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java

Implicit acknowledgement of TaskStatus messages requires that exit from
the Scheduler `statusUpdate` function implies complete processing of the
message.  Processing on an async thread breaks this assumption.
It's also making the DefaultSchedulerTest.testConfigurationUpdate non-deterministic. 
NOTE:  The diff looks weird.  I just removed the executor service and stopped wrapping calls to `statusUpdate` with use of that service.

[INFINITY-2187] Process TaskStatus messages synchronously

---

docs/pages/tutorials/secrets-tutorial.md

I have been preparing a tutorial with a real application such as NGINX secure web server. There is a branch ready about secure-NGINX with secrets.
The problem is that we need to create a new framework for this tutorial. And we do not have a framework generation procedure. Generating a new framework from template is not automated and it requires a lot of explanation.
Eventually, secret tutorial would become more about how to write a standalone framework using SDK.
Since we do not have a automated and easy way to create a new framework, and we do not want to go into all build and universe details about how to generate a framework, it is best to skip secure-NGINX example, and use something that already exists in dcos-commons, such as hello-world for secrets tutorial.

[INFINITY-1877] Add Secrets Tutorial

---

frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache
frameworks/elastic/universe/config.json
frameworks/elastic/universe/marathon.json.mustache
frameworks/hdfs/universe/config.json
frameworks/hdfs/universe/marathon.json.mustache
frameworks/helloworld/tests/test_tls.py
frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache
frameworks/kafka/universe/config.json
frameworks/kafka/universe/marathon.json.mustache
frameworks/template/universe/config.json
frameworks/template/universe/marathon.json.mustache
testing/sdk_install.py

This changes only the keyword in config.json (what a typical user sees), not in yaml so SDK code should not be affected.
@keithchambers principle -> service_account change
related PR #1432

[INFINITY-1260] Change "principal" to "service_account" in config.json options 

---

testing/sdk_install.py

New version uses `service_account` instead of `principal` in config.json.

Give "principal" in additional options, to install a previous version.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java

I stress tested suppress/revive yesterday.  Ran it for many hours with `hello-world` at different `SLEEP_DURATION`s.  Found a deadlock.  Long story short it's a deadlock through the `MesosToSchedulerDriverAdapter`.  TaskStatus updates or offers at the same time a revive/suppress attempt is made can generate the condition below.  So I've made the event bus asynchronous which will break the cycle.  I'm stress testing again overnight.
```
Java stack information for the threads listed above:
===================================================
"Thread-13542":
at com.mesosphere.sdk.scheduler.SuppressReviveManager.transitionState(SuppressReviveManager.java:121)
- waiting to lock <0x00000000e06e18d8> (a java.lang.Object)
at com.mesosphere.sdk.scheduler.SuppressReviveManager.handleTaskStatus(Suppre …
```

Make event bus asynchronous

---

sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

Wait for task to be starting before sending TASK_RUNNING status as that is what happens in the real world.

[INFINITY-2075] Fix DefaultSchedulerTest.testConfigurationUpdate

---

frameworks/helloworld/tests/test_recovery.py
frameworks/kafka/tests/test_availability.py

* Ensure graceful shutdown tests are marked to run only on dc/os 1.10+.
* Fix merge conflict on sdk_tasks -> tasks -> sdk_tasks (import change).
For reconciliation sake, see https://github.com/mesosphere/dcos-commons/pull/1331 for the list of tests introduced for the feature.

[KAF-350] Ensure Graceful Shutdown is tested on 1.9+

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/TaskUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SuppressReviveManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/state/StateStoreUtils.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/SuppressReviveManagerTest.java

While testing we ran into this situation:
```
INFO  2017-08-22 01:44:32,946 [Thread-108] com.mesosphere.sdk.state.StateStore:storeStatus(198): Storing status 'TASK_KILLED' ...
...
INFO  2017-08-22 01:44:33,002 [pool-8-thread-1] com.mesosphere.sdk.scheduler.recovery.DefaultRecoveryPlanManager:getRecoveryRequirements(212): New pods needing recovery: []
...
INFO  2017-08-22 01:44:33,004 [pool-12-thread-1] com.mesosphere.sdk.scheduler.SuppressReviveManager:setOfferMode(210): Suppressing offers.
...
INFO  2017-08-22 01:44:37,241 [Thread-110] com.mesosphere.mesos.HTTPAdapter.MesosToSchedulerDriverAdapter:received(181): Received event of type: HEARTBEAT
INFO  2017-08-22 01:44:52,243 [Thread-111] com.mesosphere.mesos.HTTPAdapter.MesosToSchedulerDriverAdapter:received(181): Received event of type: …
```

[INFINITY-2264, INFINITY-2270] Suppress transition from REVIVED to WAITING_FOR_OFFER

---

test.sh

With this change, ctrl + c will exit test.sh and kill the container.
ctrl + q + p to simply detach.

Use -t and -i to make the docker attach behave as a normal shell script.

---

testing/sdk_tasks.py

- Sometimes it can take over 15 minutes for a task to get up and running, perhaps due to very slow IO around downloading resource URIs and extracting the files.

[ELASTIC-120] Elastic deployment sometimes fails to COMPLETE

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultResourceSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultVolumeSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/NamedVIPSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/PortSpec.java

These strings may be used in e.g. config validation errors. Clean them up:
- Subtypes can just prepend the parent type's info
- Ensure subtypes have all fields filled in, and follow json naming while we're at it

INFINITY-2292 Better resource strings

---

frameworks/kafka/docs/upgrade.md

Upgrading from 0.10 version to 0.11 version (See PR #1239)
(step 1) Update to 0.11 version but use an options.json file to set protocol/log version to 0.10
(step 2) Change protocol version to 0.11.0 and update again
(step 3) Change log version to 0.11.0 and update again

[KAF-362] Add upgrade documentation for Kafka upgrade from 0.10.2.x to 0.11.0

---

frameworks/cassandra/src/main/dist/cassandra.yaml

While reviewing #1426 @mhrabovcin found an error in `cassandra.yaml` file where `CASSANDRA_COMMITLOG_TOTAL_SPACE_IN_MB` was not being correctly closed and thus not applied to `commitlog_total_space_in_mb`.
For the record:
```sh
grep -R -E ":\s+\{\{\w+[^\}]$" .
```
shows the missing braces (and no others), but is not an exhaustive set.
An open question is how to test these kinds of changes? Any thoughts?

[INFINITY-2306] Correct closing brace in Cassandra Moustache setting 

---

frameworks/cassandra/tests/config.py

Fix flakes such as:
```
I0824 23:10:39.743618 13789 executor.cpp:160] Starting task test_cassandra_delete-data_20170824231038Ct4vr.71daf3e1-8921-11e7-8c06-8a15a895e7e2
<stdin>:1:OperationTimedOut: errors={'10.0.0.175': 'Request timed out while waiting for schema agreement. See Session.execute[_async](timeout) and Cluster.max_schema_agreement_wait.'}, last_host=10.0.0.175
```
and:
```
I0824 23:21:45.697402  6594 executor.cpp:160] Starting task test_cassandra_verify-deletion_20170824232123MtB9C.f1f221b5-8922-11e7-8c06-8a15a895e7e2
Connection error: ('Unable to connect to any servers', {'9.0.6.2': error(None, "Tried connecting to [('9.0.6.2', 9042)]. Last error: timed out")})
W0824 23:21:45.697402  6591 logging.cpp:91] RAW: Received signal SIGTERM from process 6305 of user 0; exiting
```

INFINITY-2304 cassandra tests: retry on failure

---

frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/tests/test_overlay.py
frameworks/cassandra/tests/test_sanity.py
frameworks/cassandra/universe/config.json

- The cassandra VIP was previously only enabled because VIP presence == shown in `endpoints`. Now that the two are decoupled, the cassandra VIP should be removed.
- Renames the 'node' endpoint 'native-client'
- Enables display of a 'thrift-client' endpoint when thrift is enabled
- Refrains from reserving the thrift port when thrift isn't enabled

INFINITY-1975 Tweaks to Cassandra endpoints: rename node=>native-client, remove VIP, show thrift-client when enabled

---

frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/tests/test_overlay.py
frameworks/cassandra/tests/test_sanity.py
frameworks/cassandra/universe/config.json

- The cassandra VIP was previously only enabled because VIP presence == shown in `endpoints`. Now that the two are decoupled, the cassandra VIP should be removed.
- Renames the 'node' endpoint 'native-client'
- Enables display of a 'thrift-client' endpoint when thrift is enabled
- Refrains from reserving the thrift port when thrift isn't enabled

BACKPORT: INFINITY-1975 Tweaks to Cassandra endpoints: rename node=>native-client, remove VIP, show thrift-client when enabled

---

frameworks/helloworld/src/main/dist/examples/sidecar.yml
frameworks/helloworld/tests/test_sidecar.py

This is a straight backport of #1434 (5a5efb32e16910163ca5425e7a1ef49c7e461769)

[INFINITY-2216] backport #1434 to fix toxic sidecar tests

---

frameworks/cassandra/docs/connecting-clients.md
frameworks/cassandra/docs/quickstart.md

- `node` has been renamed to `native-client` to align with DSE
- Mention that an additional `thrift-client` endpoint is automatically exposed if Thrift is enabled (via `cassandra.start_rpc`)
- Fix indent for a code block in quick start
- Added caveat about IPs possibly changing if cassandra nodes are moved between machines
- Added note to quick start about specifying multiple addresses in production use (too much for quick start?)

INFINITY-2335 Documentation updates to reflect Cassandra endpoint rename

---

tools/release_builder.py

Syntax error was the missing 'path' variable in the prior log

Fix syntax error, log all changes made in package.json

---

frameworks/cassandra/tests/config.py
frameworks/elastic/tests/config.py
frameworks/elastic/tests/test_sanity.py

INFINITY-2274: elastic - replace import-time cluster actions
(also a one-line, unused dependency added to cassandra)

elastic - replace import-time cluster actions

---

frameworks/kafka/docs/upgrade.md

This needs to be verified manually to ensure all these instructions are up to date and correct.
->
Originally  a **generic** document was prepared,  explaining upgrade from _0.10.2 Kafka_ to _0.11.1 Kafka_, and explaining upgrade in strict mode with service account change. It was referring versions as **old version** (with x) and **new version** (with y). 
Then based on reviewers, _version numbers_ in the current document were added. Now the existing document is not a generic document. It became version specific. 
See the following PRs:
#1449
#1429
2.0.0 GA release does not have any `upgradesFrom` field, so this document will be misleading
We do not support upgrade from betas to GA for the moment.
This PR is to modify the upgrade document from 1.1.26-beta to 1.1.27-beta (these are the …

[INFINITY-2236] Verify Kafka upgrade instructions from 1.1.26-beta 

---

frameworks/cassandra/tests/config.py
frameworks/cassandra/tests/test_sanity.py
frameworks/elastic/tests/config.py
frameworks/elastic/tests/test_sanity.py
frameworks/hdfs/tests/config.py
frameworks/hdfs/tests/test_sanity.py
frameworks/kafka/tests/config.py
frameworks/kafka/tests/test_sanity.py
testing/sdk_api.py
testing/sdk_cmd.py
testing/sdk_hosts.py
testing/sdk_install.py
testing/sdk_jobs.py
testing/sdk_marathon.py
testing/sdk_metrics.py
testing/sdk_networks.py
testing/sdk_plan.py
testing/sdk_repository.py
testing/sdk_security.py
testing/sdk_tasks.py
testing/sdk_upgrade.py
testing/sdk_utils.py

This checks each service for reporting a set of specific metrics, the logic being that if this set is reported by the service then the greater set of all metrics is being properly reported as well.
Some autopep8 cosmetic edits are also in this change set.

[INFINITY-2301] Verify service-specific metrics are being reported

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/api/ConfigResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/EndpointsResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/PlansResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/PodResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/api/ConfigResourceTest.java

- Annotations and generic type on ConfigResource: Fixing some jersey warnings emitted on scheduler startup.
- Downgrade of EndpointResource logs: Produces noise on every query, which is only really useful for service developers anyway
- Other log fixes: Nitpicks.

INFINITY-2326/2327 Cleanup of some startup warnings, and other minor logging improvements

---

frameworks/kafka/docs/configure.md
frameworks/kafka/docs/connecting-clients.md
frameworks/kafka/tests/test_tls.py
frameworks/kafka/universe/config.json

This removes the Kafka TLS settings from the stable branch. I've simply removed them from config.json and the docs. The overall plumbing still exists.

[INFINITY-2359] Disable kafka tls in stable

---

frameworks/cassandra/docs/limitations.md
frameworks/cassandra/universe/config.json

Our implementation does not support less than 2 seeds and 1 data node.

[INFINITY-2351] Require a minimum node count of 3

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/PreReservationCannotChange.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/TLSRequiresServiceAccount.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/PodSpecsCannotShrinkTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/PreReservationCannotChangeTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/ServiceNameCannotContainDoubleUnderscoresTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/TLSRequiresServiceAccountTest.java

Backport of #1510.
For the release notes: 
> Removal of a Pod could result in a null-pointer exception.

[INFINITY-2316] Fix removal of pod causes NPE

---

frameworks/hdfs/docs/api-reference.md
frameworks/hdfs/docs/configure.md
frameworks/hdfs/docs/connecting-clients.md
frameworks/hdfs/docs/index.md
frameworks/hdfs/docs/install.md
frameworks/hdfs/docs/managing.md
frameworks/hdfs/docs/quick-start.md
frameworks/hdfs/docs/troubleshooting.md
frameworks/hdfs/docs/uninstall.md

* Ensure all command line blocks are taged as `bash`
* Ensure all command line examples start with `$`
* Change incorrect reference to Apache Cassandra
* Change incorrect reference to Kafaka
* Other minor typo corrections.
I have another branch with similar changes to 0.30.X, but we can try a backport first.

[DCOS-17876] Add $ to command line examples in HDFS docs

---

frameworks/cassandra/tests/test_tls.py
frameworks/helloworld/tests/test_secrets.py
frameworks/helloworld/tests/test_tls.py
frameworks/kafka/tests/test_tls.py
testing/sdk_utils.py

Detect DC/OS Open and disable tests for features that do not work there.
Adds a `sdk_utils` pytest mark.
Disables TLS and secrets tests.

[INFINITY-2374] Disable tests that will not pass in open

---

testing/sdk_jobs.py
testing/sdk_metrics.py

`job show runs` no longer returns the just-started job if it finished too quickly(???).
Get around this by extracting the ID directly from the `job run` output.
For example:
```
》dcos job run test.cassandra.verify-deletion
Run ID: 20170907163128RQ9AC
0
》dcos job show runs test.cassandra.verify-deletion --json
[]
0
》[2.2s/10m] spinning...
...
```

INFINITY-2174 Fix more metronome flakes

---

frameworks/helloworld/tests/test_secrets.py
frameworks/helloworld/tests/test_tls.py
frameworks/kafka/tests/test_tls.py
testing/sdk_utils.py

* Detect DC/OS Open and disable tests for features that do not work there.
* Bad python
* Disable C* TLS test in open

[INFINITY-2374] Disable tests that will not pass in open (#1567) (backport)

---

frameworks/helloworld/tests/test_recovery.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DeploymentStep.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DeploymentStepTest.java
testing/sdk_utils.py

* Fix typo
* Only wait for world-0 on pod replacement
* Minior cleanup of check tasks updated
* Temporary state hack
* Modify DeploymentStep status calculation to be the "least" status of its consituent tasks.
* Add explicit order parameter to Status.java
* Add testing for getStatus()
* Add clear doc of why the logic is valid.
* Revert "Add explicit order parameter to Status.java"
This reverts commit 0a0f90f89ceb497b7a3ac69380b329c0820342ef.
* Explicitly handle all expected states.
* PMD fix
* Clarify comments

[INFINITY-2309] Fix handling of DeploymentStep status changes. (#1488) (backport)

---

docs/pages/operations-guide.md

* Remove `beta-` from package names in docs.
* beta-dse was referenced, but dse is not w/i this repo, so the content was replaced w/ hdfs, so required changing the output to match.

Remove `beta-` from package names in docs.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/api/PlansResource.java

Log the parameters supplied in start, and also return them in feedback to the user.
The CLI receives:
```
Mesospheres-MacBook-Pro-2:dcos-commons benwood$ dcos beta-cassandra --name=cassandra plan start backup-s3 -p TEST0=BANANA -p TEST1=PIE
{
"message": "Received cmd: start backup-s3 with parameters: {TEST0=BANANA, TEST1=PIE}"
}
```
The scheduler logs show:
```
INFO  2017-09-08 02:37:42,184 [qtp202217792-38] com.mesosphere.sdk.api.PlansResource:startPlan(114): Started plan backup-s3 with parameters {TEST0=BANANA, TEST1=PIE} by user request
```

[INFINITY-2384] PlansResource should log parameters on plan start.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/OfferQueue.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/OfferQueueTest.java

The work represented by plans is not solely accomplished by the consumption of offers.  In particular the leaf element of plans, a step, can return an `Optional<PodInstanceRequirement>` when it is started.
The execution of plans is today driven by the presence or absence of offers, however logically when no work requiring offers is present the scheduler should suppress offers.  However steps which do not require offers should still be processed.
In this change, we now no longer block plan execution on waiting for offers.  If offers are present they are consumed otherwise plan execution continues without them.
This is a pre-requisite for #1578

Decouple plan execution from the offer cycle

---

frameworks/cassandra/src/main/dist/svc.yml

Following #1539 and also https://github.com/mesosphere/dcos-commons/pull/1617#discussion_r138995536
I have removed `CONFIG_TEMPLATE_PATH` from the Cassandra service spec.

Remove CONFIG_TEMPLATE_PATH from cassandra

---

docs/pages/developer-guide.md

Checked all instances of `plans:` and cleaned up the ones that were out of date. Validated against yaml reference as well as relevant `Raw*.java` (yaml reference appears up to date)

INFINITY-2418 Fix plan examples in dev guide

---

frameworks/helloworld/tests/test_sanity.py
frameworks/kafka/tests/test_sanity.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/Constants.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/OfferUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/ReviveManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SuppressReviveManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanCoordinator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanCoordinator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PodInstanceRequirement.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/OfferUtilsTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/ReviveManagerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/SuppressReviveManagerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanCoordinatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/UninstallSchedulerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/PodTestUtils.java
testing/sdk_install.py
testing/sdk_upgrade.py

Instead of suppressing offers when all work is complete, we now set a decline timeout of 2 weeks (a.k.a. forever) whenever we suppress any offer.  When we see *new* work (`PodInstanceRequirement`s) we assume that the offers we've declined forever may be useful to that work, and so we revive offers.
Pseudo-code algorithm is like this:
```
// We always start out revived
List<Requirement> currRequirements = getRequirements();
while (true) {
List<Requirement> newRequirements = getRequirements() - currRequirements;
if (newRequirements.isEmpty()) {
print “No new work”;
} else {
currRequirements = newRequirements;
revive();
}
}
```
I've left out the `supress` portion of the logic in the pseudocode, but it's in the real code.  Basically if there's no work, suppress.
A natural question is why do …

[INFINITY-2364] Move from suppress/revive to decline/revive logic

---

frameworks/hdfs/tests/test_sanity.py
frameworks/kafka/cli/dcos-kafka/.gitignore
testing/sdk_tasks.py

* Fix HDFS test_sanity.test_modify_app_config, send proper task
prefixes.
* Improve tasks updated detection, not yet reconciled log line to
use set methods to report the intersection and difference instead
of iteration.
Unrelated, but discovered:
* Fix .gitignore for Kafka to match pattern used in other services.

[INFINITY-2408] Fix HDFS test_sanity - tasks updated detection

---

frameworks/kafka/tests/test_availability.py

* Make env variable name consistent BROKER_KILL_GRACE_PERIOD.
* Remove errant personal pytest mark.
backport PR #1611

[KAF-374] Fix test_availability env variable consistency

---

tools/README.md
tools/release_builder.py

When an org maintains their own universe fork this allows them to use `release_builder.py` to submit automated PR's to it.

Optionally override target GitHub repo for release

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManager.java

Recovery and Default plan managers were calculating dirty assets in
different ways and the RecoveryPlanManager was doing it wrong.

Standardize dirty asset computation

---

build.sh
sdk/common/build.gradle
tools/build_go_exe.sh

* Squelch common lib test coverage.
* Benefit of common lib test coverage is low, coverage is including
lines that cannot cause issue such as setting a const used as a key.
* Fix unrelated golang sub-project setup, closing out the great
re-vendoring.

[INFINITY-2422] Squelch common lib test coverage

---

frameworks/sdkspark/src/main/dist/svc.yml
frameworks/sdkspark/universe/config.json
frameworks/sdkspark/universe/marathon.json.mustache

To run with the history server, set the follow config values in config.json or via DC/OS UI:
- service.eventlog_enabled (=true)
- service.eventlog_dir (example: hdfs://hdfs/history)
- hdfs.config-url (example: "http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints")

[INFINITY-2435] Config to enable running with history server

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/ReviveManager.java

This is a small PR with a big effect because it relies on Mesos behavior.  The end result of this PR is that any given set of crash looping tasks generate at most `1` revive call.  This means that very scalable recovery is possible without any actions which impact other frameworks (i.e. `revive` calls) and without relying on our revive throttling mechanism.
No revive calls are necessary from a Mesos perspective when a Task crashes.  The task was originally launched by _accepting_ an offer.  So that offer was not declined forever (2 weeks).  When the task crashes those resources will be re-offered to the scheduler.  The re-offer is guaranteed in our case because we reserve resources.  The scheduler should accept them and recover the task.
From an SDK scheduler perspective we now treat work …

[INFINITY-2462] Rely on Mesos offer accept/decline behavior

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/state/ConfigStore.java

Used VisualVM profiler to find what was slowing down DefaultSchedulerTests.  ConfigStore was caching the ServiceSpec's serialized format but still parsing it every time some component looked up a configuration.  The parsing was taking a long time.  So I've added some caching post-parsing.  This manifested in the Scheduler logs as an approximately `0.250s` delay on an empty iteration of the scheduling loop.  This delay has disappeared.

Cache config objects in memory in the ConfigStore

---

frameworks/elastic/src/main/dist/elasticsearch.yml
frameworks/elastic/universe/config.json
frameworks/elastic/universe/marathon.json.mustache

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html#_deprecated_script_settings

[ELASTIC-136] Add scripting parameters. Please note that deprecated settings are omitted

---

frameworks/elastic/universe/package.json

This PR updates the default resource requirements to match master (with 0 ingest nodes). This was done for master in #1532.

[ELASTIC-137] Update default resources for 0 ingest nodes

---

frameworks/helloworld/universe/marathon.json.mustache

HW scheduler was using 1.0 CPUs. Reduced to 0.5 CPUs to match other frameworks.

Reduce HW scheduler CPU to match other frameworks.

---

cli/commands/plan.go
cli/commands/plan_test.go

Backport of #1664:
* INFINITY-2454: Handle a 417 return code on the plan endpoint.
(this replaced #1663)

[INFINITY-2454] Handle a 417 return code on the plan endpoint. (#1664)

---

docs/pages/developer-guide.md
docs/pages/operations-guide.md
docs/pages/reference/yaml-reference.md
docs/pages/tutorials/kafka-tutorial.md
docs/pages/tutorials/secrets-tutorial.md
frameworks/hdfs/docs/api-reference.md
frameworks/hdfs/docs/install.md
frameworks/hdfs/docs/managing.md
frameworks/kafka/docs/api-reference.md

We changed the option name.  Docs should follow.
I'm assuming the "principal" that appears in resource sets, reservations, and log messages about offers are all unchanged.

[INFINITY-2446] Update docs for changed option for service account.

---

cli/client/cosmos.go
cli/commands/update_test.go

This PR properly handles integers (or non-string data type) in update specification errors.
The main problem was the the `Found` field in `cosmosError` was specified as a `string`, meaning that `int` data (e.g. the number of nodes) could not be properly unmarshalled.
I changed the field type (and that of `Expected`) to `interface{}` allowing all data types to be handed.
I also added two simple unit tests for two cases.

[INFINITY-2455] Properly parse ints in update errors

---

cli/client/cosmos.go
cli/commands/update_test.go

This is a backport of the changes from #1698 to properly handle validation errors in service update.

[INFINITY-2455] correctly handle errors in options json

---

docs/pages/reference/yaml-reference.md
frameworks/hdfs/src/main/dist/svc.yml
frameworks/helloworld/src/main/dist/examples/overlay.yml
sdk/common/src/main/java/com/mesosphere/sdk/offer/taskdata/EnvConstants.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/EndpointUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java

- Adds `FRAMEWORK_VIP_HOST` in parallel to existing `FRAMEWORK_HOST`: a domain for pointing service tasks to VIPs within the service
- Replaces `FRAMEWORK_SCHEDULER_NAME` (originally added for, and currently only used by, HDFS) with `SCHEDULER_API_HOSTNAME`, allowing tasks to avoid hardcoding the rest of the scheduler API VIP in tasks.
- Update docs and examples to reflect the above

INFINITY-2434 Add task envvars: service VIP domain, scheduler API hostname

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/PortEvaluationStageTest.java

* If a task is being replaced, drop its previous dynamic ports from consideration.
Add test for this behavior.
* Fix merge issue

[INFINITY-2498] Drop sticky dynamic ports on replacement (#1702)

---

tools/dcos_login.py

Docker passes in the envvars added in https://github.com/mesosphere/dcos-commons/commit/15fb4dcd6a402c48184fb40581fb47ae1c32f961 as `" "` in the case that the user does not have them set.
I've patched this in the Python, rather than trying figure out how to get Docker to NOT do this. And also because this was the fastest way I thought of to fix it.

[INFINITY-2514] Fix automatic login regression

---

tools/dcos_login.py

Login sporadically flakes out if attempted directly after deployment time

Retry login for up to 2 minutes

---

cli/client/response.go

Certain error conditions in the CLI can result in an error that looks like this:
```
dcos-edgelb: error: Get http://172.17.0.2/service/edgelb/v1/ping: Got 401 Unauthorized response from http://172.17.0.2/service/edgelb/v1/ping
"- Bad auth token? Run 'dcos auth login' to log in., try --help
```
It's preferable to see this:
```
dcos-edgelb: error: Get http://172.17.0.2/service/edgelb/v1/ping: Got 401 Unauthorized response from http://172.17.0.2/service/edgelb/v1/ping
- Bad auth token? Run 'dcos auth login' to log in, try --help
```

Remove quote and period from error string

---

frameworks/cassandra/tests/test_backup_and_restore.py

Primary change on Line 64. The `config.` was missing from the `run_backup_and_restore()` call.
See for example: https://teamcity.mesosphere.io/viewLog.html?buildId=820033&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Cassandra_Open_DcOs110Open#testNameId-5215163970954276115
Other minor fomatting changes

Fix missing module name in Cassandra azure backup test

---

frameworks/helloworld/tests/test_sanity.py
testing/sdk_install.py
testing/sdk_security.py
testing/sdk_utils.py

* Skip v1 api in strict
* Use mark.skipif
Backport of #1737

Skip the v1 API test in strict mode (#1737)

---

frameworks/helloworld/tests/test_resource_refinement.py

`test_resource_refinement.test_install` cannot currently succeed in *strict* mode.
Disable this so that this failure does not cascade to other tests.
This would also allow the enabling of a strict-mode PR job.
This should also be backported.

[INFINITY-2540] Add module-level skip for test_resource_refinement in strict

---

frameworks/elastic/tests/test_tls.py

The TLS tests were still enabled for Elastic on Open DC/OS and were failing:
https://teamcity.mesosphere.io/viewLog.html?buildId=820071&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Elastic_Open_DcOs110Open#testNameId3594191691547943286
This should be backported.

[INFINITY-2553] Skip Elastic TLS tests in Open DC/OS

---

docs/reference/swagger-api/swagger-spec.yaml
sdk/scheduler/build.gradle
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/OfferAccepter.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/OfferUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/Metrics.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/ReviveManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerApiServer.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerRunner.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/OfferUtilsTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/MetricsTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/SchedulerApiServerTest.java

We now expose some metrics.
1. LAUNCH count
1. LAUNCH_GROUP count
1. revive count
1. decline_long (2 weeks) count
1. decline_short (5 seconds) count
1. received_offers count
1. processed_offers count 
1. process_offers performance histogram (how long does it take to process a set of Offers)
They're exposed in standard json format at `v1/metrics` and in prometheus format at `v1/metrics/prometheus`
This was needed as part of scale testing.  It's been very handy and may turn out to be handy elsewhere.
*EDIT*: After comments addressed:
```
{
version: "3.1.3",
gauges: {},
counters: {
declines.long: {
count: 15
},
offers.processed: {
count: 18
},
offers.received: {
count: 18
},
operation.create: {
count: 5
},
operation.launch_group: {
count: 3
},
operation.reserve: {
count: 20
},
revives: { …
```

[INFINITY-1546] Scheduler Metrics

---

build.gradle
sdk/scheduler/build.gradle
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerRunner.java

It worked:
```
$ curl --header "Authorization: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE1MDg4NTU4MTIsInVpZCI6ImJvb3RzdHJhcHVzZXIifQ.EnsERVeexRm4z7wLOZaUArQkSi4_DZa09cj1LtZpzpSLYgDsTUoSobhnTvhGqgNPXHCbyWZcRT1f4Cm3pbYQxE4JneUnqr3dnOfYeiMkAvU6bySH85HsuobLaOjp-zpeg_0W3ESZUiHs4h4OtupjIrPKlVRZLzxX7bTqiViix4RupdPm3FjJdUU-8kNWIyyDuj0KRlxtcJU4X_aMhFGpLKlUhAPOzIDeJCnskZP3xlZCDP_xgN_a4OAHFbBRhgPwWawg-copsef9iwY--ssBMfsUSDfYPaKfPkY75-8ZPG5cMfaakYbFHpQli9WVN5B86EPJKy38XZXCz9B0y4o3KQ" -s http://localhost:61001/system/v1/metrics/v0/containers/1a94c064-7c62-4cae-8904-fa0f879e29ba/app | jq .
{
"datapoints": [
{
"name": "offers.process.m15_rate",
"value": 0.51,
"unit": "",
"timestamp": "2017-10-20T00:58:15Z"
},
{
"name": "offers.process.p50",
"value": 0.37,
"unit": "",
"timestamp": …
```

[INFINITY-1547] Emit scheduler metrics through statsd

---

conftest.py
frameworks/cassandra/tests/conftest.py
testing/sdk_utils.py

This is a copy/paste backport of the log handling on failure work from `master`. (Cherry picking was catching some unrelated changes.)
`infinity/helloworld` tests are failing consistently with the `0.30.X` branch.

backport log handling on failure from master

---

frameworks/helloworld/tests/test_overlay.py
testing/sdk_cmd.py
testing/sdk_networks.py

The test `test_overlay.test_srv_records()` fails on 1.9. This PR adds some basic logging to make it simpler to debug this failure.

[INFINITY-2552] Add basic logging to get_framework_srv_records

---

frameworks/helloworld/tests/test_overlay.py
testing/sdk_cmd.py
testing/sdk_networks.py

Backport of #1747
* Adds a retry to `get_framework_srv_records`
* Cleans up the handling of json output from CLI commands.

[INFINITY-2552] Add basic logging to get_framework_srv_records (#1747)

---

docs/pages/reference/yaml-reference.md
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/PodSpecsCannotShrink.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultPodSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/PodSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawPod.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/PodSpecsCannotShrinkTest.java

Just updates the spec and config validation to implement the new bit. The actual shrink flow will be implemented separately. The YAML reference has also been updated a bit to reflect current reality following some recent prior changes. Going to leave this unmentioned in the ops guide until it's actually usable (and until the actual decommission behavior is more quantifiable).

INFINITY-2573 Add opt-in bit to pod specs allowing truncation of pods

---

sdk/common/src/main/java/com/mesosphere/sdk/offer/taskdata/LabelConstants.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/taskdata/AuxLabelAccess.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/state/PersistentLaunchRecorder.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/taskdata/AuxLabelAccessTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

The feature introduces more complexity than it's really worth in practice, and can lead to a race wrt unreserving resources when uninstalling the service.
Revert back to the prior behavior where the task always starts "pinned" regardless of initial launch outcome.

(BACKPORT) INFINITY-2564 Remove auto-replace on failed initial launch

---

frameworks/template/src/test/java/com/mesosphere/sdk/template/scheduler/ServiceTest.java
sdk/common/src/main/java/com/mesosphere/sdk/offer/taskdata/LabelConstants.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/taskdata/AuxLabelAccess.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/state/PersistentLaunchRecorder.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/taskdata/AuxLabelAccessTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

The feature introduces more complexity than it's really worth in practice, and can lead to a race wrt unreserving resources when uninstalling the service.
Revert back to the prior behavior where the task always starts "pinned" regardless of initial launch outcome.

INFINITY-2564 Remove auto-replace on failed initial launch

---

frameworks/helloworld/tests/test_sanity.py

We stopped giving root special permissions but we were secretly using them in Hello World.
Strict run: https://teamcity.mesosphere.io/viewLog.html?buildId=837339&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Sdk_Stri_DcOs110Strict

Remove root shim from hello world upgrade.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/ReviveManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Element.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Status.java

When doing scale tests I noticed occasional revives where I expected none.  The fact that we were getting the work candidates, then processing offers then deciding whether we needed to revive was causing a situation where the Steps changed status.  So...
* Move revive calculation right next to candidate selection
There was also the fact that things move in and out of the candidate set, but shouldn't have revives called on them.  Once something moves into the active workset it should only leave upon completion.  So...
* We merge the steps which are in progress (not complete and not pending) into the active work set
N.B. All tasks will be detected as PENDING and in need of revive as part of the getCandidates call.
Scale testing confirms no unexpected revives.  20 schedulers with 80 tasks …

Improve revive calculation

---

frameworks/cassandra/tests/test_backup_and_restore.py

Root is needed for azure CLI, but we don't run the azure test in strict.

[INFINITY-2616] Don't set user=root when running in strict

---

build.gradle
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/MesosResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/MesosResourcePool.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceBuilder.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/ResourceBuilderTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/OfferTestUtils.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/ClusterState.java

1. Stop warning on javadoc style errors
2. Suppress deprecated API use warnings
3. Fix some style complaints about ending with a `.`

[INFINITY-2630] Reduce excessive style warning output

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/AbstractRoundRobinRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/AttributeRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/HostnameRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/MaxPerAttributeRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/MaxPerHostnameRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/MaxPerRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/RoundRobinByAttributeRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/RoundRobinByHostnameRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/StringMatcherRule.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/MaxPerAttributeRuleTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/MaxPerHostnameRuleTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/DefaultCapabilitiesTestSuite.java

All tests are mostly unbothered.  This PR generalizes some patterns so that adding region/zone rules is easier.  Will need to generalize testing in the next PR, but this PR proves that at least no harm was done.

Generalize constraints for region/zone extension

---

cli/commands/plan.go
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/types/PhaseInfo.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/types/PlanInfo.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/CanaryStrategy.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/DependencyStrategy.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/ParallelStrategy.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/RandomStrategy.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/SerialStrategy.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/Strategy.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/api/types/PlanInfoTest.java

An example from hello-world:
```
deploy (serial strategy) (COMPLETE)
├─ hello (serial strategy) (COMPLETE)
│  └─ hello-0:[server] (COMPLETE)
└─ world (serial strategy) (COMPLETE)
├─ world-0:[server] (COMPLETE)
└─ world-1:[server] (COMPLETE)
```
I imagine we'll have some back and forth about how to format this, but I think we're all on the same page that element strategy should be represented textually rather than through some graphical or formatting arrangement.

Return strategy names from plan info endpoint and display in CLI

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/AttributeRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/AttributeRuleFactory.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/HostnameRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/HostnameRuleFactory.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/MarathonConstraintParser.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/PlacementUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/RuleFactory.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/StringMatcherRule.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/AttributeRuleTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/HostnameRuleTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/NotRuleTest.java

This PR reduces substantially the amount of boilerplate needed to write a StringMatcher based Rule.  It also now enforces interface requirements instead of relying on convention.
I'm going to need this to add Zone/Region rules.

Refactor the StringMatcher rules

---

frameworks/kafka/docs/kerberos.md
frameworks/kafka/tests/test_auth.py
tools/kdc.json

As @NimaVaziri pointed out for #1843, the auth tests don't work as expected on Strict mode clusters.
The tests were merged in #1769

[INFINITY-2687] Fix the authn test for Kafka in strict

---

frameworks/hdfs/tests/test_auth.py
frameworks/hdfs/tools/hdfsclient.json
test.sh
tools/kdc.json
tools/kdc.py

The main issue with this not working initially was performing operations in the `kdc` (and `hdfsclient` app) as `root` user, hence it working in permissive. When the same set of steps were performed, it obviously failed because the images (and the files/executables being accessed) weren't given the appropriate permissions/ownership for user `nobody`.
Since this now works in both strict and permissive, it's safe to say these pieces of the auth tooling are relatively stable now, so we should probably move the image to the `mesosphere` docker hub  account.

[INFINITY-2611] Enable tests to work correctly in strict mode clusters

---

test_requirements.txt

I have added some new functionality in to DC/OS CLI ([this](https://github.com/dcos/dcos-cli/commit/d5031e0c20c4ed04f494cdf6aa4e95b1e58ff0d2)) and `dcos-commons` needs to use the latest cli in order to pass [this teamcity CI check](https://teamcity.mesosphere.io/viewLog.html?buildId=862133&buildTypeId=ClosedSource_MesosphereEnterpriseDcOs_IntegrationTests_DcOsCommonsSmokeTest&tab=buildResultsDiv) in [mesosphere/dcos-enterprise/pull/1612](https://github.com/mesosphere/dcos-enterprise/pull/1612)

Update DC/OS CLI Version

---

test_requirements.txt
tools/kdc.json

Reverts mesosphere/dcos-commons#1856
Because of errors like this https://teamcity.mesosphere.io/viewLog.html?buildId=866935&buildTypeId=ClosedSource_MesosphereEnterpriseDcOs_IntegrationTests_DcOsCommonsSmokeTest&tab=buildLog&_focus=2796 
Copy pasting @mellenburg comments  : 
- we define a specify SHA to pull down github.com/dcos/dcos-cli
- dcos/dcos-cli only has a top-level setup.py file for the `dcos` module. The `dcoscli` module is a completely separate module that lives inside the `cli` folder. When pip3 installs the specific SHA of dcoscli, it completely ignores dcoscli because its not in setup.py and therefore effectively doesnt exist to pip
- shakedown is the next dependency on the list. It is only linked to a top-level pypi version of dcos/dcoscli. When pip3 tries to install that, …

Revert "Update DC/OS CLI Version"

---

frameworks/cassandra/tests/test_sanity.py
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache
frameworks/elastic/tests/test_sanity.py
frameworks/elastic/universe/config.json
frameworks/elastic/universe/marathon.json.mustache
frameworks/hdfs/tests/test_sanity.py
frameworks/hdfs/universe/config.json
frameworks/hdfs/universe/marathon.json.mustache
frameworks/helloworld/tests/test_sanity.py
frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache
frameworks/kafka/tests/test_sanity.py
frameworks/kafka/universe/config.json
frameworks/kafka/universe/marathon.json.mustache
frameworks/template/universe/config.json
frameworks/template/universe/marathon.json.mustache
sdk/scheduler/src/main/java/com/mesosphere/sdk/dcos/Capabilities.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerDriverFactory.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/dcos/CapabilitiesTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/SchedulerDriverFactoryTest.java
tools/universe/package_builder.py

This is based off of @elezar 's change, will rebase once that's done and then actually move each `config.json` over to use `V1` as the default value for `service.mesos_api_version`.

Use V1 Mesos HTTP API by default across services

---

frameworks/kafka/docs/kerberos.md
frameworks/kafka/src/main/dist/kafka_server_jaas.conf.mustache
frameworks/kafka/universe/config.json
frameworks/kafka/universe/marathon.json.mustache
testing/sdk_auth.py
tools/kdc.py

This PR enables Kerberos support for ZooKeeper from Kafka and fixes some minor issues with the KDC utility.
See mesosphere/dcos-zookeeper#38
@benclarkwood @NimaVaziri what do you think of where the ZooKeeper setting is currently enabled? I'm not 100% happy with it, and feel that a `kafka.zookeeper.uri` and `kafka.zookeeper.kerberos.enabled` may be better. Thoughts?

[INFINITY-2673] kerberos for zookeeper

---

tools/kdc.json

This env var gets injected into the krb5.conf file that's picked up at runtime.

Add configurable encryption types to KDC

---

frameworks/kafka/src/main/dist/svc.yml
frameworks/kafka/universe/marathon.json.mustache
frameworks/kafka/universe/resource.json

This PR updates ZK to pull down, and then include a custom zookeeper library jar. This library jar is then used by Kafka's ZK client.
That jar is based on this changeset on ZK 3.4.10: https://github.com/benclarkwood/zookeeper/compare/branch-3.4...benclarkwood:release-3.4.10-mesosphere?expand=1
This allows us to run Kerberized ZK without adding principals beyond those for the autoip DNS entries as Kafka will now use the autoip DNS as the principal.

[INFINITY-2737] Pull down and use custom ZK lib

---

frameworks/kafka/src/main/dist/kafka_server_jaas.conf.mustache

This PR adds `useTicketCache=false` to the JAAS config for Kafka. This makes the setting explicit instead of relying on the default.

[INFINITY-2740] Explicitly set useTicketCache to false in Kafka JAAS config

---

test_requirements.txt
testing/sdk_jobs.py

* Bump py
* Bump dcos-launch
* Update job history command for new behavior
--show-failures has been replaced with --failures
which only will return the failure as to both the
failures and successes

Cherrypick: Bump pytest (#1897)

---

frameworks/elastic/src/main/dist/elasticsearch.yml

This makes the Elasticsearch rack awareness configuration only be set when `ZONE` is available.

ELASTIC-153: Make sure zone information is available.

---

frameworks/kafka/tests/test_zookeeper_auth.py

The zookeeper stub for Kafka has expired.
This changes the stub to that being tested in Soak.

Update kafka-zookeeper stub to beta-1

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/MesosResourcePool.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluationUtils.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTestBase.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/PodInstanceRequirementTestUtils.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/OfferTestUtils.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/ResourceTestUtils.java

The section of code handling increasing an existing reservation was always passing ANY_ROLE (aka "\*"), instead of the desired pre-reserved role. This would cause problems in the common "slave_public" case where there are no resources available under "\*". The fix is a one-liner, but testing that fix needed some additional support for pre-reserved roles in the test code.
This only affects increasing reservations after initial deployment. Initial deployment is handled by a separate section of code which was passing the correct role.
In addition, this PR makes some small improvements to offer eval logging to provide better information.

INFINITY-2795 Fix resource increment when using pre-reserved roles

---

frameworks/elastic/src/main/java/com/mesosphere/sdk/elastic/scheduler/Main.java
frameworks/elastic/tests/test_sanity.py
frameworks/elastic/universe/marathon.json.mustache
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java

Everything with TASKCFG_ALL_* gets forwarded to tasks automatically. In this case the BASE64 version is only used by the scheduler itself so avoid passing the BASE64 version to tasks.
Ultimately a nitpick but doesn't hurt to fix.

INFINITY-2796 Fix lint, refrain from passing base64 version of yaml block to tasks

---

frameworks/kafka/tests/auth.py
frameworks/kafka/tests/test_kerberos_auth.py
frameworks/kafka/tests/test_kerberos_authz.py
frameworks/kafka/tests/test_ssl_auth.py
frameworks/kafka/tests/test_zookeeper_auth.py

This PR adds retries to the write and read operations for Kafka tests.
* write is retried if `"Error: UNKNOWN_TOPIC_OR_PARTITION"` is found in STDERR.
* read is retried if `"kafka.consumer.ConsumerTimeoutException"` is in STDERR (i.e. the consumer timesout)

[INFINITY-2805] fix kafka authz tests

---

frameworks/kafka/tests/test_topics.py
frameworks/kafka/tests/topics.py

This PR improves the topic offset check which has failed (for example on https://teamcity.mesosphere.io/viewLog.html?buildId=889665&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Kafka_BuildAndTestPr)

[INFINITY-2805] Make topic offset test more stable

---

frameworks/hdfs/tests/test_auth.py

This should fix the current kafka test failure: https://teamcity.mesosphere.io/viewLog.html?buildId=892018&buildTypeId=DcosIo_DcosCommons_Hdfs_BuildAndTestPr
Edit: HDFS, not kafka.

INFINITY 2583 ensure uniform security settings

---

frameworks/hdfs/tests/test_auth.py
frameworks/kafka/tests/test_kerberos_auth.py
frameworks/kafka/tests/test_kerberos_authz.py
frameworks/kafka/tests/test_ssl_auth.py
frameworks/kafka/tests/test_zookeeper_auth.py

This PR disables tests that use a fixture to setup KDC.
These are currently failing with (for example):
```
conftest.py 74 ERROR Test test_authz_acls_required failed in setup phase, dumping state
```

[INFINITY-2815] disable tests that use the KDC fixture

---

frameworks/hdfs/tests/test_auth.py
frameworks/kafka/tests/auth.py
frameworks/kafka/tests/test_kerberos_auth.py
frameworks/kafka/tests/test_kerberos_authz.py
frameworks/kafka/tests/test_ssl_auth.py
frameworks/kafka/tests/test_zookeeper_auth.py

Reading from topics can result in a not authorized to access group error message.

[INFINITY-2815] Make authorized check robust to group changes.

---

frameworks/kafka/tests/test_kerberos_auth.py
frameworks/kafka/tests/test_kerberos_authz.py
frameworks/kafka/tests/test_zookeeper_auth.py

Reenable the KDC-based Kafka tests disabled in #1940 
The HDFS tests are enabled in #1942.
This includes test fixes from #1936 (which should be ready to merge soon).

[INFINITY-2815] enabled kafka tests

---

frameworks/kafka/tests/auth.py
frameworks/kafka/tests/test_utils.py

This PR uses the scheduler task ID (which is not returned from `sdk_tasks.get_task_ids`) to perform the wait for the broker DNS.
This fixes this function for services where the service name is not `kafka*`.

[KAF-341] Use the correct scheduler task ID

---

frameworks/hdfs/src/main/dist/core-site.xml
frameworks/hdfs/src/main/dist/hdfs-site.xml
frameworks/hdfs/tests/test_auth.py

`SECURITY_`  should be prepended to the `KERBEROS_` envars.
(Should have been included in #1949)

[INFINITY-2583] Fix missed envar renames

---

frameworks/kafka/tests/test_zookeeper_auth.py

This PR removes the kafka-zookeeper stubs that are no longer required since beta-kafka-zookeeper was released to the universe.

Remove stub Zk universe

---

frameworks/cassandra/tests/test_sanity.py
frameworks/elastic/tests/test_sanity.py
frameworks/hdfs/tests/test_sanity.py
frameworks/helloworld/tests/test_sanity.py
frameworks/kafka/tests/test_sanity.py
testing/sdk_install.py
testing/sdk_marathon.py
testing/sdk_metrics.py

Released builds only work on strict clusters with V0 of the Mesos API (their default), while test builds work with V1 (their default).
- Update strict-mode tests to use whatever Mesos API default is declared by the package, rather than overriding with V0 all the time.
- Update Kafka upgrade test to not force V1. This breaks Kafka's strict tests as the released version won't work with V1. Instead we should just use the declared default in each respective version.

INFINITY-2808 Fix strict: Use v0 on releases, v1 on test builds

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultServiceSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

This PR enables the scheduler to parse `ONCE` and `FINISHED` goal states from the config store, enabling it to be downgraded to from a later version making use of those new states.

Create compatibility layer in preparation for new goal states

---

tools/release_builder.py

For example, if `myservice` is being released as `myservice-beta`, the `upgradesFrom`/`upgradesTo` values should default to a preceding `myservice-beta` release.

INFINITY-2851 Update upgradesFrom if the package name is changing

---

frameworks/helloworld/tests/test_goal_states.py

Smoke tests in dcos/dcos are failing due to this test:
https://teamcity.mesosphere.io/viewLog.html?buildId=903328&buildTypeId=ClosedSource_MesosphereEnterpriseDcOs_IntegrationTests_DcOsCommonsSmokeTest&tab=buildLog&_focus=1729
However, in CI on master it does not fail.
Clearly the test is dependent on the CI sanity environment and is not safe to run in a purely smoke environment

Remove smoke marker from test_goal_states.py

---

frameworks/cassandra/universe/marathon.json.mustache
frameworks/elastic/universe/marathon.json.mustache
frameworks/hdfs/universe/marathon.json.mustache
frameworks/helloworld/universe/marathon.json.mustache
frameworks/kafka/universe/marathon.json.mustache
frameworks/template/universe/marathon.json.mustache
sdk/scheduler/src/main/java/com/mesosphere/sdk/api/HealthResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/api/HealthResourceTest.java

Marathon health check looks at `deploy`+`recovery` plans, but in the case of uninstall, there is no `recovery` plan. Therefore after 15 minutes the uninstall scheduler will enter an 'unhealthy' state regardless of how things are going.
Instead of patching this situation by propping up a fake/noop `recovery` plan to keep health checks happy during uninstall, lets just add a dedicated endpoint and point the health checks to that instead. For now it's kept simple and opaque, just returning the response code depending on plan states (`deploy`+`recovery` in normal scheduler, or just `deploy` in uninstall scheduler).

INFINITY-2855 Fix health check when in uninstall mode

---

conftest.py
frameworks/cassandra/tests/config.py
frameworks/elastic/tests/test_sanity.py
frameworks/helloworld/tests/test_taskcfg.py
frameworks/kafka/tests/test_tls.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/reconciliation/DefaultReconciler.java
test.sh
test_requirements.txt
testing/sdk_cmd.py
testing/sdk_install.py
testing/sdk_marathon.py
testing/sdk_plan.py
testing/sdk_tasks.py
testing/sdk_upgrade.py
testing/sdk_utils.py

- Avoid taking forever to fetch plans if scheduler is gone: Set a short timeout, exit early.
- Task log fetching: Fetch all tasks launched since the last failure in the same test suite. Previous logic only fetched tasks which were launched within the same test. Give better information as tasks are fetched/written.
- Task log writing: Include an index prefix in the log directory, so that test ordering is easy to follow when browsing logs.
- Logs: Include "START/END" headers before/after every test, and various other log cleanup.

INFINITY-2871 Several improvements to test flakes and logging behavior

---

frameworks/cassandra/tests/config.py
frameworks/cassandra/tests/test_overlay.py
frameworks/cassandra/tests/test_sanity.py
frameworks/cassandra/tests/test_soak.py
frameworks/cassandra/tests/test_tls.py

- Now that the delete job is idempotent anyway, there isnt any reason for a separate `delete_once` attempt.
- Running jobs with `restart_policy=NEVER` is apparently flaky, often producing this error in the CLI. Not clear if it's the CLI's fault or Metronome's fault:
`Service likely misconfigured. Please check your proxy or Service URL settings. See dcos config --help.`

INFINITY-2877 Replace delete_once job with delete_retry job

---

frameworks/kafka/tests/test_ssl_auth.py

This PR disables the Kafka TLS Authn/z tests at a module level so as to prevent the test fixtures being triggered.
The principals fixture was causing failures on DC/OS Open.

Disable KAFKA ssl tests on open

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java

`helloworld19` tests were extremely unreliable because the paused task in integration tests was failing due to lacking a bootstrap binary. This should make those tests dependably pass, and then part 2 of fixing this will verify that pausing generates no failed tasks in the test itself.

Always, always add the bootstrap URI to paused tasks

---

test.sh

This PR removes support for using envvars for AWS and requires that the `~/.aws/credentials` file exists.
@gabrielhartmann @benclarkwood this does not affect any of the tests themselves, but only running locally.

[INFINITY-2895] Switch to using .aws/credentials instead of environment variables

---

frameworks/cassandra/tests/config.py

Metronome unintentionally made the `forcePullImage` field required

[INFINITY-2876] Fix backup/restore metronome job definition

---

test.sh

Pass along `S3_BUCKET` override env var to `build.sh aws`.

Override S3 bucket used for deploying stub universe during tests

---

test.sh

Don't use interactive mode `-i` with `docker run` when not running `test.sh --interactive`.  When STDIN is not available you will get the error `the input device is not a TTY` in an automation context, such as Jenkins.
`the input device is not a TTY`

Only pass docker run -i when running interactive mode

---

testing/sdk_auth.py
testing/sdk_cmd.py
testing/sdk_marathon.py
testing/sdk_security.py

This PR adds some improvements to the `KerberosEnvironment` class to make the Kerberos tests more stable. The changes are:
* Add retrying and better logging to the installation of the kdc marathon app.
* Use `requests` with retry to download the keytab instead of CURL.
* Reduce the number of member variables set in the constructor.

[INFINITY-2879] address kdc test instability

---

tools/release_builder.py

For example, if `myservice` is being released as `myservice-beta`, the `upgradesFrom`/`upgradesTo` values should default to a preceding `myservice-beta` release.
(reattempt of #1969 which was reverted in #1996 due to a bug)

INFINITY-2851 Update upgradesFrom if the package name changes

---

cli/client/dcoscli.go
cli/commands/plan_test.go
cli/commands/update_test.go
release.sh
sdk/cli/README.md
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/TemplateUtils.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/CosmosRenderer.java
tools/pip/.gitignore
tools/pip/README.md
tools/pip/build.sh
tools/pip/cmd_wrapper/__init__.py
tools/pip/setup.py
tools/release_builder.py
tools/universe/package_builder.py

Adds tooling which builds a `.whl` file for each of `testing/` and `tools/`, and updates the release script to upload these `.whl` files to S3.
The provided `tools/pip/build.sh` includes example steps for both executing tools and for importing testing libs. In theory external repos can just point their builds to these `.whl`s and avoid the need to manually copy `testing/` and `tools/`, but for now this is really just setting up a source of truth for use in future tooling.

INFINITY-[1532,1533] First pass at releasing testing/+tools/ .whl's

---

test.sh

`grep [${aws_profile}]` was matching a bracket regular expression instead of a
string with literal brackets.
Also the expansion of `$( echo "$PROFILES" | grep "\[${aws_profile}\]" )`
needs to be enclosed in double quotes so that the != operator works and
doesn't give us "unary operator expected" errors when the output is empty.

Fix grep matching and subshell output expansion.

---

frameworks/helloworld/tests/test_recovery_partition.py

This fails due to https://jira.mesosphere.com/browse/DCOS-20123.
https://jira.mesosphere.com/browse/INFINITY-2914 filed to re-enable.
https://teamcity.mesosphere.io/viewLog.html?buildId=922130&buildTypeId=DcosIo_DcosCommons_Sdk_Stri_DcOsMasterStrictPartition&tab=testsInfo

Disable tests broken by CLI bug

---

conftest.py

Puts the timestamp at the start of the file so that files are sorted by time.
We only have access to month/day/hour/min, so here's what it'll look like:
`0104_1709.hello-world.0fe39302-f18b-11e7-a6f9-ae11b3b25138.stdout`
(timestamp: `mmdd_HHMM`)

INFINITY-2917 CI: Include timestamp in fetched log filenames

---

docs/pages/operations-guide.md

Minimize references to "framework" and "SDK".

Update ops guide to minimize certain references

---

frameworks/kafka/tests/test_kerberos_auth.py
frameworks/kafka/tests/test_kerberos_authz.py
frameworks/kafka/tests/test_ssl_auth.py
frameworks/kafka/tests/test_zookeeper_auth.py

When attempting to run the integration tests for the Kafka framework I encountered errors with the `create_tls_artifacts` setup method in the `test_ssl_auth.py` test module.  This method uses the running `kafka-client` marathon app based on a docker image `elezar/kafka-client` to sign a certificate.  During this process, a curl command returns an OOM error at the following LoC:
https://github.com/mesosphere/dcos-commons/blob/master/frameworks/kafka/tests/test_ssl_auth.py#L344
After some troubleshooting with @elezar we discovered that when running the `kafka-client` on an agent not running CoreOS, that the `nobody` user is not assignable to an internal user within the `elezar/kafka-client`.  For some reason, this results in the OOM error with curl, although other commands seem to work …

Use default user for kafka-client marathon app def

---

frameworks/helloworld/tests/test_uninstall.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerRunner.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/TaskKiller.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/DeregisterStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/TaskKillStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallPlanBuilder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallRecorder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/TaskKillStepTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/UninstallSchedulerTest.java

The Uninstall Scheduler had some finicky callback ordering for SchedulerDrivers / Plan construction. 
I could not debug why DCOS-19854 failed from logs.  So I've improved logging of the uninstall plan and removed the callbacks to improve reliability.

[DCOS-19854] Improve uninstall

---

tools/publish_aws.py

This was introduced with
https://github.com/mesosphere/dcos-commons/commit/31224ec8dcddc1e5f4f090acfc38f8c6f7e275e5
`dict.get` does not return the default if the value is an empty string so
we need to check for that.

Handle `S3_BUCKET` being an empty string by default now.

---

frameworks/elastic/tests/config.py
frameworks/elastic/tests/test_sanity.py

Consolidate (most) curl calls into `_curl_query`, and have `_curl_query` automatically retry when the command itself fails or if the response fails to parse as JSON. Callers can then have their own retry logic when the data returned isn't as expected (e.g. missing field).

INFINITY-2924 Sanitize retry handling in elastic curl queries

---

conftest.py

This adds a missing import for `subprocess` to `conftest`.
This requirement was added in  #2051
Causing errors: https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=925773&_focus=1830

[INFINITY-2927] Add missing subprocess import to conftest.py

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/MesosResourcePool.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/MesosResourcePoolTest.java

In any given offer it is possible that no resources are available in a
given role.  This includes the * role.  When resources in a given role
are not present an empty Map, not null, should be returned.

[INFINITY-2937] Fix getting unreserved resources when not present

---

frameworks/hdfs/tests/test_auth.py

Until fix is found. Current guess is kdc producing bad keytabs.

HDFS-493 Disable broken HDFS tests

---

Dockerfile

The current approach doesn't set the version to 1.7.  That repo changed underneath us.  It was falling back to 1.9.2 or something from Ubuntu.
There appears to be some problems with using go 1.9 when building bootstrap.

Fix the build environment to go 1.8.5

---

tools/README.md
tools/release_builder.py

While setting up release automation I noticed that `release_builder.py` was inconsistent between using SSH auth and the GH token when interfacing with GitHub.
This PR changes `release_builder.py` to use the already provided token during the `git clone` step of the process.  This resolves several first time/automation issues such as.
* Pre-approving the OpenSSH server fingerprint
* Providing an SSH profile and setting up an SSH agent
A new environment var, `GITHUB_USER` can be provided to specify the GitHub user associated with a token, required when doing basic AUTH with the git CLI.  I took care to make the default user `mesosphere-ci`, which I think will allow this PR to be merged without breaking your infrastructure.

Use user and gh token for git over https when cloning universe

---

frameworks/kafka/tests/auth.py

The strict nightly tests for Kafka are failing due to the curl command not being called with the `--insecure` option or the correct `--cacert`.
This PR adds the `--insecure` option.

[INFINITY-2964]: Use insecure in curl

---

frameworks/elastic/src/main/dist/svc.yml

Currently Elasic fetches unnecessary xpack archive even when it's disabled.

Fetch xpack binary only when xpack enabled

---

conftest.py
frameworks/elastic/tests/config.py
frameworks/elastic/tests/test_sanity.py
testing/sdk_install.py
testing/sdk_repository.py
testing/sdk_upgrade.py

Adding a 4th data node can sometimes fail due to bad resource packing on the cluster. To get around this, only add one data node in `test_sanity`.
Also cleans up some test logging and upgrade handling.

INFINITY-2930 Resolve elastic flake: data node addition

---

frameworks/kafka/docs/kerberos.md
frameworks/kafka/tests/active_directory.py
frameworks/kafka/tests/auth.py
frameworks/kafka/tests/test_active_directory_auth.py
frameworks/kafka/tests/test_active_directory_zookeeper_auth.py
frameworks/kafka/tests/test_kerberos_auth.py
frameworks/kafka/tests/test_ssl_kerberos_auth.py
frameworks/kafka/tests/test_zookeeper_auth.py
testing/sdk_auth.py

This PR adds:
- optional Active Directory tests for Kafka and Zookeeper
- an Active Directory to the Kafka Kerberos docs
- parameterisation of the krb5 environment setup for the creation of the JAAS and Kerberos config files
The tests are controlled by setting the `TESTING_ACTIVE_DIRECTORY_SERVER` to the address of the active directory server where the relevant principals have been created.

[INFINITY-2950] Add a basic Active Directory test for Kafka

---

frameworks/hdfs/docs/kerberos.md
frameworks/hdfs/src/main/dist/krb5.conf
frameworks/hdfs/tests/test_active_directory_auth.py
testing/sdk_auth.py

This PR aligns the HDFS kerberos settings with those of the other frameworks (Kafka and Zookeeper). Most importantly:
- Simplifies the krb5.conf file
- Makes the Kerberos realm configurable
- Adds selective Active Directory tests (see #2093 for the equivalent Kafka tests)

[INFINITY-2953] Add Active Directory support for HDFS

---

frameworks/hdfs/src/main/dist/svc.yml
frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManager.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/AbstractSchedulerTest.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/ClusterState.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/Expect.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/Send.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java

1. A task has failed transiently
1. A service provides custom permanent recovery logic
1. A user initiates a permanent replacement of the transiently failed task
1. BOOM!
Here `BOOM!` means that the recovery plan contains phases for both the transient recovery and permanent recovery of the same pod.  The recovery manager doesn't like that and it's also the wrong outcome.
The user initiated permanent replacement should override the previously detected transient failure.  This PR makes that happen.
Note:
The new ServiceTest failed without the fix.  It contained both permanent and transient recovery phases for `hello-0` as expected.

[INFINITY-2995] Fix transient to custom permanent recovery transition

---

frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/Constants.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/ClusterState.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/Expect.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/LaunchedPod.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/LaunchedTask.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/SendOffer.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java

Needed some changes to the simulation handling:
- Include additional overhead resources for the default executor to use.
- Use the ExecutorInfo from the parent LaunchGroup, rather than one of the TaskInfos.
- Hello world: Account for the added resources when checking the decommission plan

INFINITY-3005: Simulate default executor instead of custom executor

---

frameworks/hdfs/tests/auth.py
frameworks/hdfs/tests/test_active_directory_auth.py
frameworks/hdfs/tests/test_ssl_kerberos_auth.py
frameworks/hdfs/tests/test_tls.py
testing/sdk_auth.py

This PR adds a basic test for HDFS when both TLS and Kerberos are enabled.
The following basic checks are performed:
* The correct certificate is presented to the client for the `name`, `journal`, and `data` nodes (TLS test)
* Kerberos user authnz behaves as expected. 
I will follow up wit a second PR to remove some duplication for handling TLS. (See #2126)

[INFINITY-2842] Add tls krb5 tests for HDFS

---

frameworks/cassandra/docs/limitations.md

Would backup/restore work with [AllowAllAuthenticator](https://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/secureConfigNativeAuth.html) and [AllowAllAuthorizer](https://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/secureConfigInternalAuth.html) (the default auth configuration)?
If yes we should probably mention it too.

Warn that cassandra doesn't currently support backup/restore with auth.

---

frameworks/helloworld/tests/test_zzzrecovery.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceBuilder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ExecutorEvaluationStage.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ExecutorResourceMapper.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluationUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ResourceEvaluationStage.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStage.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/ExecutorEvaluationStageTest.java

1. Stop constructing ExecutorInfo twice
1. Make the ExecutorEvaluationStage care solely about the ExecutorId
1. Make the VolumeEvaluationStage take care of setting correct protobufs always
1. Make the ResourceEvaluationStages take care of setting correct protobufs always
1. Construct volume protobufs correctly (w/ DYNAMIC type)

[INFINITY-3003] Fix multiple different constructions of ExecutorInfo

---

frameworks/kafka/tests/test_zookeeper.py

Sometimes this test gets stuck like this:
```
recovery STARTING:
- zookeeper-0:[metrics, server] STARTING: zookeeper-0:[metrics, server]=STARTING
[2018-01-24 09:20:47,693|sdk_cmd|INFO]: Got 202 for GET /service/kafka-zookeeper/v1/plans/recovery
[2018-01-24 09:20:47,694|sdk_plan|INFO]: Waiting for recovery plan to have IN_PROGRESS status:
recovery STARTING:
- zookeeper-0:[metrics, server] STARTING: zookeeper-0:[metrics, server]=STARTING
[2018-01-24 09:20:48,714|sdk_cmd|INFO]: Got 202 for GET /service/kafka-zookeeper/v1/plans/recovery
[2018-01-24 09:20:48,714|sdk_plan|INFO]: Waiting for recovery plan to have IN_PROGRESS status:
...
```
It's waiting for `IN_PROGRESS`, but `STARTING` should be good enough.  We already have a test method for that.

[INFINITY-3022] Fix ZK test to wait for kicked off recovery, not in progress recovery

---

frameworks/cassandra/tests/test_backup_and_restore.py

Not clear how this could have been passing before, but it's failing now! Remove AZURE_ prefix from some parameters per [documentation](https://mesosphere.github.io/dcos-commons/services/cassandra/disaster-recovery.html) and svc.yml content.

INFINITY-3034 Fix azure backup parameters

---

frameworks/hdfs/src/main/dist/svc.yml

A deployment failure in CI appeared to be because the readiness check expired before the name node could finish starting. More diagnosis would depend on INFINITY-2998 (fetching executor logs)

INFINITY-3025: Increase namenode readiness check timeout

---

frameworks/helloworld/tests/test_taskcfg.py
testing/sdk_tasks.py

Instead of guessing via snapshots of task state, just read the mesos task status history directly

INFINITY-3033 Fix flaky task death check

---

frameworks/kafka/docs/limitations.md
frameworks/kafka/src/main/dist/svc.yml
frameworks/kafka/tests/test_kerberos_auth.py

VIPs will not work with Kerberos. Disable them when Kerberos is enabled.

[KAF-398] Disable vips when kerberos enabled

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/validation/ValidationUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawServiceSpec.java

There are two changes:
1. I used `testEssentialTaskFailure` from the hello-world ServiceTest as a profiler test.  `ValidationUtils.validate` was taking significant time.  Repeated construction of the factory and validator seemed wasteful, and it was.
Before:
```
ValidationUtils.validate(Object) 1691 ms
ValidationUtils.validate(Object) 1657 ms
ValidationUtils.validate(Object) 1569 ms
Average: 1639 ms
```
After:
```
ValidationUtils.validate(Object) ValidationUtils.java 622 ms
ValidationUtils.validate(Object) ValidationUtils.java 435 ms
ValidationUtils.validate(Object) ValidationUtils.java 417 ms
Average: 491 ms
```
2. Construction of the Object mapper is expensive.  No need to do it for every RawServiceSpec.Builder construction.
I also did some tests of Cassandra start up time.  This change …

Avoid unnecessary construction of validator

---

frameworks/kafka/src/main/dist/svc.yml

It is nice to be able to label the custom ZK lib we inject as something different than what is already there. 
By removing the pre-existing one, we make sure we aren't simply relying on luck vis a vis the classpath.

[KAF-399] Remove existing ZK jar before moving in the new one

---

frameworks/kafka/src/main/dist/svc.yml

This is a backport of #2162 to remove existing `zookeeper-*.jar` files in the target library path so as to prevent issues when more than one ZooKeeper library exists in the class path.

[KAF-399][Backport] ensure correct zk library

---

frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/CassandraZoneValidator.java
frameworks/elastic/src/main/java/com/mesosphere/sdk/elastic/scheduler/ElasticZoneValidator.java
frameworks/elastic/src/main/java/com/mesosphere/sdk/elastic/scheduler/Main.java
frameworks/elastic/src/test/java/com/mesosphere/sdk/elastic/scheduler/ServiceTest.java
frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/HDFSZoneValidator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/validation/ZoneValidator.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/validation/ZoneValidatorTest.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/Expect.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java

I was originally just supposed to be adding zone transition validation to Elastic.  While writing a test validating it worked I found out Zone Validation is broken everywhere.
So this PR:
1. Fixes Zone validation
1. Adds it to Elastic
1. Fixes bad original zone validation tests (they shouldn't reference tasks at all)
I'll add more PRs for more extensive testing of Cassandra and HDFS which already had validation turned on.
I have validated manually that C* and Elastic now act as they're supposed to.

Fix zone validation and add validation to Elastic

---

frameworks/helloworld/tests/test_sidecar.py

Unexpected failures such as
```
2018-01-31 03:43:10: E0131 03:43:10.656471 8137 fetcher.cpp:600] EXIT with status 1: Failed to fetch 'https://infinity-artifacts-ci.s3.amazonaws.com/autodelete7d/hello-world/20180131-014315-YPFWH5iTn8Bmw85E/executor.zip': Error downloading resource, received HTTP return code 500
2018-01-31 03:43:10: End fetcher log for container cd517841-d8f2-4f3b-8550-758e295ea620.04393fc7-4d95-4d59-a9a0-83bd5d94f5fd
2018-01-31 03:43:10: E0131 03:43:10.756141 4011 fetcher.cpp:568] Failed to run mesos-fetcher: Failed to fetch all URIs for container 'cd517841-d8f2-4f3b-8550-758e295ea620.04393fc7-4d95-4d59-a9a0-83bd5d94f5fd': exited with status 1
```
aren't expected in the current implementation of this test. _Any_ failure can throw off the test even if the failure is not …

[INFINITY-3065] Make hello-world test more resilient to unexpected failures

---

conftest.py

This PR adds an `INTEGRATION_TEST__SKIP_LOG_COLLECTION` which disables log collection. This can be quite verbose locally.
We would want to backport this too.

Add environment variable to opt out of log collection

---

docs/pages/ops-guide/overview.md

After this is merged and released to the [docs site](https://docs.mesosphere.com/services/ops-guide/overview/), we can add references to it from the individual service docs.

[INFINITY-3063] Document valid zone transitions for rack-aware schedulers

---

frameworks/kafka/tests/test_zookeeper.py

The creation of a service account (even when not used) is causing the `test_zookeeper.*` tests to fail on open. This PR only adds the service account if required (in strict) and deletes the created secret on cleanup.

[INFINITY-3067] Only create a service account when needed

---

frameworks/helloworld/universe/package.json

A quick pre-weekend fix for a hello-world documentation link that was invalid.
There is also a universe PR at mesosphere/universe#1692 to correct the link in the packages that have already been released.

[INFINITY-3076] Fix uninstall documentation link in hello-world postUninstallNotes.

---

frameworks/kafka/universe/marathon.json.mustache

We only need the broker count when SSL Authz is enabled. This wraps the injection such that it will only be injected if:
1. Kerberos is off
2. TE is enabled
3. SSL Auth is enabled
4. Authorization is on

[KAF-405] Conditionally inject broker count

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/http/PodResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/TaskCleaner.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/TaskKiller.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/decommission/DecommissionPlanFactory.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/decommission/TriggerDecommissionStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/TaskKillStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallPlanBuilder.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/http/PodResourceTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/TaskCleanerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/TaskKillerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/decommission/DecommissionPlanFactoryTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanCoordinatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPlanSchedulerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManagerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/TaskKillStepTest.java

There were two problems to address.
1. Constructing / passing around `TaskKiller`s was messy, error prone and inconvenient (because you had to have a `SchedulerDriver` handy).
1. Killing a task in Mesos isn't "reliable".  They may drop the message without consequence at anytime so your'e on your own. 
So now we enqueue tasks to kill and periodically attempt to kill them.  This in conjunction with the `TaskCleaner` will make it very unlikely any tasks fall through the cracks.  Note that there's no anticipated task kill latency introduced here.  We still issue kill messages as fast ever.  Only in very rare obscure scenarios could some component issue a kill before a driver is available to do the killing.  For example maybe the API server comes up fast and someone very urgently wants to …

Make task killing more reliable

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/http/types/PhaseInfo.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/http/types/PlanInfo.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Element.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/ParentElement.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Step.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/CanaryStrategy.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/DependencyStrategyHelper.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/http/types/PlanInfoTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPhaseTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DeploymentStepTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/PlanUtilsTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/RandomRecoveryStrategyTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/strategy/ParallelStrategyTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/strategy/SerialStrategyTest.java

- Fetch plan status after phase/step status. If the steps change in the middle of this, then we end up with e.g. a plan that's still `IN_PROGRESS` when its steps are all `COMPLETE`. This is less ugly for users.
- Move some Element-level functions into internal utilities. Started on this in an earlier version of this fix, may as well keep it around.

INFINITY-2975 Make plan status behave better in a race

---

sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

This fixes a testing bug introduced in #2201 (as a follow-up to #2193) which causes the SDK builds to fail.
I have tested locally with `./gradlew clean build`.
The `TaskKiller` now interacts with the **global** `Driver` and does not maintain its own reference to a `SchedulerDriver`.

Correct setDriver call to use Driver singleton

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/TaskUtils.java

I swear I fixed this once.  Maybe a merge un-fixed it.  Anyway, fixed again.

Do not recover tasks with a goal state of FINISHED

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/http/types/PhaseInfo.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/http/types/PlanInfo.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Element.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/ParentElement.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Step.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/CanaryStrategy.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/DependencyStrategyHelper.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/http/types/PlanInfoTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultPhaseTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DeploymentStepTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/PlanUtilsTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/RandomRecoveryStrategyTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/strategy/ParallelStrategyTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/strategy/SerialStrategyTest.java

(BACKPORT OF: #2174)
- Fetch plan status after phase/step status. If the steps change in the middle of this, then we end up with e.g. a plan that's still IN_PROGRESS when its steps are all COMPLETE. This is less ugly for users.
- Move some Element-level functions into internal utilities. Started on this in an earlier version of this fix, may as well keep it around.

INFINITY-2975 Make plan status behave better in a race (#2174)

---

frameworks/cassandra/tests/test_tls.py
frameworks/cassandra/tests/test_toggle_tls.py

This PR has sequential tests that will install Cassandra with no TLS, turn it on and then off again, while making sure clients can perform CRUD operations in each step. It also includes a test to make sure that data written in Cassandra with default configs is persisted after toggling TLS.
There is some code duplication that we might want to address after we get the rest of the TLS toggling PRs merged.

INFINITY-3039: Add Cassandra TLS toggling tests.

---

cli/commands.go
cli/config/config.go

If `--name` (or the `<modname>.service_name` option) isn't specified, the CLI currently defaults to using the package name. However, this doesn't work for `beta-foo` packages, where the default service name is `foo`.
With this change, the CLI default behavior will align with the service name convention used by beta packages. Users interacting with default installs of beta packages will no longer be required to provide the `--name` argument. If they provide a custom name then they will need to specify the `--name` argument, as they would with a GA package.

INFINITY-3107 Trim 'beta-' prefix for default service name in CLI

---

cli/commands.go
cli/config/config.go

(BACKPORT of #2217)
If `--name` (or the `<modname>.service_name` option) isn't specified, the CLI currently defaults to using the package name. However, this doesn't work for `beta-foo` packages, where the default service name is `foo`.
With this change, the CLI will align with the service name convention used by beta packages. Users interacting with default installs of beta packages will no longer be required to provide the `--name` argument. If they provide a custom name then they will need to specify the `--name` argument, as they would with a GA package.

INFINITY-3107 Trim 'beta-' prefix for default service name in CLI (#2217)

---

README.md

The current developer guide link now results in a 404 not found. I've replaced with the correct link.

Fix 404 for developer-guide link on readme

---

testing/sdk_auth.py
tools/kdc/kdc.py

This PR does the following:
* Adds support for rerunning `kdc.py` without affecting the current `kdc` app
* Adds support for specifying the secret name (default is still `__dcos_base64__keytab`)
* Adds support for binary secrets (`--binary-secret` command line flag)
I also used this to redeploy a keytab for INFINITY-2997.

[INFINITY-2725] fix kdc soak issues

---

frameworks/helloworld/tests/test_soak.py

The pod pause soak tests fail occasionally when waiting for a task to reach `PAUSED` or `RUNNING`, since the offer cycle is longer on account of the cluster's size. This moves to a smarter way of dealing with that.

Use retrying instead of sleep to wait on goal states in larger clusters

---

cli/client/http.go

Use Go's `http.ProxyFromEnvironment` when performing requests to honor these envvars automatically, and align with the main DC/OS CLI's behavior.

INFINITY-3153 Support HTTP[S]_PROXY/NO_PROXY envvars

---

frameworks/helloworld/src/main/dist/examples/pre-reserved-sidecar.yml
frameworks/helloworld/tests/test_pre_reserved_sidecar.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/TaskUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ExecutorResourceMapper.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluationUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ResourceLabels.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TaskResourceMapper.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStage.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStageTest.java

You need to do 3 things to encounter the bug fixed here.
1. Have a volume at the pod level
1. Have a sidecar task on that pod
1. Consume pre-reserved resources for that pod
`edge-lb` does all three of those things and so can't use `0.40.X` versions of the SDK.  This should fix that.  I'll confirm with them before release of `0.40.2`.
This change can be a little bit hard to follow.  There were a couple things that needed to happen.
1. Use the `ResourceBuilder` class to build executor volumes so you get the reservation refinement stuff.
1. Pass around the `sourceRoot` field so we can build `MOUNT` volumes for Executor reuse.
We have moved to a consistent construction pattern for protobufs.  That is we don't pull them out of the StateStore and reuse them _ever_.  This had problems for mount …

Fix sidecar refinement / MOUNT volume reuse

---

frameworks/cassandra/universe/marathon.json.mustache

This PR re-adds the `LIBMESOS_URI` environment variable that was removed as part of #2233  
d441869ce51bbf4d9211f39ce9c8a9be899a86c0

INFINITY-3167: Add LIBMESOS_URI envvar removed by accident 

---

frameworks/template/src/test/java/com/mesosphere/sdk/template/scheduler/ServiceTest.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/DefaultConfigValidators.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/PlacementRuleIsValid.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/AndRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/InvalidPlacementRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/MarathonConstraintParser.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/OrRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/PlacementRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultServiceSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/PlacementRuleIsValidTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/AndRuleTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/InvalidPlacementRuleTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/MarathonConstraintParserTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/TestPlacementUtils.java

This PR adds better validation support for placement constraints. Invalid constraints are wrapped in a placement rule and a validator is added to check for this.
This means that:
* If the initial deployment has an invalid placement constraint, the scheduler does not crash and one can successfully uninstall it.
* If a config update introduces an invalid constraint, deployment plan has an error as with any other invalid config change.
One question:
* I have only added an overloaded `isValid()` method to the `AndRule` and `InvalidPlacementRule`, but it would make sense to add this to all rules.
Example output of a failed update:
```
deploy (serial strategy) (ERROR)
├─ hello (serial strategy) (COMPLETE)
│  └─ hello-0:[server] (COMPLETE)
└─ world (serial strategy) (COMPLETE)
├─ …
```

[INFINITY-3111] Gracefully handle invalid placement constraints

---

testing/sdk_auth.py
tools/kdc/kdc.py

This is the backport to sdk-0.40 for #2212 
- Support operations on Soak:
- Reuse the KDC app if it is installed
- Support for setting the secret name
- Support binary secrets
- base64-encoding is only done if name requires it
Properly handle secret name and binary secrets
Use a unique keytab name on the KDC to allow for better logging

[INFINITY-2725] fix kdc soak issues (#2212)

---

frameworks/template/src/test/java/com/mesosphere/sdk/template/scheduler/ServiceTest.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/DefaultConfigValidators.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/PlacementRuleIsValid.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/AndRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/InvalidPlacementRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/MarathonConstraintParser.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/OrRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/PlacementRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultServiceSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/PlacementRuleIsValidTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/InvalidPlacementRuleTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/MarathonConstraintParserTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/TestPlacementUtils.java

Backporting for @elezar:
This PR adds better validation support for placement constraints. Invalid constraints are wrapped in a placement rule and a validator is added to check for this.
This means that:
* If the initial deployment has an invalid placement constraint, the scheduler does not crash and one can successfully uninstall it.
* If a config update introduces an invalid constraint, deployment plan has an error as with any other invalid config change.
Example output of a failed update:
```
deploy (serial strategy) (ERROR)
├─ hello (serial strategy) (COMPLETE)
│  └─ hello-0:[server] (COMPLETE)
└─ world (serial strategy) (COMPLETE)
├─ world-0:[server] (COMPLETE)
└─ world-1:[server] (COMPLETE)
Errors:
- Field: 'PlacementRule'; Value: 'AndRule{rules=[IsLocalRegionRule, …
```

[INFINITY-3111] Gracefully handle invalid placement constraints (#2221)

---

frameworks/helloworld/src/main/dist/examples/pre-reserved-sidecar.yml
frameworks/helloworld/tests/test_pre_reserved_sidecar.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ExecutorResourceMapper.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluationUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ResourceLabels.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TaskResourceMapper.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStage.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStageTest.java

* Add hello-world example for sidecars on pre-reserved resources
* Fix executor construction for shared volumes on refined reservations
* Add pre-reserved sidecar integration test
* Fix MOUNT volume reuse

[INFINITY-3172] Fix sidecar refinement / MOUNT volume reuse (#2207)

---

docs/pages/_includes/services/uninstall.md

Describes using `force-complete` to get unstuck, with `janitor.py` as an escape hatch if there are still issues.

INFINITY-2949 Add instructions for debugging uninstall

---

docs/pages/_includes/services/uninstall.md

BACKPORT of #2257 
Describes using force-complete to get unstuck, with janitor.py as an escape hatch if there are still issues.

INFINITY-2949 Add instructions for debugging uninstall (#2257)

---

tools/airgap_linter.py

This adds `${FRAMEWORK_HOST}` and `${MESOS_CONTAINER_IP}` alongside `$FRAMEWORK_HOST` and `$MESOS_CONTAINER_IP` as accepted envvars in the airgap linter.
Note: I'm not going to backport this as no downstreams require this change.

[INFINITY-3174] Add alternate form of accepted envvars in airgap_linter.

---

frameworks/kafka/tests/test_toggle_security.py

* The security toggle tests added should be skipped on 1.9.
* A TLS test should not use the `broker` endpoint.

[INFINITY-3195] Fix security toggle tests

---

frameworks/hdfs/src/main/dist/svc.yml
frameworks/hdfs/universe/config.json
frameworks/hdfs/universe/marathon.json.mustache

The update strategy for HDFS is currently configurable to `serial, parallel` but a parallel update actually doesn't make sense for any component of HDFS.
Journal Nodes need to be updated serially as a parallel update would crash the name nodes, and thus the service.
Name nodes can't be updated in parallel because the service becomes unavailable to new clients.
Data nodes can't be updated in parallel because data access will be down for the duration of the update.

[INFINITY-3115] Remove update strategy

---

frameworks/hdfs/universe/config.json

The docs reflecting this change are in #2216

[INFINITY-3214] Nullify default value for HDFS authz mapping

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/SerialStrategy.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/strategy/SerialStrategyTest.java

Each element in a serial strategy should have a dependency on ALL previous elements, not just the immediately previous element.
In particular this fixes the `decommission` plan which executes elements out of order when executing a `serial` strategy.

[INFINITY-3269] Fix serial strategy

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/TaskKiller.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/http/PodResourceTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/TaskKillerTest.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java

Support disabling the background executor in tests, so that it doesn't kill tasks when we don't expect it.

INFINITY-3211 Fix flakes in TaskKiller unit tests

---

frameworks/kafka/setup-helper/setup_helper.go
frameworks/kafka/setup-helper/setup_helper_test.go
frameworks/kafka/universe/config.json

Only advertise IPs when security is not enabled.
This is consistent with the current behavior in 2.0.X.

[INFINITY-3280] Regression in advertised listeners behavior

---

frameworks/kafka/setup-helper/setup_helper.go
frameworks/kafka/setup-helper/setup_helper_test.go
frameworks/kafka/universe/config.json

* Only advertise IPs when security is not enabled.
This is consistent with the current behavior in 2.0.X
* Review feedback on boolean logic
* Use the correct [DEPRECATED] tag in the config.json description
Backport of #2313

[INFINITY-3280] Regression in advertised listeners behavior (#2313)

---

frameworks/helloworld/tests/test_zzzrecovery.py

This PR re-enables a test that was skipped due to a pending external ticket.
I re-ran the nightlies with this test enabled: https://teamcity.mesosphere.io/viewLog.html?buildId=983064&buildTypeId=DcosIo_DcosCommons_Sdk_Perm_DcOsMasterPermissivePartition&tab=testsInfo

[INFINITY-3047] Remove skipped test due to blocked ticket

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/TaskKiller.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/http/PodResourceTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/TaskKillerTest.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java

BACKPORT of #2317
Support disabling the background executor in tests, so that it doesn't kill tasks when we don't expect it.

INFINITY-3211 Fix flakes in TaskKiller unit tests (#2317)

---

frameworks/hdfs/tests/config.py
frameworks/hdfs/tests/test_active_directory_auth.py
frameworks/hdfs/tests/test_overlay.py
frameworks/hdfs/tools/hdfsclient.json

The PR switches to `elezar/hdfs-client:dev` (originally based off `nvaziri/hdfs-client:dev`) but without the regression pushed yesterday.

[INFINITY-3285] Fix HDFS tests using client docker container

---

sdk/common/src/main/java/com/mesosphere/sdk/offer/CommonIdUtils.java
sdk/common/src/test/java/com/mesosphere/sdk/offer/CommonIdUtilsTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java

Update current code to support a format that may be used in the future:
- Current format: `<name>__<uuid>`
- Potential future format: `<otherthings>__<name>__<uuid>`

INFINITY-3240 Support taskids with multiple entries

---

tools/release_builder.py

In release_builder.py, the variable `stripped_version` is not initialized if `is_beta` is false. (Compare with the method above it, apply_beta_prefix())

[TOOLS] Fixed uninitialized variable in release_builder.py::apply_beta_version

---

sdk/common/src/main/java/com/mesosphere/sdk/offer/CommonIdUtils.java
sdk/common/src/test/java/com/mesosphere/sdk/offer/CommonIdUtilsTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java

BACKPORT of #2331 
Update current code to support a format that may be used in the future:
- Current format: `<name>__<uuid>`
- Potential future format: `<otherthings>__<name>__<uuid>`

INFINITY-3240 Support taskids with multiple entries (#2331)

---

frameworks/kafka/src/main/dist/server.properties.mustache
frameworks/kafka/universe/config.json
frameworks/kafka/universe/marathon.json.mustache

* Add all the missing properties to the plumbing
* Use templating to only include values when they're enabled
* Add a bunch of minimums
Fix a mistake in a number type parameter
Remove Apache Kafka's confusing Deprecation notice
* Fix bad JSON after adding new parameters / moving some parameters
* I've been convinced to set topic delete back to false by the fact we have a test that makes sure it is false.
Backport of #2323

[KAF-409] Add all the missing properties to the plumbing (#2323)

---

docs/pages/_data/services/cassandra.yml
docs/pages/_data/services/elastic.yml
docs/pages/_data/services/hdfs.yml
docs/pages/_data/services/kafka.yml
docs/pages/_includes/services/security-configure-transport-encryption.md
docs/pages/_includes/services/security-kerberos-ad.md
docs/pages/_includes/services/security-service-keytab.md
docs/pages/_includes/services/security-transport-encryption-lead-in.md
frameworks/cassandra/docs/security.md
frameworks/elastic/docs/security.md
frameworks/hdfs/docs/security.md
frameworks/kafka/docs/security.md

* Update templates and security.md's to the right format for docs-site-repo
* Tweak the allow plaintext include in the config
* Take out unsupported mustache conditional

Backport refactor of security templates

---

frameworks/kafka/build.sh
frameworks/kafka/src/test/java/com/mesosphere/sdk/kafka/scheduler/ServiceTest.java
frameworks/kafka/universe/marathon.json.mustache
frameworks/kafka/universe/resource.json
frameworks/kafka/versions.sh

This should make upgrading the base tech easier and avoid weird version template value mismatch errors like https://jira.mesosphere.com/browse/DCOS_KAFKA-27

Derive Kafka version from a single source.

---

frameworks/hdfs/src/main/dist/svc.yml

The journal nodes start processing edits once a segment is opened, which is when the name node flushes its cached edits to the journal nodes. Using a `rollEdits` call when the journal node comes up initiates a new edits segment and the presence of in-progress segment acts a proxy for the journal node readiness check.
This allows us to simplify the readiness check and side step having to go through SPNEGO (as `/jmx` is an HTTP endpoint).
Since we're removing the JMX field look ups, this also removes the false-positive error currently incurred through a readiness check of a Kerberized HDFS instance.

[INFINITY-3133] Update HDFS readiness check to remove JMX dependency

---

frameworks/cassandra/tests/test_tls.py
frameworks/cassandra/tests/test_toggle_tls.py
frameworks/elastic/tests/test_tls.py
frameworks/hdfs/tests/test_kerberos_auth.py
frameworks/hdfs/tests/test_ssl_kerberos_auth.py
frameworks/hdfs/tests/test_tls.py
frameworks/kafka/tests/test_ssl_auth.py
frameworks/kafka/tests/test_ssl_kerberos_auth.py
frameworks/kafka/tests/test_tls.py
frameworks/kafka/tests/test_toggle_security.py
testing/sdk_security.py
testing/security/transport_encryption.py

This PR restructures how service accounts are created in the setup process, and adds fine-grained settings for DC/OS 1.11.
For clarity the effective changes are as follows:
* Use the same service account fixture for *all* TLS tests requiring a service account.
* On 1.11 clusters use fine-grained permissions instead of `superuser` for this service account.
* Use return a dict from the fixture instead of a string so as to allow for latter setting different secrets and service account names.
What has not changes:
* The logic in calling `create_service_account` and `delete_service_account`
* The names of the service account and secrets created (with the exception of one Kafka test where service account name and service account secret are now the same for uniformity).
* The setup of service …

[INFINITY-3080] Use fine-grained permissions for DC/OS 1.11.

---

testing/sdk_repository.py

The build script for the Elastic service builds 2 packages: Elastic and Kibana. A stub Universe is created for each, and for PR builds their URLs are appended to a file (`$UNIVERSE_URL_PATH`), one URL per line.
https://github.com/mesosphere/dcos-commons/blob/3814626ec94197386a0fe2ced623b988e5d4507b/tools/publish_aws.py#L93-L98
https://github.com/mesosphere/dcos-commons/blob/3814626ec94197386a0fe2ced623b988e5d4507b/frameworks/elastic/build.sh#L35
The TC test runner script (TEST_SCRIPT in the TC build parameters) runs `export STUB_UNIVERSE_URL=$(cat $UNIVERSE_URL_PATH)`, making `$STUB_UNIVERSE_URL` a newline-separated string.
During PR build test runs the code that adds the stub Universe repos splits that string by comma (instead of by newline), ending up sending a 2 line command to …

[INFINITY-3321] Kibana CI install failure

---

frameworks/helloworld/tests/test_multistep_plan.py
frameworks/helloworld/tests/test_resource_refinement.py

* Fix cleaning up other framework's volumes
* Remove errant "ben" pytest mark
* Add an integration test that verifies we do not clean up Marathon volumes
* Review comments
* Fix errant rebase artifacts
Backport of #2365

[INFINITY-3331][Backport] Add integration test (#2365)

---

frameworks/cassandra/tests/test_tls.py
frameworks/cassandra/tests/test_toggle_tls.py
frameworks/elastic/tests/test_tls.py
frameworks/hdfs/tests/test_kerberos_auth.py
frameworks/hdfs/tests/test_ssl_kerberos_auth.py
frameworks/hdfs/tests/test_tls.py
frameworks/kafka/tests/test_ssl_auth.py
frameworks/kafka/tests/test_ssl_kerberos_auth.py
frameworks/kafka/tests/test_tls.py
frameworks/kafka/tests/test_toggle_security.py
testing/sdk_security.py
testing/security/transport_encryption.py

This is a straight backport of #2310.
* Use fine-grained permissions for DC/OS 1.11.
* Add missing service_account element access.
* Correct typo in install
* Raise exception when service account is created in strict.
* Formatting changes to sdk_security.
* Improve docstring
* Set up propper permissions for strict mode TLS.
* Add missing service_name paratmer.

[INFINITY-3080] Use fine-grained permissions for DC/OS 1.11. (#2310)

---

tools/publish_aws.py
tools/universe/package_builder.py
tools/universe/package_manager.py

This is a backport of #2360.
* Fix dryrun for package version and md5 hash
* Use snapshot verison

[INFINITY-3329] Fix dryrun for package version and md5 hash (#2360)

---

frameworks/hdfs/src/main/dist/svc.yml
frameworks/hdfs/tests/test_kerberos_auth.py

Missed this the first time around - the kerberos tests don't do a restart/replace of the journal nodes so the readiness check doesn't actually succeed after the first time it passes.

[INFINITY-3133] Added missing Kerberos auth for readiness check

---

test_requirements.txt

if not, python-analytics or another library will
install 2.7.0 and botocore will block usage

Install botocore first

---

frameworks/kafka/tests/config.py
frameworks/kafka/tests/test_active_directory_zookeeper_auth.py
frameworks/kafka/tests/test_zookeeper.py
frameworks/kafka/tests/test_zookeeper_auth.py

This PR removes the use of a ZooKeeper stub from the kafka integration tests as this version of ZK has been published to the universe.
It also does some minor cleanup of the ZooKeeper-related tests in Kafka.

[INFINITY-3328] Remove stub from ZooKeeper tests

---

test_requirements.txt

This is a backport of #2380 which aligns the sdk-0.40 docker file with that in master.

Install botocore first to fix CI issue with dcos-launch (#2380)

---

frameworks/elastic/tests/config.py
testing/sdk_cmd.py

This reverts commit 546feeef26bad42ecb3f32f6ad05ccad96801206.
The change had side-effects that caused the kafka tests on 1.9 to fail because environment variables in the command line are different for bash commands (the `;` is required) or for executables like `./bootstrap` (either `export` or no `;` is required).

Revert "[ELASTIC-177] Fix Kibana test failure on 1.9. (#2381)"

---

frameworks/hdfs/tests/test_kerberos_auth.py

The test added in #2367 should also be skipped on 1.9.

[INFINITY-3366] Skip all HDFS Kerberos tests on DC/OS 1.9

---

frameworks/elastic/tests/config.py

ELASTIC-177 made all `sdk_cmd.task_exec` commands be run with `bash -c '<command>'` so that every command had access to environment variables being injected manually, i.e. `bash -c 'FOO=1; <command>'`. Previously only `./bootstrap` commands would use the `bash -c` invocation since bootstrap needs `LIBPROCESS_IP` set.
This broke a few of those commands that previously didn't run under `bash -c '<command>'`, in two different ways: 1. curl requests with JSON bodies (the Elastic CI failure) due to double quotes present in the JSON body and 2. processes needing access to environment variables (the Kafka CI failure) due to the splitting of setting variables and running commands (the `;`, which was introduced so that things like `bash -c 'A=1 B=$A; echo $B'` would work).
Example of #1:
Doesn't …

[ELASTIC-179] Fix Kibana command on 1.9 with localized change.

---

frameworks/helloworld/src/main/java/com/mesosphere/sdk/helloworld/scheduler/Main.java
frameworks/helloworld/tests/test_region_awareness.py
frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/DefaultConfigValidators.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/RegionCannotChange.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultServiceSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/ServiceSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/validation/RegionValidator.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/RegionCannotChangeTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/SchedulerBuilderTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/validation/ZoneValidatorTest.java

Adding tests for this functionality now, but I wanted to make sure we were all on the same page about how it works. The downside I can see is that, if you have placed your scheduler in a single region explicitly and then change that region in your config, `RegionValidator` won't catch that and so you'll only find out once offers start getting rejected. This is a hazard of `ZoneValidator` too, though, and since computing equality over things like a regex-based placement rule isn't feasible I think that's a limitation we'll have to accept.

Add region config change validator and builder method for ensuring single-region constraint

---

frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/Main.java
frameworks/cassandra/src/test/java/com/mesosphere/sdk/cassandra/scheduler/ServiceTest.java
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache
tools/airgap_linter.py

This change is based off the SDK region awareness change which I made a small change to and am waiting for tests to pass again. Once that's merged, I'll rebase. The relevant changes here are only in the Cassandra framework.

Enable region support in Cassandra

---

frameworks/helloworld/tests/test_zzzrecovery.py

This PR disables the tests affected by shakedown / paramiko on 1.9 while we get them fixed.

[INFINITY-3203] Skip agent-based recovery tests on 1.9

---

frameworks/kafka/tests/test_zookeeper.py

@benclarkwood this is another take at #2395. It explicitly checks for success in the new kafka logs.
I will run this against the Teamcity jobs a couple of times to check before merging.
This also supersedes #2404.

[INFINITY-3363] Fix Kafka ZooKeeper reresolution test

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/RegionCannotChange.java

This fixes error reporting when a region config update fails to validate. Unfortunately, localizing creation of `IsLocalRegionRule` to `RegionRuleFactory` is not compatible with the current interface to `RuleFactory`, and so I'll defer that to a later cleanup.

Clean up logic in region matching and report region mismatch correctly

---

frameworks/helloworld/tests/test_zzzrecovery.py

This is a clean backport of #2401

[INFINITY-3203] Skip agent-based recovery tests on 1.9 (#2401)

---

frameworks/helloworld/tests/test_region_awareness.py

This change successfully passes against a multi-region cluster. The check for pod replace has been removed, since the scheduler permits no further pod actions after an erroneous config has been specified (meaning that recovery will never be initiated since the pod will not be killed by a replace), instead maintaining the last valid target configuration until the current configuration is fixed. This is the desired behavior.

Clear pod replace check in multi-region tests

---

frameworks/helloworld/tests/test_custom_service_tld.py
frameworks/kafka/tests/auth.py
frameworks/kafka/tests/test_ssl_kerberos_custom_domain_auth.py
frameworks/kafka/universe/config.json
frameworks/kafka/universe/marathon.json.mustache
testing/sdk_hosts.py

This PR:
1. Extracts the behavior to get the cluster crypto domain into sdk_hosts
2. Updates the relevant HWorld test
3. Adds plumbing to allow the user to set service.security.custom_host in Kafka
4. Adds a test that this works for TLS and Kerberos

[INFINITY-3363] Add custom domain and testing for Kafka security

---

frameworks/kafka/tests/test_zookeeper.py

This PR skips the ZooKeeper reresolution test that has been causing problems. It will be properly addressed as part of INFINITY-3363.

[INFINITY-3363] Skip ZooKeeper reresolution test

---

frameworks/kafka/src/main/dist/server.properties.mustache
frameworks/kafka/tests/client.py
frameworks/kafka/tests/test_active_directory_auth.py
frameworks/kafka/tests/test_active_directory_zookeeper_auth.py
frameworks/kafka/tests/test_availability.py
frameworks/kafka/tests/test_kerberos_auth.py
frameworks/kafka/tests/test_kerberos_authz.py
frameworks/kafka/tests/test_kerberos_authz_no_acls_required.py
frameworks/kafka/tests/test_rack_awareness.py
frameworks/kafka/tests/test_sanity.py
frameworks/kafka/tests/test_ssl_auth.py
frameworks/kafka/tests/test_ssl_kerberos_auth.py
frameworks/kafka/tests/test_ssl_kerberos_authz.py
frameworks/kafka/tests/test_ssl_kerberos_custom_domain_auth.py
frameworks/kafka/tests/test_toggle_security.py
frameworks/kafka/tests/test_topics.py
frameworks/kafka/tests/test_utils.py
frameworks/kafka/tests/test_zookeeper_auth.py
frameworks/kafka/tests/test_zookeeper_authz.py
frameworks/kafka/tests/topics.py

This PR extends the AuthZ tests for Kafka and includes:
* Adds the same authz tests that exist for SSL auth to Kerberos auth.
* Adds the same authz tests that exist for SSL auth to Kerberos auth with a custom Kerberized ZooKeeper
* Add the same authz tests that exist for SSL auth to SSL-Kerberos auth
It also: 
* applies some minor flake8 corrections to the kafka tests.
* Correctly replaces the `wait_for_brokers` function with `sdk_cmd.resolve_hosts` (see #2412)

[INFINITY-2971] improve kafka authz test coverage

---

frameworks/kafka/src/main/dist/server.properties.mustache
frameworks/kafka/tests/client.py
frameworks/kafka/tests/test_active_directory_auth.py
frameworks/kafka/tests/test_active_directory_zookeeper_auth.py
frameworks/kafka/tests/test_availability.py
frameworks/kafka/tests/test_kerberos_auth.py
frameworks/kafka/tests/test_kerberos_authz_no_acls_required.py
frameworks/kafka/tests/test_rack_awareness.py
frameworks/kafka/tests/test_sanity.py
frameworks/kafka/tests/test_ssl_kerberos_auth.py
frameworks/kafka/tests/test_ssl_kerberos_authz.py
frameworks/kafka/tests/test_ssl_kerberos_custom_domain_auth.py
frameworks/kafka/tests/test_toggle_security.py
frameworks/kafka/tests/test_topics.py
frameworks/kafka/tests/test_utils.py
frameworks/kafka/tests/test_zookeeper_auth.py
frameworks/kafka/tests/test_zookeeper_authz.py
frameworks/kafka/tests/topics.py
testing/sdk_cmd.py

Backport of #2419 
* RELEASE_NOTES: INFINITY-3425: Fix a bug where Kafka authz was using SSL principals instead of Kerberos principals as documented when both transport encryption and Kerberos were enabled.
* Address flake8 issues.
* Refactor acls script to use get_bash_command.
* Add a KafkaClient class for testing and use this in an authz test.
* Use KafkaClient for existing authz test.
* Add connect method that resets client state.
* Use the client for the ssl authz tests.
* Switch ZK auth tests to KafkaClient.
* Call kerberos.get_realm() instead of accessing sdk_auth.REALM directly.
* Use KafkaClient in test_kerberos_auth.
* Add function to remove acls and apply `--force` to skip prompt
* Add Kafka authz test using Zookeeper.
* Minor code formatting
* Use KafkaClient in ssl-kerberos …

[INFINITY-2971][INFINITY-3425] improve kafka authz test coverage (#2419)

---

frameworks/kafka/tests/test_toggle_security.py

This PR skips the Kafka security toggle tests for the time being until https://jira.mesosphere.com/browse/INFINITY-3367 can be properly addressed.

[INFINITY-3367] Skip kafka security toggle test

---

tools/universe/package_builder.py

Addresses [INFINITY-3455](https://jira.mesosphere.com/browse/INFINITY-3455). 
`libmesos-bundle-1.9.0-rc2-1.2.0-rc2-1.tar.gz` is being used `queries/testdata` of cli as well. Comment if I am incorrect in assuming `testdata` need not be updated.

Bump libmesos bundle version

---

Dockerfile
tools/distribution/UPDATING.md
tools/distribution/init

This PR adds some short documentation on updating non-mono-repo frameworks.
This was prompted by mesosphere/dcos-zookeeper#90 and will ensure that this is present in all future updated repositories.

Add updating md

---

frameworks/cassandra/universe/package.json
frameworks/elastic/universe/package.json
frameworks/hdfs/universe/package.json
frameworks/helloworld/universe/package.json
frameworks/kafka/universe/package.json
frameworks/template/universe/package.json

small change to test CI, part of changes to remove custom executor and move to default executor in dcos versions greater than 1.9

Updating min dcos release version from 1.9 to 1.10

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/TokenBucket.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/framework/TokenBucketTest.java

Invoke `increment()` manually to avoid dependence on the executor thread behaving consistently. In CPU-starved CI machines, it apparently doesn't!

INFINITY-3439 Fix timing flake in TokenBucketTest.replenishTokens

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/dcos/DcosVersion.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/DomainCapabilityValidatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/dcos/CapabilitiesTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/dcos/DcosVersionTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

Addresses [INFINITY-3420](https://jira.mesosphere.com/browse/INFINITY-3420). Detailed discussion of DC/OS feature at [DCOS_OSS-2283](https://jira.mesosphere.com/browse/DCOS_OSS-2283). 
This can be used after https://github.com/dcos/dcos/pull/2663 is merged.

Add variant info to DcosVersion object

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/DefaultConfigValidators.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/ServiceNameCannotBreakDNS.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/ServiceNameCannotBreakDNSTest.java

did:
ERROR new deployments on a too long DNS name
Do nothing to old deployments (but do warn)
I can't decide if we can actually do this or not. It's probably possible for a user to wind up in a situation where they can't re-install their service with a too long name.
Maybe we don't even work at all with too long names? I'll find out...

[INFINITY-3446] Reject Service Names that violate DNS length requirements.

---

frameworks/elastic/build-kibana.sh
frameworks/elastic/build.sh
tools/build_package.sh
tools/publish_aws.py
tools/publish_dcos_file.py
tools/publish_http.py

Now, `build.sh` can take a `version` parameter to populate the package version. Something like : 
`.../build.sh .dcos 1.2.3`. This however forces `elastic` to have same version for `elastic` and `kibana` (which is acceptable for now).

Parameterize version of package from build.sh scripts

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/EnvStore.java

Useful for parsing CPU requirements from env store, consistent with strings, ints, longs

Add get{Optional,Required}Double methods to EnvStore

---

frameworks/kafka/tests/test_zookeeper_auth.py
frameworks/kafka/tests/test_zookeeper_authz.py

The CI tests are failing in open due to authnz tests being included for Kafka/ZooKeeper.
https://teamcity.mesosphere.io/project.html?projectId=DcosIo_DcosCommons_Kafka_Open&tab=projectOverview
This disables them.

Skip ZooKeeper authnz tests in Open

---

frameworks/kafka/tests/test_zookeeper_auth.py
frameworks/kafka/tests/test_zookeeper_authz.py

Straight backport of #2494 to disable the ZooKeeper Authnz tests.
The next update for Confluent-Kafka should then fix the open tests there.

Skip ZooKeeper authnz tests in Open (#2494)

---

Dockerfile

Can't use our packaging-defined URL since that's a JRE rather than a JDK. Therefore it uses a common PPA to get the JDK.

Switch to Oracle JDK8, bump go to latest(1.10.2)

---

tools/airgap_linter.py

When using the `SCHEDULER_API_HOSTNAME` var instead of `FRAMEWORK_HOST` the airgap_linter complains.

tools: add SCHEDULER_API_HOSTNAME as an exception

---

frameworks/template/tests/config.py
frameworks/template/tests/conftest.py
testing/sdk_security.py

It'd be good to make more configurable the sdk_security package. In our case, we need to add additional permissions to the default ones, but we'd like to define the service account or even the linux user.
related to: https://jira.mesosphere.com/browse/DCOS-29232

[DCOS-29232] sdk_security: more the package functions more configurable

---

frameworks/helloworld/tests/test_sanity.py

Mark the test_plan_cli test for inclusion in DC/OS smoke tests: Catch when the mesos master crashes

DCOS-37814/MESOS-8945 Add repro of Mesos master crash to smoke tests

---

frameworks/kafka/tests/test_sanity.py
frameworks/kafka/tests/test_zookeeper.py
frameworks/kafka/tests/test_zookeeper_auth.py
frameworks/kafka/tests/test_zookeeper_authz.py
frameworks/template/tests/config.py
frameworks/template/tests/conftest.py
testing/sdk_auth.py
testing/sdk_cmd.py
testing/sdk_security.py
testing/security/transport_encryption.py

In order to address DCOS-37718, I had to make some sdk_security changes, and I am upstreaming these here.
This also builds on @hectorj2f's change in #2498.
Some changes:
* The security setup now supports arbitrary *foldered* service names
* Security info is now stored for cleanup in the teardown fixtures

[DCOS-37718] fix sdk security

---

frameworks/helloworld/tests/test_tls.py
testing/sdk_cmd.py
testing/sdk_security.py
tools/universe/package_manager.py

- Use new endpoint to just download info for the targeted package, instead of all packages
- Just use urllib instead of `requests` -> `curl` fallback

DCOS-37981 Just retrieve individual packages, instead of whole repo

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawServiceSpec.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java
tools/universe/package_manager.py

While reviewing mesosphere/prometheus#12 I noted that there were issues due to undefined envvars in `svc.yml` were not triggering any errors in the unit tests.
This PR adds a strict mode in the `RawServiceSpec.Builder` that is enabled for the tests.
It may be good to backport the change too so that it ends up in an earlier SDK package.

Add strict checking to svc yml tests

---

frameworks/kafka/src/main/dist/svc.yml

setup-helper relies on MESOS_CONTAINER_IP in the no security case which.... is not set yet. Whoops!

Make sure MESOS_CONTAINER_IP is set before running helper

---

frameworks/kafka/src/main/dist/svc.yml

This is a straight backport of #2510. 
It fixes a possible issue running Kafka when `MESOS_CONTAINER_IP` is not set when starting the broker tasks.

[BACKPORT][DCOS_OSS-3555] Make sure MESOS_CONTAINER_IP is set before running helper (#2510)

---

frameworks/elastic/tests/test_sanity.py
frameworks/elastic/tests/test_tls.py

This PR backports https://github.com/mesosphere/dcos-commons/pull/2539.

[DCOS-38238][BACKPORT] Temporarily disable tests that are failing due to Mesos Fetcher regression.

---

frameworks/cassandra/universe/marathon.json.mustache
frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawServiceSpec.java
sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java

This PR backports #2527  the addition of a strict rendering mode for `svc.yml` files.
Additional changes required:
* Set the `CASSANDRA_CQLSH_SSL_FLAGS` envvar to blank instead of leaving it unset.

[BACKPORT][TESTS][TOOLS] Add strict rendering checks to svc.yml tests

---

testing/sdk_marathon.py

1. Fix sdk_marathon.install_app infinite waiting bug.
The shakedown.wait_for_task call keeps blocking even after the app task starts running.
2. Allow installation of Marathon apps with slashes in the name.

[DCOS-38168] Port testing changes from spark-build.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/OfferProcessor.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/OfferQueue.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/ReviveManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/http/endpoints/ConfigResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/http/endpoints/MultiConfigResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/http/endpoints/MultiPlansResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/http/endpoints/MultiPodResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/http/endpoints/PlansResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/http/endpoints/PodResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/http/queries/PlansQueries.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/Metrics.java

If an exception is passed up into the Mesos HTTP adapter, it could result in a zombie scheduler. Instead, log the exception and restart the scheduler process.
Also cleans up some HTTP resource-related warnings that the scheduler was emitting in stderr during startup.

DCOS-38473 Log and exit if exception is about to reach Mesos code

---

frameworks/helloworld/tests/test_multiservice_dynamic.py

Looking at #2545, I think the check that we are performing for a relaunched scheduler is incorrect. 
When we initially get the task ID of the scheduler (a `marathon` task) we use `.startswith(SERVICE_NAME)` as a match condition, but in the current `check_task_relaunched` function, we check `== SERVICE_NAME` which does not seem to yield the desired result.
This PR adds a *local* check function to the test file that is affected by this error. If this passes, we can move the function to `sdk_tasks` in a separate PR.
Note that this is also blocking the DC/OS smoke tests: https://teamcity.mesosphere.io/viewLog.html?buildId=1112832&buildTypeId=DcOs_Enterprise_Test_FrameworkTests_DcOsCommonsSmokeTest&tab=buildResultsDiv

[DCOS-38379] Correctly check for a relaunched scheduler task

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/ProcessExit.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/http/endpoints/DebugResource.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
testing/sdk_diag.py

1. Adds an API to get a thread dump on-demand
2. Adds a thread dump to any Process.exit() call.
3. Grab thread dump of scheduler when test fails

Add thread dumps to diagnostics

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/ApiServer.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkRunner.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/http/EndpointUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/framework/ApiServerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/framework/FrameworkRunnerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/SchedulerConfigTestUtils.java

This adds a check that the scheduler DNS entry is correct before completing the API server bring-up.

[DCOS-38592] Scheduler DNS is not resolvable when the first tasks launch

---

frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/OfferProcessor.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/state/StateStoreUtils.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

Before this change, we only checked whether the service finished deployment following a scheduler restart. In that situation, we can effectively end up comparing the OLD persisted task states against the NEW deploy plan (not the old plan, because plans are not persisted). If, for example, new steps had been added to the deploy plan in the meantime, this can lead to us thinking that deployment didn't complete before, when in reality it did.
To avoid this problem, we can simply store the fact that we've finished deployment at the moment that it happens, rather than waiting for the next scheduler restart and hoping that the plans vs state happen to line up.
In the meantime, the previous 'after restart' check is left as-is, as users upgrading from prior SDK releases may only be caught by that …

DCOS-38586 Don't wait for restart to store "finished-deploy" bit in ZK

---

tools/airgap_linter.py
tools/build_go_exe.sh

This PR upstreams some the build chain modifications we had in edgelb's SDK integration[1]:
* permit specifying custom Go linker flags in `build_go_exe.sh`. We were using it to add version information to `edgelb` CLI via `git describe --tags`
* force rebuilding of all the native executable deps when deciding if the rebuild of all the executables is necessary.
* airgap linter should not try to lint binary files
I do not have much information on the technical reasoning behind the second bullet point apart from the edgelb's original git commit message [2]:
```
Switched cli builds to `go build -a`. There is some weird caching that
breaks compiling without the `-a` flag
```
[1] https://github.com/mesosphere/dcos-edge-lb/tree/master/framework
[2] …

DCOS-37673: Upstream buildchain modifications from edgelb

---

frameworks/kafka/universe/marathon.json.mustache

Following on from #2512 this PR sets the `KAFKA_ADVERTISE_HOST` for use with the setup helper utility.
Using the value `"set"` was breaking legacy behaviour when `kafka.kafka_advertise_host_ip` was set to `true` in the configuration options.
@kohend your comments are welcome here.
* Fix Kafka behaviour when specifying the `kafka.kafka_advertise_host_ip` configuration option.

[DCOS_OSS-3555] Use a valid boolean value for Kafka envvar

---

frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/CassandraRecoveryPlanOverrider.java
frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/HdfsRecoveryPlanOverrider.java
frameworks/helloworld/src/main/java/com/mesosphere/sdk/helloworld/scheduler/DecomissionCustomizer.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/TaskUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/AbstractRoundRobinRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/MaxPerRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/PlacementUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/TaskTypeRule.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/decommission/EraseTaskStateStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/decommission/TriggerDecommissionStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DeploymentStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/PlanScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/Step.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/RecoveryPlanOverrider.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/RecoveryPlanOverriderFactory.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/RecoveryStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/DeregisterStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/ResourceCleanupStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/TLSCleanupStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/TaskKillStep.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/PlanSchedulerTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/TestStep.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/ResourceCleanupStepTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/TaskKillStepTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/PlanGeneratorTest.java

While working towards footprint-up-front, an initial pass was made to break up `PodInstanceRequirement`. A better strategy has since been worked out, but it'd make sense to retain some of the minor cleanup from that initial effort:
- `Step.start()` now returns void, instead of returning the content of getPodInstanceRequirement(). This greatly clarifies the expected behavior of the `start()` function.
- Remove duplicate code between `TaskUtils.isSamePodInstance(TaskInfo, PodInstance)` and `PlacementUtils.areEquivalent(TaskInfo, PodInstance)`
- Various other minor changes like cleaning up log statements and adding javadoc where missing.

DCOS-38149 Cleanup salvaged from PodInstanceRequirement breakup

---

frameworks/helloworld/src/main/dist/update_plan.yml
frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/SchedulerBuilderTest.java

- Adds a new ServiceTest to hello-world which verifies expected behavior around custom update plans.
- Fixes a minor bug where suppress didn't occur when a custom update plan is defined AND we're on the initial deployment of the scheduler: The update plan was included in the list of plans even when it's not used. This can lead to suppress never occurring because it iterates over all defined plans to determine if the service is idle. This only affects suppress logic, and it resolves itself if the scheduler is restarted after initial deployment, at which point the plan list is built correctly.

DCOS-38687 Add update plan test, and fix suppress when one is provided

---

frameworks/helloworld/tests/test_multiservice_dynamic.py

Seems there is a flaw in the retry logic since the scheduler seems to be restarted, adding logging here so we can see the list of task_ids returned.

[DCOS-38379] adding logging in the retry to find cause of multi service test flakiness

---

frameworks/helloworld/tests/test_zzzrecovery.py

Increasing the count of world pods to minimize risk of tasks on shut down host. Adding install/uninstall helper with options as well for the tests

[DCOS-38519] fix flakiness in test_zzzrecovery.test_shutdown_host_teardown

---

tools/ci/checks/run_pylint_checks.sh

This PR is a follow-up for #2532 and adds passing the `PYTHONPATH` environment variable to the `pylint -E` check. This is needed when changed files are not in the `testing` folder, for example.

Add PYTHONPATH for pylint checks

---

.flake8
.pre-commit-config.yaml
CONTRIBUTING.md
Dockerfile
TESTING.md
test_requirements.txt
testing/sdk_diag.py
testing/sdk_hosts.py
testing/sdk_install.py
testing/sdk_jobs.py
testing/sdk_metrics.py
testing/sdk_plan.py
testing/sdk_tasks.py
testing/sdk_upgrade.py
tools/ci/checks/get_applicable_changes.py
tools/ci/checks/get_base_branch.sh
tools/ci/checks/run_flake8_checks.sh
tools/ci/checks/run_pylint_checks.sh
tools/ci/steps/check_python_files.sh
tools/distribution/init

This is a backport with minor formatting modifications of #2532 and #2562.
The PR makes the following specific changes:
* Adds `flake8` as a requirement in the docker image
* Adds `pylint` as a requirement in the docker image
* Adds a collection of scripts to drive these kinds of checks
* adds a `pre-commit-config.yaml` file for enabling checks locally
* Make some change to Python files in `testing/` while checking the commit hooks and scripts.

[TOOLS][TESTS][BACKPORT] Add tooling for running flake8 in CI (#2532)

---

frameworks/kafka/client/Dockerfile
frameworks/kafka/client/README.md
frameworks/kafka/client/client-jaas.conf
frameworks/kafka/client/client.properties
frameworks/kafka/client/krb5.conf
frameworks/kafka/client/start.sh
frameworks/kafka/src/test/java/com/mesosphere/sdk/kafka/scheduler/ServiceTest.java
frameworks/kafka/tests/client.py
frameworks/kafka/tests/test_zookeeper_authz.py
frameworks/kafka/versions.sh

Backports #2542 
Resolves [DCOS-37640](https://jira.mesosphere.com/browse/DCOS-37640)
This PR updates Kafka to version 1.1.0 and the `kafka-client` used in the Kafka tests. It also includes Dockerfiles needed to build the image.

[DCOS-37640][BACKPORT] Update Kafka to 1.1.0 && update kafka-client (#2542)

---

hooks/post_push

This PR adds a docker hub post_push hook to add additional tags to the Docker image automatically built off the master branch.
The following tags are added:
- `{{SHA}}`
- `YYYYMMDD-{{SHA}}`
where `SHA` is the git SHA of `master` at the time of the build and `YYYYMMDD` is a date timestamp for the build.
*Note:* I tested the automatic build settings in my own [clone](https://github.com/elezar/dcos-commons) of the `dcos-commons` repo: https://hub.docker.com/r/elezar/dcos-commons/

[DCOS-29208] Add post_push hook to add additional docker tags

---

frameworks/cassandra/tests/test_tls.py
testing/sdk_recovery.py

This is a follow up for #2556 which was not triggered as part of the PR fro Cassandra as that specific PR job has `-k "sanity and not recovery"` selector. It failed the nightlies since a permanent node recovery results in a rolling update of other node tasks.
This PR:
* Removes the `recovery` mark from the test (it could be re-added once it is confirmed that this fix addresses the issue)
* Adds support to the `check_permanent_recovery` for updating multiple pods.

[COPS-3222][DCOS-38688] Cassandra pod replace performs rolling update

---

testing/sdk_diag.py

Something appears to use file suffixes to decide if it can display them directly in the browser. Other .log files in the zip packages display fine, so lets go with that.

DCOS-38967 Include '.log' suffix in filenames

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/DependencyStrategyHelper.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/TLSCleanupStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallPlanFactory.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/MaxPerHostnameRuleTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/UninstallSchedulerTest.java

Each resource to be unreserve gets its own step. At the moment, we have a single flat phase for all resources in the cluster to be unreserved. With this PR, we will now group the resources by agent hostname. This provides two benefits to the operator:
- Makes it obvious when resources tied to a given agent are all stuck, since they should all be grouped within a given phase.
- Makes it easier to bypass all resources on a given stuck agent by specifying the (per-agent) phase name when invoking the CLI command.

DCOS-29329 Uninstall: Group resources by hosting agent

---

frameworks/cassandra/tests/test_sanity.py
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache
frameworks/elastic/tests/test_sanity.py
frameworks/elastic/universe/config.json
frameworks/elastic/universe/marathon.json.mustache
frameworks/hdfs/tests/test_sanity.py
frameworks/hdfs/universe/config.json
frameworks/hdfs/universe/marathon.json.mustache
frameworks/helloworld/tests/test_sanity.py
frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache
frameworks/kafka/tests/test_sanity.py
frameworks/kafka/universe/config.json
frameworks/kafka/universe/marathon.json.mustache
frameworks/template/universe/config.json
frameworks/template/universe/marathon.json.mustache
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
testing/sdk_marathon.py

drop option to use mesos v0 api. Seems to be causing CI issues and is no longer necessary for support

[DCOS-38840] Drop mesos v0 support across frameworks

---

frameworks/helloworld/tests/test_multiservice_dynamic.py

This PR removes an additional `test_multiservice_dynamic` test from the set of smoke tests. The original was removed in a68699864f5e6da65f325993ba5098d8a1e1e05d.

[DCOS-38379][TESTS] Remove all multiservice dynamic tests from smoke

---

tools/build_package.sh
tools/universe/s3_uploader.py

If an upload to S3 fails, an attempt will be automatically made to reauth before reattempting the upload. If reauth fails, or if `maws` is not present in the local `PATH`, then it reverts to current behavior and just gives up.
Automatically determines the profile to renew via the `AWS_PROFILE` envvar, with a fallback of extracting the profile name from the credentials INI file.

DCOS-39121 Automatically renew creds with 'maws' when upload fails

---

tools/release_builder.py

Split value coming from ENV var by comma and strip whitespace.
Without this change there doesn't seem to be a way to specify multiple versions in "upgradeFrom".
Example with multiple versions:
```
$ export UPGRADES_FROM='2.0.3-3.0.14, 2.1.0-3.0.16'
$ AWS_ACCESS_KEY_ID=<...> AWS_SECRET_ACCESS_KEY=<...> DRY_RUN=true FORCE_ARTIFACT_UPLOAD=true ./tools/release_builder.py move 2.3.0-3.0.16-rc3 <...>
Read PACKAGE_NAME=
Getting package name from stub universe URL
Got package name %s from stub universe URL
Using non-beta package name cassandra
Uploading assets for cassandra to cassandra/assets
aws-cli/1.11.179 Python/2.7.10 Darwin/17.6.0 botocore/1.7.37
###
Source URL:      https://infinity-artifacts.s3.amazonaws.com/autodelete7d/cassandra/20180711-105725-7AFU7b6yktt4sIgP/stub-universe-cassandra.j …
```

[TOOLS] Fix release with multiple "upgradeFrom"s.

---

tools/release_builder.py

When this script is run from `make-stub-permanent` the ENV variable is an empty string. When it's run from `release-framework-to-universe` the ENV variable isn't set, so `os.environ.get('UPGRADES_FROM')` returns `None`.

[TOOLS] Default upgrades_from to an empty string.

---

tools/release_builder.py

When the ENV variable was an empty string `self._upgrades_from` ended up being `['']`. This commit fixes that and the conditional that checks if `self._upgrades_from` has values. Before, if it didn't, it was `None`, but now it's an empty array.

[TOOLS] Filter empty strings and fix conditional.

---

frameworks/helloworld/tests/test_multiservice_dynamic.py

task name will be the same, it is the id that will be different. Also the old task id will always show up if we query for completed tasks.

[DCOS-38379] fixing flaky multi service test

---

.pylintrc
frameworks/cassandra/tests/test_tls.py
frameworks/cassandra/tests/test_toggle_tls.py
frameworks/elastic/tests/test_tls.py
frameworks/hdfs/tests/test_sanity.py
frameworks/hdfs/tests/test_tls.py
frameworks/helloworld/tests/test_tls.py
frameworks/kafka/tests/config.py
frameworks/kafka/tests/test_tls.py
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStage.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStageTest.java
testing/sdk_recovery.py
testing/security/transport_encryption.py

This PR is a backport of #2556 and #2576.
This PR addresses an issue where we request multiple mounts of the same secret on TLS enabled data services. This currently only affects HDFS, but could be an issue for any service running multiple tasks with TLS per pod.
The changes included are:
* Modify `TLSEvaluationStage` to not add duplicate volumes to the `PodInfoBuilder`
* Modify `OfferEvaluator` to not add duplicate `TLSEvaluationStages` to the offer evaluation pipeline
* Add `pod replace` integration tests for HDFS, Kafka, Elastic, and Cassandra
(The tests were added first to confirm that this was only affecting HDFS -- after which the fix was implemented).
*Note*: I had originally tried to also run this through a `ServiceTestRunner`, but found that the TLS-handling (especially the …

[COPS-3222][DCOS-38688] Ensure Mounts for TLS secrets are not duplicate

---

test.sh

This PR adds two options to test.sh for better integration into other tooling (such as that used by EdgeLB). This was after a discussion with @vespian today.
The options are:
- `-e ENV_PASSTHROUGH`
- `--envfile ENV_FILE`
Where `ENV_PASSTHROUGH` is a comma-separated list of environment variables and `ENV_FILE` is a path to a local environment file.
In both cases, these options are passed through *in addition* to those already handled by the script. The mechanism for passing the environment to `docker run` command remains a temporary environment file.
Additional improvements:
* A timestamp has also been added to the names of the temporary envfile and credentials file created by the script to allow multiple containers to be run simultaneously.
* Don't require a framework to be specified if …

[TOOLS] Add -e and --envfile flags to test.sh to pass environment

---

frameworks/cassandra/tests/test_racks.py

This PR adds an upgrade test for custom racks in Cassandra.
@nickbp we could probably rather add a Unit Test that ensures that the property is present in the Cassandra racks configuration file, but that would not really test upgrade.

[DCOS-38688] Add custom rack upgrade test

---

test.sh

This is a backport of #2588 and updates `test.sh` to that of `master`.
The changes from #2588 include:
* Add -e and --envfile flags to test.sh to pass environment
* Also allow the docker image to be overridden
This is required to cut the new SDK release.

[BACKPORT][TOOLS] Add -e and --envfile flags to test.sh to pass environment (#2588)

---

frameworks/cassandra/tests/test_racks.py

This is a backport of #2591 adding a custom rack upgrade test.
This also adjusted the arguments to the `nodetool.cmd` function to align with the state in the `sdk-0.40` branch.

[DCOS-38688] Add custom rack upgrade test (#2591)

---

sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java

Backport of fix from master: Disable `TaskKiller` background thread so that it doesn't misfire while running these tests
Example flakes:
- https://teamcity.mesosphere.io/viewLog.html?buildId=1138378&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Sdk_BuildAndTestPr
- https://teamcity.mesosphere.io/viewLog.html?buildId=1136314&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Sdk_BuildAndTestPr
- https://teamcity.mesosphere.io/viewLog.html?buildId=1136300&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Sdk_BuildAndTestPr
- https://teamcity.mesosphere.io/viewLog.html?buildId=1135396&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Sdk_BuildAndTestPr
- https://teamcity.mesosphere.io/viewLog.html?buildId=1135364&tab=buildResultsDiv&buildTypeId=DcosIo_DcosCommons_Sdk_BuildAndTestPr

DCOS-39806 Fix TaskKiller-related flakes

---

testing/sdk_diag.py

This fixes an exception where `_dump_task_logs_for_agent` would use its return value to increment a number. `sdk_diag._dump_task_logs_for_task` could return `None` in some conditions.
```python
task_byte_count += _dump_task_logs_for_task(item, agent_id, agent_executor_paths, task_entry)
```

[TOOLS] Make `sdk_diag._dump_task_logs_for_task` return int.

---

conftest.py
frameworks/helloworld/tests/test_custom_service_tld.py
frameworks/helloworld/tests/test_overlay.py
frameworks/helloworld/tests/test_zzzrecovery.py
frameworks/kafka/tests/client.py
frameworks/kafka/tests/config.py
frameworks/kafka/tests/test_tls.py
frameworks/kafka/tests/test_zookeeper.py
frameworks/kafka/tests/test_zookeeper_auth.py
frameworks/kafka/tests/test_zookeeper_authz.py
test.sh
testing/sdk_cmd.py
testing/sdk_diag.py
testing/sdk_install.py
testing/sdk_utils.py
testing/security/cipher_suites.py

We're occasionally seeing flakes in `test_srv_records` which were traced down to frameworks not being correctly unregistered. After uninstall, validate that the framework was correctly unregistered, and throw an exception (triggering log collection) if the check fails.
Other misc fixes:
- Also throw if dangling resources are found. We were previously logging them but not throwing, so it's not clear if this is actually a thing. We should check this though, as any issues here imply an uninstall bug.
- Fix error produced by linux `mktemp` when running `test.sh`, and prettify the timestamp used: `mktemp: too few X's in template`
- Misc python lint fixes, and cleanup of lightly-used functions in `sdk_utils`.

DCOS-29474 Detect leftover frameworks after uninstalls

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultHealthCheckSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultHealthCheckSpecTest.java

SDK 0.52.0 switched to `grace-period`, but didn't include compatibility with the prior `gracePeriod`.
Add dual-read and dual-write support to `DefaultHealthCheckSpec` to support upgrade and downgrade compatibility across this divide. After a few months (and a few SDK releases), the `gracePeriod` handling can then be removed.

DCOS-40149 Fix compatibility with gracePeriod field

---

build.gradle

Our CI sometimes fails due to the `com.github.ben-manes.versions` plugin. This PR bumps it to the latest version.

[DCOS-39326] Bump Gradle Versions Plugin to 0.20.0

---

frameworks/helloworld/tests/test_zzzrecovery.py
tools/ci/checks/run_pylint_checks.sh

We disabled these in 0.50, backporting the disable to 0.40.

Disable flaky hello-world recovery tests in 0.40

---

.dockerignore
Dockerfile

This adds `.pre-commit-config.yaml` to the Docker image to allow the same checks to be easily used in other projects.

Add .pre-commit-config.yaml to Docker image

---

frameworks/helloworld/src/main/dist/multiport.yml

We should always wait for DNS resolution before using the hostnames.

DCOS-40402 Wait for DNS resolution in multiport yml

---

frameworks/elastic/tests/test_sanity.py
frameworks/elastic/tests/test_tls.py

Our TeamCity builds launch DC/OS clusters based off the `testing/master` channel, which means dcos master branch. The dcos master branch is currently [pinning Mesos](https://github.com/dcos/dcos/blob/4961d8182917d102284f7a0ccc29e4c422913565/packages/mesos/buildinfo.json#L11) at [84749967](https://github.com/dcos/dcos/blob/4961d8182917d102284f7a0ccc29e4c422913565/packages/mesos/buildinfo.json#L11), which contains the Mesos Fetcher fix. Given this, we shouldn't see the Kibana failures anymore in our CI builds.
The Mesos Fetcher fix was merged to the Mesos master branch and [will be released on Mesos 1.7.0](https://github.com/apache/mesos/blob/751ef19270ca2a9d82cff5946e1820d28e8e508f/CHANGELOG#L100)

[DCOS-38370] Re-enable Kibana tests.

---

TESTING.md
test.sh

This PR:
* Adds a section on interactive testing to `TESTING.md`
* Improves interactive mode for `test.sh` by using an existing AWS credentials file if it exists. This allows credentials to be refreshed without having to restart the docker container.

[DCOS-40636][TOOLS] Add interactive testing note to TESTING.md

---

frameworks/helloworld/src/main/dist/overlay.yml
testing/sdk_cmd.py

VIPs are not accessible from readiness checks in 1.10 and 1.11, resulting in failed nightlies on test_overlay.
As a workaround this switches to checking the server port directly, with a TODO to switch back to the VIP later.
We still check that the VIP is reachable from regular tasks via the later 'getter' task.

DCOS-40888 Workaround readiness check VIP inaccessibility on 1.10/1.11

---

Dockerfile

These can be removed someday after external repos (spark-build, dcos-zookeeper, ...) no longer depend on them, but for now let's avoid breaking things.

DCOS-40885 Re-add pip dependencies required by external repos

---

Dockerfile
test_requirements.txt

- The previous method of adding them directly to the Dockerfile doesn't work, they need to be in `test_requirements.txt` or else pip effectively ignores the specified versions.
- The dcoscli dependency is also needed to avoid breaking on an internal `servicemanager` dependency within the `dcos` library.

DCOS-40885 Second attempt at fixing 'dcos' deps for extern/sdk-0.40

---

sdk/common/build.gradle

Makes a change equivalent to the Gradle change in #2645 to the sdk-0.40 branch. This is required to unblock #2644 which in-turn unblocks #2639
We would still need to make the change to the docker file for `pre-commit`.

Use UNKNOWN as git sha for scheduler JAR in case of error

---

frameworks/helloworld/src/main/dist/secrets.yml
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/taskdata/EnvUtils.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/LaunchEvaluationStageTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorPortsTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/taskdata/EnvUtilsTest.java

I added a port env-key to the secrets test to test this as an integration in the future, and wrote some unit tests for withEnvVar.

DCOS-38256 Fixed bug where if Port env-key was defined, env based secrets were empty.

---

frameworks/helloworld/src/main/dist/multiport.yml

https://github.com/mesosphere/dcos-commons/pull/2627/files
This PR added bootstrap to cmd to wait for DNS resolution of the pod before trying to do networking. Unfortunately it didn't add the URI for the bootstrap binary, so ./bootstrap was unable to be found. This adds the URI so the binary is pulled into the sandbox, and should fix DCOS-41242.

[DCOS-41242] Download bootstrap URI from scheduler for DNS lookup for multiport test.

---

frameworks/helloworld/src/main/dist/secrets.yml
sdk/common/src/main/java/com/mesosphere/sdk/offer/taskdata/EnvUtils.java
sdk/executor/src/main/java/com/mesosphere/sdk/offer/taskdata/ProcessBuilderUtils.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/LaunchEvaluationStageTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorPortsTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/taskdata/EnvUtilsTest.java

Backport to 0.40
* DCOS-38256 Fixed bug where if Port env-key was defined, env based
secrets had an empty string value.

DCOS-38256 Backport Fixed bug where if Port env-key was defined, env based secrets were empty.

---

frameworks/cassandra/tests/test_sanity.py
frameworks/elastic/tests/test_sanity.py
frameworks/hdfs/tests/test_sanity.py
frameworks/kafka/tests/test_sanity.py

This PR just disables the metrics tests (which are failing) on 1.12.
For the record, I also have #2664 to add a hello-world smoke test for this so that we can easily test alternative fixes.

[TESTS] Disable metrics tests on 1.12

---

testing/sdk_install.py

DCOS-39567
Display SDK deploy plan before performing uninstall. This is to help diagnose hanging uninstalls.

DCOS-39567 Show SDK Plan before performing uninstall.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java

Log if the scheduler is about to hit a nullref
this is to help us detect the bug in https://jira.mesosphere.com/browse/DCOS-40696
if we determine this is the correct null ref we can work backwords to detect why it was null in that case.

[DCOS-40696] log if scheduler is about to hit a null reference

---

tools/kdc/kdc.py

This PR ensures that the `persist=True` flag is passed to the KDC when running the `deploy` subcommand. If this is not done, the installed KDC will be torn-down. This is not favourable, for example, in Soak.

[TOOLS] Also persist KDC when deploying

---

build.gradle

Releasing 0.42.3 today, bumping up snapshot.

Update build.gradle to point to next SNAPSHOT

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/DefaultRecoveryPlanManager.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java

- Check for a `resource_id` label when examining resources during uninstall. The immediate issue is a no-op where the scheduler tries to unreserve resources which are only statically pre-reserved, but it doesn't hurt to be conservative and always check for the `resource_id` label before unreserving. This should avoid the possibility of attempting to unreserve an offered resource that wasn't created by the SDK. Note that there are already upstream filters in FrameworkScheduler for filtering out Marathon volumes, so this check is effectively redundant in that case.
- Avoid (repeated) logging of the recovery plan when it's currently complete. It can be non-empty but complete in the case when prior recoveries had occurred within the lifespan of the scheduler process.
To be clear, neither of …

DCOS-42191 Don't try unreserving pre-reserved resources, fix plan spam

---

test.sh

This PR contains the changes from #2693 for the `master` branch in order to allow `dcos-commons` to be used as a submodule when building edge-lb.
Important changes:
* Allow `REPO_ROOT_DIR` to be overridden.
* Don't require a framework to be specified if a custom `DOCKER_COMMAND` is specified.

Fix bugs in test.sh for edge-lb

---

frameworks/kafka/universe/config.json
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/PodInstanceRequirementTestUtils.java

Previously, we were selecting a random task in the pod when performing a recovery (restart/replace) operation. This interim fix improves on the existing (lack of) selection logic by making it do the right thing in today's typical cases. A larger change will be made in sdk-0.50+ to improve the config update flow itself to avoid mixed configs in the same pod unless explicitly needed via e.g. a custom plan.
- Only examine tasks which are being included as part of the recovery operation, rather than all tasks in the pod.
- Among tasks being recovered, prefer the tasks which have a RUNNING goal state, over those with a FINISHED or ONCE goal state.
- Improve logging of the decision itself.
... and while we're in sdk-0.40, this PR also fixes an encoding issue in Kafka's config options for …

DCOS-42539 (backport) Improve recovery config ID selection

---

frameworks/kafka/universe/config.json
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java

Previously, we were selecting a random task in the pod when performing a recovery (restart/replace) operation. This interim fix improves on the existing (lack of) selection logic by making it do the right thing in today's typical cases. A larger change will be made in a following PR to improve the config update flow itself to avoid mixed configs in the same pod unless explicitly needed via e.g. a custom plan.
- Only examine tasks which are being included as part of the recovery operation, rather than all tasks in the pod.
- Among tasks being recovered, prefer the tasks which have a RUNNING goal state, over those with a FINISHED or ONCE goal state.
- Improve logging of the decision itself.

DCOS-42539 Improve recovery config ID selection

---

frameworks/hdfs/src/main/dist/core-site.xml
frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/HDFSAuthEnvContainer.java
frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/HDFSUserAuthMapperBuilder.java
frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/Main.java
frameworks/hdfs/src/test/java/com/mesosphere/sdk/hdfs/scheduler/HDFSUserAuthMapperBuilderTest.java
frameworks/hdfs/tests/auth.py
frameworks/hdfs/tests/test_default_kerberos_setup.py

This PR is a backport of #2682 and adds a sane default for the HDFS auth-to-local mapping that allows HDFS with Kerberos to be installed with the default options.

[DCOS-29502] Add default principal pattern for HDFS

---

testing/sdk_marathon.py

This PR ensures that the `sdk_marathon.destroy_app` call waits until the marathon app is completely removed. Before we only checked if it is still registered.

[DCOS-42770] Wait until no deployments are queued after deletion

---

frameworks/cassandra/tests/test_sanity.py
frameworks/elastic/tests/test_sanity.py
frameworks/hdfs/tests/test_sanity.py
frameworks/kafka/tests/test_sanity.py

The metrics container structure probably has changed slightly so even with the newer changes the test fail. As follow-up https://jira.mesosphere.com/browse/DCOS-43546 is created.

Disable metrics test due to changed container metrics structure

---

testing/sdk_cmd.py

The key verify sometimes exists in kwargs causing errors in _get_cluster, an example of this from dcos-kubernetes-cluster:
`
[2018-10-11 06:08:26,861|tests.conftest|ERROR]: Test test_disk_pressure failed in call phase, dumping state
[06:09:26][2018-10-11 06:09:26,930|tests.conftest|ERROR]: Mesos state collection failed!
[06:09:26]Traceback (most recent call last):
[06:09:26]  File "/go/src/github.com/mesosphere/dcos-kubernetes-1.x/kubernetes/tests/conftest.py", line 163, in pytest_runtest_makereport
[06:09:26]    get_mesos_state_on_failure(item.name)
[06:09:26]  File "/go/src/github.com/mesosphere/dcos-kubernetes-1.x/kubernetes/tests/conftest.py", line 213, in get_mesos_state_on_failure
[06:09:26]    r = sdk_cmd.cluster_request('GET', '/mesos/{}'.format(name), verify=False, …

sdk_cmd: Added check for 'verify' key

---

.dockerignore
Dockerfile
frozen_requirements.txt
test_requirements.txt
tools/ci/checks/get_applicable_changes.py
tools/diagnostics/create_service_diagnostics_bundle.py

I'm aware this is horrible. See the jira ticket for why simpler approaches did not work.

[DCOS-43889] Freeze all pip depencies to recover from build breakage.

---

Dockerfile

This should prevent build breakage whenever a broken dcos binary happens to be
picked up by the image build.

[DCOS-43953] Use a stable snapshot of dcos CLI.

---

tools/universe/package_builder.py

This PR is a backport of #2728 :
* Updates the JRE version to `8u192`
* Updates the SDK version string in `package_builder.py` to match that in `build.gradle` (Cosmetic change)

[DCOS-43947] Update JRE to 8u192 to address CVEs (#2728)

---

build.gradle

Bump the version in `build.gradle` for the SDK release.

[DCOS-44086] Bump snapshot version for 0.42.5 release

---

frozen_requirements.txt

Remove the frozen `python-apt` version as this conflicts with the version installed by apt.

[DCOS-44265] Remove python-apt from frozen_requirements.txt

---

testing/sdk_diag.py

As discussed on slack with @mpereira.
As background, in the Kubernetes package we install the package only once for the whole test suite (with the exception of testing installs and upgrades obviously). In this case, that means that sdk_diag does not collect logs, plans, bundles, etc for tasks created by Kubernetes package because it is running before tests run. Adding whitelist in this PR allows us to collect diagnostic data that we need when tests fail.

Enable whitelisting of tasks and services in sdk_diag via pytest markers

---

tools/airgap_linter.py

Prior to this PR, the check would fail only if the last image happened to be "bad", otherwise `bad_image = False` would be reset at every loop iteration.
Also modified regex to work with quoted images.

fix validate_images check

---

frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache

Config setting service.verbose_mesos_logging = 0 can be used to disable verbose Mesos prints.

DCOS-40763 - Enable GLOG_v=1 in hello-world scheduler by default.

---

frameworks/cassandra/universe/marathon.json.mustache
frameworks/elastic/universe/marathon.json.mustache
frameworks/hdfs/universe/marathon.json.mustache
frameworks/helloworld/universe/marathon.json.mustache
frameworks/kafka/universe/marathon.json.mustache
sdk/bootstrap/main.go
sdk/bootstrap/main_test.go
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java

- Introduce regex based blacklisting of log-sensitive environment variables
- Add file based secret handling support for SDK. We still support environment based secrets for backwards compatibility.
- Update frameworks mustache files with file based secrets.

[DCOS-44605] Filter sensitive environment keys and add file based secret support for frameworks

---

tools/diagnostics/create_service_diagnostics_bundle.sh
tools/diagnostics/full_bundle.py

Apparently DCOS foldered service names may or may not omit the first slash. This script was looking for the service based on its name with the first slash omitted.
For example: in soak112s a service named `/data-services/cassandra` has `data-services/cassandra` as the service `name` field. On the cluster related to https://jira.mesosphere.com/browse/COPS-4058 a service named `/green/cassandra-green7` has `/green/cassandra-green7` as the service `name` field.

Handle case where service name does *not* omit the first slash.

---

frameworks/cassandra/tests/test_sanity.py
frameworks/cassandra/universe/marathon.json.mustache
frameworks/elastic/tests/test_sanity.py
frameworks/elastic/universe/marathon.json.mustache
frameworks/hdfs/tests/test_sanity.py
frameworks/hdfs/universe/marathon.json.mustache
frameworks/helloworld/tests/test_sanity.py
frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache
frameworks/kafka/tests/test_sanity.py
frameworks/kafka/universe/marathon.json.mustache
sdk/bootstrap/main.go
sdk/bootstrap/main_test.go
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
testing/sdk_cmd.py
testing/sdk_metrics.py
tools/diagnostics/create_service_diagnostics_bundle.sh
tools/diagnostics/full_bundle.py

Updates the task refresh logic to explicitly update the StateStore TaskInfos for ALL tasks sharing a ResourceSet when any task in that set is updated. This avoids the possibility of hitting mismatches between TaskInfos, and makes it easier to track down what resources a given task is expected to be using at any given time, and avoids the current problems around TaskInfo data (config IDs) potentially being out of date in sidecar tasks. The new logic explicitly treats resource evaluation as per-ResourceSet, and then applies the resulting changes to the paired TaskInfo(s). See comments in OfferEvaluator for more info.
Other unrelated fixes for this last PR:
- Allow overriding the executor resource "overhead" via scheduler envvars
- Remove the long-deprecated FINISHED goalstate, which was …

DCOS-42539 Fix how TaskInfos are updated with sidecar tasks and resource sets

---

frameworks/elastic/universe-kibana/resource.json
frameworks/elastic/universe/resource.json

I uploaded the resources using the [Jenkins job](https://jenkins.mesosphere.com/service/jenkins/view/Infinity/job/infinity-tools/job/production-asset-tools/job/upload-production-asset/) and tested on a local cluster. Apparently the `svg` Kibana icon images lose the `image/svg` content type when uploaded, so they don't show up in the DC/OS UI. I still need to look into that.

[DCOS-41496] Use Elastic and Kibana resources from downloads.mesosphere.com.

---

frameworks/cassandra/universe/marathon.json.mustache
frameworks/elastic/universe/marathon.json.mustache
frameworks/hdfs/universe/marathon.json.mustache
frameworks/helloworld/universe/marathon.json.mustache
frameworks/kafka/universe/marathon.json.mustache

- ClassicRPCAuthenticatee is used when using V0 API. We use V0 in `1.10` clusters.
- HttpAuthenticatee is used when using V1 API.
Going forward, i think we can introduce helloworld in `1.10`, `1.11`, `1.12` (both permissive and strict) for our PR CI in dcos-commons. This would also be useful when we remove the frameworks from dcos-commons repo.

[DCOS-44873] Add file name to ClassicRPCAuthenticatee module

---

docs/pages/developer-guide.md
docs/pages/yaml-reference.md
frameworks/helloworld/src/main/dist/svc.yml
frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java
frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/TaskUtils.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/taskdata/TaskLabelWriter.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultNetworkSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultTaskSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/TaskSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawNetwork.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawTask.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/LaunchEvaluationStageTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/taskdata/TaskLabelReaderWriterTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/PodInstanceRequirementTestUtils.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultServiceSpecTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultTaskSpecTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/TestConstants.java
sdk/scheduler/src/test/resources/invalid-labels.yml
sdk/scheduler/src/test/resources/invalid-network-labels-blank.yml
sdk/scheduler/src/test/resources/invalid-network-labels-format.yml
sdk/scheduler/src/test/resources/invalid-task-labels-blank.yml
sdk/scheduler/src/test/resources/invalid-task-labels-format.yml
sdk/scheduler/src/test/resources/valid-exhaustive.yml
sdk/scheduler/src/test/resources/valid-labels.yml
sdk/scheduler/src/test/resources/valid-task-labels.yml

Some external tools such as [Traefik](https://docs.traefik.io) require tasks to be configured with custom labels which are accessed by reading Mesos state. This change allows for functionality like the following to be defined in a service spec YAML:
```
pods:
hello:
tasks:
server:
...
labels: "traefik.enable:true,traefik.frontend.entryPoints:http,traefik.frontend.rule:PathPrefix:/"
ports:
http:
port: 8080
advertise: true
```

Add support for Arbitrary Task Labels to Service Spec YAML

---

Dockerfile
Dockerfile.base
frozen_requirements.txt

Update the following packages:
- cryptography to 2.3.1
- requests to 2.20.0
Remove pycrypto-2.6.1 by removing python3-crypto
Replace pycrypto-2.6.1 with pycryptodome-3.7.0

[DCOS-44001] Fix GitHub Security Warnings

---

frameworks/helloworld/universe/marathon.json.mustache

This PR adds an evvar to all tasks to ensure that an upgrade can be tested even when the latest universe version and the version under test have an IDENTICAL task configuration.
If this was not done, ALL upgrade tests would fail as the tasks were not restarted. The scheduler now shows:
```
INFO  2018-11-22 15:18:37,694 [main] DefaultConfigurationUpdater:printConfigDiff(320): Difference between configs:
--- ServiceSpec.old
+++ ServiceSpec.new
@@ -71,4 +71,5 @@
"value" : "env && echo hello >> hello-container-path/output && sleep $SLEEP_DURATION",
"environment" : {
+          "PACKAGE_VERSION_TO_FORCE_UPDATE" : "stub-universe",
"SLEEP_DURATION" : "1000"
}
@@ -185,4 +186,5 @@
"value" : "# for graceful shutdown\n#  trap SIGTERM and mock a cleanup timeframe\nterminated () {\n  echo \"$(date) …
```

Add envvar to force hello world upgrade

---

frameworks/hdfs/tests/config.py
frameworks/hdfs/tests/test_kerberos_auth.py
frameworks/kafka/tests/client.py
frameworks/kafka/tests/test_active_directory_auth.py
frameworks/kafka/tests/test_active_directory_zookeeper_auth.py

This PR switches the testing client Docker images to ones in the mesosphere docker org.
These are hosted at: https://github.com/mesosphere/dcos-commons-ci/tree/master/docker/testing-client

[DCOS-29208] switch to mesosphere client images

---

testing/sdk_cmd.py

This PR updates some of the functionality of the `sdk_cmd._ssh()` and `sdk_cmd._scp()` functions.
First, it adds a missing `-W` parameter to the `sdk_cmd._scp()` function. Without this, the underlying 'scp' with a proxy through SSH would never have worked. I'm guessing this function is no longer used at the moment or else someone would have run into this.
Second, it adds the ability to only send a single key to both `sdk_cmd._ssh()` and `sdk_cmd._scp()`. Previously, there was no way to specifically set the identity file for use by the underlying 'ssh' and 'scp' commands. Now there is.

Update fixes to 'sdk_cmd.{_ssh(), _scp()}'

---

frameworks/helloworld/src/main/dist/pod-profile-mount-volume.yml

The changes the script from 'folded block' to 'literal block' to
preserve line breaks. Also, not setting the 'TEST_PROFILE_VOLUME_COMMAND'
will still result in a sleep.

Refine the 'pod-profile-mount-volume' service definition.

---

testing/sdk_install.py

Running janitor on CentOS fails silently due to the lack of `sudo` which is needed to run Docker containers in this OS. This PR adds `sudo` to janitor command.

Adding 'sudo' to janitor docker run command

---

tools/build_go_exe.sh

we added `GOARCH` as `386` when we first added `tools/build_go_exe.sh` in [Jan 2017](https://github.com/mesosphere/dcos-commons/commit/a3a90ccda4d949ab48cf017f67ec390396170159#diff-6f6fe33cd5affd9513259ffffd6cc88bR64). Considering that is relatively recent, i am going to assume no one has faced a problem with using `386` arch builds in 64 bit systems _so far_. Recently, a customer was using a `Ubuntu` in `windows` subsystem and they were not able to execute the binary ([DCOS-45987](https://jira.mesosphere.com/browse/DCOS-45987)). This is the error one gets when tried to execute the `386` binary in a `ubuntu running in 64-bit Windows` : 
```
<filename>: cannot execute binary file: Exec format error.
```
We have two standards that we can comply with:
- Our universe spec says the CLI …

[DCOS-45987] Always publish x86-64 compatible builds for CLI

---

frameworks/hdfs/src/main/dist/svc.yml
frameworks/hdfs/tests/test_sanity.py

Resolves [COPS-4148](https://jira.mesosphere.com/browse/COPS-4148)
This fixes the issue of quorum failing on HDFS when replacing a HDFS Journalnode and adds an integration test.
https://jira.mesosphere.com/browse/COPS-4148
Integration tests.

[COPS-4148] fixes failing quorum on replacing HDFS journalnode

---

renovate.json

Renovate bot creates a lot of noise in CI if we let a rebase on stale PRs. This PR changes the configuration to not rebase stale PRs. we can update the branch (which auto reruns the CI) if a PR is considered high risk or else we merge as-is.

[TOOLS] Do not rebase stale PRs - via renovatebot.json

---

frameworks/hdfs/tests/config.py
frameworks/hdfs/universe/config.json

Added a regex validator to check stub universe name for the service instance consisted of a series of words separated by slashes. Each word must be at least 1 alphanumeric character and may only contain digits (`0-9`), dashes (`-`), dots (`.`), and lowercase letters (`a-z`). The word may not begin or end with a dash",
Manually by creating a HDFS package on a CCM cluster.

[DCOS-46514] Adding a regex validator

---

frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache
frameworks/elastic/src/main/dist/svc.yml
frameworks/elastic/universe/config.json
frameworks/elastic/universe/marathon.json.mustache
frameworks/hdfs/src/main/dist/svc.yml
frameworks/hdfs/universe/config.json
frameworks/hdfs/universe/marathon.json.mustache
frameworks/helloworld/src/main/dist/svc.yml
frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache

Make readiness-check interval, timeout and delay configurable for the following:
- Cassandra
- HDFS (current defaults maintained for journal-node, name-node and data-node)
- Elasticsearch
- Hello-World
Default readiness interval is set to 60 and timeout to 20 to match Marathon default values. Values still need to be fine-tuned via discussion through this PR.

COPS-4320: Configurable timeouts for readiness checks.

---

frameworks/cassandra/universe/package.json
frameworks/elastic/universe-kibana/package.json
frameworks/elastic/universe/package.json
frameworks/hdfs/universe/package.json
frameworks/helloworld/universe/package.json

At the request of our legal counsel, all packages in universe need to have the license field set correctly, since we are redistributing the packaged software and correct license attribution is part of our legal obligation. Ravi and I are working through the packages already deployed, but this PR fixes the templates in dcos-commons for future version releases of the frameworks there.

Fix template package.json to include license fields

---

tools/diagnostics/base_tech_bundle/__init__.py
tools/diagnostics/base_tech_bundle/kafka_bundle.py
tools/diagnostics/bundle.py

- Save `broker list` and `broker get`s in KafkaBundle.
- Use KafkaBundle for confluent-kafka as well.
- Document file naming convention.

[DCOS-46788] Improve confluent-kafka support in diag bundle script

---

frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache
frameworks/elastic/src/main/dist/svc.yml
frameworks/elastic/universe/config.json
frameworks/elastic/universe/marathon.json.mustache
frameworks/hdfs/src/main/dist/svc.yml
frameworks/hdfs/universe/config.json
frameworks/hdfs/universe/marathon.json.mustache
frameworks/helloworld/src/main/dist/svc.yml
frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache

Extract and templatize elastic's RLIMIT_NOFILE settings.
Apply elastic's defaults (128000) from above to the following:
- Cassandra.
- HDFS
- Hello-World

DCOS-46811: Configureable RLIMITs for RLIMIT_NOFILE

---

tools/diagnostics/full_bundle.py

This happens due to a name mismatch. The DCOS_SERVICE_NAME label in SDK services and the service name provided through the CLI (i.e. `dcos $package --name=$service_name ...`) may or may not be prefixed by a slash, so comparing the two as-is sometimes doesn't work.
This change makes sure to get the scheduler task with and without a slash prefix in the name.

[DIAGNOSTICS] Fix condition where scheduler task can't be found.

---

frameworks/elastic/tests/test_upgrade.py

This test has failed a few times because the timeout for its runtime is exactly 20 minutes and it takes on average 20 minutes to complete (sometimes a bit more, sometimes a bit less).

Increase Elastic xpack_upgrade_matrix test timeout.

---

frameworks/elastic/src/main/dist/elasticsearch.yml
frameworks/elastic/tests/test_rack_awareness.py

This prevents shards from being unable to be allocated due to heterogeneity in @zone constraints for pods.
I first added the test, made sure it failed without the config file change, then added the config file change and verified that the test passed.

[DCOS-47377] Configure `node.attr.zone` as long as `ZONE` is available.

---

tools/diagnostics/base_tech_bundle/__init__.py
tools/diagnostics/base_tech_bundle/cassandra_bundle.py
tools/diagnostics/base_tech_bundle/elastic_bundle.py
tools/diagnostics/base_tech_bundle/hdfs_bundle.py
tools/diagnostics/base_tech_bundle/kafka_bundle.py
tools/diagnostics/base_tech_bundle/kubernetes_bundle.py
tools/diagnostics/full_bundle.py
tools/diagnostics/service_bundle.py

In this PR we refactor the code to allow the introduction of a kubernetes_bundle
Diagnostics for the following commands have been added in this patch:
- `manager describe`
- `manager pod status --json`
- `manager plan list` and associated `manager plan status` for each plans from the list.
- `cluster list`
- `cluster debug state properties`
- `cluster debug endpoints`
- `cluster debug pod status --json`
Commands which deal with iterating through properties of the cluster such as
`dcos kubernetes cluster debug config list` aren't supported right now as not all commands in the `dcos kubernetes` cli sub-command group support a full JSON output as of this moment (particularly ones such as `cluster list`).
Lacking a JSON output makes it error-prone to parse the output. Work will be required on …

[DIAGNOSTICS][DCOS-477820] Add initial support for kubernetes diagnostic bundles

---

tools/diagnostics/base_tech_bundle/__init__.py
tools/diagnostics/base_tech_bundle/edgelb_bundle.py

In this PR we add initial support for Edge-LB Pools with the following edgelb related commands:
- `dcos edgelb version`
- `dcos edgelb ping`
- `dcos edgelb list --json`
Additionally for each pool in the list above, the following edgelb commands are issued:
- `dcos edgelb status <pool-name> --json`
- `dcos edgelb endpoints <pool-name> --json`
- `dcos edgelb lb-config <pool-name>`
- `dcos edgelb template show <pool-name>`
Executor logs for *only the specified edge-lb pool* are collected ie:
`./tools/diagnostics/create_service_diagnostics_bundle.sh --package-name=edgelb-pool --service-name=dcos-edgelb/pools/test-http-pool --yes`
will collect the executor logs only for `dcos-edgelb/pools/test-http-pool`. Other pools executor logs will not be present in this collection.
Executor logs for other …

[DIAGNOSTICS][DCOS-47783]: Initial support for Edge-LB Diagnostic Bundle

---

frameworks/helloworld/tests/test_resource_refinement.py
testing/sdk_upgrade.py

Improve error-reporting particularly in spots where we have an `assert` within a `try-catch` clause. The assert gets caught leading to confusing error messages that don't help with diagnosing the root cause.

[DCOS-47843] Improve error-reporting for SDK CI

---

frameworks/helloworld/tests/test_zzzrecovery.py
testing/sdk_agents.py

According to [DCOS-18981](https://jira.mesosphere.com/browse/DCOS-18981) and [1.11 Release Notes](https://docs.mesosphere.com/1.11/release-notes/1.11.0-rc1/#platform) decommission is relatively new and thus we should run tests 1.11 and above only.

[DCOS-47829] Use dcos node decommission only in DC/OS 1.11 and above

---

frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/tests/config.py
frameworks/cassandra/universe/marathon.json.mustache
frameworks/cassandra/universe/resource.json
tools/universe/test_package.py

- Upgrade Cassandra base tech version for cassandra package release.
- Defaults to the package CQL sh version which is 5.0.1
- By running a CI build.

[DCOS-46650] Cassandra base tech upgrade to 3.11.3

---

frameworks/cassandra/universe/config.json

- Adds a regex validator to check that the Cassandra service instance name adheres to the following:
- Has a name consisting of a series of words separated by slashes.
- Each word must be at least 1 alphanumeric character and may only contain digits (`0-9`), dashes (`-`), dots (`.`), and lowercase letters (`a-z`) 
- The word may not begin or end with a dash
- Running a CCM cluster and checking the validator works

Regex validator to check service name for Cassandra

---

tools/diagnostics/agent.py

And executor logs into "executor" directory. Without this change the opposite happens.

[DIAGNOSTICS][DCOS-48058] Download task logs into "task" directory.

---

frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/tests/test_sanity.py

Resolves [DCOS-48462](https://jira.mesosphere.com/browse/DCOS-48462)
Apache Cassandra 3.11+ adds in new logic and classes for parsing the `JMX_PORT` from `conf/cassandra-env.sh` which is hardcoded to `7199`. This commit replaces the value in the file with the user-specified framework config.
Added an integration tests for checking logs do output the correct jmx port

[DCOS-48462][Cassandra] Honor config JMX_PORT

---

frameworks/elastic/src/main/dist/elasticsearch.yml
frameworks/elastic/tests/config.py
frameworks/elastic/tests/test_sanity.py

As per the manual/spec[1] on which the Java library we use bases its
implementation, one needs to use triple braces for variables that
should not have escaped characters when expanded. Without this, for
example, if one has quotes in the YAML content, they will get expanded
to their HTML entity: `&#34;`.
[1]: http://mustache.github.io/mustache.5.html

[DCOS-47352][COPS-4389] Don't escape characters for Elastic custom YAML.

---

testing/sdk_upgrade.py

This is required because the following line in this function gets the
scheduler configuration state based on a previous configuration
update. We need to make sure the scheduler finishes its deployment
first to get the new configuration state.

[DCOS-48772] Wait for scheduler Marathon task to finish deployments.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/config/DefaultConfigurationUpdater.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/ConfigValidationError.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/UserCannotChange.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/config/ConfigurationUpdaterTest.java

Previously the SDK would detect a change of `user` in the `ServiceSpec`, emit a warning and *not* propagate and store these updates into ZK. The scheduler would however continue to keep running with the updated user and this can cause issues with downstream components such as volumes which may have permissions set for the previous user.
This change explictly disallows changing of users on a previously deployed service. The scheduler issues a *shutdown* with a prescriptive message of how to resolve this issue.
Operators should note the scheduler crash-looping with the following message in the scheduler logs when a service user change is applied:
'INVALID CONFIGURATION UPDATE. Cannot change user of deployed service from 'userA' to 'userB'.
Revert to previous user 'userA' to proceed. Current …

[COPS-4469] Shutdown the scheduler when service user changes in a ServiceSpec update

---

docs/reference/swagger-api/swagger-spec.yaml

We added a 417 error code via https://github.com/mesosphere/dcos-commons/pull/1365/files#diff-9a32c2bd67042145f1dc9d3f533b2c9bR76 but swagger spec doesn't seem to reflect the same. This PR addresses that to avoid any confusion.

[TOOLS] Update swagger spec for v1/plans/<plan>

---

frameworks/helloworld/tests/conftest.py
frameworks/helloworld/tests/scale/test_scale.py
frameworks/helloworld/tests/scale/threading_utils.py

- Add support for threading to dispatch hello-world runs in parallel. This cuts down the running time of hello-world in MWT from hours to a few mins.
- Add support for batch cleanup of hello-world runs in MWT. This is a nice-to-have but useful.

Dispatch Hello-World MWT Scale Test Jobs in Parallel

---

testing/sdk_utils.py

Read environment variable if call to GET dcos-metadata/bootstrap-config.json fails.

[DCOS-49103][SDK Utils] Nightly CI fixes, read SECURITY env var as fallback.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorPersister.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/curator/CuratorUtilsTest.java

When SDK is writing data to zk, in some cases it is creating a `KeeperException.NodeExistsException` and this may lead to large exhibitor log files in unstable (agent disconnected etc..) clusters with multiple SDK schedulers running. This PR addresses this by problem checking for the existing zk node data before creating/updating it.

[DCOS-49331] Write data to zk only when needed

---

tools/universe/package.py

While adding mypy checks to this repository - https://jira.mesosphere.com/browse/DCOS-48816, we noticed that this parameter / attribute is unused.
That is - nothing is ever supplied to the parameter, and the private attribute is never used.

Remove unused raw_data parameter from Package

---

testing/sdk_utils.py

This fixes a bug in #2943 which inturn was introduced in #2939.

Fix incorrect use of string.lower.

---

tools/publish_aws.py
tools/publish_dcos_file.py
tools/publish_http.py
tools/universe/package_builder.py

While adding mypy checks to this repository ([DCOS-48816](https://jira.mesosphere.com/browse/DCOS-48816)), we found that there was a type error.
In particular, `universe.Package`'s "version" parameter is expected in the class to be a `Version`.
However, multiple callers of the class were giving `version` as a `str`.
A `Version` includes a `release_version` (`int`) and a `package_version` (`str`).
In this PR, we choose for all existing callers which ignored `release_version` to set that to 0.
I am happy to take other suggestions!
From what I can tell, it just so happens that none of these callers ever call use any functionality of `Package` which rely on the `version` being set correctly.
Tests for `tools` are not touched because they are removed in …

Use the `Version` type when creating a Package

---

Dockerfile

This tells renovatebot what tag to take updates from.
It is effectively a revert of #2745.
We can do this now that a recent-enough docker is installed on TeamCity
(DCOS-44509).

[DCOS-44511] Insert `:latest` tag into FROM line

---

frameworks/helloworld/src/main/dist/plan.yml
frameworks/helloworld/tests/test_parallel_plans.py

In `test_parallel_plans.py` we use plans from sidecar.yml which has multiple pods with all tasks sharing a single resource-set, this sometimes leads to inconsistencies (offer starvation) when all the tasks are run in parallel and the test times out before all the offers are received back to make progress. This PR adds new plans to `plan.yml` that can be used more reliably to make sure that all the plans progress simultaneously without waiting for each other.

Add multiple custom plans to plan.yml

---

frameworks/elastic/tests/config.py
frameworks/elastic/tests/conftest.py
frameworks/elastic/tests/test_overlay.py
frameworks/elastic/tests/test_rack_awareness.py
frameworks/elastic/tests/test_sanity.py
frameworks/elastic/tests/test_tls.py
frameworks/elastic/tests/test_upgrade.py
testing/sdk_security.py

This is a subset of #2979.
@wavesoft already looked at the changes there.
However, as that PR was huge, I was fairly asked to split it up.
A key question from @wavesoft was why we wrap a few things in `bool()`.
The answer is that sometimes `mypy` is not sure that something will evaluate to a boolean.
For example, if we take the following pseudocode:
```
@retry.retry(...)
def my_function() -> bool:
return True
my_var = my_function()
```
We can fairly interpret as humans that `my_var` is likely a boolean.
However, the `retry` function has no type hints and could in theory change the return value of the function.

Add mypy types to the elastic framework

---

tools/create_testing_volumes.py

verified this via https://teamcity.mesosphere.io/viewLog.html?buildId=1715989&buildTypeId=Frameworks_Orchestration_DcosCommons_PrJobs_TestOnpremHelloWorldPr&tab=buildResultsDiv

[TOOLS] Source required file for setting MESOS_WORK_DIR in clusters created with onprem amis 

---

frameworks/helloworld/tests/test_decommission.py
testing/sdk_upgrade.py

Propagate `from_options` as `to_options` in the upgrade scenario when `to_options` are not explicitly defined to maintain compatibility.
Explicitly propagate hello-world install-options for upgrade scenario in test_decomission tests.

[DCOS-51307] Propagate options in sdk_upgrade when to_options not specified.

---

Dockerfile.base

This time I tested these should be sufficient.
Required for https://github.com/mesosphere/dcos-commons/pull/2987

[DCOS-51458] Add all necessary dependencies for new pygobject package.

---

Dockerfile
frozen_requirements.txt

There is a circular dependency between updating pygobject (whose newer
version needs pkg-config) and updating the base image to newer version
whihch contains pkg-config (but whose test job fails beause older
pygobject is no longer installable - pruned from PyPI).
This PR contains both changes.

[DCOS-51458] Update both pygobject and base image.

---

Dockerfile

This will allow the updating instructions in older copies of UPDATING.md
to still work.

[DCOS-52239] Reinstate the init script

---

frameworks/cassandra/src/main/dist/cassandra.yaml
frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/tests/config.py
frameworks/cassandra/tests/test_auth.py
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache

[DCOS-51573][DCOS-51574] authn authz implementation
With this Release internal authentication and internal authorization will be added to this framework.
Cassandra uses rolenames and passwords for internal authentication. Role-based authentication encompasses both users and roles to bring a number of useful features to authorization. Roles can represent either actual individual users or roles that those users have in administering and accessing the Cassandra cluster.
Design Document :- 
https://docs.google.com/document/d/1L2MR7czxXYcfHxlKLMQGNGVq5cj4L0wXQblIKD6cny8/edit?usp=sharing

[DCOS-51573][DCOS-51574] authn authz implementation

---

frameworks/helloworld/README.md

Fix broken links. The location of yamls has changed from `src/main/dist/examples` to `src/main/dist`

Fix broken links

---

changelog.md

This note is helpful for framework developers to get the mesos 1.8.0 snapshot artifact.

[TOOLS] Add note on new repo

---

Dockerfile
tools/ci/launch_cluster.sh
tools/ci/test_runner.sh
tools/container/README.md
tools/container/venvs/wrap.sh

Introduce a wrapper script around `dcos-launch` as the first stage of encapsulating it and its dependencies. Actual logic will be added once the callers defined in TeamCity configs are converted to use it.
More details about the design in the ticket.

[DCOS-52245] Preparatory change for wrapping dcos-launch

---

README.md
changelog.md

Remove the short section on the service spec - there is a very similar but
better one in the developer guide already, and it's not really appropriate
to attack a complete newcomer with such details.
Instead, re-add the quick-start section that should be more useful to
someone who wants to start using the SDK. In there, point them at the
dcosdev tool and the helloworld example for the lack of a better HOWTO
guide.

[DCOS-52239] Replace the spec section with a quickstart one

---

frameworks/elastic/build-kibana.sh
frameworks/elastic/kibana/init.sh
frameworks/elastic/kibana/nginx.conf.tmpl
frameworks/elastic/tests/test_sanity.py
frameworks/elastic/tests/test_tls.py
frameworks/elastic/universe-kibana/marathon.json.mustache
frameworks/elastic/universe-kibana/resource.json

This was done to address the issue surfaced by COPS-4781: accessing the Kibana service URL resulted in a redirect to an invalid URL. Namely:
```
GET /service/kibana/ => /service/kibana/service/kibana/app/kibana
```
The expected redirect should have been:
```
GET /service/kibana/ => /service/kibana/app/kibana
```
This happened because of a breaking change in Kibana 6.x which caused requests to the Kibana web server hitting the root path (`/`) resulted in an invalid redirect, depicted above.
This could be the place where this bug was introduced:
https://github.com/elastic/kibana/pull/21408/files#diff-230bb53cded88451213fc31d8a4b0774L103
The solution here was to add an nginx proxy in between Admin Router and the Kibana web server, that rewrites requests that would hit the Kibana web server …

[DCOS-53557][COPS-4781] Expose Kibana web server through an nginx proxy.

---

Jenkinsfile.dcos-commons

Reverts mesosphere/dcos-commons#3039 since our jenkins does not like the syntax, perhaps it's too old:
```
WorkflowScript: 22: expecting '}', found ',' @ line 22, column 51.
tag pattern "^0\\.5[6-9]\\..*", comparat
```

Revert "Build and push docker image on release tags too."

---

Jenkinsfile.dcos-commons-base

If this works at all, we can change the other one.
Based on
https://stackoverflow.com/questions/43214730/how-to-set-github-commit-status-with-jenkinsfile-not-using-a-pull-request-builde/47162309#47162309
customizing only the property we need, the rest should work fine by
default.

[DCOS-53417] Customize the context of base image build job

---

Jenkinsfile.dcos-commons-base

```
WorkflowScript: 54: The ‘post’ section can only contain build condition names with code blocks. Valid condition names are [always, changed, fixed, regression, aborted, success, unsuccessful, unstable, failure, notBuilt, cleanup] @ line 54, column 9.
setBuildStatus("mesosphere/${IMAGE}")
^
WorkflowScript: 53: post can not be empty @ line 53, column 5.
post {
```

[DCOS-53417] Fix the syntax

---

Jenkinsfile.dcos-commons-base

Somehow the default resolves to an empty string:
```
[Set GitHub commit status (universal)] PENDING on repos [] (sha:c4cb692) with context:mesosphere/dcos-commons-base
```

[DCOS-53417] Add repo name

---

frameworks/cassandra/tests/test_auth.py

Resolves [DCOS-53489](https://jira.mesosphere.com/browse/DCOS-53489)
Recently added integrations test test_auth.py is failing in open DCOS , this change will fix it.
TC CI tests and manually tested over Open DCOS

[DCOS-53489] cassandra test_auth failing on DC/OS Open

---

frameworks/cassandra/src/main/dist/cassandra.yaml
frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/Main.java
frameworks/cassandra/tests/test_auth.py
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache

Resolves [DCOS-53277](https://jira.mesosphere.com/browse/DCOS-53277)
Current implementation of AuthN+Z is hardcoded to either AllowAllAuthenticator or PasswordAuthenticator + similar values for authz.
added YAML block to configure cassandra.yaml, it will allow customer to provide custom values.
TC CI tests

[Dcos-53277] generalize auth n+z configs

---

frameworks/elastic/universe-kibana/marathon.json.mustache

Added two more task labels for Kibana 
ref: https://jira.mesosphere.com/browse/DCOS-53604
_MARATHON_SINGLE_INSTANCE_APP_ is set to true so that user cannot scale same app to 2 instances (scaling won't work as Kibana is not HA)

[DCOS-53604] Added extra mesos task labels

---

frameworks/helloworld/universe/package.json
testing/sdk_upgrade.py

Fixes the flaky `test_sidecar.test_envvar_accross_restarts` in helloworld

[DCOS-54393] wait for marathon app deployment during service update correctly

---

frameworks/hdfs/tests/config.py
testing/sdk_cmd.py

Tests were failing due to warnings like:
```
The attached cluster is running DC/OS 1.14 but this CLI only supports DC/OS 1.12.
```
that were sneaking into the `stderr` causing tests to incorrectly think that failures existed.
This PR ignores those warnings and allows the tests to proceed.

[HDFS] Ignore CLI version warnings in stderr

---

frameworks/helloworld/universe/package.json

This was causing failures in nightlies when the tests try to install helloworld with version as `stub-universe`.
The python tests have enough checks in place in to ensure seccomp is only tests 1.13 and above. this may still cause problems if someone tried to do a manual install for seccomp but i guess we can live with this until we find a better fix.

Revert helloworld minDcosReleaseVersion to 1.11

---

frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache
frameworks/elastic/universe/config.json
frameworks/elastic/universe/marathon.json.mustache
frameworks/hdfs/universe/config.json
frameworks/hdfs/universe/marathon.json.mustache

Resolves [DCOS-53561](https://jira.mesosphere.com/browse/DCOS-53561)
Added code for a check to show accurate scheduler plan status in UI with SDK 0.56.0 or later. Also, The default values are parameterized so that they can be configured at the time of deployment.
TC CI tests

[DCOS-53561] Add support for accurate Scheduler Plan status in the UI with SDK 0.56.0+

---

frameworks/cassandra/src/main/dist/svc.yml

Cassandra runs the `bootstrap` command to configure a container and install any necessary certificates.
Previously `JAVA_HOME` was set after running `bootstrap` and the following message is seen in the container's `stderr` logs:
```
No JAVA_HOME provided. Cannot install certs.
```
The historical reasons for why this is the case is unknown.
This patch fixes the issue.

Cassandra: set JAVA_HOME before running bootstrap in svc.yml

---

frameworks/cassandra/dashboards/DC_OS_Cassandra_Dashboard.json
frameworks/cassandra/dashboards/DC_OS_Cassandra_Dashboard_1_12.json
frameworks/cassandra/dashboards/DC_OS_Cassandra_Dashboard_1_13.json
frameworks/cassandra/dashboards/README.md

Resolves [DCOS-53276](https://jira.mesosphere.com/browse/DCOS-53276)
add the Grafana dashboard as a file inside the Cassandra project.
The idea here is that we want users to be able to deploy their Cassandra cluster (or clusters) and right after easily deploy the monitoring service so they can properly track metrics.
Manually testing

[DCOS-52831] Add Grafana dashboard to C* project with README

---

tools/universe/package_builder.py

When building stubs (that ultimately make it to universe), the `package.json` file included URLs like `https://docs.mesosphere.com/services/kafka/v2.6.0-5.1.2/` which would lead to `Page not found`s. Removing the `v` fixes the links to point to the right service pages.
See associated fixes: https://github.com/mesosphere/universe/pull/2297

Fix documentation-path in package_builder

---

frameworks/cassandra/tests/config.py
frameworks/cassandra/universe/marathon.json.mustache
frameworks/cassandra/universe/resource.json

- Upgrade Cassandra base tech version for cassandra package release.
- By running a CI build.

[DCOS-54121] Cassandra upgrade to 3.11.4

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DeploymentStep.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/state/StateStore.java

Add support for handling of addtional task-statuses enabled by the PARTITION_AWARE capability added in DCOS-40703 (#2884)
JIRA: DCOS-53490

Add PARTITION_AWARE task-statues.

---

frameworks/cassandra/tests/test_custom_domain.py
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache

Added the support for custom domain in the Cassandra Framework. Added Integration test "test-custom-domain.py" in the tests.
Resolves [DCOS-54764](https://jira.mesosphere.com/browse/DCOS-54764)
Built Cassandra and launched it on a Cluster. It worked without any issue.
-Manual Testing by setting custom_domain parameter
-Automated testing with the help of "test-custom-domain.py" Integration test.
Cassandra can now support custom domain feature.

Added support for custom_domain for Cassandra FW

---

frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache

Resolves [DCOS-54750](https://jira.mesosphere.com/browse/DCOS-54750) 
Added code to support DSS Volume profile in disk(volume) of the FW node.

[DCOS-54750] Add DSS volume profile support in Cassandra

---

frameworks/cassandra/universe/config.json
frameworks/hdfs/universe/config.json

Added Media Attribute change for Service Account and Secret , post this change autosuggestion will appear as drop down for the service account and secret present on the cluster. 
Resolves [DCOS-51986: Add appropriate media attribute for secrets and service accounts to json ](https://jira.mesosphere.com/browse/DCOS-51986)
Changes were tested on CCM cluster by locally building the stub , screen shot for the same been attached to JIRA ticket 
Enabled Autocomplete widgets for Service Account and Secret , Enables users to quickly find and select from a pre-populated list of values.

[DCOS-51986] Add media attribute to service account and secret settings.

---

frameworks/cassandra/tests/test_auth.py

fixing failed backup and restore azure test by ignoring it from open DC/OS.

Ignore authenticated backup and restore Azure test on DC/OS Open

---

tools/standardize_config_json.py

This allows for the script to also standardize project specific sections. Right
now it only standardizes the order of the "service" section.
For example, I'm using it to standardize the order of the "elasticsearch"
section for the Elastic service. By providing a configuration file that looks
like the following:
`dcos_commons.json`:
```
{
"standardize_config_json": {
"sections": {
"elasticsearch": {
"head": [
"custom_elasticsearch_yml",
"health_user",
"health_user_password",
"plugins",
"plugin_http_proxy_host",
"plugin_http_proxy_port",
"plugin_https_proxy_host",
"plugin_https_proxy_port",
"xpack_http_proxy_host",
"xpack_http_proxy_port",
"xpack_graph_enabled",
"xpack_ml_enabled",
"xpack_monitoring_collection_enabled",
"xpack_monitoring_enabled",
"xpack_security_audit_enabled", …
```

[DCOS-56081] Make "service configuration JSON"-standardizing script more flexible.

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/config/DefaultConfigurationUpdater.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkConfig.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkRunner.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultResourceSet.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/NamedVIPSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/PortSpec.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/framework/FrameworkRunnerTest.java

- Always subscribe with `MULTI_ROLE` capability.
- Subscribe to Mesos with both the old and new roles.
- Fix the roles in ServiceSpec to match previous configuration on a scheduler upgrade.

[WIP] Add support for scheduler upgrades with new role.

---

frameworks/helloworld/tests/test_quota_upgrade.py

- Update scheduler to new role.
- Update pods to new role via `pod replace`, restart scheduler in between each replaced pod to ensure mixed-mode roles are applicable.
- Add additional pods post scheduler update, ensure that new pods are launched under the new role.

[WIP] SI Tests for Quota migration

---

frameworks/hdfs/tests/auth.py
frameworks/hdfs/tests/config.py
frameworks/hdfs/tests/test_ssl_kerberos_auth.py
frameworks/hdfs/tests/test_ssl_kerberos_custom_domain_auth.py
frameworks/hdfs/universe/config.json
frameworks/hdfs/universe/marathon.json.mustache

Added the support for custom domain in the HDFS Framework. Added Integration test "test_ssl_kerberos_custom_domain_auth.py" in the tests.
Resolves [DCOS-54768](https://jira.mesosphere.com/browse/DCOS-54768)
Built HDFS and launched it on a Cluster. It worked without any issue.
-Manual Testing by setting custom_domain parameter
-Automated testing with the help of "test_ssl_kerberos_custom_domain_auth.py" Integration test.
HDFS can now support custom domain feature.

[DCOS-54768] HDFS add custom domain support.

---

testing/sdk_auth.py
tools/kdc/kdc.py

Current KDC configuration in `sdk_auth` loads app definition from a JSON file and ignores `id` field overriding it with hard-coded constant `KERBEROS_APP_ID`. This PR allows overrides of `KERBEROS_APP_ID` and `REALM` at least via env vars.

Allow override KDC Marathon App ID and REALM via env vars

---

frameworks/cassandra/tests/config.py
frameworks/cassandra/tests/test_backup_and_restore.py

Added integration test to check backup functionality of Cassandra over S3 compatible storage, in this test case S3 compatible storage is minio.
Resolves [DCOS-55313](https://jira.mesosphere.com/browse/DCOS-55313)
N/A

[DCOS-55313] Cassandra integration test for S3_ENDPOINT_URL

---

Dockerfile.base
dind-wrapper.sh
test.sh

In order to make sure that all the build dependencies are at the exact version required by SDK, edge-lb's SDK is built inside dcos-commons container. Creating `.dcos` bundles require running docker daemon though, as per:
https://github.com/mesosphere/dcos-commons/blob/5211125494a87311de423e9f99d8d3c45070bdf6/tools/publish_dcos_file.py#L104-L129
And this was breaking our build process, as there is no running docker container support in dcos-commons build container yet, hence this PR. Existing scripts/builds will not be affected as there needs to be a command-line option to enable DinD behavior.
In theory, we could modify the scripts to write compilation artifacts somewhere while still inside `dcos-commons` build container and then have the .dcos build step pick them up afterward after …

Add DinD support for test.sh script

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/state/StateStore.java

Yet another attempt to fix [DCOS-42593](https://jira.mesosphere.com/browse/DCOS-42593). While we can be more confident that the fix should work this time, it's not fully clear why zk limit is still exceeded in the last release. We were able to capture the following in the previous MWT logs:
```
"[myid:1] WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@383] - Exception causing close of session @kibana-highlighted-field@0x400005b9961014b@/kibana-highlighted-field@: Len error 1049509"
```
1049509 is just 933 bytes more than the value of 1024 * 1024. I presume this is some zk internal overhead that is being added. In that case, changing our limit to 1000 * 1000 is more conservative but should fix the length error. I am still trying to write a test with hello-world that would …

[DCOS-42593] Decrease the max zk payload to a conservative limit of 1000 X 1000B

---

frameworks/hdfs/tests/test_hdfs_kerberos_upgrade.py

Added test script to 
deploys kdc
deploys kerberized HDFS
upgrades it to the latest stub (of the current code)
Resolves [[HDFS] Integration test for Kerberized HDFS upgrade](https://jira.mesosphere.com/browse/DCOS-57175)
Test script ran on permissive and strict cluster locally and its passes successfully , it install kdc , deploys kerberised hdfs service and upgrades to the stub
New integration test script now help testing upgrade of kerberised hdfs service

[DCOS-57175] Add integration test for Kerberized HDFS upgrade

---

test.sh

This is needed because projects using dcos-commons as a submodule will use its tooling, most commonly the `run_container.sh/test.sh` script, which runs a container that has its Docker `WORKDIR` set to dcos-commons' directory, which contains the dcos-commons `settings.gradle` file listing projects available in the monorepo. For example, as of today, it looks like this:
```text
rootProject.name = 'dcos-commons'
include 'frameworks/cassandra'
project(':frameworks/cassandra').name = 'cassandra'
include 'frameworks/hdfs'
project(':frameworks/hdfs').name = 'hdfs'
include 'frameworks/helloworld'
project(':frameworks/helloworld').name = 'helloworld'
include 'frameworks/helloworld/tests/tls/keystore'
project(':frameworks/helloworld/tests/tls/keystore').name = 'keystore-app'
include 'sdk/scheduler' …
```

Override dcos-commons' gradle.settings file.

---

build.gradle
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java

`sdk-60-poc` will be used as the test branch for all future work related to SDK on USI. it will have usi as a moving dependency on usi. 
The failing CI is due to lack of SDK 60 docker image.

Create SDK 60 branch

---

Jenkinsfile.dcos-commons-base_

https://jenkins.mesosphere.com/service/jenkins/job/dcos-commons-base%20docker%20image/indexing/console
has already been pointed at the new name.

[DCOS-57609] Rename the file to make autobuilder work again

---

Dockerfile.base

Adding -V -oDebug::pkgDepCache::AutoInstall=yes to make future
debugging of such issues easier.

[DCOS-57609] Skip grub-pc installation, add some debugging

---

sdk/scheduler/build.gradle
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/MarathonConstraintParser.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultPodSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawNetwork.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawPod.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawServiceSpec.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/MarathonConstraintParserTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultServiceSpecTest.java
sdk/scheduler/src/test/resources/invalid-image-null.yml

[COPS-5211](https://jira.mesosphere.com/browse/COPS-5211) With the current [logic](https://github.com/mesosphere/dcos-commons/pull/3160/files?file-filters%5B%5D=.java#diff-f9f1a86bdbc6c184aef9211aa067b057R135-R144) around parsing the placement constraint string, there may be a case where only the first few characters in the string are parsed in to json object. 
For e.g.:
```
["a","b"],[["asd"]
```
would be parsed as
```
["a","b"]
```
with the trailing tokens being ignored. This PR upgrades the `jackson.core:jackson-databind` (along with other jackson libraries) to a newer version which has the provision to specify sth like `DeserializationFeature.FAIL_ON_TRAILING_TOKENS` in order to make sure the entire string is a valid json array before we try to parse it.

[COPS-5211] Fix marathon constraint parser bug

---

Dockerfile

This is just getting ahead of renovatebot (which runs on saturdays) - the base docker image currently in use was created on August 2nd. However, there have been more commits afters Aug 2nd and we want the base image to be latest.
See https://github.com/mesosphere/dcos-commons/pull/3158 for why we are not on latest base image.

Update base docker image to latest sha

---

frameworks/cassandra/src/main/dist/svc.yml

Resolves [DCOS-54125](https://jira.mesosphere.com/browse/DCOS-54125) 
Fix DC/OS 1.11 Teamcity test fail issue
DC/OS 1.11 build was failing due to following reason 
```
Failed to write rendered template from envvar 'CONFIG_TEMPLATE_JMX_CONFIG' to '.ssl/jmx-ssl-setup.sh': open .ssl/jmx-ssl-setup.sh: no such file or directory
```
because path .ssl doesn’t exist in DC/OS 1.11 hence was failing, in this PR i have moved jmx-ssl-setup.sh to root folder, which would be accessible for all DC/OS versions.

[DCOS-54125] Fix DC/OS 1.11 Teamcity test fail issue

---

testing/sdk_auth.py
tools-internal/kdc-api-server/Dockerfile.heimdal-alpine
tools-internal/kdc-api-server/Dockerfile.heimdal-centos7
tools-internal/kdc-api-server/Dockerfile.mit-alpine
tools-internal/kdc-api-server/Dockerfile.mit-centos7
tools-internal/kdc-api-server/server/server.go

This PR adds a `checksum` property on the list and check API calls that is unique for the contents of the keytab stored in the secret.
This checksum can be used to detect unwanted changes in the keytab. (eg. when KDC is restarted and the keytab is re-issued).

Including keytab checksum on KDC API Response

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java

I think we are at a point now where we can safely rely on the zk state to see if the deploy plan has been completed. Initially this was planned for SDK 60, but due to uncertainty around when that will be out, I am doing this as tech debt.

Remove manual plan sync that is applicable to sdk 40 -> 50 upgrades

---

frameworks/hdfs/build.sh
frameworks/hdfs/cli/build.sh
frameworks/hdfs/cli/main.go
frameworks/hdfs/cli/main_test.go
frameworks/hdfs/cli/vendor
frameworks/hdfs/src/main/dist/svc.yml
frameworks/hdfs/tests/test_cli.py
frameworks/hdfs/universe/marathon.json.mustache
frameworks/hdfs/universe/resource.json

Added new command `hdfs` that allows to run HDFS CLI commands via DC/OS CLI
```
$ dcos hdfs hdfs dfs -mkdir /dir
$ dcos hdfs hdfs dfs -ls /
Found 1 items
drwxr-xr-x   - nobody supergroup          0 2019-09-02 10:11 /dir
```
List of HDFS CLI commands: https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HDFSCommands.html
- added new command to hdfs framework - frameworks/hdfs/cli/main.go, remaining arguments after `hdfs` command will be considered as subcommands and flags for HDFS CLI
- added building CLI tool as part HDFS framework build
- `test_cli.py` test creates a directory in HDFS via command line commands and verifys it

[DCOS-57593][HDFS] Add base tech cli commands

---

build.gradle

This is to unbreak the HDFS and cassandra builds while we prepare and test the proper fix for DCOS-58875 described in the ticket.

[DCOS-58875] Quick workaround while we fix our CI

---

frameworks/helloworld/src/main/dist/svc.yml
sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawTask.java

Due to recent upgrade of jackson library(#3160), yaml fields with empty values are being parsed as null references instead of blank string references. This behaviour led to problems during upgrade for edgelb and dse (mesosphere/dcos-edge-lb/pull/482 and mesosphere/datastax-service/pull/380)

Parse NULL as empty for TaskSpec env map

---

Dockerfile
build.gradle
frameworks/cassandra/universe/resource.json
frameworks/hdfs/universe/resource.json
frameworks/helloworld/tests/tls/keystore/build.gradle
frameworks/helloworld/universe/resource.json
gradle/quality.gradle
sdk/scheduler/build.gradle
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/taskdata/AttributeStringUtils.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/security/TLSArtifactsGeneratorTest.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/state/SchemaVersionStoreTest.java
sdk/testing/build.gradle
sdk/testing/src/main/java/com/mesosphere/sdk/testing/CosmosRenderer.java
test.sh
tools/universe/package_builder.py

This PR bumps the jre for schedulers to java 11 and the framework jre is still at java 8.
Also credits to initial work @kaiwalyajoshi did via #3027

Bump scheduler java runtime to Java 11

---

tools/distribution/copy-files

Reverts mesosphere/dcos-commons#3186
Reverting as its causing issue with SDK bump in Datastax, also its not fulfilling the purpose which was to solve error in dcos-zookeeper while bumping to latest SDK version.
I am facing issue after this changes , also confirmed with @takirala that dse update SDK is working with images before this changes :- 
```
$ docker run --rm -ti -v $(pwd):$(pwd) mesosphere/dcos-commons:latest copy-files $(pwd) --update-sdk 0.57.0
INFO:__main__:Copying /dcos-commons-dist/conftest.py to /home/vivek/datastax-service/
INFO:__main__:Copying /dcos-commons-dist/run_container.sh to /home/vivek/datastax-service/
cp: cannot stat '/dcos-commons-dist/run_container.sh': No such file or directory
Traceback (most recent call last):
File "/build-tools/copy-files", line 140, in …
```

Revert "Added run_container.sh to copy files list."

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java

Whenever a next release cut happens, I think we can enable region awareness by default.

Allow region awareness by default

---

sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/SchedulerConfigTest.java

Follow up for #3198 
It was my bad to miss the failing unit tests in earlier PR.

Fix unit tests for region awareness default flag

---

Dockerfile
tools/distribution/copy-files

This PR -
1. copies `run_container.sh` in the dcos-commons docker container.
2. adds `run_container.sh` in the `copy-files` list.

Copy run_container.sh in the docker container.

---

tools/universe/s3_uploader.py

According to [DCOS-45814](https://jira.mesosphere.com/browse/DCOS-45814), and more specifically Marvin's comment, we should switch away from `public-read` ACL and use `bucket-owner-full-control` instead.
This PR is intended to be used during the transitional phase of the projects, allowing non-braking changes. Whoever wants to use the new ACLs should first
```
export AWS_UPLOAD_ACL=bucket-owner-full-control
```

Making upload ACL permissions from `public-read` to configurable

---

testing/sdk_security.py

This is required since [MARATHON-8706](https://jira.mesosphere.com/browse/MARATHON-8707) was enabled on [DC/OS 2.0](https://github.com/dcos/dcos/pull/6416) and later clusters, especially on master.
Most SDK frameworks test with a canonical foldered name such as `/test/integration/<foo>` where `enforceRole` will be set on the top-level group `test`, and the scheduler will require the `test` role.

DCOS-60595: Add 'test' as one of the roles to configure for strict-mode clusters.

---

Dockerfile.base
Jenkinsfile.dcos-commons
Jenkinsfile.dcos-commons-base_

The [`mesosphere:dcos-commons-base`](https://github.com/mesosphere/dcos-commons/blob/master/Jenkinsfile.dcos-commons-base_#L42) and [`mesosphere:dcos-commons`](https://github.com/mesosphere/dcos-commons/blob/master/Jenkinsfile.dcos-commons#L41) images are built with the `--squash` argument to the `docker build` command.
`docker build --squash` requires[ experimental features](https://docs.docker.com/engine/reference/commandline/build/#squash-an-images-layers---squash-experimental) to be enabled, in the Mesosphere build environment this specifically requires the [DinD images to have experimental support enabled](https://github.com/mesosphere/dcos-jenkins-dind-agent/tree/0.6.0-experimental).
This patch switches the build tooling to a jenkins mesos plugin tag that has `--squash` support.

[TOOLING] DCOS-61702: Use dcos-commons jenkins mesos-plugin tag for Jenkins builds.

---

sdk/scheduler/build.gradle

Fix `ClassNotFoundException` errors in scheduler stderr logs due to removal of JAXB from JDK-9 and later runtimes.
JIRA: COPS-5580

COPS-5580: Fix Jersey exceptions filling scheduler stderr logs.

---

tools/publish_http.py

Bug fixed when the python program "publish_http.py" try to add the repository to a DC/OS cluster with the dcos-cli.

Fixed publish http server launch

---

gradle/quality.gradle

Fix the deprecated warning of PMD Gradle plugin (PMD project):
`
Use Rule name category/java/errorprone.xml/AvoidBranchingStatementAsLastInLoop
instead of the deprecated Rule name 
rulesets/java/basic.xml/AvoidBranchingStatementAsLastInLoop.
PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/AvoidDecimalLiteralsInBigDecimalConstructor
instead of the deprecated Rule name 
rulesets/java/basic.xml/AvoidDecimalLiteralsInBigDecimalConstructor.
PMD 7.0.0 will remove support for this deprecated Rule name usage.
`

Fix the deprecated warnings of PMD gradle plugin

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/http/queries/PodQueries.java

Services such as Cassandra can have pods with many auxiliary tasks, for these auxiliary tasks that are usually `PENDING`, check that the `TaskId` actually exists before making the call to reset backoff.
Otherwise we get the following exception in the scheduler logs.
```
com.mesosphere.sdk.offer.TaskException: ID '' is malformed. Expected '__' to extract name from ID. IDs should be generated with CommonIdUtils.
at com.mesosphere.sdk.offer.CommonIdUtils.extract(CommonIdUtils.java:220) ~[scheduler-0.58.0-SNAPSHOT.jar:?]
at com.mesosphere.sdk.offer.CommonIdUtils.extractTaskNameFromId(CommonIdUtils.java:203) ~[scheduler-0.58.0-SNAPSHOT.jar:?]
at com.mesosphere.sdk.offer.CommonIdUtils.toTaskName(CommonIdUtils.java:96) ~[scheduler-0.58.0-SNAPSHOT.jar:?]
at …
```

[DCOS-63182] Check TaskId exists for auxiliary pod tasks before reset of Backoff.

---

tools/universe/azure_uploader.py

Temporarily relax the requirement for `msrest` till we resolve the build breaks in our environment.

[DCOS_OSS-5905] Remove requirement for msrest in azure_uploader.

---

frameworks/cassandra/src/main/dist/metrics-reporter-config.yaml
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache

This commit introduces the metrics_period_min configuration parameter that allows adjusting
the metrics flushing interval to statsd. This can be used to reduce the load on telegraf
in the case of large data sets.

[DCOS-61505] Controlling metrics period

---

Dockerfile.base

It updates `Dockerfile.base` to use Ubuntu 18.04 instead of 18.10 as base image. 18.04 is an LTS version and it would be more stable, whereas current version have many repository removed from the support and that is causing building docker image to fail.

Update ubuntu version from 18.10 to 18.04

---

frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache

This patch allows default log sizes to be configureable for [logrotate](https://docs.d2iq.com/mesosphere/dcos/1.13/monitoring/logging/configure-task-logs/#logrotate-options).
This patch only allows the following env-vars to be altered:
```
CONTAINER_LOGGER_LOGROTATE_MAX_STDOUT_SIZE
CONTAINER_LOGGER_LOGROTATE_MAX_STDERR_SIZE
```
These env-vars cannot be changed since DC/OS 1.13 due to [MESOS-9564](https://issues.apache.org/jira/browse/MESOS-9564) and were intentionally not included:
```
CONTAINER_LOGGER_LOGROTATE_STDOUT_OPTIONS
CONTAINER_LOGGER_LOGROTATE_STDERR_OPTIONS
```

D2iQ-65350: Add configureable logrotate options.

---

frameworks/cassandra/tests/test_backup_and_restore.py
frameworks/cassandra/tests/test_sanity.py
frameworks/hdfs/tests/config.py
testing/sdk_security.py

- Fixes issues in `test_sanity.test_custom_jmx_port` where the `lsof` command is missing.
- Skip `test_backup_and_restore_to_s3_compatible_storage` till [D2IQ-69805](https://jira.d2iq.com/browse/D2IQ-69805) is resolved.
- Grants `dcos_marathon` permissions to run Apps with `root` user, this is specifically needed to launch `hdfs-client` which is used in many tests for HDFS.

HDFS & Cassandra CI Fixes

---

test.sh

While running the the zookeeper tests locally on a cluster created using terraform, I was constantly getting
```
sdk_cmd.py                 219 INFO     Got exit code 255 to command: ssh -oBatchMode=yes -oStrictHostKeyChecking=no -oConnectTimeout=50 -A -q -l centos  54.158.200.145 -- "ssh -oBatchMode=yes -oStrictHostKeyChecking=no -oConnectTimeout=50 -A -q -l centos 172.16.1.238 -- \"sudo usermod -aG docker centos\""
sdk_cmd.py                 409 INFO     NOTE: Could be due to mis-configured SSH credentials. Configured keys are: 
```
Since we are using `id_rsa.pub` for creating the tf cluster, I replaced `ccm.pem` with the private RSA key `id_rsa` and it worked.

Update the ssh_path

---

frameworks/cassandra/src/main/dist/cassandra.yaml

customers might not have `REMOTE_SEEDS`. in that case the comma in the end tells the config parser that the list end with a NULL, which in turn is converted to `127.0.0.1`, which then results in the debug log constantly spewing errors about the gossip protocol not being able to communicate with localhost.
i'd love to learn how to properly test this change. it's currently untested and just a best guess to illustrate what i think needs to happen in order to fix COPS-5547

[COPS-5547] REMOTE_SEED Fixes.

---

tools/publish_azure.py

Signed-off-by: Rishabh <rishabhbohra01@gmail.com>
The builds were failing because of 
```
tools/publish_azure.py:13:1: F401 'random' imported but unused
tools/publish_azure.py:14:1: F401 'string' imported but unused
tools/publish_azure.py:16:1: F401 'time' imported but unused
tools/publish_azure.py:53:5: E303 too many blank lines (2)
tools/publish_azure.py:76:5: E303 too many blank lines (2)
tools/publish_azure.py:98:89: E502 the backslash is redundant between brackets
tools/publish_azure.py:99:17: E131 continuation line unaligned for hanging indent
tools/publish_azure.py:99:50: W291 trailing whitespace
tools/publish_azure.py:100:21: E128 continuation line under-indented for visual indent
tools/publish_azure.py:101:21: E128 continuation line under-indented for visual indent …
```

misc: fix flake8 errors

---

conftest.py
frameworks/helloworld/tests/conftest.py
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/security/TLSArtifactsGeneratorTest.java
test.sh
testing/sdk_agents.py
testing/sdk_external_volumes.py
testing/sdk_utils.py
tools/dcos_login.py

- Update `dcos` cli binary to latest version. This binary adds support for `dcos node drain` commands.
- Update how `dcos` cli authenticates with the cluster, use username/password auth due to cli binary refactorings.
- Add `drain_agent()` and `reactivate_agent()` utility calls to `sdk_agents.py`
- Add `enable_external_volumes` flag and associated `ENABLE_EXTERNAL_VOLUMES` env-var to provision external-volumes via `sdk_external_volumes.py`

Update Tooling for External Volumes

---

sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ExternalVolumeProviderFactory.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/GenericDockerVolumeProvider.java
sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/security/TLSArtifactsGeneratorTest.java

- Renamed class `NetAppVolumeProvider` to `GenericDockerVolumeProvider`
- `GenericDockerVolumeProvider` will be used for any driver name except `pxd`, provided by the user.

Adds Generic Docker Volume Provider

---

frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache
frameworks/hdfs/universe/config.json
frameworks/hdfs/universe/marathon.json.mustache

Resolves [D2IQ-72495](https://jira.d2iq.com/browse/D2IQ-72495)
This patch allows the following env-vars to be altered:
```
CONTAINER_LOGGER_LOGROTATE_MAX_STDOUT_SIZE
CONTAINER_LOGGER_LOGROTATE_MAX_STDERR_SIZE
```
Relates to https://github.com/mesosphere/dcos-commons/pull/3242

[D2IQ-72495] Add configurable logrotate options

---

conftest.py
frameworks/cassandra/src/main/dist/svc.yml
test.sh
tools/dcos_login.py

- Add `--insecure` flag to dcos-login which prevents authentication with dev clusters.
- Add `--disable-external-volumes` flag.
- Enable external-volumes by default.

Add --insecure flag to dcos-login. Enable external volumes by default. Add --disable-external-volumes flag.

---

conftest.py
frameworks/cassandra/src/main/dist/svc.yml
frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/Main.java
frameworks/cassandra/tests/conftest.py
frameworks/cassandra/tests/test_external_volumes.py
frameworks/cassandra/universe/config.json
frameworks/cassandra/universe/marathon.json.mustache
frameworks/helloworld/src/main/dist/external-volumes.yml
frameworks/helloworld/src/main/dist/multiport.yml
frameworks/helloworld/src/main/java/com/mesosphere/sdk/helloworld/scheduler/Main.java
frameworks/helloworld/tests/test_external_volumes.py
frameworks/helloworld/tests/test_placement.py
frameworks/helloworld/tests/test_quota_upgrade.py
frameworks/helloworld/universe/config.json
frameworks/helloworld/universe/marathon.json.mustache
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java
sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/recovery/monitor/TimedFailureMonitor.java
testing/sdk_external_volumes.py

SDK:
- Add improved logging to indicate Pod-Replacement policy has been used.
Hello-World:
- Add scenario with external-volumes and basic integration test.
Cassandra:
- Add flag to enable/disable Pod-Replacement failure policy.
- Remove mentions of Portworx from service spec, switch NetApp to Generic Driver.
- Add basic integration test.

External Volumes Integration Tests for Hello-World and Cassandra.
